galaxyproject/tools-iuc

- packages/package_atlas_3_10/tool_dependencies.xml
- packages/package_numpy_1_7/tool_dependencies.xml
- packages/package_numpy_1_8/tool_dependencies.xml
- packages/package_numpy_1_9/tool_dependencies.xml
- packages/package_scipy_0_12/tool_dependencies.xml
- packages/package_scipy_0_14/tool_dependencies.xml
* Update the ATLAS stable version in to 3.10.2
* Provide a binary build for Linux x86_64
* Prevent OS X from attempting to build ATLAS - BLAS and LAPACK are already provided by Apple's bundled vecLib, and these are the preferred versions for SciPy, for which ATLAS is being built.
* Update the build instructions to bypass the CPU throttling check, as is done for Debian.
* Build shared libraries as well as full BLAS and LAPACK libraries.
* Depend on `package_atlas_3_10`
The ATLAS build script follows (the binary package was built in a Debian Squeeze docker container):
```
#!/bin/bash
version=3.10.2
urls="
http://downloads.sourceforge.net/project/math-atlas/Stable/${version}/atlas${version}.tar.bz2
http://www.netlib.org/lapack/lapack-3.5.0.tgz
"
#
#
mkdir /build &&
cd /build &&
( for url in …
```
> Provide ATLAS for SciPy and NumPy

- CONTRIBUTING.md
Describes how to fork, pull request, etc.... Github will display a link to this information in certain contexts and even if it didn't it can be very useful to potential developers.
Lots of TODO left here - what to contribute, what not to contribute, mention how to write tests, update test-data, decide if linting is required and provide links - but since I am not on the IUC I shouldn't be writing policy I just wanted to make sure all the most relevant Galaxy repositories have CONTRIBUTING files before we submit our GSOC application.
> Add a CONTRIBUTING file.

- packages/package_perl_5_18/tool_dependencies.xml
On OSX, I am getting error when editing my Makefile in tool_dependencies.xml (sed -i 's/O2/O2 -fPIC/' Makefile doesn't work, sed -i -e 's/O2/O2 -fPIC/' Makefile works). When installing this package on OSX, I am getting very similar error. Maybe this small edit will help. 
http://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed
> differences in OSX/UNIX sed

- tools/tool_factory_2/rgToolFactory2.xml
One is a fix and the other is an enhancement that makes it easier to implement a new `planemo tool_factory` command for quickly launching a Galaxy instance configured only with upload and the tool factory (mirroring the `planemo serve` command).
> A couple Tool Factory tweaks.

- data_managers/data_manager_bowtie_index_builder/README
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_color_space_index_builder.xml
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.py
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.xml
- data_managers/data_manager_bowtie_index_builder/data_manager_conf.xml
- data_managers/data_manager_bowtie_index_builder/tool-data/all_fasta.loc.sample
- data_managers/data_manager_bowtie_index_builder/tool-data/bowtie_indices.loc.sample
- data_managers/data_manager_bowtie_index_builder/tool-data/bowtie_indices_color.loc.sample
- data_managers/data_manager_bowtie_index_builder/tool_data_table_conf.xml.sample
- data_managers/data_manager_bowtie_index_builder/tool_dependencies.xml
This data manager was developed by @jj-umn and is already part of the TTS. 
As discussed with @jj-umn we would like to include it into the IUC repository and release a IUC branded version to the TSS and the TS under the IUC account.
In addition to the version available from the TTS I cleaned up the wrappers a little bit and added a new `tool_dependencies.xml` file to use the `devteam` version of bowtie1.
> Add data_manager for Bowtie1 indices. Thanks to James Johnson!

- tools/deseq2/deseq2.xml
it looks like there was a regression here. you had the correct publication DOI and then swapped in the pre-print DOI. the publication is open access and the final version of the paper.
> publication DOI

- tools/gemini/gemini_load.xml
See Note 1 in http://gemini.readthedocs.org/en/latest/
> Restrict available VCF files to load into Gemini to hg19, Homo_sapiens_nuHg19_mtrCRS, hg_g1k_v37

- packages/package_rnastructure_5_7/tool_dependencies.xml
Previous install recipe wouldn't work as written, and some of the programs need the contents of <source>/data_files in an environment variable.
> Fix install recipe.

- packages/package_r_3_1_2/tool_dependencies.xml
The readline errors reported in #101 turned out to be due to ncurses not being in the list of linked libraries.
> Fix readline related compilation failure

- .travis.yml
- Lint tools
- Fail on errors only (too many missing citations WARNINGS to fail on that)
- Only report warnings+, all is too noisy for easy log viewing
> Make travis work harder

- packages/package_blat_35x1/.shed.yml
- packages/package_chemfp_1_1/.shed.yml
- packages/package_eigen_2_0/.shed.yml
- packages/package_eigen_3_1/.shed.yml
- packages/package_ghostscript_9_07/.shed.yml
- packages/package_libtool_2_4/.shed.yml
- packages/package_numpy_1_7/.shed.yml
- packages/package_numpy_1_7_with_atlas/.shed.yml
- packages/package_numpy_1_8/.shed.yml
- packages/package_numpy_1_9/.shed.yml
- packages/package_perl_5_18/.shed.yml
- packages/package_qt_4_8/.shed.yml
- packages/package_qt_5_1/.shed.yml
- packages/package_r_3_0_1/.shed.yml
- packages/package_r_3_0_2/.shed.yml
- packages/package_r_3_0_3/.shed.yml
- packages/package_r_3_1_2/.shed.yml
- packages/package_readline_6_2/.shed.yml
- packages/package_scikit_learn_0_13/.shed.yml
- packages/package_scikit_learn_0_13_with_atlas/.shed.yml
- packages/package_scikit_learn_0_14/.shed.yml
- packages/package_scikit_learn_0_14_with_atlas/.shed.yml
- packages/package_scikit_learn_0_15/.shed.yml
- packages/package_scipy_0_12_with_atlas/.shed.yml
- packages/package_scipy_0_14/.shed.yml
- packages/package_segemehl_0_1_6/.shed.yml
- packages/package_segemehl_0_2_0/.shed.yml
- packages/package_seqtk_1_0_r75/.shed.yml
- packages/package_weblogo_2_8_2/.shed.yml
- packages/package_zlib_1_2_8/.shed.yml
> Fix widely used copy-paste error

- packages/package_numpy_1_8/tool_dependencies.xml
- packages/package_numpy_1_9/tool_dependencies.xml
libf77blas.so.3 was not being found when using tools that depended on
one these two numpy packages/versions.
Also, possibly related to #104 .
> Packages numpy 1.8 and 1.9 now declare ATLAS

- packages/package_bioperl_1_6/tool_dependencies.xml
- test_repositories/setup_perl_environment/tool_dependencies.xml
Had a user report that they'd seen a hardcoded changeset revision, this removes those. 
@jmchilton how would you feel about adding warnings on `changeset_revision`/`toolshed` to planemo?
> Remove hardcoded changesets

- suites/suite_fasta_tools/.shed.yml
- suites/suite_fasta_tools/repository_dependencies.xml
I would like to create some basic tools suites and collect a bunch of high quality tools that we as IUC can recommend. 
The first one is: Tools to manipulate FASTA files
The following suites I would like to add if we agree this is a good idea for the IUC.
* GFF/GTF tools
* Sequence Searches (BLAST, Diamond, Kraken etc...)
* Exome-Seq (all different callers + Annotation)
* Statistics
> add suite of FASTA tools to the IUC repository

- packages/package_muscle_3_8_31/tool_dependencies.xml
I don't have an OS X to test, but it should pretty safe.
> Fix muscle installation on 64-bit OS X.

- tools/hmmer3/hmmconvert.xml
- tools/hmmer3/hmmfetch.xml
- tools/hmmer3/macros.xml
Now that I'm actually using them...I find that they support clustal/fasta (after not having a clustal/fasta -> stockholm converter on hand, @jmchilton where are we on biopython? I'd like to add in AlignIO converters...)
> Support clustal format in hmmer tools

- packages/package_vsearch_1_1_3/tool_dependencies.xml
This is a bug fix for the installation of the `vsearch` binaries for `package_vsearch_1_1_3`, which appears to be broken.
Specifically, the `move_file` action erroneously moved the downloaded binary to a subdirectory of the target `bin` directory and failed to change its name; the binary was then unavailable to the `vsearch` Galaxy tools after installation.
The fix is to add an explicit `rename_to` attribute and update the `destination` element to point to the `bin` directory.
The changes in this pull request have been made for both `darwin` and `linux` target architectures. I have tested the `linux` target locally but cannot verify the `darwin` target as I don't have access to a Mac.
> Fix move of downloaded vsearch binaries for package_vsearch_1_1_3

- packages/package_cummerbund_2_8_2/tool_dependencies.xml
If multiple packages are specified in the setup_r_environment,
only the final one will be used to generate the resulting env.sh
file. This commit ensures that R is the last package, so that
cummeRbund will load correctly on usegalaxy.org
Also replaced \r\n with \n throughout.
> Fix install recipe for cummeRbund.

- packages/package_mono_4_0/.shed.yml
- packages/package_mono_4_0/tool_dependencies.xml
PeptideShaker from the GalaxyP project is using some Mono dependent search engine. Hopefully, we will get this to work with this package.
> Add mono package

- packages/package_fatotwobit_35x1/tool_dependencies.xml
This is a transitional package you should migrate to use packages with the name package_ucsc_tools_312 and upwards.
Should fix: https://github.com/galaxyproject/tools-iuc/issues/175
> Update package to get a version copy of all binaries.

- packages/package_rnastructure_5_7/tool_dependencies.xml
The code refers to version 5.6 in ./src/ParseCommandLine.cpp. This doesn't allow galaxy tools to set <version_command> tags that match the package's version 5_7 because 5.6 is passed through to the *--version* argument.
> replace 5.6 in the code for 5.7

- packages/package_kraken_0_10_5/tool_dependencies.xml
Precompiled package had the wrong extension, and install_kraken.sh always exits with code 1.
> Fix install recipe for kraken.

- tools/rgrnastar/rg_rnaStar.xml
RNA STAR requires \~27GB of RAM for hg19.
This patch will make the tool ends up in error state if STAR crashes because it can't allocate enough memory.
Instead of allowing all lines in stderr and making exceptions for those that are critical errors (```<regex match=".*" source="both" level="warning" description="Some stderr/stdout text"/>```), I think it would be more convenient to disallow all lines in stderr and make an exception for those lines that are not critical, like these:
```
Jun 30 15:49:24 ..... Started STAR run
Jun 30 15:50:07 ..... Started mapping
Jun 30 15:50:09 ..... Finished successfully
```
Please share your thoughts on this.
> RNA-STAR: Not enough memory error captured in stdio

- packages/package_barrnap_0_7/.shed.yml
- packages/package_barrnap_0_7/tool_dependencies.xml
Barrnap is a rRNA finder in sequences. Version 0.7 supports bacteria, eukaryotes, mitochondria and Archaea..
> Added new dependency definition for barrnap v0.7 - package_barrnap_0_7

- packages/package_atlas_3_10/tool_dependencies.xml
As documented in #190, if the version of (lib)gfortran on the system is newer than the version bundled with the version in this package, compiling dependant packages (SciPy) will fail. As proposed in that issue, this will copy the system version to the tool dependency's lib directory if the system version exists and is newer.
I could not find a reliable way to locate a shared library and gfortran itself doesn't provide a way to locate it (or link to it) that I could find, so I'm:
1. Creating an empty Fortran program
2. Compiling it with gfortran
3. Using ldd to find the linked libgfortran
4. Comparing the minor version numbers embedded in the GNU ELF format's symbol version section
5. Copying in the system version if its minor version is greater than the bundled version
If gfortran is not …
> ATLAS: Use system version of libgfortran when available

- packages/package_atlas_3_10/tool_dependencies.xml
- packages/package_numpy_1_7/tool_dependencies.xml
This PR attempts to address issues with the tool dependency packages `package_atlas_3_10` and `package_numpy_1_7`.
Specifically: although the packages appear to install correctly from the toolshed into a Galaxy instance, when other tools or dependencies attempt to `import numpy` then the import fails with errors of the form e.g.:
ImportError: /path/to/tool_dependencies/atlas/3.10.2/iuc/package_atlas_3_10/b36c9ee883e9/lib/atlas/libblas.so.3: undefined symbol: ATL_zger2
I've encountered this problem on Fedora 19 and Scientific Linux 6.2, affecting installation of dependencies for the `iuc` tool `macs2` (unable to install the `scipy` dependency) and Bjoern's `deepTools` suite (unable to install the `matplotlib` dependency). It may be that this problem only occurs when the ATLAS libraries are …
> Fixes to package_atlas_3_10 and package_numpy_1_7

- packages/package_muscle_3_8_31/tool_dependencies.xml
- packages/package_perl_5_18/tool_dependencies.xml
- packages/package_python_2_7/tool_dependencies.xml
- packages/package_samtools_1_0/tool_dependencies.xml
- packages/package_samtools_1_1/tool_dependencies.xml
- packages/package_samtools_1_2/tool_dependencies.xml
- packages/package_tpp_4_6_3/tool_dependencies.xml
- packages/package_tpp_4_7_0/tool_dependencies.xml
- packages/package_trnascan_1_3_1/tool_dependencies.xml
OSX encounters an error when `sed -i` is run without a suffix for in-place substitution, this resolves that issue.
> Add .bak suffix to sed -i commands for OSX compatibility.

- packages/package_matplotlib_1_2/tool_dependencies.xml
Downloads via sourceforge are returning (for me) JavaScript which is
being used to rewrite the URL to use a mirror site.  For example,
http://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.1/matplotlib-1.2.1.tar.gz
could be rewritten to:
http://ufpr.dl.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.2.1/matplotlib-1.2.1.tar.gz
```html
<html>
<head>
<title>SourceForge</title>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
DR_sf_main(DR_loc);
} else {
window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head>
<body>
<noscript>
We're sorry -- the Sourceforge site is currently …
```
> Changed URL of source code from sourceforge to GitHub.

- packages/package_bzlib_1_0/tool_dependencies.xml
the package_bzlib_1_0 recipe.  The source directory is at the same level
as the lib directory.
> Fix LD_LIBRARY_PATH and LIBRARY_PATH environment variable settings for

- tools/taxonomy_krona_chart/.shed.yml
We agreed with @nekrut on IRC that the best experience for users would be to update  https://toolshed.g2.bx.psu.edu/view/crs4/taxonomy_krona_chart/ instead of creating a new iuc repository. I think that https://toolshed.g2.bx.psu.edu/view/iuc/taxonomy_krona_chart/ creation was an oversight and can be deprecated.
N.B.: iuc has write access to the crs4 repository, which I have just updated to the latest commit with planemo using this .shed.yml file and the iuc API key.
> Add .shed.yml for taxonomy_krona_chart using crs4 as owner.

- packages/package_perl_5_18/tool_dependencies.xml
set $HOME during perl installation, to prevent cpanm installation
into ~/.cpan.
Tested on OSX and ubuntu-14.04.
Should fix issue #205
> Fix "sed: RE error: illegal byte sequence" error on OSX and

- packages/package_cython_0_23_1/.shed.yml
- packages/package_cython_0_23_1/tool_dependencies.xml
To address issue https://github.com/galaxyproject/tools-iuc/issues/256, the package wrapper for version 0.23.1 of Cython, compatible with the python 2.7 build from galaxy.
> Package wrapper for Cython 0.23.1 (UCS2 python compatible)

- tools/rgrnastar/.shed.yml
- tools/rgrnastar/rg_rnaStar.xml
This PR changes:
- A link was broken (STAR moved from google code to github)
- The DOI was broken due to the 'doi: '-prefix and couldn't compile ('Failed to fetch BibTeX for DOI.')
- The name into 'RNA STAR' which I think is more appropriate than 'rnastar'.
> Small star changes

- packages/package_chemfp_1_1/tool_dependencies.xml
- packages/package_monocle_1_0_0/tool_dependencies.xml
- packages/package_rnashapes_2_1_6/tool_dependencies.xml
The old links gave HTML downloads, these now match the other links to https://github.com/bgruening/download_store - does this look fine @bgruening ?
This was done with an in-place sed search and replace to the packages folder.
Found while testing https://github.com/galaxyproject/planemo/pull/310
> Fix github raw links in selected packages

- packages/package_hmmer_3_1b1/.shed.yml
- packages/package_hmmer_3_1b1/tool_dependencies.xml
- packages/package_hmmer_3_1b2/.shed.yml
- packages/package_hmmer_3_1b2/tool_dependencies.xml
- tools/hmmer3/macros.xml
- tools/hmmer3/tool_dependencies.xml
`package_hmmer3_1b1` is renamed to the standard `package_hmmer_3_1b1` . The old package was broken due to the missing PATH prepending, so I see no harm in deprecating the old package.
This also adds the new `package_hmmer_3_1b2`.
> HMMER 3.1b1 package fix and new 3.1b2

- tools/dexseq/dexseq.R
This changes the last column of the output from ```c("FBtr0071763", "FBtr0100521")``` to ```FBtr0071763, FBtr0100521```.
When the test is working again, the test-data should be updated as well.
> Join operation on the last column of DEXSeq output

- packages/package_cairo_1_12_14/tool_dependencies.xml
As discussed in issue #304 
Additionally, do not build html documentation, which fails if gtk-rebase is not available.
Requires re-upload or metadata reset (not sure if metadata reset is enough?!) of r packages
- package_r_3_1_1
- package_r_2_15_0
- package_r_2_11_0
- package_r_3_2_0
- package_r_3_1_0
- package_r_3_0_3
- package_r_3_1_2
- package_r_3_2_1
Tested on gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) and gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
> Fix cairo compilation on gcc-4.9 and fix non-fatal make error.

- packages/package_bzlib_1_0/tool_dependencies.xml
I believe a recent change to this recipe broke the installation on osx.  I've tested the changes here on both OS X and Linux.
> Fix for installing on osx.

- packages/package_bcftools_1_2/tool_dependencies.xml
- packages/package_meme_4_10_0/tool_dependencies.xml
The first action has a subtle effect on the working directory used, see https://github.com/galaxyproject/galaxy/issues/896
@bgruening are you able to test this which is the change you suggested here: https://github.com/galaxyproject/planemo/pull/321#issuecomment-147486763
The path issue does not appear to be important in this case, but I think currently the source code for these tools would be left under ``$INSTALL_DIR`` which would be used as the working directory. After my change the download and compilation should happen in a temporary folder.
> Reorder compile from source recipes

- packages/package_cairo_1_12_14/tool_dependencies.xml
- packages/package_cairo_1_14_2/tool_dependencies.xml
Exposing CAIRO_CFLAGS and CAIRO_LIBS is needed for some R packages, even if cairo support is compiled into R. xref https://github.com/galaxyproject/galaxy/pull/929#issuecomment-148710483
> Fix cairo cflags

- packages/package_bowtie_2_2_5/tool_dependencies.xml
Per report from @jgoecks, bowtie2 2.2.5 fails to compile on osx, but precompiled binaries are available.
> Enable bowtie2 2.2.5 installation on osx

- packages/package_bz2file_0_98/.shed.yml
- packages/package_bz2file_0_98/tool_dependencies.xml
- packages/package_khmer_2_0/tool_dependencies.xml
- packages/package_python_2_7_10_khmer_2_0/.shed.yml
- packages/package_python_2_7_10_khmer_2_0/tool_dependencies.xml
- packages/package_screed_0_9/.shed.yml
- packages/package_screed_0_9/tool_dependencies.xml
- tools/khmer/macros.xml
- tools/khmer/tool_dependencies.xml
The previous package would result in an empt khmer directory.
@bgruening should we change the name to package_python_2_7_10_khmer_2_0 ?
> Add python-2.7.10 dependency to package_khmer_2_0

- packages/package_bowtie_2_2_6/tool_dependencies.xml
Move precompiled binaries into the path set in the environment settings.
> Correct destination path.

- packages/package_cmake_3_2_3/tool_dependencies.xml
- packages/package_freetype_2_4/tool_dependencies.xml
- packages/package_gnu_coreutils_8_21/tool_dependencies.xml
- packages/package_gnu_coreutils_8_22/tool_dependencies.xml
- packages/package_gnu_grep_2_14/tool_dependencies.xml
- packages/package_graphicsmagick_1_3/tool_dependencies.xml
- packages/package_infernal_1_1/tool_dependencies.xml
- packages/package_infernal_1_1rc4/tool_dependencies.xml
- packages/package_libpng_1_6_7/tool_dependencies.xml
- packages/package_libxml2_2_9_1/tool_dependencies.xml
- packages/package_mcl_12_135/tool_dependencies.xml
- packages/package_meme_4_10_0/tool_dependencies.xml
- packages/package_ncurses_5_9/tool_dependencies.xml
- packages/package_ncurses_6_0/tool_dependencies.xml
- packages/package_openbabel_2_3/tool_dependencies.xml
- packages/package_openms_2_0/tool_dependencies.xml
- packages/package_piranha_1_2_1/tool_dependencies.xml
- packages/package_r_3_0_1/tool_dependencies.xml
- packages/package_r_3_0_1_with_atlas/tool_dependencies.xml
- packages/package_r_3_0_2/tool_dependencies.xml
- packages/package_readline_6_2/tool_dependencies.xml
- packages/package_readline_6_3/tool_dependencies.xml
- packages/package_tophat_2_0_14/tool_dependencies.xml
- packages/package_tpp_4_7_0/tool_dependencies.xml
I deliberately only covered what looked like easy cases. This also fixed the indentation in a few cases - we should lint all the XML files to a standard indentation pattern.
There are lots more recipes which could be re-factored to use these more advanced actions, making them shorter. On the other hand I do quite like the alternative ``shell_command`` action with CDATA approach to embed an entire bash script ;)
**This is untested**
Do we have a mechanism for mass testing all the dependency installations scripts? (I used to depend on the TTS for doing this)
> Use autoconf and make_install actions more

- tools/art/macros.xml
- tools/art/tool_dependencies.xml
Apparently you have to use the version number, giving a different name doesn't work. I was sorta under the impression that you declared a dependency in tool_dependencies and could call it whatever you wanted, however that is not the case. Instead we have to (this is insane) explicity duplicate the package name + version and it's incredibly unclear why. Whatever, this makes ART work again.
> Make art package installable

- data_managers/data_manager_hisat2_index_builder/data_manager/hisat2_index_builder.py
The argparse default for --indexer_options was set to None but has to be empty string. Evaluation of None by shlex.split( options.indexer_options) will make shlex.split try to read a string from stdin. This obviously never happens, so it blocks indefinitely.
> Fix infinite wait of hisat2_index_builder.py when default parameters are used

- packages/package_cairo_1_12_14/tool_dependencies.xml
- packages/package_cairo_1_14_2/tool_dependencies.xml
- packages/package_fontconfig_2_11_1/tool_dependencies.xml
- packages/package_pixman_0_32_4/tool_dependencies.xml
- packages/package_pixman_0_32_6/tool_dependencies.xml
This PR removes some of the unnecessary export statements when using `LD_LIBRARY_PATH` ad `LD_INCLUDE_PATH`, allowing use of autoconf.
This PR also contains a fix for pixman on OS X (--disable-mmx).
Marked WIP because needs more testing.
> Cleanup packages

- tools/pear/pear.xml
Will also retain the original input datatype assignment.
> Fix PEAR to work with only PHRED scaled quality score FASTQ files and properly pass the --phred-base argument.

- tools/qiime/pick_open_reference_otus.xml
This PR is a first attempt at updating the wrapper for qiime's `pick_open_reference_otus.py` as part of issue #426, to tidy up the original generated wrapper from https://github.com/lparsons/galaxy_tools/tree/qiime/tools/qiime1.9.0 and output explicit datasets to the history rather than just a tar.gz file.
**This initial version is a WIP and still needs work before it can be merged** as it doesn't yet define any tests and fails when run manually.
> Add tool wrapper for Qiime pick_open_reference_otus.py

- packages/package_cairo_1_12_14/tool_dependencies.xml
My bad ... :(.
I will also open a PR for the devteam version.
> Remove double ampersand that remained after switching to autoconf

- packages/package_cairo_1_12_14/tool_dependencies.xml
- packages/package_cairo_1_14_2/tool_dependencies.xml
- packages/package_r_3_2_1/tool_dependencies.xml
fontconfig needs to be a dependency of cairo (as done for package_cairo_14_2).
Disable aqua (else R in conjunction with cairo will default to plotting on-screen on OS X).
> Disable aqua and add fontconfig to cairo dependencies.

- tools/sickle/sickle.xml
Follow up to https://github.com/galaxyproject/tools-iuc/pull/369#discussion_r43800084 now that https://github.com/galaxyproject/galaxy/issues/699 has been fixed.
The output format of `output_paired_coll_single` will be `data` for Galaxy < release_16.01 .
> Add paired collection support to sickle.

- packages/package_mash_1_0_2/.shed.yml
- packages/package_mash_1_0_2/tool_dependencies.xml
This PR adds the mash package as part of the [2nd IUC hackathon](
https://github.com/galaxyproject/tools-iuc/issues/299).
Mash: https://github.com/marbl/Mash
> Add mash package

- packages/package_bcftools_1_3/.shed.yml
- packages/package_bcftools_1_3/tool_dependencies.xml
BCFTools 1.3 just came out. So I added a package (pretty much identical to your 1.2 except with 1.3 references, URL, and help output instead.
Currently bcftools1.3 is not in the depot so that commented part can just be uncommented and updated with the 1.3 depot URL whenever it's on there.
> Added package for bcftools 1.3

- packages/package_python_2_7_bx_python_0_7_2/tool_dependencies.xml
`package_python_2_7_bx_python_0_7` ends up getting installed as an egg. This requires `site.py` in `package_python_2_7_bx_python_0_7/a6b1f4f37b64/lib/python` getting run, but that won't happen **unless** this package happens to be the first thing in `sys.path`. This gets around that by manually added the egg to PYTHONPATH. This package also installs distribute as an egg, but I assume that that side-effect isn't needed by anything.
> Fix package_python_2_7_bx_python_0_7, since eggs and PYTHONPATH don't mix

- packages/package_ncurses_5_9/tool_dependencies.xml
A fix for issue https://github.com/galaxyproject/tools-iuc/issues/477
Could testers report their GCC version as well?
> package_ncurses_5_9: Fixes critical compilation error for GCC5.1+

- tools/cwpair2/cwpair2.xml
This one is not critical, but just wanted to standardize the parameter label across tools.
> Make output param label the same as that for repmatch_gff3

- packages/package_circos_0_67_5/tool_dependencies.xml
Replaced the dead link:
http://www.cpan.org/authors/id/J/JV/JV/Getopt-Long-2.45.tar.gz
With the following link:
http://pkgs.fedoraproject.org/repo/pkgs/perl-Getopt-Long/Getopt-Long-2.45.tar.gz/md5/ea5c085b30915efe522f9ac58fcc343d/Getopt-Long-2.45.tar.gz
> Replace dead link in package_circos_0_67_5

- packages/package_circos_0_67_5/tool_dependencies.xml
Uses the cargo-port url for https://github.com/galaxyproject/tools-iuc/pull/526
> Perl Getopt-Long v2.4.5: cargo-port url + sha256sum

- tools/hisat2/hisat2.xml
- tools/hisat2/hisat2_macros.xml
HISAT2 crashes when changing the *Spliced alignment parameters* because of 2 typo's.
These settings are necessary if you want to use the alignments with cufflinks/cuffdiff/cummerbund.
When you select those parameters you get a `failure preparing job` error and paster.log says:
```
File "<galaxy home dir>/lib/galaxy/jobs/runners/pulsar.py", line 256, in __prepare_job
job_wrapper.prepare( **prepare_kwds )
File "<galaxy home dir>/lib/galaxy/jobs/__init__.py", line 859, in prepare
self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
File "<galaxy home dir>/lib/galaxy/tools/evaluation.py", line 422, in build
raise e
NotFound: cannot find 'no_spliced_alignment' while searching for 'spliced_options.no_spliced_alignment' …
```
> HISAT2: Fixes 2 issues for using advanced parameters

- packages/package_python_2_7_10_pybigwig_0_2_3/.shed.yml
- packages/package_python_2_7_10_pybigwig_0_2_3/tool_dependencies.xml
This adds a copy of the most recent version of pyBigWig to the toolshed. It's just an updated version of the files used for the current copy. This python package is used by deepTools, the next release of which will be released within the next week.
> Add pyBigWig-0.2.3, which will be a deepTools-2.0.0 requirement

- tools/extract_genomic_dna/extract_genomic_dna.xml
so it exactly mimics the behavior of the original tool.
> Fix output tag set for the modern extract_genomic_dna tool

- tools/rgrnastar/rg_rnaStar.xml
More parameters for users to select (output, seed, alignment, and chimeric alignment).
Re: STAR-Fusion preset option -- the recommended parameter '--twopassMode Basic' is not available in STAR 2.4.0, but it is possible to run a second pass by adjusting other parameters.  However, doing so resulted in a failure in test #3, so these parameters have been commented out (lines 81-82).
> RNA-STAR: additional parameters

- packages/package_macs2_2_1_0_20151222/tool_dependencies.xml
Installation of MACS2 is problematic when gcc version is < 4.6. See https://github.com/taoliu/MACS/issues/75. This is implements the suggested patch from the author.
PR (https://github.com/taoliu/MACS/pull/109) was issued upstream to address this, but hopefully this patch addresses things in this version.
> Patch macs2 install for old gcc versions

- packages/package_perl_5_18/tool_dependencies.xml
This PR fixes a problem in `package_perl_5_18`, which is observed to fail when installing from the toolshed on Ubuntu 14.04 and Scientific Linux 6.5.
The problem seems to be related to the download and unpacking of the `local-lib` library post-Perl installation. This fails at the explicit untarring step with the error:
tar (child): local-lib-1.008009.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Using `download_by_url` and removing the explicit `tar xvfz ...` appears to fix the problem.
> Fix broken lib-local install in package_perl_5_18

- tools/bedtools/closestBed.xml
Output name was exposing the actual file location on disk, fall back to
using ${on_string} since no simple solution when there are multiple
inputs.
Also, dropped the deprecated optional attribute from the
addition2_select param.
> Fix closestBed output name

- packages/package_galaxy_json_data_source/.shed.yml
- packages/package_galaxy_json_data_source/tool_dependencies.xml
WIP due to using a download from a branch on my fork that provides additional --version arg.
Perhaps IUC should consider adopting the https://github.com/mdshw5/galaxy-json-data-source repo. Haven't talked to @mdshw5, however.
> New package for tool to create multiple galaxy datasets, with metadata, using JSON.

- packages/package_gnu_coreutils_8_25/.shed.yml
- packages/package_gnu_coreutils_8_25/tool_dependencies.xml
It appears that this version doesn't hang on first compile on ubuntu 14.04, due to a newer nanosleep.c
The issue was mentioned here: http://dev.list.galaxyproject.org/JBrowse-on-dev-branch-progress-td4668897.html
> coreutils version 8.25

- packages/package_perl_5_18/tool_dependencies.xml
as mentioned before, due to a newer nanosleep.c in coreutils this should fix hangs during the ./configure on ubuntu trusty systems.
> rely on newer coreutils version

- tools/stacks/tool_dependencies.xml
Stacks 1.37 with iuc dependency.
IMPORTANT NOTE: This will only work if stacks is made available via iuc
> advance to stacks 1.37 with iuc dependency

- packages/package_python_2_7_numpy_1_9/tool_dependencies.xml
This PR attempts to fix an issue with `package_python_2_7_numpy_1_9` and its dependency on `package_atlas_3_10`; essentially the former fails to use the ATLAS libraries provided by the latter when building `numpy`:
* In cases where there is a pre-existing set of ATLAS libraries on the system, `numpy` may compile against these instead and cause installation failures subsequently for other packages that depend on `numpy` (for example `package_python_2_7_scipy_0_14`). This is what I'm observing on our production server when trying to update the `deepTools` tool (we are running Scientific Linux and have the `devel` package for the ATLAS libraries installed).
* In cases where the system ATLAS is not picked up (or doesn't exist), the installation failures may not be observed - however the …
> package_python_2_7_numpy_1_9 update to explicitly specify ATLAS libs from toolshed

- tools/gatk2/haplotype_caller.xml
Probably a typo, this fixes the Haplotype reference to the BAM files specified in the Macros.
> fixed - @INPUT_BAMS@ to @BAM_INPUTS@

- tools/jbrowse/jbrowse.py
- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
- tools/jbrowse/test-data/gff3/test.xml
This represents the v0.5 release of JBrowse-in-Galaxy. 
- The roadmap can be seen in #508, the features/issues for this version are copied from there.
- The branch should not be deleted post-merge, I'm continuing development on it.
- Review is welcome but this is a small release. I'm PRing it as that's our practice.
- SPARQL support has been moved back to the next release, so that code is commented out.
You can now update existing instances with new tracks. This is a useful feature as it will allow you to curate JBrowses over the course of a workflow, rather than having to create a single *gigantic* instance at the end.
You are now allowed to select between Canvas and HTML features. This is not likely to be a well used feature for the time being, but there are some odd cases where we've …
> Jbrowse v0.5

- tools/bioperl/macros.xml
- tools/bioperl/tool_dependencies.xml
bp_genbank2gff3 required bioperl 1.6, but the package_bioperl_1_6
actually provides version 1.6.922.
> Fix bioperl version in bp_genbank2gff3

- packages/package_python_2_7_10_twobitreader_3_1_4/.shed.yml
- packages/package_python_2_7_10_twobitreader_3_1_4/tool_dependencies.xml
This will be used by the next version of deepTools. It's also an alternative to bx-python for anything that needs to handle .2bit files and work with both python2 and python3.
> Add package_python_2_7_10_twobitreader_3_1_4

- packages/package_trinity_2_1_1/tool_dependencies.xml
I thought everything was ok with trinity, but it turns out an url is wrong in tool_dependency.xml (my prod galaxy is not yet using conda)
> Trinity: fix dependency url

- packages/package_trinity_2_1_1/tool_dependencies.xml
Hum, another dependency problem with trinity. Sorry about that
> Trinity: add missing dep for Biobase

- packages/package_deseq2_1_10_0/tool_dependencies.xml
- packages/package_trinity_2_1_1/tool_dependencies.xml
Ok, I should have checked the sha256sum before committing instead of just pasting it from package_deseq2_1_10_0 (I fixed it there too just in case)
> Trinity: fix wrong sha256sum

- packages/package_python_2_7_pandas_0_16/tool_dependencies.xml
This PR explicitly pulls in `six` Python package, which is an implicit dependency of `pandas` as it's required by the `python-dateutils` package (see [this StackOverflow post](http://stackoverflow.com/a/21222511/579925), which refers to `matplotlib` not `pandas` but appears to be the same problem).
Without this patch I get the following error when running a tool that imports `pandas`:
Fatal error: Exit code 1 ()
File "/XXXXXX/filter_summary_stats.py", line 5, in <module>
import pandas as pd
File "/XXXXXX/tool_dependencies/pandas/0.16/iuc/package_python_2_7_pandas_0_16/99747a5bdac1/lib/python/pandas/__init__.py", line 13, in <module>
"extensions first.".format(module))
ImportError: C extension: No module named six not built. If you want to import pandas …
> package_python_2_7_pandas_0_16 needs to explicitly pull in Python 'six' module

- packages/package_numpy_1_9/tool_dependencies.xml
tl;dr:
This PR attempts to fix an issue with `package_numpy_1_9` and its dependency on `package_atlas_3_10`; essentially the former fails to use the ATLAS libraries provided by the latter when building `numpy`.
More details:
In cases where there is a pre-existing set of ATLAS libraries on the system, `package_numpy_1_9`  will compile against these and not the ones provided by `package_atlas_3_10`; this causes installation failures subsequently for other packages that depend on `package_numpy_1_9`. (This is what we're observing on our test server running Scientific Linux, when attempting to install e.g. `package_biopython_1_66`).
In cases where the system ATLAS is not picked up or doesn't exist, the installation failures may not be observed; however the toolshed ATLAS libs are not picked …
> package_numpy_1_9 update to explicitly specify ATLAS libs from toolshed

- packages/package_deseq2_1_10_0/tool_dependencies.xml
Here's a fix for a missing package for deseq2 1.10.0 installation (and I consequently had to update other packages)
> Fix deps for deseq2 1.10.0

- packages/package_r_3_2_1/tool_dependencies.xml
**tl;dr**
This PR tries to fix the setting of the `R_LIBS` env variable when requiring R 3.2.1 from `package_r_3_2_1` so that any previously included R libraries are still available. As it stands, the use of `set_to` on the `R_LIBS` environment variable clobbers any existing value; the proposed fix is to use `prepend_to` so the existing value is extended instead.
**More details:**
I'm working on a tool which uses R 3.2.1 plus a set of R libraries; these are defined in the `tool_dependencies.xml` file using the `setup_r_environment` action (https://wiki.galaxyproject.org/SetUpREnvironment), e.g.
<package name="dplyr" version="0.4.3">
...
<actions>
<action type="setup_r_environment">
<repository name="package_r_3_2_1" owner="iuc">
<package name="R" version="3.2.1" />
</repository> …
> package_r_3_2_1 should 'prepend_to' R_LIBS to avoid clobbering existing value

- packages/package_deseq2_1_10_0/tool_dependencies.xml
Another (last?) PR to fix a compilation error for a deseq2 1.10.0 dependency.
I switched to the same versions as in bioconda for the problematic packages
> Fix deseq2 1.10 broken dependency

- .tt_blacklist
- tools/sra-tools/fastq_dump.xml
- tools/sra-tools/sam_dump.xml
- tools/sra-tools/sra_macros.xml
- tools/sra-tools/tool_dependencies.xml
Added ability to pass a text file where there is a single SRA per line to allow for serial bulk download. After download is complete, outputs will either be put into single end  or pair list collection. Each SRA entry is check to ensure no funny business and works in /bin/bash and /bin/sh environments.
All test pass.
> Allow fastq/fasta and sam/bam wrapper for bulk SRA download

- .travis.yml
Galaxy 16.04 was just released and I think it's important to start testing with the most recent stable version as well.
> Update travis' galaxy dependency to 16.04

- packages/package_lapack_3_4/tool_dependencies.xml
Hi,
This should fix #780: the lapack was only built in static mode, but shared libs are needed. I now compile both as many packages seem to depend on lapack, and I'm not sure if they expect static builds
Anthony (back to business!)
> Lapack: build shared lib too

- packages/package_meme_4_11_0/tool_dependencies.xml
1. fix for this: https://groups.google.com/forum/#!topic/meme-suite/rHmLmSt2IiQ
2. add PERL5LIB path to meme runtime environment so it can find Perl dependencies
> Meme 4.11.0 fixes

- packages/package_libxslt_1_1_28/tool_dependencies.xml
This should fix the following compile time error for package_meme_4_11_0 which has a dependency on package_libxslt_1_1_28:
```
./configure --prefix=/home/greg/work/ts_install/tool_dependency_dir/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125  && make && make install
STDERR
configure: WARNING: libxml2 library not found
/home/greg/work/ts_install/tool_dependency_dir/libxslt/1.1.28/iuc/package_libxslt_1_1_28/15c6da429d88/bin/xslt-config: line 94: xml2-config: command not found
/home/greg/work/ts_install/tool_dependency_dir/libxslt/1.1.28/iuc/package_libxslt_1_1_28/15c6da429d88/bin/xslt-config: line 94: xml2-config: command not found
configure: WARNING:
```
> Add env values for required libxml2 to the environment for libxslt

- packages/package_perl_xml_parser_expat_2_41/tool_dependencies.xml
This will allow dependent packages to locate the Perl environment at compile time and / or runtime.
> Propogate the Perl environment to the perl_xml_parser_expat recipe.

- tools/trinity/tool_dependencies.xml
We need quotes here or env.sh will fail to set TRINITY_MEM_OPTIONS variable (and trinity will use as much memory as it wants)
> Trinity: add quotes to TRINITY_MEM_OPTIONS

- .travis.yml
Also:
- Quote Bash variables that may contain spaces.
- Use 'read' Bash builtin to read `$CHUNK` file line-by-line in order to prevent problems with whitespaces.
> Perform shed_update only if $CHUNK file is not empty and only on its lines

- tools/bam_to_scidx/bam_to_scidx.xml
@bgruening pointed out a flaw in how I was linking bam and bai files in this tool https://github.com/gregvonkuster/tools-iuc/tree/master/tools/pe_histogram, which I based on this bam_to_scidx tool.  So I made this fix as soon as I could.  Perhaps this will have a positive affect on this issue https://github.com/galaxyproject/galaxy/issues/2460 for this tool running on Galaxy main, but I'm not sure.
> Fix linking bam and bai files for bam_to_scidx tool

- README.md
First one was for some reason not public.
> Adopt URL to gitter

- packages/package_graphicsmagick_1_3_20/tool_dependencies.xml
- packages/package_meme_4_11_1/tool_dependencies.xml
Some meme features require it to be compiled using either ImageMagick or GraphicsMagick.  This version uses GraphicsMagick to be compatible with conda.
> Enable meme 4.11.1 to find graphicsmagick at compile time

- packages/package_imagemagick_6_9_3/tool_dependencies.xml
- packages/package_meme_4_11_0/tool_dependencies.xml
Some meme features require it to be compile dwith either ImageMagick or GraphicsMagick.  This version uses ImageMagick due to historical reasons.
> Enable meme 4.11.0 to find ImageMagick at compile time

- packages/package_fontconfig_2_11_1/tool_dependencies.xml
This is needed by libpng which is a dependency of freetype, which is a
dependency of fontconfig.
Fixes #813
> Set zlib environment for install of fontconfig

- packages/package_trinity_2_1_1/tool_dependencies.xml
Closes #836
The packaged version of samtools with trinity won't compile when the
environment is setup for `package_zlib_1_2_8`. Since the packaged
version is not needed, we can simply avoid compiling it.
> Avoid compiling trinity's packaged samtools

- .tt_blacklist
- tools/gemini/gemini_autosomal_recessive.xml
- tools/gemini/gemini_comp_hets.xml
- tools/gemini/gemini_de_novo.xml
- tools/gemini/gemini_gene_wise.xml
- tools/gemini/gemini_macros.xml
- tools/gemini/gemini_mendel_errors.xml
- tools/gemini/gemini_region.xml
More options to select columns from the variants table. I needed this to pick things like
`gt_ref_depths.sample1, gt_alt_depths.sample1`
which you can't add to the list of choices statically.
> Gemini morecols

- tools/trinity/align_and_estimate_abundance.xml
`$inputs.paired_fragment_length` is only set when in paired-end mode and thus should only appear on the command line when paired-end mode was selected, otherwise we get the error `cannot find 'paired_fragment_length' while searching for 'inputs.paired_fragment_length'`
> Set max_ins_size only in paired-end mode

- .travis.yml
Prevent the following error during `pip install planemo`:
```
html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 12.0.5)
```
> Upgrade setuptools for html5lib (planemo dep)

- tools/stringtie/stringtie.xml
Fix #882.
It seems over-specifying the filter is needed: for example, if advanced options are not specified, `option_set['abundance_estimation']` is not set, but the original filter will pass anyway and the output dataset created. @jmchilton: is this a Galaxy bug?
> More specific output filters

- tools/bedtools/genomeCoverageBed.xml
Also quote `genome` param in `<command>`.
Requested by @ethering.
> Genome input param is not needed for BAM input

- packages/package_python_2_7_deeptools_2_3_1/.shed.yml
- packages/package_python_2_7_deeptools_2_3_1/tool_dependencies.xml
@bgruening: The 2.3.0 tarball on pypi was basically borked. This works and has been merged into bioconda. When you have a chance, can you update the wrapper stuff in your repos?
> Bump deepTools version yet again

- packages/package_python_2_7_deeptools_2_3_3/tool_dependencies.xml
Apparently we never updated the package dependencies to add twobitreader.
> The twobitreader dependency was missing in the deepTools package

- packages/package_fastx_toolkit_0_0_14/.shed.yml
- packages/package_fastx_toolkit_0_0_14/tool_dependencies.xml
- packages/package_libgtextutils_0_7/.shed.yml
- packages/package_libgtextutils_0_7/tool_dependencies.xml
This should help https://github.com/galaxyproject/tools-devteam/pull/375.
Ping @bgruening 
Tested on OSX and linux (and is already on TTS).
> Fastx 0.0.14

- .tt_blacklist
- tools/featurecounts/featurecounts.xml
- tools/htseq_count/htseq-count.xml
I forgot to remove featureCounts from the blacklist so let's hope the test still passes. Therefore some small changes to trigger testing. I also added `profile="16.04"` to htseq-count because of the metadata feature.
Thanks @peterjc
> Removed featureCounts from .tt_blacklist thanks to @peterjc

- .travis.yml
Workaround for https://github.com/travis-ci/travis-ci/issues/2668 , should fix #961.
I should note that TravisCI testing works properly only for:
- pull requests
- pushes on branches, but not force-pushes (i.e. rebases).
In fact, in case of a rebase this change will use `git diff master...`, i.e. it will test all the tools changed in the non-master branch since it was branched from master, while normally it would test only the changes since the last push on this branch.
> Fix TRAVIS_COMMIT_RANGE when empty or after rebase

- packages/package_abricate_0_3/.shed.yml
There was no package under @madiflannery in the MTS - let's maintain it by IUC
> abricate: fixes deployment issue #2

- packages/package_python_2_7_deeptools_2_3_6/.shed.yml
- packages/package_python_2_7_deeptools_2_3_6/tool_dependencies.xml
This bumps the version of deepTools to 2.3.6, which addresses a bug hitting someone on usegalaxy.org at the moment. N.B., the package is being added to bioconda now.
@bgruening: Can you push out the 2.3.6 wrappers to the toolshed? I believe I've already updated the XML for them.
ping: @jennaj
> Add deepTools 2.3.6

- packages/package_python_2_7_py2bit_0_2_0/.shed.yml
- packages/package_python_2_7_py2bit_0_2_0/tool_dependencies.xml
py2bit will be required by the next deepTools release, so please consider this PR so that it's already available once that comes out.
As an aside, this is a convenient package for reading 2bit files that works with python 2 or 3, if anyone happens to need to do such a thing.
> Add py2bit-0.2.0, which will be needed by the next deepTools release

- .tt_blacklist
- tools/gemini/gemini_annotate.xml
- tools/gemini/gemini_macros.xml
Currently only BED files can be used for annotating a GEMINI database. This commit enables VCF files to be used for annotation as well.
> Enable VCF to be used for annotating GEMINI database.

- packages/package_python_2_7_10/tool_dependencies.xml
In the specific case where I encountered this issue, matplotlib was trying to link to /usr/local/lib/libpython2.7.a, when it should have been using $INSTALL_DIR/lib/python2.7/config/libpython2.7.a
This was fixed by adding LDFLAGS as in the tool dependency definition.
> Fix matplotlib installation in some environments

- packages/package_trinity_2_2_0/tool_dependencies.xml
update checksum
```
File "/w/galaxy/galaxy3/galaxy/lib/tool_shed/galaxy_install/install_manager.py", line 125, in install_and_build_package_via_fabric
tool_dependency = self.install_and_build_package( install_environment, tool_dependency, actions_dict )
File "/w/galaxy/galaxy3/galaxy/lib/tool_shed/galaxy_install/install_manager.py", line 110, in install_and_build_package
initial_download=False )
File "/w/galaxy/galaxy3/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 31, in execute_step
initial_download=initial_download )
File "/w/galaxy/galaxy3/galaxy/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 1362, in execute_step
self.url_download( work_dir, filename, url, extract=False, checksums=checksums )
File …
```
> package_trinity_2_2_0

- tools/hmmer3/hmmscan.xml
- tools/hmmer3/hmmsearch.xml
- tools/hmmer3/macros.xml
- tools/hmmer3/readme.rst
- tools/hmmer3/tool-data/hmm_database.loc.sample
- tools/hmmer3/tool_data_table_conf.xml.sample
A really soft PR to add the possibility to scan a "build-in" database like pfam-a
I only add this feature for hmmscan because I'm not sure it's interesting for the other hmm*
But let me know if you disagree.
> Add built-in HMM model database for hmmscan

- tools/khmer/macros.xml
Apparently a token can't contain other tokens.
> Fix Khmer help footer

- tools/jbrowse/tool-data/all_fasta.loc.sample
- tools/jbrowse/tool_data_table_conf.xml.sample
I just noticed the latest changes to jbrowse tools (#994) were not pushed to MTS. I have tried doing it by hand, and it complained about "This file requires an entry in the tool_data_table_conf.xml file". Here's a fix for it.
I also get these errors, but I suppose it's harmless (these images/html are not used by the tool):
```
The file "/srv/toolshed/main/var/data/repos/001/repo_1536/static/images/bam.png" contains image content.
The file "/srv/toolshed/main/var/data/repos/001/repo_1536/static/images/bigwig.png" contains image content.
The file "/srv/toolshed/main/var/data/repos/001/repo_1536/static/images/blast.png" contains image content.
The file "/srv/toolshed/main/var/data/repos/001/repo_1536/static/images/opacity.png" contains image content.
The file …
```
> Jbrowse: add missing tool_data_table_conf.xml.sample file

- packages/package_python_2_7_deeptools_2_4_1/.shed.yml
- packages/package_python_2_7_deeptools_2_4_1/tool_dependencies.xml
This adds deepTools-2.4.1, which is also now available via conda.
@bgruening Can you upload the wrappers to the toolshed too? There are some people at EMBL waiting on this version to handle some issues they're experiencing.
> Add deepTools-2.4.1

- tools/ebi_tools/macros.xml
Since your tools are python2 only, a python3 environment will not work. We need to strictly state python2 as dependency.
ping @bebatut
> depend also on python2

- .travis.yml
- tools/bedtools/macros.xml
- tools/bedtools/reldist.xml
As part of the next release we should switch to this next release and test tools against latest stable.
This PR should also test Galaxy 16.10.
@galaxyproject/iuc
> Travis update to 16.10

- tools/jbrowse/jbrowse.py
Some code that needed to be ported to python3 (just converted as explained in http://stackoverflow.com/questions/4296249/how-do-i-convert-a-hex-triplet-to-an-rgb-tuple-and-back)
> Jbrowse: finish python3 conversion

- data_managers/data_manager_bowtie_index_builder/tool_data_table_conf.xml.sample
- data_managers/data_manager_gemini_database_downloader/tool_data_table_conf.xml.sample
- data_managers/data_manager_hisat2_index_builder/tool_data_table_conf.xml.sample
- data_managers/data_manager_mothur_toolsuite/tool_data_table_conf.xml.sample
- data_managers/data_manager_snpeff/tool_data_table_conf.xml.sample
- data_managers/data_manager_snpsift_dbnsfp/tool_data_table_conf.xml.sample
- data_managers/data_manager_star_index_builder/tool_data_table_conf.xml.sample
- tool_collections/snpeff/tool_data_table_conf.xml.sample
- tool_collections/snpsift/snpsift_dbnsfp/tool_data_table_conf.xml.sample
- tool_collections/snpsift/snpsift_dbnsfp_generic/tool_data_table_conf.xml.sample
- tool_collections/snpsift/snpsift_genesets/tool_data_table_conf.xml.sample
- tools/extract_genomic_dna/tool_data_table_conf.xml.sample
- tools/gatk2/tool_data_table_conf.xml.sample
- tools/gemini/tool_data_table_conf.xml.sample
- tools/hisat2/tool_data_table_conf.xml.sample
- tools/kraken_taxonomy_report/tool_data_table_conf.xml.sample
- tools/kraken_taxonomy_report/tool_data_table_conf.xml.test
- tools/meme/tool_data_table_conf.xml.sample
- tools/mothur/tool_data_table_conf.xml.sample
- tools/rgrnastar/tool_data_table_conf.xml.sample
- tools/transtermhp/tool_data_table_conf.xml.sample
Prevents duplicate entries from appearing in data table when they exist in the files. Prevents cases where a duplicate entry occurs and is then passed as a comma separated list onto the command line (which breaks most tools).
I just did all of the data tables here, if folks could review and check if any of these tables actually should allow duplicate entries, that would be a big help.
> Set allow_duplicate_entries="False" for Tool Data Tables.

- .travis.yml
As explaind in https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step : "When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result."
xref. https://github.com/travis-ci/travis-ci/issues/1066
Example of a build which continued instead of aborting: https://travis-ci.org/galaxyproject/tools-iuc/jobs/191070928#L878
> Abort build immediately if a script command fails

- tools/ebi_tools/generate_macros.py
- tools/ebi_tools/macros.xml
- tools/hmmer3/hmmsearch.xml
- tools/hmmer3/jackhmmer.xml
- tools/hmmer3/nhmmer.xml
- tools/hmmer3/nhmmscan.xml
- tools/hmmer3/phmmer.xml
- tools/kobas/kobas_identify.xml
- tools/macs2/macs2_bdgdiff.xml
- tools/macs2/macs2_callpeak.xml
- tools/prokka/prokka.xml
- tools/vsearch/.shed.yml
- tools/vsearch/vsearch_macros.xml
- Use `optional="false"` instead of `no_options` validator for multiselect
- Check that multiselect is not `None` in output filters
See commits for details.
> Multiselect fixes

- tools/hisat2/hisat2.xml
- tools/hisat2/hisat2_macros.xml
- tools/hisat2/test-data/test_unaligned_reads.fasta
ping @yhoogstrate 
This enables the use of the `--un`/`--un-conc` and `--al`/`--al-conc` options in the hisat2 wrapper, as mentioned in #1041 . The changes are modelled on the devteam bowtie2 wrapper. I've tested single/paired/paired-collection with galaxy-docker-stable, though I haven't added any new tests for these features. Let me know if that should be done.
> Implement #1041 (add fastq output to hisat2)

- tools/busco/busco.xml
Just a little bugfix for the --species of busco. It turns out "generic" is not a good default value (returns 0 results), it's better to specify a species only if we know exactly which one.
> Bugfix for Busco

- tools/macs2/macs2_callpeak.xml
This option hasn't existed in a few years. Macs2 uses a q-value cutoff of 0.05 by default, so neither `--pvalue` nor `--qvalue` need to be explicitly specified.
> Remove --foldenrichment option from macs2

- tools/bcftools/bcftools_call.xml
- tools/bcftools/bcftools_plugin_counts.xml
- tools/bcftools/macros.xml
The optional —novel-rate can take 1 to 3 floats (comma separated) as
arguments.
> bcftools_call fix novel_rate param

- tools/jbrowse/jbrowse.py
- tools/jbrowse/jbrowse.xml
3 little fixes for jbrowse:
- parse menus in xml file only when applicable (fixes tool error with bam track for example)
- add another placeholder in the generated menuTemplate: this is needed because apollo have 4 default menu items by default instead of 3 for jbrowse. (on jbrowse there will be an empty line in the menu, but couldn't find a better way)
- I also changed the urlTemplate for bam/vcf/wig tracks: it generated urls like http://jbrowse/data/../data/ that worked well most of the time, but failed with https://github.com/galaxy-genome-annotation/galaxy-tools/blob/master/tools/jbrowse/jbrowse_to_container.xml
ping @erasche I think :)
> Jbrowse fixes

- tools/jbrowse/jbrowse.py
- tools/jbrowse/jbrowse.xml
As discussed in https://github.com/GMOD/Apollo/issues/1483, added the --type option when selecting HTMLFeature track type
> JBrowse: Add --type option for htmlfeature

- data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml
```
$ planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error data_managers/data_manager_humann2_database_downloader/
Linting repository /usr/users/ga002/soranzon/software/galaxyproject_tools-iuc/data_managers/data_manager_humann2_database_downloader
Error loading tool with path /tmp/planemo_tmp_yfUlf1/83901c99b429ead8a454823bbaa1c331/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml
File "/usr/users/ga002/soranzon/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/galaxy/tools/loader_directory.py", line 107, in _load_tools_from_path
tool_element = loader_func(possible_tool_file)
ParseError: not well-formed (invalid token): line 49, column 32
+Linting tool …
```
> Fix broken data_manager_humann2_database_downloader

- tools/stringtie/stringtie_merge.xml
stringtie-merge did not handle case for absent guide file. If was consistently giving the following error:
```
Fatal error: Exit code 1 ()
Error: reference annotation file (None) not found
```
this commit fixes this and adds appropriate test
> fixed handling of guide gtf in stringtie merge

- tools/deseq2/deseq2.R
I was going through the script and noticed the typo. It took me a while, to realize, it was just part of the function name.
> minor typo in the comments of deseq2.R

- tools/macs2/macs2_bdgbroadcall.xml
- tools/macs2/macs2_callpeak.xml
Fixed several things: 
- html generation part of the `<command>` tag was missing `;`
- fixed error noticed by @nsoranzo 
- made sure stderr gets printed when tool fails
- added test for presence of html report
> Additional (critical) MACS2 fixes

- tools/fastqc/.shed.yml
- tools/fastqc/rgFastQC.py
- tools/fastqc/rgFastQC.xml
Xref: #1128 
Compressed input into the current FastQC wrapper only works if the history item's name ends in `.gz`. That will generally work for uploaded or linked in files (assuming people don't change the names) but won't if you run FastQC on trimmed data. I've now modified the python script to pay closer attention to whether the input datatype is `fastq.gz` (or `fastq.bz2`). This fixes things locally for me at least.
> Fix compressed input into FastQC

- tools/mothur/make.contigs.xml
This Pull Request concern an update of the make.contigs wrapper (as discussed previously with @shiltemann)
The wrapper has been modified so that the end user can use make.contigs in combo mode (i.e. make it process more than one pair of fastq files at a time).
The end user can now select a list:paired collection as input.
If such a collection is selected, the wrapper will create a valid combo file "on the fly" and use it in the make.contigs command line through the "file" option.
My goal here was to avoid forcing the end user to run many make.contigs in batch mode and then use several tools (merge.files, make.group) to merge all the result files (since make.contigs is already able to do it by itself).
The new test added in the <tests> section use md5 checksums to avoid having more test …
> Make.contigs - Combo mode

- tools/taxonomy_krona_chart/taxonomy_krona_chart.xml
The `tput: No value for $TERM and no -T specified` message is sent to stderr, but the exit code remains 0.
> Better fix for running headless krona

- tools/qiime/qiime_core/core_diversity_analyses.xml
this test can be re-enabled again now that we have the extended log output timeout limit in travis.
> QIIME: re-enable alpha diversity test

- .travis.yml
It may be empty in some chunk. Reported by @nekrut.
Also:
- rename `changed_repositories_chunk.list` to `changed_repositories.list`
- run `planemo conda_install` only if `planemo test` will be run
Even with these fixes, a few things remain broken:
- `planemo shed_lint` is run on all changed repositories in each job; it should probably be split in a separate job together with `flake8`
- `planemo conda_install` is run for all changed repositories instead of the repos whose tools are going to be tested in the job (i.e. the ones in `changed_repositories_chunk.list`)
- `planemo shed_update` is badly broken on PR merge because multiple jobs may be trying to update the same repo, this one needs to be fixed ASAP (maybe using staged builds proposed by @peterjc).
> Check that changed_tools_chunk.list is also not empty

- tools/bcftools/bcftools_concat.xml
naive option needed for merging vcf files generated per chromosome:
HISAT2 -> bamtools split -reference => bcftools mpileup => bcftools
call => bcftools concat (naive) ->
> bcftools concat - add naive option

- data_managers/data_manager_gatk_picard_index_builder/data_manager/data_manager_gatk_picard_index_builder.py
The sorted_names list was extended ad infinitum. Not only did it append "_random" to all items in the list, but it kept adding it, creating an infinite list of x_random_random_random(etc.) items.
This would eat all memory until the Linux kernel would kill the process, resulting in a failure to run the data manager.
The fix makes sure the extension is evaluated after it is complete, not during completion.
> Fixed infinite loop error in data_manager_gatk_picard_index_builder

- tools/stringtie/.shed.yml
- tools/stringtie/stringtie.xml
- tools/stringtie/stringtie_merge.xml
Fix https://github.com/galaxyproject/tools-iuc/issues/1320 .
Also:
- Fix linting warnings
- Use single quotes in `<command>`
- Fix missing param labels in `stringtie_merge`
- Remove redundant option explanations in `<help>`
- Reorder XML attributes according to IUC coding style
> Add 'merge' to stringtie_merge tool name

- tools/seqtk/.shed.yml
- tools/seqtk/macros.xml
- tools/seqtk/seqtk_comp.xml
- tools/seqtk/seqtk_cutN.xml
- tools/seqtk/seqtk_dropse.xml
- tools/seqtk/seqtk_fqchk.xml
- tools/seqtk/seqtk_hety.xml
- tools/seqtk/seqtk_listhet.xml
- tools/seqtk/seqtk_mergefa.xml
- tools/seqtk/seqtk_mergepe.xml
- tools/seqtk/seqtk_mutfa.xml
- tools/seqtk/seqtk_randbase.xml
- tools/seqtk/seqtk_sample.xml
- tools/seqtk/seqtk_seq.xml
- tools/seqtk/seqtk_subseq.xml
- tools/seqtk/seqtk_trimfq.xml
- tools/seqtk/tool_dependencies.xml
Remove `tool_dependencies.xml`
Also:
- Fix `seqtk_seq` `-M` param to be of type `data`
- Single quotes around data and text params in `<command>`
- Consistent 4-spaces indentation
- Use `argument` attribute
> Condafy seqtk

- .travis.yml
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_color_space_index_builder.xml
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.py
- data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.xml
- tools/bcftools/.shed.yml
The 3 stages are:
- lint (1 job) for `flake8` and `planemo shed_lint`
- test (3 jobs) for `planemo test`
- deploy (1 job) for `planemo shed_update` to TTS and MTS
Also:
- Cache pip files
- Use `--conda_auto_install` option of `planemo test` instead of running
`planemo conda_install` beforehand. This will install only the tool
dependencies required by the tools tested in the job
xref. https://github.com/galaxyproject/tools-iuc/pull/1316#issue-230036801
Fix https://github.com/galaxyproject/tools-iuc/issues/1308.
> Use 3 build stages for Travis

- tools/jbrowse/jbrowse.py
I noticed that bam tracks generated using the jbrowse tools, once loaded into an apollo instance are not using the prettier default apollo track style.
So a little patch to fix this.
Before the patch:
And after:
> Better visualisation of bam tracks in apollo

- data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.py
- data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml
- data_managers/data_manager_humann2_database_downloader/data_manager/macros.xml
Hi,
There were a duplication of a database name in the tool data table generated by the HUMAnN2 data manager.
I fixed it  and I increased the version number.
Bérénice
> Fix a wrong database name in HUMAnN2 data manager

- tools/jbrowse/macros.xml
Updating to the latest jbrowse version 
@erasche do you prefer to merge it before or after gcc? the "name store" error message should be gone with this new version, but I haven't tested all the options
> Update Jbrowse to 1.12.3

- data_managers/data_manager_star_index_builder/data_manager/rna_star_index_builder.py
- data_managers/data_manager_star_index_builder/data_manager_conf.xml
- data_managers/data_manager_star_index_builder/tool-data/rnastar_index2.loc.sample
- data_managers/data_manager_star_index_builder/tool_data_table_conf.xml.sample
Xref: https://github.com/galaxyproject/tools-iuc/pull/1379
I remember now why I preferred `withGTF`, it made creating the dict easier since you can keep the `dict()` function call, which won't allow strings as keywords.
> Finish withGTF -> with-gtf changes in the STAR datamanager

- data_managers/data_manager_star_index_builder/tool_data_table_conf.xml.sample
The column in the [rgrnastar tool_data_table_conf.xml.sample](https://github.com/galaxyproject/tools-iuc/blob/a831282140ce160035a4ce984f48cc20198ed0a1/tools/rgrnastar/tool_data_table_conf.xml.sample) is `with-gtf`. The conflicting names prevents Galaxy from being able to merge the data tables on startup (and it therefore fails to start).
Ping @dpryan79
> Change the STAR index builder DM's sample tool_data_table_conf.xml `withGTF` column to `with-gtf` to match the tool

- data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.py
Hi,
We had an issue on the Freiburg instance that the data manager tried to update the HUMAnN2 configuration file to define the downloaded database as the reference database. But it could not access. We do not need this feature as the databases as to be always defined in the wrapper.
I hope this change will fix the issue: I just disable the update of the configuration file.
I tested the data manager in a Galaxy Docker.
Bérénice
> HUMAnN2 data manager - Disable the update of the configuration file

- data_managers/data_manager_qiime_database_downloader/data_manager/data_manager_qiime_download.py
ping @bebatut 
I had a problem with the `value` column always being `1.0` for every entry in the loc file:
```
value 	name 	dbkey 	path
1.0 	greengenes (13_8) - 79_otus 	greengenes_13_8_79_otus.fasta 	/data/galaxy/galaxy-dist/tool-data/qiime_rep_set/greengenes_13_8_79_otus.fasta
1.0 	greengenes (13_8) - 76_otus 	greengenes_13_8_76_otus.fasta 	/data/galaxy/galaxy-dist/tool-data/qiime_rep_set/greengenes_13_8_76_otus.fasta
1.0 	greengenes (13_8) - 70_otus 	greengenes_13_8_70_otus.fasta 	/data/galaxy/galaxy-dist/tool-data/qiime_rep_set/greengenes_13_8_70_otus.fasta
```
now if you select one of these in a tool (for instance `qiime_pick_closed_reference_otus`) it would always pass all files (as a comma separated list) to qiime, because all entries matched on this. I changed it so the value …
> Qiime data manager: fix value column value

- tools/raxml/.shed.yml
- tools/raxml/raxml.py
- tools/raxml/raxml.xml
- tools/raxml/tool_dependencies.xml
- Remove most of the duplication in the Python script
- Remove deprecated `interpreter` attribute of `<command>`
- Use single quotes in `<command>`
- IUC code style and indentation fixes
- Use `with` statement to open/close files
- Various fixes
> Condafy and rewrite raxml

- tools/genetrack/genetrack.xml
- tools/genetrack/genetrack_macros.xml
- tools/genetrack/genetrack_util.py
and apply recent standards to command line.  It turns out the default numpy install now uses Python 3 but the genetrack code currently supports only Python 2.
> Require Python 2 for genetrack

- tools/taxonomy_krona_chart/taxonomy_krona_chart.xml
<string>:4: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "krona".
> fixing krona warnings

- tools/enasearch/.shed.yml
- tools/enasearch/README.md
- tools/enasearch/enasearch_retrieve_analysis_report.xml
- tools/enasearch/enasearch_retrieve_data.xml
- tools/enasearch/enasearch_retrieve_run_report.xml
- tools/enasearch/enasearch_retrieve_taxons.xml
- tools/enasearch/enasearch_search_data.xml
- tools/enasearch/generate_macros.py
- tools/enasearch/macros.xml
- tools/enasearch/search_macros.xml
Add [ENASearch](https://github.com/bebatut/enasearch), a Python library for interacting with ENA's API
> Add ENASearch

- data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.py
The current HUMAnN2 data manager is broken: the downloaded files are moved into a subdirectory and HUMAnN2 can not find them. It was because the destination directory was created before. I fixed it and tested it via the TestToolShed
> Fix HUMAnN2 data manager

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
This PR has two changes
- in the output html report if only one factor was input the sample check table had extra empty columns, this fixes it to have just the single factor column that it should
-  reverting a suggested change from the previous review, reverting back to using cp instead of the suggested mv as otherwise, on downloading the report or exporting the history, the tsv files are missing, so changing back from mv to: 
`cp '$outReport.files_path'/*.tsv output_dir/ `
> Small fixes for limma-voom output

- tools/jbrowse/jbrowse.py
- tools/jbrowse/jbrowse.xml
Hey,
Just 2 quick fixes for the jbrowse tool:
- create symlinks instead of hardlinks for bigwig (otherwise it fails on my setup because you can't create hardlinks between different filesystems)
- unsanitize the track labels (as they come from element_identifier which are always sanitized by galaxy)
> Jbrowse small fixes

- data_managers/data_manager_sam_fasta_index_builder/data_manager/data_manager_sam_fasta_index_builder.xml
I've worked on testing data manager installation and table reloads in galaxy and I would like to include an integration test case that fetches a rhinovirus genome and then uses this datamanager to create an index, but samtools 0.1.19 is broken on OSX.
> Update samtools dependency for sam_fasta_index_builder dm

- tools/hisat2/hisat2.xml
Sorry to be bringing hisat2 back again! but I just discovered that I accidentally left in a bracket that means that it's producing outputs that should be filtered out 😮 I left in the last bracket here: 
`<filter>(library['type'] == 'paired' or library['type'] == 'paired_collection') and (adv['output_options']['output_options_selector'] == "advanced" and adv['output_options']['unaligned_file'] is True) </filter>`
I fixed it here. I also learnt that I can include <test expect_num_outputs="num"> to check that the correct number of outputs are produced so I've added that in.
(a slightly weird thing to me is that nothing complained about the stray bracket, not planemo lint, test or travis. I was wondering if something should or if I really do need to get myself some better 👀!)
> fix hisat2 extra outputs

- tools/rgrnastar/rg_rnaStar.xml
This fixes #1511 and adds a couple other `--limit*` options that people might occasionally want to tweak. The defaults in the wrapper match those from the command line.
> Allow STAR to use (some) --limit options

- tools/crossmap/crossmap_bam.xml
- tools/crossmap/crossmap_bed.xml
- tools/crossmap/crossmap_bigwig.xml
- tools/crossmap/crossmap_gff.xml
- tools/crossmap/crossmap_vcf.xml
- tools/crossmap/crossmap_wig.xml
- tools/crossmap/macros.xml
- tools/crossmap/test-data/cached_locally/liftOver.loc
As requested (https://biostar.usegalaxy.org/p/24086/#25011) 
It may be handier to limit the number of possible cached chain files in the dropdown to those that match the input file's dbkey.
> CrossMap: cached chain file selection dbkey sensitive

- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.xml
- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.py
- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.xml
- data_managers/data_manager_snpeff/data_manager_conf.xml
- data_managers/data_manager_snpeff/tool-data/snpeffv_annotations.loc.sample
- data_managers/data_manager_snpeff/tool_data_table_conf.xml.sample
- tool_collections/snpeff/readme.rst
- tool_collections/snpeff/snpEff.xml
- tool_collections/snpeff/snpEff_macros.xml
- tool_collections/snpeff/tool-data/snpeffv_annotations.loc.sample
- tool_collections/snpeff/tool-data/snpeffv_databases.loc.sample
- tool_collections/snpeff/tool_data_table_conf.xml.sample
- tool_collections/snpsift/snpsift/snpSift_annotate.xml
Also increase JVM maximum memory allocation to 8GB for `SnpSift annotate` tool.
> SnpEff: Remove unused data tables. Update to 4.3r

- tools/gdcwebapp/.shed.yml
- tools/gdcwebapp/gdcwebapp.xml
Galaxy tool for the GDCWebApp asynchronous data source. A detailed description of the service is reported on [https://github.com/fabio-cumbo/GDCWebApp4Galaxy](https://github.com/fabio-cumbo/GDCWebApp4Galaxy). This tool requires the improvement of the *async.py* [#4198](https://github.com/galaxyproject/galaxy/pull/4198) to work properly. It exploits the [*json_collect_data_source*](https://github.com/fabio-cumbo/galaxy-json-collect-data-source) BioConda package [#5034](https://github.com/bioconda/bioconda-recipes/pull/5034) to import and optionally organize data (in collections) into the Galaxy History.
> GDCWebApp: Asynchronous Data Source

- tools/minimap2/minimap2.xml
This avoids reference-based compression (otherwise alignments against custom
references cannot be uncompressed).
> Use no_ref option for CRAM output in minimap2

- tools/mothur/make.shared.xml
Make.shared seems to produce multiple log files in the working directory: e.g. 
`mothur.1507547483.logfile  mothur.1507547484.logfile  mothur.out.log`. Hence `mv *log outfile` gives an error: 
```
Fatal error: Exit code 1 ()
mv: target `/gpfs1/data/galaxy_server/galaxy/jobs_dir/001/1248/galaxy_dataset_2683.dat' is not a directory
```
Using cat instead works. 
Question is: is make.shared supposed to produce more than one log file? And maybe: are we interested in all?
> mothur: make.shared cat logs instead of move

- tools/ngsutils/bam_filter.xml
Not all locations on our cluster support script execution.
Without this change the tool fails with:
```
tool_script.sh: line 18: /data/users/mvandenb/gx124/data/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/ngsutils_bam_filter/9b9ae5963d3c/ngsutils_bam_filter/filter.py: Permission denied
```
> ngsutils filter: Don't rely on executable bit for python script

- tools/featurecounts/featurecounts.xml
Metadata column names had been using `$dataset.name`. This was updated
to use the newer (and often clearer) `$dataset.element_identifier`.
Fixes #1582.
> Update featureCounts column name to use `element_identifer`

- tools/megahit/megahit_wrapper.xml
Hi,
This PR adds the possibility to run MEGAHIT on paired-end data that are not in a paired-collection.
Bérénice
> MEGAHIT: enable paired-end outside of paired-collection

- tools/multiqc/multiqc.xml
Having the brackets outside of the `$` allowed Cheetah to properly parse
the variable name, but it added the bracket characters (`{` and `}`) as
strings.
> MultiQC fixed misplaced brackets {}

- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwa/bwa_macros.xml
- 4 space indentation consistently
- Command and tokens without leading indentation
- Double-quotes replaced with single quotes
Also adds multihreaded samtools sorting, which should really
speedup bwa with high GALAXY_SLOTS variables.
If you are going to review this it is probably a good idea to look
at the individual commits, to not be thrown off by the indentation
changes.
> Bring bwa/bwa-mem up to IUC standards

- tools/colibread/discosnp_RAD.xml
- tools/colibread/discosnp_pp.xml
- tools/colibread/kissplice.xml
- tools/colibread/macros.xml
- tools/colibread/mapsembler2.xml
- tools/colibread/takeabreak.xml
While looking at the failing test in #1600, I found out that the colibread tools are creating symlinks outside the working dir, so here's a fix for this problem
I still don't understand why the tests in #1600 failed, maybe it's related? Let's see if it goes green
ping @cmonjeau
> Colibread: fix symlink creation outside working dir

- tools/multiqc/multiqc.xml
Currently, it runs `mulitqc --version` rather than `multiqc --version`.
> Fix a typo in the multiqc --version command

- tools/multiqc/multiqc.xml
This primarily fixes #1581. The initial implementation of this wrapper had issues in part due to the `Status` line being stripped in the featureCounts wrapper (which is itself due to `featureCounts` not using the `element_identifier`). This PR does two things:
1. It uses the `element_identifier` if the `Status` line is empty. This respects whatever people have labeled things and plays well with dataset collections (at least in my test, since I'm using this now in our local installation).
2. If a user uploads a featureCounts summary file, then it leaves that untouched and all file names that the user originally used (outside of Galaxy) will still be displayed as normal.
Thankfully, the `featureCounts` wrapper in Galaxy doesn't run featureCounts on multiple files at once (hopefully it will …
> Fix #1581, bump multiqc wrapper version

- tools/kallisto/kallisto_pseudo.xml
- tools/kallisto/kallisto_quant.xml
- tools/kallisto/macros.xml
Per suggestion by @jxtx, it would be more accurate to refer to the reference input as a transcriptome.
> Change 'genome' to 'transcriptome'

- .travis.yml
- tools/trinity/abundance_estimates_to_matrix.xml
- tools/trinity/align_and_estimate_abundance.xml
This forces Conda to choose packages depending on r-base 3.4.1, which resolves 2 problems:
- the conda solver got stuck
- some old r-3.3.1 builds were not built with conda-build>2.0
> Update some dependencies of Trinity tools

- tools/trinity/README.rst
- tools/trinity/macros.xml
- tools/trinity/trinity.xml
Those commits will allow Trinity to support Dataset Collections of the type list of pair as Trimmomatic, bowtie2 ...
I'm aware of those 2 ongoing PR : https://github.com/galaxyproject/tools-iuc/pull/1620 and  https://github.com/galaxyproject/tools-iuc/pull/1557 and with the issue with conda https://github.com/conda/conda/issues/5536#issuecomment-350067404. But I was not sure to get spare time at the moment when those PR will be merged. So sure, at some point, I will resolve the conflict :)
In my point of view, the next move will be to handle some `.gz`?
> Trinity collection paired

- tools/trinity/trinity.xml
Added missing require parameter `genome_guided_max_intron`
Link bam file so it has a `.bam` extension which seems to be required by
Trinity's `ensure_coord_sorted_sam.pl` script.
> Fix bugs in Trinity genome guided mode

- .travis.yml
Workaround for conda/conda#5536 to properly test galaxyproject/tools-iuc#1620
> Exclude R from the channels used for testing.

- tools/bwa/bwa_macros.xml
This happens when unexpected input is provided. For instance a fa.tar file is used (I also read that spaces in the sequence may cause this message).
> bwa: added a regular expression to stdio

- tools/macs2/macs2_callpeak.xml
- tools/macs2/macs2_macros.xml
This PR has suggested modifications for MACS2, mainly because I ran into the same issue as @zfrenchee here: https://github.com/galaxyproject/tools-iuc/issues/1501
The changes here are to:
- add conditionals for more flexible handling of treatment and control inputs
- add r-base 3.4 as requirement to macros.xml (to remove of some errors due to defaulting to use R 3.2)
- change to only produce narrowPeaks file as default output
- add more info to Help section
- increase wrapper version for callpeak
@zfrenchee what do you think of the changes here for the conditionals you wanted? (here: https://github.com/galaxyproject/tools-iuc/pull/1627)
I think this should allow MACS2 to accept as input:
- single treatment/control files
- equal length treatment/control collections
- treatment …
> macs2: modify inputs, outputs, help and add r-base 3.4 as requirement

- tools/enasearch/enasearch_retrieve_taxons.xml
- tools/enasearch/macros.xml
the missing echo gives a `command not found` error on the info page of data sets created with enasearch.
> added missing echo to version command

- tools/multiqc/multiqc.xml
Hi Team, 
I am trying to use mulitiqc to summarise the outputs of 'Read Distribution from RSeQC'. I realised that this module is not working properly. The condition for 'read_distribution' is missing in the 'command' tag of multiqc.xml. I believe this pull request will fix this issue.
> fix for 'Read distribution from RSeQC' in MultiQC 

- data_managers/data_manager_fetch_gene_annotation/data_manager/data_manager.py
- data_managers/data_manager_fetch_gene_annotation/data_manager/gene_annotation_fetcher.xml
Including automatic FTP file decompression which required copy/pasting more code than I'd like to from an SO answer, but I didn't find any standard library way to do the same thing.
The existing implementation doesn't support FTP because the `requests` package doesn't support FTP. There's a requests_ftp package but it's pretty shoddy and doesn't do the automatic decompression that HTTP gets.
> Add FTP support

- tools/bowtie2/bowtie2_wrapper.xml
This contains some important upstream bugfixes and a new  "continuous FASTA" input format (-F) for aligning all the k-mers in the sequences of a FASTA file (not implemented in the wrapper yet).
> Bump bowtie2 version to 2.3.4

- .travis.yml
The new [4.3.33 release](https://github.com/conda/conda/releases/tag/4.3.33) contains an important bugfix for the dependency resolver: https://github.com/conda/conda/pull/6766
> Use conda 4.3.33

- tools/unicycler/unicycler.xml
This release of unicycler introduces new option `--existing_long_read_assembly`. Unfortunately it cannot yet be used in our case because Racon bioconda package is in conflict with unicycler due to zlib version incompatibility.
> Update to version 0.4.4

- tools/taxonomy_krona_chart/.shed.yml
- tools/taxonomy_krona_chart/taxonomy_krona_chart.xml
I made a tool to convert mothur taxonomy files to krona text input format, so it is no longer restricted to MetaPhlAn output, changed wording to reflect this.
ping @bebatut
> Krona: make wording for text input more generic

- tools/deseq2/deseq2.xml
this is required by out wrapper in https://github.com/galaxyproject/tools-iuc/blob/76065f751b678abf87e6c723be680fecaa8cb589/tools/deseq2/deseq2.R#L240, which is not always used, but it will be used for running deseq2 on salmon data.
> Add genomicfeatures to requirements

- tools/iwtomics/macros.xml
The citation to the Bioconductor package has been replaced with the doi to the published article on [Bioinformatics](https://doi.org/10.1093/bioinformatics/bty090).
> IWTomics: updating citations

- tools/rgrnastar/rg_rnaStar.xml
This feature is now available in STAR 2.5 and I would really like to use it.
> STAR: Add two pass mode

- tools/lastz/lastz.xml
- tools/lastz/lastz_d.xml
- tools/lastz/lastz_macros.xml
Having `fasta.gz` and `fastq.gz` causes errors as these datatypes are not understood by `lastz`. The conversion will be taken care by implicit converted I previously added during lastz rewrite
> fixed input datatypes for lastz

- tools/msaboot/msaboot.xml
Replaced use of AlignIO.write with custom implementation to output in relaxed PHYLIP format. I am updating the wrapper accordingly.
> Update Msaboot to version 0.1.2 - support relaxed PHYLIP output

- tools/fastp/fastp.xml
- tools/fastp/macros.xml
Now that I've tried fastp a bit I have some suggestions for modifications to the wrapper here:
- add sample id (element identifier) to report title
- group and reorder options similar to Cutadapt
- bump wrapper version (because of changing output - adding sample id above)
> Fastp - minor modifications

- tools/umi_tools/umi-tools_whitelist.xml
Logs were bleeding into the whitelist output. Now it just prints to stderr.
> umi_tools extract: log2sterr fix

- tools/collection_column_join/collection_column_join.xml
- tools/collection_column_join/test-data/out_3.tabular
- tools/collection_column_join/test-data/out_4.tabular
Hi,
A new little option for the collection_column_join tool, we'll need it in a workflow.
The option makes more sense when joining multiple files with 2 column (ie id -> value). It allows to keep only the dataset name as column header instead of <dataset_name>_<col_name>.
> Collection column join: add new 'Keep original column header' option

- tool_collections/snpeff/snpEff_create_db.xml
Without this addition, snpEff will report the following error when using a custom-built database for annotating variants:
`java.lang.RuntimeException: Property: '$__DBKEY__.genome' not found
at org.snpeff.interval.Genome.<init>(Genome.java:106)
at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:681)
at org.snpeff.snpEffect.Config.readConfig(Config.java:649)
at org.snpeff.snpEffect.Config.init(Config.java:480)
at org.snpeff.snpEffect.Config.<init>(Config.java:117)
at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:1000)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:984)
at org.snpeff.SnpEff.run(SnpEff.java:1183)
at org.snpeff.SnpEff.main(SnpEff.java:162)`
> Also generate or append snpEff.config file.

- tools/mageck/mageck_count.xml
Just found the new version of mageck count still fails if you run it on a "Tool on data N" file. I should have also added the quotes to the symlink! Fixed here.
> MAGeCK: Also add single quotes in symlink in mageck count

- tools/stringtie/stringtie.xml
Sort only on the first column, otherwise an output count file may become something like:
```
G1000	2
G100	1
G1001	2
G1002	2
```
instead of:
```
G100	1
G1000	2
G1001	2
G1002	2
```
> Fix sorting of rows in StringTie outputs

- tools/edger/edger.R
- tools/edger/edger.xml
- tools/edger/test-data/anno.txt
- tools/edger/test-data/out_rscript.txt
- Add similar changes as recently made for it's twin tool limma-voom (https://github.com/galaxyproject/tools-iuc/pull/1830 and https://github.com/galaxyproject/tools-iuc/pull/1871)
- Allow unordered annotations to be input
- Remove quotes from output tables
- Minor edits to text
- Fix MD plot highlighted genes
- Fix typo in report for CPM counts
- Add colours to samples in MDS plot pdf
- Output additional MDS plots if additional factors input (samples coloured by factors)
> EdgeR: fixes and improvements to output with annotations, plots and report

- tools/crossmap/crossmap_bam.xml
- tools/crossmap/crossmap_bed.xml
- tools/crossmap/crossmap_bigwig.xml
- tools/crossmap/crossmap_gff.xml
- tools/crossmap/crossmap_vcf.xml
- tools/crossmap/crossmap_wig.xml
- tools/crossmap/macros.xml
No need to use `lines_diff` (there are no randomly changed lines in the SAM version of the BAMs).
But we need to specify `ftype="bam"` for the output data, otherwise Galaxy won't convert them to SAM when checking the outputs and fail with:
```
======================================================================
FAIL: CrossMap BAM ( crossmap_bam ) > Test-1
----------------------------------------------------------------------
File "/opt/galaxy/test/functional/test_toolbox.py", line 316, in test_tool
self.do_it(td)
File "/opt/galaxy/test/functional/test_toolbox.py", line 82, in do_it
raise e
JobOutputsError: History item  different than expected, difference (using diff):
( /usr/users/ga002/soranzon/software/nsoranzo_tools-iuc/tools/crossmap/test-data/test …
```
> Update CrossMap to 0.2.7. Fix crossmap_bam tests

- tools/featurecounts/featurecounts.xml
@jennaj I've added info on the built-in annotation now and moved up the stranded parameter out of Advanced options, as discussed in Gitter. What do you and/or anyone else think.
> FeatureCounts: small modifications (move up stranded param and add info on built-in annotation to Help)

- tool_collections/bamtools/bamtools_filter/bamtools-filter.xml
Fixes the job setup error encountered when a rule is defined:
```pytb
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 191, in prepare_job
job_wrapper.prepare()
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 865, in prepare
self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 435, in build
raise e
TypeError: <galaxy.tools.wrappers.InputValueWrapper object at 0x7f2929ada2d0> is not JSON serializable
```
I am not sure if this worked in some older version of Galaxy and failed due to tool framework changes, but this fixes it for 18.05, at least.
Originally reported in …
> Explicitly cast BamTools Filter's rules param to a string

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
as otherwise it will throw a wobbly. NAs are handled in the current Glimma version (1.18.1) but can't use that version yet as need to wait for Bioc 3.7 conda support. So in the interim have fixed it in the limma-voom wrapper here.
> Limma-voom: Make gene labels unique for Glimma plot to prevent errors with NAs

- tools/featurecounts/featurecounts.xml
I should have added this line in the last PR.
> FeatureCounts: Add how to get gene names for Entrez identifiers to Help section

- tools/picard/picard_AddCommentsToBam.xml
- tools/picard/picard_AddOrReplaceReadGroups.xml
- tools/picard/picard_BedToIntervalList.xml
- tools/picard/picard_CleanSam.xml
- tools/picard/picard_CollectAlignmentSummaryMetrics.xml
- tools/picard/picard_CollectBaseDistributionByCycle.xml
- tools/picard/picard_CollectGcBiasMetrics.xml
- tools/picard/picard_CollectInsertSizeMetrics.xml
- tools/picard/picard_CollectRnaSeqMetrics.xml
- tools/picard/picard_CollectWgsMetrics.xml
- tools/picard/picard_DownsampleSam.xml
- tools/picard/picard_EstimateLibraryComplexity.xml
- tools/picard/picard_FastqToSam.xml
- tools/picard/picard_FilterSamReads.xml
- tools/picard/picard_FixMateInformation.xml
- tools/picard/picard_MarkDuplicates.xml
- tools/picard/picard_MarkDuplicatesWithMateCigar.xml
- tools/picard/picard_MeanQualityByCycle.xml
- tools/picard/picard_MergeBamAlignment.xml
- tools/picard/picard_MergeSamFiles.xml
- tools/picard/picard_NormalizeFasta.xml
- tools/picard/picard_QualityScoreDistribution.xml
- tools/picard/picard_ReorderSam.xml
- tools/picard/picard_ReplaceSamHeader.xml
- tools/picard/picard_RevertOriginalBaseQualitiesAndAddMateCigar.xml
- tools/picard/picard_RevertSam.xml
- tools/picard/picard_SamToFastq.xml
- tools/picard/picard_SortSam.xml
- tools/picard/picard_ValidateSamFile.xml
- tools/picard/picard_macros.xml
I recently ran into a problem with `picard` running out of disk space on our cluster as it was writing to `/tmp` on worker nodes. This behaviour is controlled by the TMP_DIR command line parameter to the picard tools. This PR adds this parameter to each wrapper and propagates the setting from the `$TEMP` environment variable
The Galaxy admin can set `$TEMP` using a `<env>` clause in `job_conf.xml`. For jobs running with the local job runner `$TEMP` is [already set](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/local.py#L50) by default.
An alternative way to set the temporary working directory for picard would be to set `-Djava.io.tmpdir=` to a sensible value as recommended on [Biostars](https://www.biostars.org/p/42613/). The effect seems to be the same as …
> Add @TMPDIR_OPTION@ to set working directory

- tools/bedtools/intersectBed.xml
Small change due to a fatal error when no overlap mode is selected. Leading to:
***** ERROR: Unrecognized parameter: None *****
However the intersect tool of bed allows for a default behavior which is not supported if the user is forced to pick an overlap mode.
> Small Change to intersectBed.xml

- tools/hisat2/hisat2.xml
Currently hisat2 and samtools sort run in parallel each with the full number of threads (ie in theory up to 2x GALAXY_SLOTS). 
The suggested solution tries to reduce the over-usage, ie. it would use at most one CPU more than GALAXY_SLOTS. 
see also https://github.com/samtools/samtools/issues/891
I you think this is not a good idea we could serialize hisat2 and samtools sort using a temporary file. 
(plus samtools is updated to 1.8)
> hisat2 serialize samtools

- .github/PULL_REQUEST_TEMPLATE.md
From the Tools IUC meeting at GCC this year, I was tasked with working on a review checklist. I thought that having a PR checklist template similar to the bioconda-recipes repo would be useful here as well. This is a WIP and please comment!
> First go at a PR template for tools-iuc

- tools/ggplot2/heatmap2.xml
FOR REVIEWER:
This is a request from a user. If you select not to cluster the input still gets reordered. This fixes that and maintains the input order.
> Heatmap.2: don't reorder input if not clustering

- tools/jcvi_gff_stats/jcvi_gff_stats.xml
FOR REVIEWER:
A tiny PR to fix the output name
> jcvi_gff_stats: fix output display name

- tools/migmap/migmap.xml
> migmap does create blast databases relative to the conda directory

- tools/cutadapt/cutadapt.xml
FOR REVIEWER:
If a paired collection is input to cutadapt the cutadapt report doesn't work well with multiqc, as multiqc uses the R2 name and currently in the cutadapt wrapper `input_r` is being used for all samples e.g see below (so multiqc can't differentiate different samples):
```
This is cutadapt 1.16 with Python 3.6.4
Command line parameters: -j 1 --format=fastq --output=out1.gz --paired-output=out2.gz --error-rate=0.1 --times=1 --overlap=3 --minimum-length=20 --pair-filter=any --quality-cutoff=20 ERR188044.fq.gz input_r.fq.gz 
```
This PR is a fix for this, it adds a _1 and _2 to the paired collection fastq names.
> Cutadapt: fix for paired collection for multiqc

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
> Limma-voom: add option to output filtered count matrix

- tools/fastp/fastp.xml
- tools/fastp/macros.xml
> fastp: update to version 0.19.3

- tools/gtfToBed12/gtfToBed12.xml
FOR REVIEWER:
This PR adds `label=` with BED12 or Table to the two outputs as they currently both get the same name.
> gtfToBed12: Add label to outputs to distinguish BED12 from table

- tools/multiqc/multiqc.xml
FOR REVIEWER:
This adds the element_identifier to RSeQC Infer Experiment results (at the moment you get "file_0_infer_experiment", "file_1_infer_experiment" used as the names in the MultiQC report)
> MultiQC: Add element_identifier to RSeQC Infer Experiment

- tools/fastp/fastp.xml
- tools/fastp/macros.xml
No other changes so far.
FOR REVIEWER:
> Parameterize repeated fastp parameters and add paired collection

- tools/xpath/tool_dependencies.xml
Found in a local admin training.
FOR REVIEWER:
> remove tool_dependencies from xpath

- tools/umi_tools/umi-tools_extract.xml
The umi-tools whitelist tool outputs a tabular barcode file but at the moment the umi-tools extract tool only accepts a tsv barcode file as input. This PR enables the whitelist tabular output to be input to umi-tools extract.
FOR REVIEWER:
> UMI-tools: Allow tabular barcode file input to umi-tools extract

- tool_collections/fastx_toolkit/fasta_nucleotide_changer/fasta_nucleotide_changer.xml
- tool_collections/fastx_toolkit/fastq_quality_filter/fastq_quality_filter.xml
- tool_collections/fastx_toolkit/fastq_to_fasta/fastq_to_fasta.xml
- tool_collections/fastx_toolkit/fastx_artifacts_filter/fastx_artifacts_filter.xml
- tool_collections/fastx_toolkit/fastx_clipper/fastx_clipper.xml
- tool_collections/fastx_toolkit/fastx_renamer/fastx_renamer.xml
- tool_collections/fastx_toolkit/fastx_reverse_complement/fastx_reverse_complement.xml
- tool_collections/fastx_toolkit/fastx_trimmer/fastx_trimmer.xml
- tool_collections/fastx_toolkit/macros.xml
From working on https://github.com/galaxyproject/tools-iuc/pull/2042 I found that there are other fastx tools that would likely have a similar issue to the one reported by @hepcat72 here: https://github.com/galaxyproject/tools-iuc/issues/2036 (e.g. outputting fastq but giving it the datatype fastq.gz). So in this PR I've added the -z flag to the tools listed below, the tools that have the -z option listed on the [fastx website](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html).
-  fastq_to_fasta
-  fastx_clipper 
-  fastx_renamer 
-  fastx_artifacts_filter
-  fastq_quality_filter
-  fastx_reverse_complement
-  fasta_nucleotide_changer
Should I increase the wrapper versions here or not?
FOR REVIEWER:
> Fastx_toolkit: Fix gzip outputs

- tools/fastp/fastp.xml
Get error if selecting polyX and disabling polyG due to small copy/paste bug. Fixed in this PR and test added.
FOR REVIEWER:
> fastp: Fix for polyX when disabling polyG

- tool_collections/snpeff/snpEff_databases.xml
Added an underscore as an allowed character for the include and exclude patterns.
Underscores are found frequently in genome names/versions, e.g. "Bacillus_subtilis_subsp_subtilis_str_168".
FOR REVIEWER:
> SnpEff genome/version names can have underscores

- tools/jbrowse/jbrowse.py
'Search for a feature' functionality is not working since the function 'generate_names()' is never called.
FOR REVIEWER:
> Update jbrowse.py : fix for 'Search for a feature' functionality

- tools/hisat2/hisat2.xml
I was trying to run hisat2 with the --seconday flag, but it would just hand forver.
Upon closer inspection I saw there is no `--secondary` flag anymore, and neither is `--max-seeds`
FOR REVIEWER:
> hisat2: Drop --secondary and --max-seeds, which don't seem to exist anymore

- tool_collections/snpeff/snpeff_get_chr_names.xml
The names and lengths are extracted from the selected snpEff database.
Files checked in: tool_collections/snpeff/snpeff_get_chr_names.xml
FOR REVIEWER:
> Initial commit of a tool to output chromosome names and lengths in a tab delimited file.

- tools/jbrowse/jbrowse.py
- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
FOR REVIEWER:
Working on https://github.com/galaxyproject/training-material/pull/950, I have some gff which contains match/match_part features, but with varying parent type name (match, expressed_sequence_match, protein_match) in the same file. Currently I can't display all the features with their subfeatures as I'm forced to specify a single parent type.
In fact CanvasFeatures tracks don't really need to specify it, by default it will auto detect everything. So here's a patch to allow leaving the option empty and let it be autodetected.
For HTMLFeautres track type, it will just display features but not subfeatures which is not dramatic I think (same as if I entered the wrong name in the field).
What do you think @erasche?
> Jbrowse: small change to match/match_part tracks

- tools/rseqc/geneBody_coverage.xml
Can tool names be changed? Can this tool name be changed to `Gene Body Coverage (BAM)` instead of the current name that has a typo (`Gene Body Converage (BAM)`) ? As `Gene Body Converage (BAM)` is what is used as the collection name in the history, see below.
Same typo is in the related `Gene Body Converage (Bigwig)` tool.
FOR REVIEWER:
> Fix typo in Gene Body Coverage tool name?

- tools/filtlong/filtlong.xml
> Filtlong: Change fastq output to fastqsanger

- tools/porechop/porechop.xml
> Porechop: Change fastq output to fastqsanger 

- tools/unicycler/unicycler.xml
> unicycler: change output GFA to tabular

- tools/featurecounts/featurecounts.xml
For the To do `Add "counts" in FeatureCounts file name (in the tool)` here: https://github.com/galaxyproject/training-material/issues/1006#issuecomment-424038382
Not sure if this is the best naming to use, if there are better ideas let me know!
FOR REVIEWER:
> featureCounts: Try to clarify the different outputs in the labels

- tools/rseqc/geneBody_coverage.xml
Addresses the issue discussed in 
https://github.com/galaxyproject/galaxy/issues/6182
FOR REVIEWER:
> Fix output names for RSeQC gene body coverage when processing collection

- tools/rseqc/inner_distance.xml
- tools/rseqc/tin.xml
> Fixed some linting errors.

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
output separately instead of within collection
FOR REVIEWER:
> Limma-voom: Output normalised and filtered counts outside collection

- data_managers/data_manager_fetch_refseq/.shed.yml
- data_managers/data_manager_fetch_refseq/data_manager/fetch_refseq.py
- data_managers/data_manager_fetch_refseq/data_manager/fetch_refseq.xml
- data_managers/data_manager_fetch_refseq/data_manager_conf.xml
- data_managers/data_manager_fetch_refseq/test-data/plastid.json
- data_managers/data_manager_fetch_refseq/tool-data/all_fasta.loc.sample
- data_managers/data_manager_fetch_refseq/tool_data_table_conf.xml.sample
> Data manager to fetch RefSeq FASTA

- tools/circos/macros.xml
> Update libgd in circos since it  doesn't pass planemo test (Error:  missing GD)

- tools/stacks/stacks_genotypes.xml
The terms 'whitelist' and 'blacklist' for inclusion or exclusion have undesirable associations, making it better to use more neutral language.
See also "Be careful in the words that we choose" in the main Galaxy Project Code of Conduct,
https://github.com/galaxyproject/galaxy/blob/dev/CODE_OF_CONDUCT.md and #2123 
Here we can't change the parameter names without breaking backward compatibility, so this is a cosmetic change only. The command line arguments -B and -W remain, but this reflects the underlying tool itself.
FOR REVIEWER:
> Avoid blacklist/whitelist in user-facing stacks genotypes text

- tool_collections/samtools/samtools_depth/.shed.yml
- tool_collections/samtools/samtools_depth/samtools_depth.xml
Adds missing shed yml file for samtools depth (also fixes a wrong macro name). 
Two questions: 
- the other samtools yml files have mixed devteam / iuc owners. I guess this is intended? 
- samtools certainly could need a suite definition. It would be great if this could be included .. maybe in this PR? I would need some information how this can be done. As far as I see its now done in the shed.yml files, but the documentation is still sparse.
FOR REVIEWER:
> samtools: added missing .shed yml for depth

- tools/macs2/macs2_callpeak.xml
Also:
- use the `argument` attribute
- fix tables in tool help
FOR REVIEWER:
> Removal `optional="true"` from boolean params

- tools/picard/picard_EstimateLibraryComplexity.xml
- tools/picard/picard_MarkDuplicates.xml
- tools/picard/picard_MarkDuplicatesWithMateCigar.xml
- tools/picard/picard_macros.xml
* [ x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x] - License permits unrestricted use (educational + commercial)
* [ x] - This PR updates an existing tool or tool collection
FOR REVIEWER:
> Avoid Python2-specific imports in picard tool wrappers

- tools/exonerate/exonerate.xml
FOR REVIEWER:
A little fix for the output format of exonerate
> Exonerate: fix output format

- tools/trinity/macros.xml
- tools/trinity/trinity.xml
FOR REVIEWER:
A little patch to fix #2143 (thanks for reporting @alpapan!)
> Trinity: fix option name

- tools/spotyping/spotyping.xml
> Switch error checking to aggressive

- tools/cutadapt/cutadapt.xml
> cutadapt: removed duplicate dollar

- tools/shovill/shovill.xml
This new version of Shovill adds support for multiple assemblers including: Spades, Velvet, Skesa and Megahit.
FOR REVIEWER:
> Upgraded shovill to version 1.0.4, including multiple assembler support

- tools/hisat2/hisat2.xml
If a user choses the advanced reporting options (eg just to check which options are available) and does not specify a value for `-k` then hisat crashed. 
The crashing behaviour was quite odd 
hisat reports: `(ERR): hisat2-align exited with value 1`
but the hisat2 perl wrapper and samtools were still running with 0 CPU load. 
FOR REVIEWER:
> hisat2: fix failing when -k is unspecified

- tools/deseq2/deseq2.R
- tools/deseq2/deseq2.xml
This pull request add additional features for deseq2 wrapper such as choosing method for estimatesizefactors, generate vst normalization file and rlog normalization file. Changing method for estimateSizeFactor will be helpful when the user gets error message like `Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : every gene contains at least one zero, cannot compute log geometric means`. 
FOR REVIEWER:
>  DESeq2: estimatesizefactors, vst normalization and rlog normalization

- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
FOR REVIEWER:
Fix https://github.com/galaxyproject/tools-iuc/issues/2174
> jbrowse: track type Bigwig defaults to autoscale "local"

- tools/meme/fimo.xml
> add validator to motif-id param

- tools/mummer4/mummer.xml
A single quote needs to be removed from the tools/mummer4/mummer.xml.
FOR REVIEWER:
> [FIX] mummer4: Remove extra single quote

- tools/spades/spades.xml
FOR REVIEWER:
Hi,
A fix for a little bug found by one of our user: when using fastqsanger input files for spades, you had an error like this:
`== Error ==  file not found: /galaxy/database/jobs_directory/000/125/125750/working/fastqsanger://galaxy/database/files/002/114/dataset_2114659.dat (interlaced reads, library number: 1, library type: paired-end)`
> Spades: fix error with fastsanger input datatype

- tools/busco/busco.xml
* Set AUGUSTUS_CONFIG_PATH for all use cases
* Copy Augustus config for all use cases (this needs to be writeable)
NOTE: Correct operation relies on BLAST+ < 2.4, this is supported from bioconda recipe for v. 3.0.2 built 9
FOR REVIEWER:
> Busco bugfix (AUGUSTUS_CONFIG_PATH issue)

- tools/repeatmasker/repeatmasker.xml
Current recipe produces a not-helpful error message if RepeatMasker is not in the PATH. This adds a check and more useful error message.
FOR REVIEWER:
> Test for RepeatMasker in PATH

- data_managers/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py
By generating a minimal configuration file before gemini first
tries to access it, we avoid potential issues with existing config
files in other places and do not have to rely on the gemini
--annotation-dir option to specify the annotation file download
location.
FOR REVIEWER:
> Simplify and document the logic of the gemini data manager

- tools/volcanoplot/volcanoplot.R
- tools/volcanoplot/volcanoplot.xml
Fix for labelling genes, as currently all significant genes get labelled unless a file of genes is supplied, the options for selected labelling are being ignored.
FOR REVIEWER:
> Volcano plot: Fix for labelling genes

- tool_collections/vcflib/vcffilter/vcffilter.xml
This PR makes the following updates to the VCFFilter:
1. Update the documentation of VCFFilter for more intuitive description of how to specify filters;
2. Ignore `"` (double-quotation) and `'` (single-quotation) for the filter field (if given, the wrapper removes the quotations);
3. Require at least one filter.
> Updates to VCFFilter documentation and filter field

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
- tools/limma_voom/test-data/factorinfo.txt
- adds some more interactive Glimma plots (MDS and volcano)
- makes Glimma output an option
- adds plot of final-mean variance trend (SA plot)
- adds reorder of samples info file in case of incorrect order
- small edits to text
FOR REVIEWER:
> Limma: some edits

- tools/featurecounts/featurecounts.xml
subread 1.6.3 is a bugfix release (http://subread.sourceforge.net/), no new options were added.
FOR REVIEWER:
> Add paste to requirements and bump subread version

- .gitignore
since I often missed to commit *log test data and was wondering why tests failed... 
I guess there is no django involved here, but the original entry was copied from somewhere 
FOR REVIEWER:
> gitignore: removed *log

- tool_collections/samtools/samtools_stats/samtools_stats.xml
Noticed this when running containerized tool tests.
FOR REVIEWER:
> samtools_stats: add perl for plot-bamstats

- tools/goenrichment/.shed.yml
Fix for https://travis-ci.org/galaxyproject/tools-iuc/jobs/477022128
FOR REVIEWER:
> Fix ToolShed category for GoEnrichment tools

- data_managers/data_manager_fetch_refseq/data_manager/fetch_refseq.xml
A bug occurs if advanced is selected and compression is not selected - it results in a spurious '' in the command line. This patch fixes that and bumps the tool wrapper version (and adds a test for this case).
FOR REVIEWER:
> Fix bug with advanced + no compress

- tools/shorah/test-data/shorah-amplicon-out1.txt
Test is failing on master because the current test data has too many significant digits.
> Fix ShoRAH tests.

- tool_collections/kraken/kraken/kraken.xml
- tool_collections/kraken/kraken_databases.loc.sample
- tool_collections/kraken/macros.xml
- tool_collections/kraken/test_database.loc
This would close #2079 by bringing the use of ``kraken_databases.loc`` in line with typical usage.
(*update:* This branch originally included work since merged as the earlier narrower pull request #2077).
FOR REVIEWER:
> Standardise kraken_databases.loc fields

- tools/jbrowse/jbrowse.py
- tools/jbrowse/macros.xml
FOR REVIEWER:
A little fix for the current jbrowse tool: now the plugins are loaded from cdn.jsdelivr.net instead of (the dead) rawgit.com. Without this you get a red scary error in the output dataset.
Fixing it in this 1.12.5 version as it is broken, and because the 1.16.1 version in https://github.com/galaxyproject/tools-iuc/pull/1683 no longer supports external plugins for now.
> Jbrowse: replace cdn.rawgit.com by jsdelivr.net

- tools/fastp/fastp.xml
- tools/fastp/macros.xml
> update fastp to 0.19.5

- tools/gemini/gemini_annotate.xml
This functionality was always present in the gemini `annotate` command line tool, but was not previously exposed through the tool wrapper interface. This changeset improves also tool parameter help and removes major parts of the tool help that were describing command line issues not relevant in Galaxy.
> Allow multiple annotations to be extracted with gemini annotate.

- tools/slamdunk/slamdunk.xml
This PR adds `multiple = True` to slamdunk fastq input as otherwise all samples get the same read group ID and SM and then don't work with Alleyoop.
> Slamdunk: add multiple=True to fastq to work with Alleyoop

- tools/varscan/varscan.py
The genotype fields modifications introduced in #2246 of the tool turned out to result in core dumps with real-world data with high coverage.
The issue is that htslib will allocate a fixed amount of space for each value of a given genotype field, when that field is first modified for any sample in a variant record. The amount of space depends on the
size of the largest value stored in the field for the sample and later attempts to add a value requiring more space to the same field (even for a different sample) will trigger the assert:
https://github.com/pysam-developers/pysam/blob/fadbafbe03c4340a6b817a07c408e7aa293bd5ef/htslib/vcf.c#L3496
resulting in a core dump.
This is fixed in this PR by modifying each genotype field starting with the sample that has the largest value for the field. …
> Fix genotype fields standardization of varscan_somatic

- tools/goseq/goseq.r
- tools/goseq/goseq.xml
Updates goseq to v1.32.0, updates dependencies, and changes plot of top 10 to raw P value instead of adj P
> Goseq: update to v1.32.0

- tools/emboss_5/emboss_seqret.xml
- tools/emboss_5/macros.xml
I found that emboss' seqret gives a specific message on insufficient memory: `Uncaught exception:  Allocation failed, insufficient memory available, raised at ajstr.c:2089`
So I added a stdio tag that detects this. Could be added to all tools. Even if the emboss documentation suggests that the error code is always 0 this was not the case here. So I left the exit code 1: detection. I you think this is useful I could add it to all other tools of the suite.
Question is `<code file="emboss_format_corrector.py" />` used at all? When is this called? I could not find a corresponding call in the job directory.
> detection of insufficient memory for seqret (EMBOSS)

- tools/deseq2/deseq2.R
- tools/deseq2/deseq2.xml
> Add parallel keyword to deseq2

- tools/deseq2/deseq2.xml
- tools/deseq2/deseq2_macros.xml
The idea here is that the user tags elements of a collection using tags that
start with `group:`. All of these tags can then be selected in the tool
form when choosing the factor levels.
This makes it very easy to select dataset combinations of interest
without having to re-shape collection contents for every contrast.
Technically the input does not need to be a collection, a
multiple="true" data input also works, but is currently not testable.
We might change this in the future.
The previous way of doing the analysis is still the default way of
using deseq2, as we currently don't auto-propagate group tags.
So in order to use this new feature users either have to manually tag collection
elements or use the `Tag elements from file from contents of a file`
to set the group tags. Hopefully …
> Use new group_tag parameter to allow selecting collection subsets

- tools/edger/edger.R
- tools/edger/edger.xml
- updates edgeR to v3.24.1 and limma dependency to v3.38.3
- plus a couple of minor changes for more robust handling of potential issues with inputs
> edgeR: update to v3.24.1 and handle single quotes if present in input annotation

- tools/edger/edger.R
- tools/edger/edger.xml
- Fix for output DE tables if changing FDR method (currently always using BH method), as reported by @bimbam23 here: https://github.com/galaxyproject/tools-iuc/issues/2283
- Clarify group names etc should not start with a number as reported by m93 here: https://help.galaxyproject.org/t/edger-error-for-paired-differential-expression-analysis/543/2
> edgeR: fix for changing FDR method and clarify group naming

- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
- tools/jbrowse/readme.rst
A little update to jbrowse 1.16.2 + added NeatHTMLFeature and NeatCanvasFeature track types (recommended now in apollo 2.3)
> Jbrowse: update to 1.16.2 + neatfeatures

- tools/jbrowse/jbrowse.py
- tools/jbrowse/macros.xml
Use gff3sort to properly sort gff files (in some cases `gene` features could be moved after their `mRNA` which jbrowse didn't like at all)
> Jbrowse: fix gff3 sorting

- tools/flash/flash.xml
If you submit fastqsanger.gz, the -p value of the command is 64 instead of the correct 33 and the tool fails.  This should fix that issue.
> Fixes wrong p value when processing g-zipped fastq

- tools/jbrowse/jbrowse.xml
- tools/jbrowse/test-data/gff3/test.xml
A little bug fix for the jbrowse tool: when you add bam tracks on a genome with many scaffolds/contig, the resulting trackList.json contains all the scaffold/contig names in a reference_names metadata. In my case the trackList.json was 175Mb and I just couldn't load with chrome
So here's a patch to just ignore too big metadata. "Too big" it 20000 chars, but I can change it of course
> JBrowse: fix huge trackList.json

- tool_collections/samtools/samtools_sort/samtools_sort.xml
I have added "unsorted.bam", "qname_sorted.bam" and "qnamed_input_sorted.bam" as input types to samtools_sort. This is needed to support the following workflow:
1. samtools_fixmate, which outputs "qname_sorted.bam"
2. samtools_sort, to coordinate sort, outputs "bam"
3. samtools_markdup
Currently, samtools_sort requires "bam" as input. so the workflow above is not possible to make.
(Automatically changing the output of samtools_fixmate to "bam" in the workflow triggers indexing, which fails (with a very strange error message) due to the file not being coordinate sorted, so that is not a solution)
> Samtools_sort: support for new BAM datatype variants

- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
- tools/jbrowse/readme.rst
- tools/jbrowse/test-data/gff3/test.xml
There's a brand new 1.16.4 of jbrowse with a few bug fixes I'm interested in, so here's the update.
Removed the default value topLevelFeatures as it should not be needed anymore in most cases (https://github.com/GMOD/jbrowse/pull/1340)
Also switched back to the `feature` default classname as the styling was fixed too in 1.16.4
I also decreased the threshold for filtering long metadata, I found a 500kb trackList.json which made the page loading veeery slow, it should be better like this.
> JBrowse: 1.16.4

- tools/macs2/macs2_callpeak.xml
- tools/macs2/macs2_filterdup.xml
- tools/macs2/macs2_predictd.xml
- tools/macs2/macs2_randsample.xml
- tools/macs2/macs2_refinepeak.xml
As macs2 seems to have difficulties with sam input.
If there's still some use for sam input the implicit conversion
will be used.
Closes https://github.com/galaxyproject/tools-iuc/issues/2313
> Drop sam input from macs2

- tools/trinity/analyze_diff_expr.xml
- tools/trinity/define_clusters_by_cutting_tree.xml
The RData datatype is not in lowercase in trinity, it made it impossible to add a spaghetti between the two tools in workflow editor
done with @r1corre
> Trinity: fix rdata datatype name

- tools/qiime/qiime_core/make_otu_heatmap.xml
- tools/qiime/qiime_core/split_libraries.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/2380
the quality file output gets an invalid datatype, I changed it to use `format_source` and match the datatype of the input quality file.
ping @erasche 
> qiime split_libraries: fix datatype of qual output

- tools/maker/macros.xml
- tools/maker/maker.xml
FOR REVIEWER:
A minor update for maker, and also added support for MPI (finally found a way to avoid systematic segfault).
I'm a little nervous with the MPI stuff, but tests are ok (= in a non-cluster environment) and it seems to work fine on our cluster with a properly configure job destination.
> Maker: update 2.31.10 + add support for mpi

- tools/maker/maker.xml
So I've tried running Maker on usegalaxy.eu, but got this error:
```
ERROR: Temporary directory set to an NFS location.
TMP=/data/dnb02/galaxy_db/job_working_directory/005/232/5232283/tmp
The temporary directory in MAKER is specifically for
operations that are not NFS-safe. You must set TMP
to a locally mounted directory such as /tmp or add
--ignore_nfs_tmp to the maker command line to
override this error message.
```
So adding the `--ignore_nfs_tmp` option in case (I hope) maker would be able to complete the job even if tmp dir is on nfs...
> Maker: allow running with TMP on NFS

- tool_collections/vcflib/vcffilter/vcffilter.xml
Operators such as "<=" or ">=" are not accepted by this tool, tool help form clearly says what are the valid operators, but it seems still users provide some unsupported operators.
ping @jennaj
> VCFFilter: Add an assertion for common incorrect operators.

- tools/augustus/augustus_training.xml
- tools/snap/snap_training.xml
A fix for snap and augustus tools used by the Maker tutorial: the 2.31.9 version of maker still depends on perl-threaded which make the tool fail. 2.31.10 is the good one to use now
> Snap and augustus: update maker dependency

- tools/busco/busco.xml
Pinning the augustus version as version 3.3 makes busco fail silently (=empty results)
> Busco: pin augustus version

- tools/fastqc/rgFastQC.xml
Follow-up on commit 6bcb3493aa6126bb1ccf93b7646fbb919bc374a1 .
> Reduce lines_diff for fastqc tests

- tools/bcftools/bcftools_mpileup.xml
fix bug where 'Per-Base Alignment Quality' select param where put 'None' when no option was selected causing command to fail.
> fix bug where 'Per-Base Alignment Quality' select param which fails cmd

- tools/fastp/fastp.xml
otherwise multiple grey data sets are generated due to https://github.com/galaxyproject/galaxy/issues/8041
> fastp: use format_source instead of structured_like

- tools/limma_voom/limma_voom.R
- tools/limma_voom/limma_voom.xml
- tools/limma_voom/test-data/contrasts.txt
* Fixes difference of differences contrasts (broke when I changed to code to allow groups to start with numbers)
* Fixes links to tsvs and rdata showing up under Plots section of report
> Limma: small fixes

- tools/featurecounts/featurecounts.xml
- tools/featurecounts/test-data/output_1_summary.tab
- tools/featurecounts/test-data/output_summary_builtin_hg19.tab
* update to v3.4.1 (and update coreutils dep to v8.31)
* change default mapping quality from 12 to 0 to be consistent with the upstream featurecounts tool. As had a user confused by this today when they were comparing results to others using the command-line tool and only then discovered Galaxy featurecounts was using a different default for mapping quality vs command-line featurecounts. Is it better to be consistent with the upstream tool?
> Featurecounts: update to v3.4.1 and change default MQ to same as upstream (0)

- tools/migmap/migmap.xml
Finally got around to fixing a bug I discovered in March, where migmap needed special permissions under the conda environment folder. While the easy fix was to make it writable, quoting @bgruening from our mutual chat  `the bigger problem is that no-one should write into this directory`. 
Also found a reference to a change that prompted this issue in PR #2014, and the fix is quite simple - expand the symlink so that the references can be accessed but temporary database is created in job_directory. At first I thought of reverting to copy, but this created ~120MB of unnecessary data for each job.
> Fix Migmap trying to write to its tool_dependencies folder

- tools/nanoplot/nanoplot.xml
Users can now choose what to do when they supply multiple files (or a collection)
1) batch mode: trigger a separate NanoPlot run for each file
2) combined mode: run NanoPlot once on all datasets together (previous behaviour)(default)
ping @willemdek11 any opinions on what default should be?
> Nanoplot: add batch mode option

- tools/snippy/snippy-core.xml
This update fixes problems with spaces in the input file names for snippy-core. See issue #2451
> Added quotes to names of snippy output dirs for snippy-core

- tools/quast/quast.xml
> quast: default single core

- tools/megahit_contig2fastg/megahit_contig2fastg.xml
the link gives a linter error
```
Linting tool /home/travis/build/galaxyproject/tools-iuc/tools/megahit_contig2fastg/megahit_contig2fastg.xml
Applying linter tool_urls... FAIL
.. ERROR: Error '404 Client Error: Not Found for url: https://github.com/voutcn/megahit/blob/master/tools/toolkit.cpp' accessing https://github.com/voutcn/megahit/blob/master/tools/toolkit.cpp
```
also linking to a cpp file seems not useful.
> megahit: fixed project url

- tools/hisat2/hisat2.xml
- tools/hisat2/hisat2_macros.xml
PR which addresses an issue in the `hisat2` tool: when the input Fastqs are in a compressed format (e.g. `fastqsanger.gz` or `fastqsanger.bz`), the tool runs the `hisat2` program so that it produces output Fastqs with the same compression type as the input, but then incorrectly assigned the datatypes of those datasets to `fastqsanger`. This had implications for downstream tools, causing them to fail.
With this patch the correct datatype should be assigned to the output Fastq datasets based on that of the inputs (based on code which performs a similar job in the `bowtie2` tool).
> hisat2: correctly assign datatype to output Fastq datasets when inputs are compressed

- tools/bowtie2/bowtie2_wrapper.xml
fixed bug where unaligned and aligned fastqs would be empty when using a paired_collection
> fixed bug where unaligned and aligned fastqs would be empty

- tools/pygenometracks/pyGenomeTracks.xml
Hi,
Sorry, I just noticed that the option plot labels for bed and genes was not written in the config file when set to off whereas the default is on...
> pygenometracks: use labels in the config file when off

- tool_collections/samtools/sam_to_bam/sam_to_bam.xml
- tool_collections/samtools/samtools_fastx/samtools_fastx.xml
- tool_collections/samtools/samtools_fixmate/samtools_fixmate.xml
- tool_collections/samtools/samtools_markdup/samtools_markdup.xml
- tool_collections/samtools/samtools_merge/samtools_merge.xml
- tool_collections/samtools/samtools_slice_bam/samtools_slice_bam.xml
- tool_collections/samtools/samtools_sort/samtools_sort.xml
- tool_collections/samtools/samtools_view/samtools_view.xml
- tools/bedtools/bamToBed.xml
- tools/bowtie2/bowtie2_wrapper.xml
- tools/bwa/bwa-mem.xml
- tools/bwa/bwa.xml
- tools/bwameth/bwameth.xml
- tools/featurecounts/featurecounts.xml
- tools/hicexplorer/hicBuildMatrix.xml
- tools/hicexplorer/hicCompareMatrices.xml
- tools/hicexplorer/hicTransform.xml
- tools/hisat2/hisat2.xml
- tools/htseq_count/htseq-count.xml
- tools/kallisto/kallisto_pseudo.xml
- tools/kallisto/kallisto_quant.xml
- tools/lastz/lastz.xml
- tools/minimap2/minimap2.xml
- tools/stringtie/stringtie.xml
- tools/telescope/telescope_assign.xml
- tools/umi_tools/umi-tools_dedup.xml
- tools/umi_tools/umi-tools_group.xml
Not doing so may leave behind untracked tmp files when not using
`outputs_to_working_directory`. When the stdout is piped it's not
necessary but more explicit and allows the admin to determine
the sort location on a per job basis.
> Consistently use -T in all tools that use samtools sort

- tools/goseq/goseq.r
- tools/goseq/goseq.xml
---
In this PR, I
- updated the wrapper to the latest version of GOSeq and other dependencies
- worked a bit on the wrapper and script
- added a new feature to extract in a table the DE genes associated with the different categories (GO/KEGG) using the mapping between categories and genes and if the genes are differentially expressed.
@mblue9 @mvdbeek could you tell me (if you have some times) if the changes make sense, specially the extraction function? Thank you 😄 
I plan to add this extraction in the reference-based RNA-seq tutorial, as participants of workshops usually ask how to get the list of DE genes for a GO term
Bérénice
> GOSeq: update and add extraction of DE genes for categories

- tools/featurecounts/featurecounts.xml
dbkey is in column 2 (i.e. index 1). I prefer to refer by name since this seems less error prone.
Also added sorting filter.
I guess this exists since https://github.com/galaxyproject/tools-iuc/commit/c6719a037ec6339405ae46e5908355772eaaf7d2
> featurecounts: fix wrong column used in data table

- tool_collections/samtools/samtools_flagstat/samtools_flagstat.xml
- tool_collections/samtools/samtools_idxstats/samtools_idxstats.xml
- tool_collections/samtools/samtools_stats/samtools_stats.xml
To get rid of the gnuplot and perl dependency
advantage: no additional mulled environment needed
> samtools stats: remove plot_bamstats call

- tools/seqtk/macros.xml
- tools/seqtk/seqtk_mergefa.xml
- tools/seqtk/seqtk_mergepe.xml
Currently pigz uses all CPUs which is not acceptable on shared systems. 
> seqtk: limit the number of CPUs used by pigz

- tools/stacks/macros.xml
- tools/stacks/stacks_populations.xml
Noticed this when a processing script choked on a stacks_population output, and while yes said script should support unicode chars, I'm guessing this wasn't intended, and anyone who will in the future write manual workflows with yaml probably doesn't want to have to copy and paste an `ĥ`
> Rename output with intended ascii char

- tool_collections/samtools/bam_to_cram/samtools_bam_to_cram.xml
- tool_collections/samtools/cram_to_bam/samtools_cram_to_bam.xml
- tool_collections/samtools/sam_to_bam/sam_to_bam.xml
- tool_collections/samtools/samtools_calmd/samtools_calmd.xml
- tool_collections/samtools/samtools_stats/samtools_stats.xml
- tool_collections/samtools/samtools_view/samtools_view.xml
- tools/bcftools/bcftools_stats.xml
- tools/bcftools/macros.xml
- tools/crossmap/macros.xml
- tools/extract_genomic_dna/extract_genomic_dna.xml
- tools/gffcompare/gffcompare.xml
- tools/gffcompare/test-data/gffcompare_out3.stats
- tools/htseq_count/htseq-count.xml
- tools/multigps/multigps.xml
just for consistency .. none of these were wrong as far a I could tell .. except for gffcompare where the asserts are now actually considered (since we now use this https://github.com/galaxyproject/galaxy/pull/8395).
> reference data table columns consistently by name

- tools/dropletutils/dropletutils.xml
- tools/dropletutils/scripts/dropletutils.Rscript
smallfix to order of inputs
fix to duplicate columns when outputting genes
> DropletUtils smallfix

- data_managers/data_manager_manual/data_manager/data_manager_manual.py
I found some errors while testing [biomaj2galaxy](https://github.com/genouest/biomaj2galaxy) with Galaxy 19.05. So this PR fixes part of the problem: the DM code is getting a galaxy.tools.wrappers.SelectToolParameterWrapper while dict keys are strings
I'm preparing a PR for Galaxy too to fix another part of the problem
> data_manager_manual: fix error with Galaxy>=19.05

- tools/bracken/macros.xml
Macro was being used to define `@WRAPPER_VERSION@` for tool, but that wasn't being correctly expanded.
See: https://toolshed.g2.bx.psu.edu/repository?repository_id=0357fb68688c419f&changeset_revision=b7b1c8bf7ae0
> bracken: fix wrapper version number

- tools/bracken/est-abundance.xml
Wrong macro was being used in bracken `est_abundance` tool.
> Fix bracken version macro

- tools/trinity/README.rst
PR to address issue #2513 by updating the `README.rst` instructions for specifying the memory limits for the `trinity` tool (NB there are no functional changes to the tool in this PR).
> trinity: update README to clarify specification of memory limit

- tools/roary/roary.xml
See issue #2545 
Hopefully this provides a fix.
> Fixed roary to include inverted quotes around input filenames

- tools/snippy/snippy.xml
It's biocontainer doesn't work for this tool because tar doesn't support ``-z`` in the container.
> Simplify implicit snippy dependencies.

- tools/trinity/analyze_diff_expr.xml
The conda package `bioconductor-qvalue==2.16.0` is buggy :
https://github.com/bioconda/bioconda-recipes/pull/18762
> trinity_analyze_diff_expr - update qvalue

- tools/bcftools/bcftools_norm.xml
> Work around case-sensitivity bug in bcftools norm

- tool_collections/samtools/test-data/cached_locally/cached_locally
Original error in the container tests: 
```
/home/runner/work/tools-iuc/tools-iuc/tool_collections/samtools/bam_to_cram/test-data/cached_locally/chr_m.fasta: No such file or directory
```
Might also because `tool_collections/samtools/bam_to_cram/test-data/cached_locally`  is a symlink to `tool_collections/samtools/test-data/cached_locally` and for some reason the files in the destination did not make it in the test environment. (a local `planemo t` was successful). 
But I think this symlink can go anyway.
> samtools: remove unnecessary symlink in global test-data

- tools/maxbin2/maxbin2.xml
- replaced by `gzip -cd | tar -xf -`
- additionally add idba out/err only if present
> maxbin2:  add idba out/err only if present (and update bioconda recipe)

- tools/newick_utils/newick_display.xml
imagemagick requirement was missing anyway. since for some reason
neither imagemagick not graphicsmagick can convert the image I
suggest to stick to svg only for now.
> newick display: add imagemagick dependency

- tools/raxml/raxml.py
- tools/raxml/raxml.xml
- tools/raxml/test-data/RAxML_parsimonyTree.galaxy.multi
> raxml: add python requirement

- tools/prokka/prokka.xml
Testdata differences were due the installed version is nowadays 1.13.7 and the version used to create the test data was 1.13. We could fix this now.
Probably does not cover the original error:
```
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[22:27:37] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.13 from https://github.com/tseemann/prokka' -Z outdir\/prokka\.err -i outdir\/prokka\.fsa 2> /dev/null
```
which I don't get for local test. 
> prokka: more flexible testing

- tools/circos/circos.xml
- tools/circos/macros.xml
- tools/circos/tableviewer.xml
seems that another problem is that the generated configfiles are moved to working/... which seems not to work in the container tests. 
`mv: can't remove '/tmp/tmpzvg40cuz/job_working_directory/000/2/tmpnuxq8_9j': Read-only file system`
We could try to cp or symlink? Or should this be fixes in another way
> circos: add tar requirement

- tools/transtermhp/transtermhp.xml
> transtermhp: add fix for env variable not set in containers

- tools/extract_genomic_dna/tool_data_table_conf.xml.sample
I wonder how this was uploaded previously though.
> Match twobit table definition to data_manager definition

- data_managers/data_manager_bwa_mem_index_builder/data_manager/bwa_mem_index_builder.xml
> Add python 3.7 dependency to bwa_mem index builder

- tools/scanpy/cluster_reduce_dimension.xml
- tools/scanpy/filter.xml
- tools/scanpy/inspect.xml
- tools/scanpy/macros.xml
- tools/scanpy/normalize.xml
- tools/scanpy/plot.xml
- tools/scanpy/remove_confounders.xml
numba write to the code directory or the home directory, neither of which is or should be writable. The profile version ensures this is written to an isolated home_dir for the job. 
> Fix scanpy by using profile

- tools/resize_coordinate_window/resize_coordinate_window.py
- tools/resize_coordinate_window/resize_coordinate_window.xml
> Fix resize_coordinate_window for python 3

- tools/seurat/Seurat.R
- tools/seurat/seurat.xml
- tools/seurat/test-data/out.html
Also:
- Update rmarkdown dependency to 2.0
- Add a requirement to pin pandoc to 2.7.3 due to a bug in rmarkdown with pandoc >=2.8 https://github.com/rstudio/rmarkdown/issues/1740
- Use @TOOL_VERSION@ macro (we forgot to bump the tool version when upgrading from Seurat 2 to 3, bad!!)
- 2 bug fixes
- Update test output data
> Update Seurat to 3.1.2, bug fixes

- tools/idr/idr.xml
just updates the test comparison, I don't think bumping the tool version is necessary
> Add delta to idr image comparison

- data_managers/data_manager_bowtie2_index_builder/data_manager/bowtie2_index_builder.xml
There is no 2.3.5.1 version on bioconda, and bowtie2 ships with python.
Given that we uploaded this version I added .1+galaxy1 as the version.
> Fix bowtie2 data manager

- tools/codeml/codeml.xml
- tools/codeml/macros.xml
before running codeml, so that one can see the script if the tool run
fails. Use cp instead of mv since configfiles are mount :ro in
containers.
> Fix containerized codeml, always copy script

- .travis.yml
- tools/bctools/rm_spurious_events.xml
Allows for this diff:
```
--- local_file
+++ history_data
@@ -1,6 +1,6 @@
+chr1	10	20	AAAAA	100	+
chr1	10	20	AAAAA	5	-
chr1	10	20	AAAAA	5	-
chr1	10	20	AAAAA	4	-
chr1	10	20	AAAAA	3	-
-chr1	10	20	AAAAA	100	+
chrX	20	30	TTTTT	7	+
```
> Fix bctools_remove_spurious_events test, run containerized tests

- tools/tetyper/test-data/tetyper_snp_profiles.loc
- tools/tetyper/test-data/tetyper_struct_profiles.loc
- tools/tetyper/tetyper.xml
- tools/tetyper/tool-data/tetyper_snp_profiles.loc.sample
- tools/tetyper/tool-data/tetyper_struct_profiles.loc.sample
- tools/tetyper/tool_data_table_conf.xml.sample
- tools/tetyper/tool_data_table_conf.xml.test
> tetyper: Optionally read variant profiles from tool data table

- tools/stacks/stacks_assembleperead.xml
Needs findutils, busybox find fails with
```
find: unrecognized: -delete
```
> Fix stacks_assembleprereads

- tools/tb-profiler/tb_profiler_profile.xml
Some advanced parameters (`--min_gene_frac`, `--call_method`, `--call_whole_genome`) are not supported in the current tb-profiler and have been removed.
https://github.com/jodyphelan/TBProfiler/blob/e124e43fccdeb0f822760819a0e3fea514669c92/tb-profiler#L324-L348
Fixed a typo (`allel`->`allele`) in two parameters.
> tb-profiler: Remove deprecated advanced params

- tools/mummer4/delta-filter.xml
- tools/mummer4/dnadiff.xml
- tools/mummer4/macros.xml
- tools/mummer4/mummer.xml
- tools/mummer4/mummerplot.xml
- tools/mummer4/nucmer.xml
- tools/mummer4/show-coords.xml
Bump gnuplot to 5.2.7 (5.2.3 has missing libxrender), work around mummer4 bug
Also needs a new extended base image for mummer+gnuplot. (conda-forge doesn't annotate extended-base, so we can't do this automatically)
> Fix mummerplot

- tools/jbrowse/jbrowse.xml
history and dataset ids don't match up when testing more than one repo
againt a test database.
> Bump up lines_diff for jbrowse test 4

- tools/jbrowse/macros.xml
`jbrowse.py` uses subprocess module to call `find` with `-xtype` flag, but the `find` command in the biocontainer does not support that flag. Adding the `findutils` dependency guarantees the existence of the proper `find`, although might not be necessary in all environments (eg: works without the requirement when using Ubuntu base image, but doesn't work in the container which I believe uses CentOS base). Tested by running `planemo mull` after adding the requirement and it worked (temporary container with the added dependency at `cloudve/jbrowse:1.16.5`)
> Adding `findutils` requirement to JBrowse

- tools/iqtree/iqtree.xml
> iqtree: handle '+' character in custom models

- tools/schicexplorer/scHicCorrectMatrices.xml
@bgruening This adds the missing scHicCorrectMatrices wrapper. Please do review+merge and installation until the paper hand-in date at latest. Thanks!
> Adding scHiCExplorer wrapper

- .github/workflows/ci.yaml
- .tt_biocontainer_skip
Job execution is fully containerized, uses postgres as database and Galaxy and planemo runs on python 3.7.
> Add cronjob that tests entire tools-iuc repo every monday morning

- tools/trinity/align_and_estimate_abundance.xml
- tools/trinity/analyze_diff_expr.xml
- tools/trinity/macros.xml
according to the changelog
https://raw.githubusercontent.com/trinityrnaseq/trinityrnaseq/master/Changelog.txt
no changes should be necessary. But this seems to be incomplete:
- remove --salmon_idx_type which seems gone
> trinity: bump to 2.9.1

- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py
- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.xml
- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.py
- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.xml
> Fix snpeff data managers (older builds are missing python)

- tools/lofreq/lofreq_call.xml
* prevent errors because of --min-bq > --min-alt-bq and --min-mq > --max-mq
* provide option to replace non-ref basequals with median of ref ones
(i.e., allow --def-alt-bq -1 to be configured)
* enable vcf_bgzip input to --ign-vcf
> Usability of lofreq call - minor improvements

- tools/hyphy/macros.xml
e.g. to run on Stampede2, we need to use the local [ibrun](https://portal.tacc.utexas.edu/user-guides/stampede2#running-launching-mpi) utility instead of `mpirun`.
> Allow env vars to override the HyPhy mpirun invocation for site-specific needs

- tools/scanpy/cluster_reduce_dimension.xml
- tools/scanpy/filter.xml
- tools/scanpy/inspect.xml
- tools/scanpy/macros.xml
- tools/scanpy/normalize.xml
- tools/scanpy/plot.xml
- tools/scanpy/remove_confounders.xml
The motivation here is to reduce the training time of the *PBMC 3K with ScanPy* training material, where there is a large time bottleneck in performing inspection on the generated H5AD sets. 
Instead of asking users to query their H5AD sets for general information, this PR aims to just print this nicely within the stdout window within the H5AD dataset in the history. The stdout at the moment contains debugging information, so this will be redirected to a seperate hidden output (so it can be still tested against, but not visible to the user).
> Fix ScanPy default stdout

- tools/gtfToBed12/gtfToBed12.xml
FOR REVIEWER:
******
Small bug:
* The tool has two outputs:
* Bed12
* Tabular (info)
The tabular file is set to only output when `infoFile` flag is set, which is unchecked by default.
However,  feed it any GTF and it will still output the tabular file (albeit completely blank). This fixes that.
* Added extra filter to fix a blank tabular from being generated on defaults
> Fix to GTF2Bed12 

- tools/mash/.shed.yml
Deployment of the new version of `mash_screen` that is capable of reading from the `mash_sketches` tool data table failed because the `tool_data_table_conf.xml.sample` file was not included in the repo.
> Include tool_data_table_conf.xml.sample in mash_screen

- tools/deseq2/deseq2.R
- tools/deseq2/deseq2.xml
Fixes https://help.galaxyproject.org/t/deseq2-returns-results-as-empty-list/3058
> Fix deseq2 dataset discovery

- tools/exonerate/exonerate.xml
- tools/exonerate/exonerategff_to_gff3.py
- tools/exonerate/macros.xml
- tools/exonerate/test-data/coding2coding.gff
- tools/exonerate/test-data/coding2coding.gff3
- tools/exonerate/test-data/est2genome.gff
- tools/exonerate/test-data/est2genome.gff3
- tools/exonerate/test-data/est2genome_introns.gff
- tools/exonerate/test-data/est2genome_introns.gff3
- tools/exonerate/test-data/out_query.gff
- tools/exonerate/test-data/out_query.gff3
- tools/exonerate/test-data/out_target.gff
- tools/exonerate/test-data/out_target.gff3
- tools/exonerate/test-data/protein2genome.gff
- tools/exonerate/test-data/protein2genome.gff3
- Added the --minintron and --maxintron options to filter irrelevant results
- Convert the raw exonerate gff into a more friendly GFF3 (should work better with jbrowse & co)
- (and fixed a bug too)
> Exonerate: add intron min/max + better gff3 output

- tools/raxml/raxml.xml
I think `getVar` only gets cheetah variables.
might fix https://github.com/galaxyproject/tools-iuc/issues/2916
> raxml: set slots and used binary using bash

- tools/kc-align/.shed.yml
`Unexpected HTTP status code: 400: {"err_msg": "Repository names must contain only lower-case letters, numbers and underscore.", "err_code": 400008}`
> Use underscores in kc_align toolshed repo name

- tools/kc-align/.shed.yml
> Remove auto_tool_repositories from kc-align

- tools/lofreq/lofreq_call.xml
- tools/lofreq/test-data/indel-call-out.vcf
This changeset fixes the broken `--only-indels` option of lofreq call.
It also improves the tool and param help to make it clearer that indels
cannot be called with lofreq without adding indel qualities first with
lofreq indelqual (the mention of GATK as an alternative is outdated
since new versions of GATK don't generate indel quality tags anymore,
and got removed).
> Fix lofreq indel call options and help

- tools/idr_download/idr_download_by_ids.py
- tools/idr_download/idr_download_by_ids.xml
This change avoids conflicts with plate names that already contain `_`
> change delimiter

- .github/workflows/pr.yaml
latest galaxy commit sha was not saved in artifacts file (workflow_artifacts/galaxy.sha) since the environment variable seems to be available only after the step where it is set.
pip cache name was inconsistent:
- pip_cache_py
- pip_cache_python_
> githup actions: fix cache names, storing of sha

- tools/jbrowse/jbrowse.xml
- tools/jbrowse/macros.xml
In response to your comment @jennaj,
> We (@dannon & @mvdbeek) were wondering if there was a way to adjust Jbrowse to be able run in anonymous (not logged in) sessions. 
this should address your issue.
(Though it would be nicer if galaxy returned a fake 'anonymous' user when trying to access that in the tool form, but I guess very few tools use this "feature".)
@abretaud if you have a chance to review?
Edit: Screenshot of how it looks when anonymous:
> permit anonymous usage of jbrowse

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
as far as I know
```
0 * * * 0
```
means Sunday 0:00, 1:00, ... 23:00
```
0 0 * * 0
```
should be Sunday 0:00
was always wondering why I got so many mails on sunday...
> fix time specs in scheduled ci workflow

- tools/sra-tools/fasterq_dump.xml
- tools/sra-tools/sra_macros.xml
With this change, the prefetch operation should succeed more often on larger lists of accessions. A local test run using SRR925743 succeeded on the second attempt.
> Retry fasterq_dump prefetch up to thrice on failure.

- tools/seurat/seurat.xml
This addresses #3008. 
**Note**: in order to make sure the older (3.1.2) version of Seurat gets fixed, this PR should be accepted *after* #3009 get accepted and pushed to the toolshed.
> Update Seurat to 3.1.5

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
New versions of the actions simplify the workflows a bit. 
Since they allow now upload of single files we could have single artifacts for `galaxy.sha` and `changed_repos.list`. 
Somehow I would like to have the tools in the final html output sorted, but I could not get this running.
> upgrade workflows to use v2 of upload and download artifact

- tools/orthofinder/orthofinder_only_groups.xml
To fix an error which appears in current release 2.1.2 (resolving of non-binary gene trees)
> Update orthofinder to 2.2.6

- data_managers/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py
I think this makes the Gemini data manager python3 compatible. It was trying to write the json dictionary out using `open(outfile, 'wb')`. This kept failing. Works when changed to `open(outfile, 'w')`.
> Gemini data manager fix

- tools/bwa/bwa_macros.xml
Rectified typos in "Read Groups are Important" section. The word variant was misspelled, which is rectified in the commit.
> Rectified Typos in BWA-MEM Tool Documentation

- tools/scanpy/macros.xml
- tools/scanpy/plot.xml
In the current version using the default colors and palette in tool the leads to:
```
sc.pl.scatter(
adata,
save='.png',
...
palette='',
color_map='',
...
frameon=True)
```
which has the unintended effect of actually not using any color or palette:
In contrast, with the additions in this PR, when selecting Default you actually allow scanpy to use its default palette and colours, producing the following code:
```
sc.pl.scatter(
adata,
save='.png',
show=False,
x='n_counts',
y='n_genes',
color='individual',
use_raw=False,
sort_order=False,
projection='2d',
legend_loc='right margin',
legend_fontsize=10,
legend_fontweight='normal',
frameon=True)
```
which doesn't set color and palette to `''`.
This also adds the ability to color by a field in `obs` or `var`, producing:
> Plot with Scanpy: Changes way in which coloring defaults are set

- tools/qualimap/qualimap_bamqc.xml
No clue if I should increment the version so just let me know of that or of any comments towards this small change.
*edit*: After looking I realized that there were 3 raw outputs missing. I've added them in
> Fix to Qualimap name issue and addition of 3 raw outputs

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- setup.cfg
Restore flake8-import-order linting, lost when moving from Travis
to GitHub workflows.
> Sync CI configuration with tools-devteam repo

- tools/minimap2/minimap2.xml
> Minimap2 enhancements

- tools/sra-tools/.shed.yml
- tools/sra-tools/README.rst
- tools/sra-tools/fasterq_dump.xml
- tools/sra-tools/fastq_dump.xml
- tools/sra-tools/sam_dump.xml
- tools/sra-tools/sra_macros.xml
We've been seeing a lot of cases where fasterq-dump would finish with exit code 0, despite not having written any fastq files at all. I hope this (together with various bugfixes in sra-tools) will make this better.
> Update sra-tools to 2.10.7, retry if no fastq files found

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- tools/heinz/bum.R
- tools/scpipe/scpipe.R
also integrate latest changes (from https://github.com/galaxyproject/tools-devteam/pull/560) from devteam repo.
> add lintr step to PR workflow

- tools/annotatemyids/annotateMyIDs.xml
A galaxy user in Australia came across this: if the DESCRIPTION checkbox is checked, the tool runs into an error `Invalid columns: DESCRIPTION. Please use the columns method to see a listing of valid arguments.`
From taking a closer look, DESCRIPTION is not a valid column.  It must have been valid for previous versions of the dbs.  All of the other output column options are still valid.
```
org.Hs.eg.db
[1] "ACCNUM" "ALIAS" "ENSEMBL" "ENSEMBLPROT" "ENSEMBLTRANS"
[6] "ENTREZID" "ENZYME" "EVIDENCE" "EVIDENCEALL" "GENENAME"
[11] "GO" "GOALL" "IPI" "MAP" "OMIM"
[16] "ONTOLOGY" "ONTOLOGYALL" "PATH" "PFAM" "PMID"
[21] "PROSITE" "REFSEQ" "SYMBOL" "UCSCKG" "UNIGENE"
[26] "UNIPROT"
org.Mm.eg.db
[1] "ACCNUM" "ALIAS" "ENSEMBL" "ENSEMBLPROT" "ENSEMBLTRANS"
[6] "ENTREZID" "ENZYME" …
```
> annotatemyids: DESCRIPTION is no longer a valid output column

- tools/bedtools/macros.xml
This is an update v2.29.0 to v2.29.2 (which is only bug fix) + add encodepeak as `STD_BEDTOOLS_INPUTS`.
> update bedtools version and add encodepeak

- tools/phyml/phyml.xml
- tools/phyml/test-data/phylip_phyml_stats.txt
Updates the PhyML tool to use `3.3.20190909`
> Update phyml to 3.3.20190909

- tools/progressivemauve/test-data/1.gff3
- tools/progressivemauve/xmfa2gff3.py
- tools/progressivemauve/xmfa2gff3.xml
The current output does not contain enough information to describe an alignment. The current output is also not GFF3 compliant. This commit is in reference to #2301
> Fix Target attribute output

- tools/shovill/shovill.xml
This update sets the memory passed to shovill based on the `GALAXY_MEMORY_MB` environment variable (as described in the [planemo docs](https://planemo.readthedocs.io/en/latest/writing_advanced.html#cluster-usage)).
Previously this was being set via the `SHOVILL_RAM` environment variable. The changes I've made will still support this functionality. Specifically, the memory will be set in the following order:
1. If `SHOVILL_RAM` exists, use this value.
2. Else, derive memory from `GALAXY_MEMORY_MB`
3. Finally, default to 4 GB if `GALAXY_MEMORY_MB` is not set.
> Update shovill to set memory using GALAXY_MEMORY_MB

- .github/workflows/pr.yaml
- .tt_skip
I also disabled testing for enasearch which made the CI fail for the last weeks.
Wondering if tools in `.tt_skip` and `.biocontainers_skip` really should be excluded from tests in the PR workflow. 
> PR deploy dependencies

- tools/compose_text_param/compose_text_param.xml
The text parameter will not appear on the command line, so this is safe.
Will allow creating awk commands using compose_text_param, which failed
due to the sanitizer for @pvanheus.
> Turn off sanitizer for compose_text_param

- tools/iedb_api/iedb_api.xml
Bepipred seems not to work (at the moment?)
> fix iedb by using different method

- tools/featurecounts/featurecounts.xml
Allow both multialign and multioverlap to use the --fraction flag, and combine all of those options into a single select
> Featurecounts multioverlap/multialign

- tools/repeatmasker/repeatmasker.xml
- tools/repeatmasker/test-data/small.fasta.cat
- tools/repeatmasker/test-data/small.fasta.gff
- tools/repeatmasker/test-data/small.fasta.stats
- tools/repeatmasker/test-data/small_repbase.fasta.stats
It seems like repeatmasker 4.0.7 no longer works with recent versions of repbase. So here's the updated wrapper with version 4.0.9.
> Update repeatmasker to 4.0.9

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
found it a good idea that tools in `.tt_biocontainer_skip` are tested at least using conda env instead of no test at all. .. not sure if implemented correctly. otherwise it makes not much sense to have two .tt_.. files.
> do not skip tools in .tt_biocontainer_skip but test un-containerized

- tools/megahit/megahit_wrapper.xml
The added code line limits the number of megahit thread to a reasonable value (all machine cpus if not specified ?)
> Set the number of megahit threads in Galaxy server

- tools/plink/plink.xml
Small fix where setting --filter-founders and not setting no_sex_select adds "None" to command.
> Plink 1.9: Remove None response on empty var

- tools/crossmap/macros.xml
I cannot figure out why the asked format for the LiftOver chain file is `cvs` nor why the tests are indeed passing. I don't see either the rational since the LiftOver chain file are most often kind of tabular-like and for sure not cvs.
Anyway this tools in its present version crashes with the test data on several artbio instances under 20.01, whereas it works with the input format `txt`, and importantly this does not affect the current tests (not surprisingly)
> set the format of chain file to txt instead of csv

- tools/query_tabular/load_db.py
- tools/query_tabular/query_tabular.xml
- tools/query_tabular/test-data/netMHC_summary_out1.tsv
- tools/query_tabular/test-data/netMHC_summary_out2.tsv
Allow query_tabular to create empty tables if possible.   This can be useful in workflows.
If there are no data rows in an input tabular dataset, query_tabular will fail unless:
a) There is a row header line in the dataset and Use first line as column names is selected
b) Specify Column Names is used to provide column names
in which case an empty table will be created with those columns.
> Update query_tabular for empty datasets

- tools/plink/plink.xml
Allow lack of flag as value in filter
> Plink default blank flags

- tools/chromeister/chromeister.xml
This fixes an important bug in the grid version
> Update chromeister version from 1.1.c to 1.2

- tools/multiqc/multiqc.xml
The specific cases fixed here are:
- bowtie2 mapping stats generated from an empty fastq
- picard MarkDuplicates stats generated from empty bams
In both cases, the MultiQC wrapper failed because it was looking for missing text patterns, while MultiQC itself is perfectly
capable of dealing with these inputs (and will simply produce empty output).
The issue is fixed here by scanning for parts of text that are constant under all conditions.
> Allow MultiQC runs with certain quasi-empty inputs

- tools/kc-align/kc-align.xml
Also set the version to the full tool version.
> Use $GALAXY_SLOTS in kc-align instead of threads as a tool param

- .github/workflows/pr.yaml
currently we see:
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
> adapt PR workflow to new way of setting env vars

- .github/workflows/ci.yaml
fixes: https://github.com/galaxyproject/tools-iuc/issues/2959
> balance chunks in CI workflow

- .github/workflows/ci.yaml
Bugs introduced in https://github.com/galaxyproject/tools-iuc/pull/3154 and https://github.com/galaxyproject/tools-iuc/pull/3239
> fix wrong variable name

- tools/pyega3/.shed.yml
- tools/pyega3/README.md
- tools/pyega3/pyega3.xml
This adds a first implementation of a tool to download data from EGA, using the new python-based client (https://github.com/EGA-archive/ega-download-client)
Users can set their credentials under their user preferences (will PR to Galaxy to add the EGA credentials fields), and if unset, then the EGA test credentials are use (which has some 1000 genomes data)
There are enhancements to be made in the future, for example to list all the user's authorized files nicely in a dropdown orso, but for now this lets users obtain a list of their authorized datasets, list the files in a dataset, or download a file (or a specified genomic range of a file) 
> Add EGA download tool (Pyega3)

- tools/hisat2/hisat2.xml
On cloud instances, some of this tool's tests returns fasta files with mostly identical outputs, but sorted differently, ie
```
read1
aaaaaaa
read2
ttttttttt
read3
gggggg
```
vs
```
read3
gggggg
read2
ttttttttt
read1
aaaaaaa
```
This just sorts the outputs to make sure they match in those tests
> hisat2 sorted output for cloud instances

- tools/mothur/clearcut.xml
- tools/mothur/list.otulabels.xml
- tools/mothur/macros.xml
- tools/mothur/mimarks.attributes.xml
- tools/mothur/remove.otulabels.xml
- tools/mothur/seq.error.xml
- tools/mothur/summary.single.xml
seems that for some reason summary.single sometimes outputs
otu.groups.ave-std.summary
and sometimes
otu.groups.ave_std.summary
so the last mv fails
> mothur: fix summary.single

- tools/genebed_maf_to_fasta/genebed_maf_to_fasta.xml
- tools/genebed_maf_to_fasta/macros.xml
- tools/interval2maf/interval2maf.xml
- tools/interval2maf/macros.xml
- tools/maf_stats/maf_stats.xml
This PR removes the input dataset dbkey filter from the maf_indexes reference in the tools that use this table. This allows a user to select any MultiZ alignment that they believe includes the appropriate species, instead of potentially needing to guess which dbkey to use.
> Remove filter from MAF data table references.

- README.md
Note is out of date. Alternatively we could add a note regarding `.tt_skip`
> remove ci_skip note from README
