- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
Computed as ~max~min(40, 4*log_2(ntools+1)) where ntools is the number of XML files in `tools/`, `tool_collections/`, and `data_managers` that do not contain `"macro"`.
Note that the formula gives 40 for the current number of tools
Fixes https://github.com/galaxyproject/tools-iuc/issues/3272
> make number of chunks dynamic

- .github/workflows/pr.yaml
- tools/maxbin2/maxbin2.xml
Apparently there were to many quotes. 
The random tool that I used for testing contained a linting problem. I "fixed" the URL via archive org. Not sure if this is acceptable (I will be away from github today. Feel free to drop that commit and merge)
> Fix PR workflow

- .tt_skip
- tools/meme/meme.xml
- tools/raven/raven.xml
- tools/vg/convert.xml
fixes this problem:
```
A call to mkdir was unable to create the desired directory:
Directory: /ompi.530361e930c3.1001
Error:     Permission denied
Please check to ensure you have adequate permissions to perform
the desired operation.
```
Not sure if we should also add `-p \${GALAXY_SLOTS:-1}`, how does MPI play on out Galaxy instances?
> meme, vg_convert: fix openmpi/xg error by setting TMPDIR

- .tt_skip
- tools/unicycler/unicycler.xml
Not yet solving https://github.com/galaxyproject/tools-iuc/issues/3203 1st commit just sets the gfa outtype more specific
> unicycler: make gfa output really gfa

- CONTRIBUTING.md
and update to the latest github workflows
The approval rule should be changed in the repos settings
I would suggest to require approval from (at least) a majority of IUC to this PR.
> update contributing to require one approval

- .github/workflows/pr.yaml
When a secret is added (Settings -> Secrets -> New repository secret) on GitHub, the secret name is changed to uppercase in the secrets list, even if it is actually lower/mixed case. I find this confusing.
N.B.: THIS CHANGE REQUIRES REMOVING AND RE-ADDING THE 2 SECRETS USING THE NEW UPPERCASE NAME! (I can do that)
> Rename secrets to uppercase

- data_managers/data_manager_mitos/data_manager/data_manager.py
- data_managers/data_manager_mitos/data_manager/data_manager_mitos.xml
- data_managers/data_manager_mitos/test-data/mitos2_refseq63.json
refseq39 reference data for MITOS2 was broken and never worked.
in the new version of the zenodo record only this data set has
been replaced. So an unversioned change of the data should be OK.
> data manager mitos: fixed refseq39 reference data

- tools/circos/alignments-to-links.xml
- tools/circos/binlinks.xml
- tools/circos/bundlelinks.xml
- tools/circos/circos.xml
- tools/circos/gc_skew.xml
- tools/circos/resample.xml
- tools/circos/scatter-from-wiggle.xml
- tools/circos/stack-histogram.xml
- tools/circos/tableviewer.xml
- tools/circos/text-from-interval.xml
- tools/circos/tiles-from-interval.xml
- tools/jbrowse/jbrowse-fromdir.xml
- tools/jbrowse/jbrowse.xml
xref https://github.com/galaxyproject/galaxy/pull/10592
> EDAM terms for Circos, Jbrowse

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
For the workflows we could require a min of 1 chunk to make the workflow pass? When no tools changed
> CI fix matrix calculation

- tools/idr/.shed.yml
- tools/idr/idr.xml
The IDR long description was not correct and made discovery in the toolshed more difficult.
>  Correct the description in .shed.yml for IDR

- data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.py
Broken in commit 02d2967f77e3fa5a18aea63dc84aa9ab418dc165
> Fix `with` statement in snpEff data manager

- tools/hyphy/hyphy_relax.xml
Tool is failing CI. So I had a look and found a few problems:
- add missing `--code` parameter
- add OMP_NUM_THREADS to avoid CPU overutilization
other tools also should use OMP_NUM_THREADS. Some even use MPI variant. I would suggest to remove this / add an MPI version of the tools.
> hyphy (relax) fixes

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
Otherwise the number of chunks won't take into account tools for which the XML was not modified but other files in the repo were.
Noticed in https://github.com/galaxyproject/tools-iuc/pull/3343/checks?check_run_id=1445440585 , where "Show tool list" returns no tools.
Also:
- Save Galaxy HEAD sha as job output instead of as an artifact.
- Sync ci and pr workflows.
> Run `planemo ci_find_tools` on changed repos to calculate chunks

- tools/mothur/make.contigs.xml
Bugfix. Actual excerpt from make.contigs logfile:
mothur > 
<-1,gapopen=-2,gapextend=-1,rename=Trueprocessors=4)
Using 1 processors.
After correcting missing comma in "rename" parameter:
mothur > 
<1,gapopen=-2,gapextend=-1,rename=True,processors=4)
Using 4 processors.
Now the tool is able to use multiple cores. No impact in the result itself so much as I could see.
> Missing comma in make.contigs.xml

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- unquote `$TOOL` (which is renamed to `TOOL_GROUP`) because its a space separated list of tools
- restore `--group_tools` argument for ci_find_tools
essentially restoring:
https://github.com/galaxyproject/tools-iuc/pull/3239
https://github.com/galaxyproject/tools-iuc/pull/3254
which have been lost somewhere ... :( I have the feeling that some of the lines are to long and diffs are easy to miss.
> fix CI & PR: unquote TOOL

- tools/hisat2/hisat2.xml
- tools/hisat2/hisat2_macros.xml
This PR is a fix for issue #3312, an update to the square root symbol in function arguments by replacing `x&#178` to `&#8730x`.
I'm not familiar with creating macros in XML but I can give it a try if you prefer it that way.
> hisat2: Fix for issue #3312, an update to square root symbol in function arguments

- .github/workflows/ci.yaml
Exclude `datatypes_conf.xml` files and check for `tool` XML element.
Estimating too many tools creates a problem for small repos like earlham-galaxytools
> More precise estimate of number of tools

- .github/workflows/pr.yaml
as already done in devteam repo
> do not lint R for cyclomatic complexity

- tools/busco/busco.xml
- tools/busco/macros.xml
- tools/busco/test-data/genome_results/full_table
- tools/busco/test-data/genome_results/missing_buscos_list
- tools/busco/test-data/genome_results/short_summary
- tools/busco/test-data/proteome_results/full_table
- tools/busco/test-data/proteome_results/missing_buscos_list
- tools/busco/test-data/proteome_results/short_summary
- tools/busco/test-data/transcriptome_results/full_table
- tools/busco/test-data/transcriptome_results/missing_buscos_list
- tools/busco/test-data/transcriptome_results/short_summary
Busco uses biopython.BioAlphabet which has been removed in biopython 1.78, but installing busco currently installs the new biopython version in the environment, and busco jobs fail.  This is a patch for 4.1.2 only: busco versions >= 4.1.4 do not use BioAlphabet.
Is it OK to add a dependency without a version bump?  The tool is not changing at all.
> Update busco to 4.1.4

- tools/jbrowse/jbrowse.py
- tools/jbrowse/macros.xml
- tools/jbrowse/readme.rst
A little update of the jbrowse tool to 1.16.10
Also added a new GALAXY_JBROWSE_SYMLINKS env var:
- if unset bam/bigwig files will be copied to the jbrowse dataset dir
- otherwise it will be symlinked
Symlinks are fine to save space, but won't work if datasets are deleted or with pulsar. With GALAXY_JBROWSE_SYMLINKS the admin has the choice
> Update Jbrowse to 1.16.10

- .github/workflows/pr.yaml
added in https://github.com/galaxyproject/tools-iuc/pull/3403 . The Planemo issue should be fixed in 0.74.1
> Revert changes in pr.yaml

- tools/maker/maker.xml
- tools/maker/readme.rst
A fix for the broken logic of mpi activation for Maker.
Also disabled it by default as it seems like mpich>=3.3 node list parsing is not super reliable, making it fail when node names are not in the expected format (I had this problem on my cluster, heard of someone else having it too some time ago). I'll try to fix it in mpich :crossed_fingers: 
(also tried to pin mpich to 3.2.1, but getting conda package conflicts)
> Maker: fix mpi activation logic

- data_managers/data_manager_manual/data_manager/data_manager_manual.py
Since 20.05 I get errors DetachedInstanceError when using data_manager_manual (#3302 and https://github.com/galaxyproject/galaxy/issues/10023).
This tiny patch makes the DM use another simpler method which seems to work better, and without these DetachedInstanceError
Tested by running biomaj2galaxy on a patched docker galaxy instance.
I haven't changed the version as I see it more like bugfix..
> data_manager_manual: fix DetachedInstanceError with >20.05

- tools/deseq2/deseq2.xml
Per @wm75 this is a trick (from @Slugger70) already used in some [other tools](https://github.com/galaxyproject/tools-iuc/blob/master/tools/snpfreqplot/snpfreqplot.xml) for getting Pulsar to transfer required files from the tool directory that don't appear directly in the command line. In this case, `get_deseq_dataset.R` is an include in `deseq2.R`.
From some discussion with @jmchilton on the admins gitter channel we'd like a way to annotate these sorts of things rather than a hack, but it's not on the list of priorities currently.
> Ensure that secondary DESeq2 R script is in <command> for Pulsar

- .github/workflows/ci.yaml
for counting tools and computing chunks.
> use planemo ci_find_repos+ci_find_tools

- tools/velvet_optimiser/velvetoptimiser.xml
velvetoptimizer runs with `-t` already multithreaded (one for each k).
with `OMP_NUM_THREADS` > 1 also each velveth run will be multithreaded.
so overall CPUs are overutilized.
removed `export OMP_THREAD_LIMIT=1` because otherwise the tool gets
stuck.
> do not use >1 threads for velveth in velveloptimizer

- tools/hmmer3/hmmbuild.xml
- tools/hmmer3/hmmscan.xml
- tools/hmmer3/hmmsearch.xml
- tools/hmmer3/jackhmmer.xml
- tools/hmmer3/macros.xml
- tools/hmmer3/nhmmer.xml
- tools/hmmer3/nhmmscan.xml
- tools/hmmer3/phmmer.xml
from the man page:
```
--cpu <n>
Set the number of parallel worker threads to <n>. On multicore machines, the default is 2. You can also control this number by setting an environment variable, HMMER_NCPU. There is also a master thread, so the actual number of threads that HMMER spawns is <n>+1.
```
I guess the test will run with GALAXY_SLOTS=1, i.e. we will know if
`--cpu 0` will work
> hmmer: fix number of CPUs

- tools/chromeister/chromeister.xml
This update fixes one new bug and a potential one. 
It also reduces the number of inline prints so that it does not clog up the stdout interface in galaxy
An additional test has been included to test the memory error
Sorry for the many updates lately!
> update chromeister to 1.5.a fixes memory error and reduces stdout prints

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
supersedes https://github.com/galaxyproject/tools-iuc/pull/3257
needs https://github.com/galaxyproject/planemo-ci-action/pull/1
I think I tested everything except for the deployment.
Co-authored-by: Marius van den Beek <m.vandenbeek@gmail.com>
> use planemo-ci-action for PR and CI workflow

- tools/humann2/humann2.xml
- tools/humann2/humann2_associate.xml
- tools/humann2/humann2_barplot.xml
- tools/humann2/humann2_genefamilies_genus_level.xml
- tools/humann2/humann2_join_tables.xml
- tools/humann2/humann2_macros.xml
- tools/humann2/humann2_reduce_table.xml
- tools/humann2/humann2_regroup_table.xml
- tools/humann2/humann2_rename_table.xml
- tools/humann2/humann2_renorm_table.xml
- tools/humann2/humann2_rna_dna_norm.xml
- tools/humann2/humann2_split_stratified_table.xml
- tools/humann2/humann2_split_table.xml
- tools/humann2/humann2_strain_profiler.xml
- tools/humann2/humann2_unpack_pathways.xml
Alternative: switch to aggressive error detection.
Just realized how outdated this tool is. It is 0.11.1 from 2017 and currently its 2.8.1 ... with 3.0 comming :(
> humann2: add MemoryError stdio to all tools

- tools/umi_tools/test-data/stats_outputs_edit_distance.tsv
- tools/umi_tools/test-data/stats_outputs_per_umi.tsv
- tools/umi_tools/test-data/stats_outputs_per_umi_per_position.tsv
- tools/umi_tools/umi-tools_dedup.xml
The existing wrapper to UMI tools doesn't allow for getting output-stats files from the tool. This adds functionality to get that info from the `dedup` tool. Note that while there is a new version of UMI tools available (1.1.1) it seems like there are some issues with dependencies with the conda wrapper and several of the parameters have changed between versions, so bumping version is not as simple as updating the `macros.xml` file, and I need this tool on a short timescale for a workflow I'm working on. A version bump to 1.1.1 is probably worth doing in the near future however.
> Updating umi-tools dedup to pickup output-stats files.

- tools/medaka/convert_VCF_info_fields.py
- tools/medaka/variant.xml
I lied in the last PR, one last medaka update before version bump. Somehow missed parenthesis in the convert_vcf_info_fields.py script.
> Medaka update

- .tt_skip
The qiime tools time out and many of them fail tool tests. 
In most of the cases this is because of the missing `uclust` binary which is not in conda. My best guess is that in the past qiime downloaded `uclust ` at setup (https://github.com/biocore/qiime/blob/76d633c0389671e93febbe1338b5ded658eba31f/setup.py#L186) and this broke at some point. 
In some instances it would even be insufficient to not use uclust from the CLI (e.g. align_seqs) since uclust is used anyway.
Alternatively one could check if there are older containers that contain uclust and remove newer ones, but since the tools use different requirement combinations this seems to be quite some effort. 
Concluding two days of analyzing this I would say that qiime(1) is a dead end and maybe it would be the best to deprecate it .. …
> skip qiime in tool tests

- tools/ncbi_entrez_eutils/efetch.xml
test for collection was ignored until 21.01 (https://github.com/galaxyproject/galaxy/pull/11313)
test file was (and is) absent anyway.
> fix efetch test

- tools/gfa_to_fa/gfa_to_fa.xml
This converter would previously fail on gfa1 files with only three fields in an S line.
> Fix bug in gfa_to_fa converter.

- tools/hicexplorer/hicFindRestrictionSites.xml
* [] - This PR does something else (explain below)
Python 3.6 does not support the `isascii()` validation of a string, only > Python 3.7 does.
> HiCExplorer Validation fix for Python 3.6 version

- tools/table_compute/allowed_functions.xml
- tools/table_compute/scripts/table_compute.py
- tools/table_compute/table_compute.xml
- tools/table_compute/test-data/pivot.tsv
- tools/table_compute/test-data/table1.tsv
This is an upgrade for table compute that allows for aggregator functions to be flexibly applied to columns based on the work from @jj-umn at https://github.com/galaxyproject/tools-iuc/pull/3480
The idea is to allow the user to override the default aggregator function when performing a pivot (default = np.mean) and enable them to choose from a list of valid aggregators. If no aggregator function is given, then the default is assumed.
Also, the user should be able to selectively apply different aggregators to different columns, and so for this a new operation "Pivot Column Map" will be added which extends the main "Pivot" mode (but removes the value parameter as this is implicit from the map).
TODO:
> Table Compute - Extend Pivot Functionality

- data_managers/data_manager_pangolearn/.shed.yml
- data_managers/data_manager_pangolearn/.vscode/settings.json
- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py
- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
- data_managers/data_manager_pangolearn/data_manager_conf.xml
- data_managers/data_manager_pangolearn/test-data/pangolearn.loc
- data_managers/data_manager_pangolearn/tool-data/pangolearn.loc
- data_managers/data_manager_pangolearn/tool_data_table_conf.xml.sample
- data_managers/data_manager_pangolearn/tool_data_table_conf.xml.test
- data_managers/data_manager_primer_scheme_bedfiles/data_manager/install_primer_scheme_bedfiles.xml
> Add data manager for pangoLEARN

- tools/stacks2/stacks_populations.xml
gtf file contains a line with a date
is currently failing CI
> fix stacks2 populations test

- tools/cutadapt/cutadapt.xml
- tools/cutadapt/macros.xml
I thought it would be better to create a pair if the input is a pair.
Maybe one should also use `format_source` for `out1` and `out2` instead of the `inherit_format_...` macros?
Just have seen that there is now cutadapt 3.x .. I think this will be a good target for argparse2tool. I was searching for a playground for this for a while :) .. 
> 'fix' paired output for cutadapt

- tools/calculate_numeric_param/.shed.yml
- tools/calculate_numeric_param/calculate_numeric_param.xml
An equivalent to https://github.com/galaxyproject/tools-iuc/blob/master/tools/compose_text_param/compose_text_param.xml, but allowing arithmetic operations on a workflow parameter. The use-case would be if I want to provide input `x` to one tool but e.g. `x+1` to another.
> add calculate_numeric_param tool

- .github/workflows/pr.yaml
Then users do not need to check the detailed job outputs. Might be more convenient.
> CI: Provide linter outputs as artifacts

- tools/goseq/goseq.r
- tools/goseq/goseq.xml
- tools/goseq/test-data/nobias.tab
- tools/goseq/test-data/samp.tab
> goseq: update to 1.44.0

- tools/seurat/seurat.xml
We no longer allow RDS output, so I am removing that to avoid confusion
> Change Seurat help text

- tools/minimap2/macros.xml
- tools/minimap2/minimap2.xml
Fixes #3734. The
problem is that minimap2 splits indexes above a certain basecount
(4GB by default, configurable with the -I parameter). If that
happens the SQ header lines won't be written, so we add them here.
Not sure about the performance impact of the additional samtools view
step ... it's probably minimal since it's sam in, sam out ?
Otherwise we could do something like
`(samtools view -H new_header.sam; minimap <options>) | samtool
sort` but getting a SAM header out of a fasta file would require
a custom script, it seems.
> Add header with samtools view for alignments produced via minimap2

- data_managers/data_manager_mothur_toolsuite/.shed.yml
- data_managers/data_manager_mothur_toolsuite/data_manager/data_manager_fetch_mothur_reference_data.xml
- data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py
This updates the data manager that fetches mothur reference datasets.
- Updated the tool to python3 with `2to3`.  Move to python 3.8. According to the python documentation moving files has had some optimizations in 3.8.
- ~Added a container requirement to circumvent any issues that arise from biocontainers base-container shennannigans (like: https://github.com/galaxyproject/galaxy/issues/12184)~
- Add the latest mothur references from the website
- Fix a bug where `os.rename` was used to move a file. `os.rename` only works for files on the same physical disk, and this is not necessarily the case on cluster filesystems. Use `shutil.move` instead, which always works.
- Fix an issue where the entire file would be read into memory during the download. This is now done in …
> Update mothur fetcher

- tools/minimap2/macros.xml
- tools/minimap2/minimap2.xml
This option needs to be specified with --cs=[string], --cs string is not
acceptable.
> Fix --cs option of minimap2

- tools/biom_format/biom_convert.xml
- set biom1 output type explicitly
- use biom2 type instead of h5
A bit unsure about the 2nd change .. are there downstream tools that use biom2 files as h5? 
> biom: convert: use biom1 and biom2 data types

- tools/presto/presto_alignsets.xml
- tools/presto/presto_assemblepairs.xml
- tools/presto/presto_buildconsensus.xml
- tools/presto/presto_collapseseq.xml
- tools/presto/presto_filterseq.xml
- tools/presto/presto_macros.xml
- tools/presto/presto_maskprimers.xml
- tools/presto/presto_pairseq.xml
- tools/presto/presto_parseheaders.xml
- tools/presto/presto_parselog.xml
- tools/presto/presto_partition.xml
- tools/presto/prestor_abseq3.xml
The tools were actually updated in #3747, but because this version macro wasn't updated, they do not appear as new versions in the Tool Shed.
> Fix missed pRESTO version macro update

- tools/dada2/macros.xml
1.20 is a bugfix release https://benjjneb.github.io/dada2/ReleaseNotes_1_20.html
> bump dada2

- tools/cutadapt/cutadapt.xml
- tools/cutadapt/macros.xml
An eagle-eyed user noticed that the cut option is present twice. It was in the tool form listed as the short form -u (as -U is the option for Read 2) and it was recently added again as --cut. This PR removes the --cut option and adds `(--cut)` to the help for the -u option to clarify it is the --cut option.
> Cutadapt: remove duplicated cut option

- tools/annotatemyids/annotateMyIDs.xml
...since the tool writes to the output dataset paths directly.
> annotatemyids: Drop from_work_dir attribute from outputs

- tools/snippy/macros.xml
This PR updates the Snippy tool up to version 4.6. According to the developers, it includes the following improvements:
- Now runs 2 to 3 times faster due to new threading support in markdup and fixmate
- All required Linux binaries are now bundled to simplify container building
- Reinstated TRAVIS testing
- Improved CPU spreading logic for main alignment pipeline stages
- Variants near contig ends will be less likely to be missed due to improved samclip
- Bundled tools now fully python3 compatible
> Update Snippy v4.6

- tools/tb_variant_filter/tb_variant_filter.xml
this should have never passed linting?
CI error reported at https://github.com/galaxyproject/tools-iuc/issues/3831
> tb_variant_filter: fix invalid xml

- tools/busco/busco.xml
- tools/busco/macros.xml
Hello! This is an automated update of the following tool: **tools/busco**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
> Updating tools/busco tool version(s)

- tools/ena_upload/ena_upload.xml
- tools/ena_upload/process_xlsx.py
- Parse the library_name from the excel sheet. Before it was created from a combination of experiment and sample alias to create a unique name.
- Fix the format of the receipt date: ENA takes different formats for the collection and receipt dates.
Was planning to stage this files until I had the code for https://github.com/galaxyproject/tools-iuc/issues/3882 but some people need this fix asap.
> Fix lib name and date

- tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.xml
PR which fixes a bug in the generation of the command line in the tool wrapper, specifically: erroneous extra arguments were being were inserted after `-s` option when specifying sequence data (`--ref_file` or `--index`, depending on the options chosen by the user - neither of which appear in the `cuffmerge` documentation http://cole-trapnell-lab.github.io/cufflinks/cuffmerge/ - the presence of the additional argument appeared to make `cuffmerge` incorrectly use the sequence file as the assembly GTF list).
> cuffmerge: fix broken generation of -s command line option in cuffmerge_wrapper.xml

- tools/ivar/ivar_removereads.xml
- tools/ivar/ivar_trim.xml
- tools/ivar/write_amplicon_info_file.py
The ivar trim and ivar remove_reads wrappers can infer amplicons from primer
names and this change makes the inference more robust and documents the regex
used in the tool wrapper help sections.
> Refine and document regex for amplicon grouping

- data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.py
```
File "/cvmfs/test.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_selection_background/bb5794942b5e/data_manager_selection_background/data_manager/data_manager_selection_background.py", line 12, in <module>
from six.moves.urllib.request import urlretrieve
ModuleNotFoundError: No module named 'six'
```
> Python 3.x compatibility for selection data manager.

- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py
- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
there are tags like: 2021-07-07-2 which made the DM fail
> fix pangolearn DM tag parsing

- tools/featurecounts/featurecounts.xml
This PR fixes the labels of the --fraction option. This small bug was reported by an user in [GHelp](https://help.galaxyproject.org/t/does-enabling-the-featurecounts-fractions-will-calculate-only-multimapping-nh-or-also-overlapping/6577).
> Update featureCounts: fix --fraction option labels

- tools/fastqe/fastqe.xml
- tools/fastqe/test-data/out.html
This resulted in firefox rendering it poorly whenever viewed in a standalone page where the documents encoding was not set. 
xref https://github.com/usegalaxy-eu/issues/issues/304
> FastQE was missing a meta header

- tools/sra-tools/fasterq_dump.xml
- tools/sra-tools/fastq_dump.xml
- tools/sra-tools/sam_dump.xml
- tools/sra-tools/sra_macros.xml
We don't need to use this anymore, the toolkit will download them from
S3 anyway.
> Revert direct aws access workaround

- tool_collections/vcflib/vcfsort/vcfsort.xml
When running with containers, you may end up in a container without coreutils `sort`. The busybox `sort`, for example, does not support `-V`.
> Add coreutils requirement to vcfsort

- tools/iqtree/iqtree.xml
Default values are currently unable to be used on the --mset parameter. The ones that appear in the help text are "(raxml, phyml or mrbayes)". Lower case is required, and they are being sanitized away with the current version. Not bumping version, since this is a bug in the wrapper.
> IQtree: --mset parameter requires lowercase

- tools/rgrnastar/rg_rnaStar.xml
Just fixing the case when an index built with a GFF guide is used. The code was assuming that the index was created during tool execution and thus was checking for the refGenomeSource.GTFconditional.sjdbGTFfile parameter, which is not present in the case of cached indexes.
[ ] - This PR does something else (explain below)
> fix twopass for cached index

- tools/bedtools/getfastaBed.xml
- tools/bedtools/nucBed.xml
If the fasta input does not have a corresponding .fai, these tools automatically create one. This assumes that the directory containing the fasta input is writable, which it should not be (albeit in many deployments it often is):
```
index file /galaxy-repl/test/object_store_cache/8/7/1/dataset_8717543b-c220-4420-9185-56ecd77f61aa.dat.fai not found, generating...
could not open index file /galaxy-repl/test/object_store_cache/8/7/1/dataset_8717543b-c220-4420-9185-56ecd77f61aa.dat.fai for writing!
```
~~The conditional in bedtools_getfastabed might be the wrong idea, since it would quietly mask a configuration problem (an entry in fasta_indexes that is present but the file itself is missing). We could just take the conditional out and unconditionally symlink the fai, which should cause the …
> Update bedtools_nucbed and bectools_getfastabed to symlink fasta input to prevent writing to read-only input directory

- tools/trinity/contig_exn50_statistic.xml
This script [writes to a file](https://github.com/trinityrnaseq/trinityrnaseq/blob/0c0e4a0a17192d48aec51ba43b41002aa8b5c2aa/util/misc/contig_ExN50_statistic.pl#L121) adjacent to the matrix input.
> Symlink matrix input in trinity_contig_exn50_statistic to avoid writing to input dataset dir

- tool_collections/snpsift/snpsift/snpSift_annotate.xml
Otherwise it tries to create `${dbSnp}.sidx`. There may be other tools in the suite that would also encounter this - any ideas @wm75?
> Update SnpSift Annotate to avoid writing to input directory

- tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml
> avoid mpileup writing to inputdir

- tools/roary/roary.xml
Honestly floored no one caught this before? It happens just during basic usage of roary if you pass in a prokka output (which of course is named `Prokka on data 28: gff` or so) it fails because that's written into a shell script, unquoted, which i'm assuming gets run. And that of course fails.
```
galaxy@sn06:/data/jwd/main/031/134/31134210$ cat tmp.20210923-121237/G7iTb3gxvu
extract_proteome_from_gff --translation_table 11 --apply_unknowns_filter 1 -d /data/jwd/main/031/134/31134210/working/out/cD0VOY4Fzb -o proteome.faa /data/jwd/main/031/134/31134210/working/Prokka on data 24: gff.gff
extract_proteome_from_gff --translation_table 11 --apply_unknowns_filter 1 -d /data/jwd/main/031/134/31134210/working/out/cD0VOY4Fzb -o proteome.faa …
```
> Fix Roary which puts unquoted filenames into command lines

- tools/nextclade/nextalign.xml
- tools/nextclade/nextclade.xml
Without a version we can't use the container.
> Fix nextclade coreutils dependency

- tools/bioext/bam2msa.xml
> avoid bam2msa to create BAM index in inputdir

- tools/iqtree/iqtree.xml
The `--help` output lists `--con-tree` and `--con-net` as parameters, but the code that parses the command line, as seen in the snippet below, defines them as `--contree` and `--connet`
```C++
if (strcmp(argv[cnt], "-con") == 0 || strcmp(argv[cnt], "--contree") == 0) {
params.consensus_type = CT_CONSENSUS_TREE;
continue;
}
if (strcmp(argv[cnt], "-net") == 0 || strcmp(argv[cnt], "--connet") == 0) {
params.consensus_type = CT_CONSENSUS_NETWORK;
continue;
}
```
> Update iqtree2 wrapper to correctly invoke consensus tree parameters

- tools/pangolin/pangolin.xml
I have updated tools/pangolin from version 3.1.11 to 3.1.14.
> Updating tools/pangolin from version 3.1.11 to 3.1.14

- tools/hyphy/hyphy_cfel.xml
Single branches are allowed, min was set too high originally
> Allow single branch set hyphy cfel

- .github/workflows/pr.yaml
- tools/artic/artic_guppyplex.xml
- tools/gatk4/macros.xml
Large test data should be avoided. So lets automatize this in the PR workflow. .. Sometimes it can even create problems: https://github.com/galaxyproject/galaxy/pull/12604
At the moment we have 410 files > 500k and 225 files > 1M
We can argue if we want to fail `determine-success` if large files are found.
> Let PR workflow check file sizes

- tools/trinity/macros.xml
- tools/trinity/trinity.xml
Trinity wrapper can use a scratch directory defined by the variable $TRINITY_SCRATCH_DIR but, in the current implementation, could happen that multiple Trinity instance running at the same time can overwrite results in that common path.
I am using mktemp to enforce a directory creation with a unique name  to be used as scratch dir per each instance.
Trinity has also the bad attitude to create millions of files in the same directory (we have had a dir with 9M), so I added a cleaning task using rsync for ensuring better performances.
Added coreutils and rsync to the dependencies.
* [X ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X ] - This PR …
> Trinity: scratch folder has to be unique to each Trinity instance 

- tools/bioext/macros.xml
Hello! This is an automated update of the following tool: **tools/bioext**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/bioext from version 0.20.2 to 0.20.4.
**Project home page:** https://pypi.python.org/pypi/biopython-extensions
> Updating tools/bioext from version 0.20.2 to 0.20.4

- tools/scater/macros.xml
- tools/scater/scater-filter.xml
Hello! This is an automated update of the following tool: **tools/scater**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/scater from version 1.20.0 to 1.22.0.
**Project home page:** http://bioconductor.org/packages/scater
> Updating tools/scater from version 1.20.0 to 1.22.0

- data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py
- data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
- data_managers/data_manager_build_kraken2_database/data_manager_conf.xml
This pull-request addresses #4073 and also adds a bit of additional functionality to download the pre-built 'Standard' databases from Ben Langmead's [Index Zone](https://benlangmead.github.io/aws-indexes/k2)
> Kraken2 Data Manager: Update URLs & Add Standard Pre-built DBs

- tools/tximport/tximport.xml
Hello! This is an automated update of the following tool: **tools/tximport**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/tximport from version 1.20.0 to 1.22.0.
**Project home page:** http://bioconductor.org/packages/tximport
> Updating tools/tximport from version 1.20.0 to 1.22.0

- tools/funannotate/funannotate_clean.xml
Just adding the --cpus option (it's not in the --help, but it works)
> funannotate clean: add cpu option

- tools/abyss/abyss-pe.xml
Hello! This is an automated update of the following tool: **tools/abyss**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/abyss from version 2.3.2 to 2.3.3.
**Project home page:** http://www.bcgsc.ca/platform/bioinfo/software/abyss
> Updating tools/abyss from version 2.3.2 to 2.3.3

- tools/ena_upload/check_remote.py
- tools/ena_upload/ena_upload.xml
- tools/ena_upload/process_xlsx.py
A small update to fix the request to the remote ENA server to check if there is an existing entry with the same alias. 
* [ X] - This PR updates an existing tool or tool collection
> Improve remote check

- tools/nextclade/macros.xml
- tools/nextclade/nextalign.xml
I have updated tools/nextclade from version 1.4.1 to 1.4.5.
> Updating tools/nextclade from version 1.4.1 to 1.4.5

- tools/prokka/prokka.xml
Prokka actually outputs gff3, not gff, which can break or complicate downstream analyses.
> Correct output datatype for prokka.

- data_managers/data_manager_interproscan/data_manager/interproscan.py
- data_managers/data_manager_interproscan/data_manager/interproscan.xml
3 tiny changes:
- fix the broken path in a `mv`
- lower memory usage why checking md5
- make debugging easier by writing logs immediately to stdout
> Bugfix for interproscan data manager

- tools/umi_tools/macros.xml
- tools/umi_tools/umi-tools_whitelist.xml
This PR includes two additional signs ($ and +) in the sanitizer. It was requested by an user in [GHelp](https://help.galaxyproject.org/t/umi-tools-extract-help-with-complex-regex-on-galaxy/7042).
> UMI-tools: include additional symbols in the sanitizer

- data_managers/data_manager_funannotate/data_manager/funannotate.xml
A tiny hacky fix: when using wget, disable all certificate checks while downloading.
I had to do it as I had different (minor) cert errors on different servers where funannotate downloads data...
> Funannotate data manager: https certificate fix

- tool_collections/vcflib/vcfcheck/vcfcheck.xml
> vcfsort: fix typo in test parameter name

- tool_collections/fastx_toolkit/fastx_clipper/fastx_clipper.xml
> fastx clipper: remove unused test param

- tools/bwa_mem2/bwa-mem2.xml
seems that this was only available in v1
> bwamem2: remove unused test param

- tools/funannotate/funannotate_annotate.xml
- tools/funannotate/funannotate_compare.xml
- tools/funannotate/funannotate_predict.xml
and remove unused hidden param
> funannotate: remove unused test param

- tools/freebayes/freebayes.xml
- tools/freebayes/leftalign.xml
- tools/freebayes/macros.xml
and restructure the corresponding section a bit + use long args
Note: still the param is odd, because it may collide with other params from this and one from another section... 
bump and switch to TOOL_VERSION
> freebayes: use standard_filters param on command line

- tools/iqtree/iqtree.xml
- tools/iqtree/iqtree_macros.xml
> iqtree: add missing seqtype param to command

- tools/meme/dreme.xml
- tools/meme/fimo.xml
- tools/meme/macros.xml
- tools/meme/meme.xml
- tools/meme/meme_psp_gen.xml
- tools/meme_chip/macros.xml
- tools/meme_chip/meme_chip.xml
I guess the validator should be sufficient, but maybe having this
additional if block can't hurt
will make the linter happy for https://github.com/galaxyproject/galaxy/pull/12724
alternatively we could extend the linter such that
parameters that do not appear on the command line
bu have a (expression) validator? are OK??
> meme*: add non_commercial_use to command

- tools/transit/macros.xml
- tools/transit/transit_gumbel.xml
- tools/transit/transit_hmm.xml
- tools/transit/transit_resampling.xml
- tools/transit/transit_tn5gaps.xml
and
- switch to `TOOL_VERSION`
- prefix tool names with `TRANSIT`
> transit: remove unused burnin test parameter

- tools/proteinortho/proteinortho.xml
- tools/proteinortho/proteinortho_macros.xml
> proteinortho: add missing parameter

- tool_collections/cufflinks/cuffdiff/cuffdiff_wrapper.xml
seems to be there since the beginning in dev-team tools.
> cuffdiff: remove unused test param

- tools/merlin/merlin.xml
> merlin: fix typo in test param name

- tools/cutadapt/cutadapt.xml
- tools/cutadapt/macros.xml
`--strip-suffix` and `--discard-cassava` were forgotten in the command block.
`read_modification` and `output_filtering` were once the selects of conditionals which were removed in ttps://github.com/galaxyproject/tools-iuc/commit
/9a3d1b1c3c2e2d1f6d06fa92e9a95580e8529291
xref https://github.com/galaxyproject/tools-iuc/issues/4095
> cutadapt: add missing arguments and remove unsued test params

- tool_collections/kraken/kraken-translate.xml
> kraken: fix typo in test parameter

- tools/lastz/lastz.xml
- tools/lastz/lastz_d.xml
- tools/lastz/lastz_macros.xml
1. Update lastz to latest 1.04.15 and apply recommend version format
2. Update all related tools (r-base, samtools, bzip2), because of compatibility in installation.
3. Add lastz_32 option. The lastz_32 is an additional build of lastz that allow the read genome larger than 2G. lastz will fail when hg38 is used for reference.
> lastz: add lastz32 option and update version

- tools/deseq2/deseq2.R
- tools/deseq2/deseq2.xml
- tools/deseq2/deseq2_macros.xml
Useful for scaling BAM files via the `bedtools genomecoverage` tool in order to better assess the Log2FC of a specific gene given in DESeq2 via manual inspection in IGV.
Sample size factor calculation was taken from this post:  https://support.bioconductor.org/p/97676/
> DESeq2 Update  - Add sample size factors output option

- tools/nextclade/macros.xml
I have updated tools/nextclade from version 1.4.5 to 1.5.0.
> Updating tools/nextclade from version 1.4.5 to 1.5.0

- tools/stringtie/macros.xml
- tools/stringtie/stringtie.xml
- tools/stringtie/stringtie_merge.xml
parameter was recently added to the inputs but not to the command:
https://github.com/galaxyproject/tools-iuc/pull/3964
> stringtie: add point features to command

- tools/transit/convert_gff.xml
As part of Galaxy Australia's updates we have install gff_prot with version "@VERSION@+galaxy0".  This is because in the macros the token has changed to @TOOL_VERSION.  This is the only instance of @VERSION@ I could find in the /transit/ directory
> replace @VERSION@ with @TOOL_VERSION@ in gff_prot wrapper

- tools/featurecounts/featurecounts.xml
tool defined a parameter `--countSplitAlignmentsOnly` that was unused in
the command section. Even worse such a parameter does not exist on the
CLI, but:
```
--splitOnly         Count split alignments only (ie. alignments with CIGAR
string containing 'N'). An example of split alignments is
exon-spanning reads in RNA-seq data.
--nonSplitOnly      If specified, only non-split alignments (CIGAR strings do
not contain letter 'N') will be counted. All the other
alignments will be ignored.
```
this has been fixed.
Furthermore some parameters from the large `Advanced options` section
have been moved to a new `Read filtering options` section (as suggested
by the nice featureCounts help output).
> featurecounts: fix unused parameters

- tools/varscan/varscan.py
- tools/varscan/varscan_copynumber.xml
unused in the CLI and apparently there is no commandline parameter
that could take the information
guess this is a copy paste error (from the mpileup tool)
> varscan copynumber: remove sample_names parameter

- tools/raven/macros.xml
Hello! This is an automated update of the following tool: **tools/raven**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/raven from version 1.6.1 to 1.7.0.
**Project home page:** https://github.com/lbcb-sci/raven/releases
> Updating tools/raven from version 1.6.1 to 1.7.0

- tools/pangolin/pangolin.xml
I have updated tools/pangolin from version 3.1.16 to 3.1.17.
> Updating tools/pangolin from version 3.1.16 to 3.1.17

- tools/limma_voom/limma_voom.xml
Hello! This is an automated update of the following tool: **tools/limma_voom**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/limma_voom from version 3.48.0 to 3.50.0.
**Project home page:** http://bioconductor.org/packages/release/bioc/html/limma.html
> Updating tools/limma_voom from version 3.48.0 to 3.50.0

- tools/nextclade/macros.xml
- tools/nextclade/nextalign.xml
I have updated tools/nextclade from version 1.5.1 to 1.7.0.
> Updating tools/nextclade from version 1.5.1 to 1.7.0

- tools/trycycler/macros.xml
Hello! This is an automated update of the following tool: **tools/trycycler**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/trycycler from version 0.5.1 to 0.5.3.
**Project home page:** https://github.com/rrwick/Trycycler/releases
> Updating tools/trycycler from version 0.5.1 to 0.5.3

- .github/workflows/pr.yaml
as pointed out here: https://github.com/galaxyproject/tools-iuc/pull/3973#issuecomment-944247753
reducing the size of test data does not decrease the repo size
if the files are already in. so we should only check for the sizes
of changed files and be strict with them
took this from https://github.com/galaxyproject/tools-iuc/pull/4077 .. which seems more controversial 
> CI: Check file sizes only for changed files

- tools/delly/classify.xml
- tools/delly/filter.xml
- tools/delly/macros.xml
Hello! This is an automated update of the following tool: **tools/delly**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/delly from version 0.8.7 to 0.9.1.
**Project home page:** https://github.com/dellytools/delly/releases
> Updating tools/delly from version 0.8.7 to 0.9.1

- tools/edger/edger.xml
Hello! This is an automated update of the following tool: **tools/edger**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/edger from version 3.34.0 to 3.36.0.
**Project home page:** http://bioconductor.org/packages/release/bioc/html/edgeR.html
> Updating tools/edger from version 3.34.0 to 3.36.0

- tools/chira/chira_collapse.xml
- tools/chira/chira_extract.xml
- tools/chira/chira_map.xml
- tools/chira/chira_merge.xml
- tools/chira/chira_quantify.xml
- tools/chira/macros.xml
extract: temperature was not set on the command line
map: unused test parameter unmapped
added argument to parameters for extract
> chira: fix parameters

- tools/dexseq/dexseq.xml
- tools/dexseq/dexseq_count.xml
- tools/dexseq/macros.xml
- tools/dexseq/plotdexseq.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/3695
but it will only work with https://github.com/galaxyproject/galaxy/pull/12712 .. which probably can not be included in 21.09 ..?
> dexseq use rds datatype

- tools/abyss/abyss-pe.xml
Hello! This is an automated update of the following tool: **tools/abyss**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/abyss from version 2.3.3 to 2.3.4.
**Project home page:** http://www.bcgsc.ca/platform/bioinfo/software/abyss
> Updating tools/abyss from version 2.3.3 to 2.3.4

- tools/minia/minia.xml
Hello! This is an automated update of the following tool: **tools/minia**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/minia from version 3.2.4 to 3.2.6.
**Project home page:** https://gatb.inria.fr/software/minia
> Updating tools/minia from version 3.2.4 to 3.2.6

- .github/workflows/pr.yaml
otherwise find fails for deleted files
not sure if we should add more. here is the man
```
--diff-filter=[(A|C|D|M|R|T|U|X|B)...[*]]
Select only files that are Added (A), Copied (C), Deleted (D),
Modified (M), Renamed (R), have their type (i.e. regular file,
symlink, submodule, ...) changed (T), are Unmerged (U), are Unknown
(X), or have had their pairing Broken (B). Any combination of the
filter characters (including none) can be used. When *
(All-or-none) is added to the combination, all paths are selected
if there is any file that matches other criteria in the comparison;
if there is no file that matches other criteria, nothing is
selected.
Also, these upper-case letters can be downcased to exclude. E.g.
--diff-filter=ad excludes added and deleted paths.
Note that not all diffs can …
```
> only check added files

- tools/bwameth/bwameth.xml
Hello! This is an automated update of the following tool: **tools/bwameth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/bwameth from version 0.2.2 to 0.2.3.
**Project home page:** https://github.com/brentp/bwa-meth/releases
> Updating tools/bwameth from version 0.2.2 to 0.2.3

- tools/spades/.shed.yml
- tools/spades/metaspades.xml
- tools/spades/rnaviralspades.xml
- tools/spades/spades.xml
Some of the tests are breaking for spades tools because of a missing file `write_tsv_script.py`
Include write_tsv_script.py in the .shed.yml file for all of the repositories except rnaspades.
Increase the tolerance of some of the has_size assertion tests.
> Spades: include write_tsv_script.py in .shed.yml

- tools/interproscan/macros.xml
It looks like the revision uploaded to TS in #4308 is somewhat broken, ans resetting metadata doesn't help...
So trying to bump the version suffix to trigger a new upload!?
> InterProScan: try to fix broken revision on TS

- tools/vardict/macros.xml
- tools/vardict/split.py
- tools/vardict/vardict.xml
To prevent OutOfMemoryError the genome needs to be split into smaller chunks, as suggested here:
- https://github.com/AstraZeneca-NGS/VarDictJava/issues/197
- https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Error-java.lang.OutOfMemoryError:-GC-overhead-limit-exceeded
In the current state vardict will crash when the regions are to large but it will keep on running endlessly in galaxy.
With this additional parameter this can be prevented.
> Add parameter to VarDict to chunk up chromosome.

- tools/happy/tool-data/fasta_indexes.loc.sample
- tools/happy/tool_data_table_conf.xml.sample
> Add missing tool data table conf for hap.py only detected during TS upload failure

- tools/artic/artic_guppyplex.xml
- tools/artic/artic_minion.xml
- tools/artic/macros.xml
This allows the user to specify which sequence input files guppyplex
should collapse into a single output, and which ones it should keep
separate. Also makes the tool work with fastq and fastq.gz data alike
and exposes the --quality threshold parameter.
The changeset also contains a fix for the artic minion pipeline, which
should make it handle input data with spaces in its name.
> Make guppyplex input handling more flexible

- tools/ncbi_datasets/macros.xml
Hello! This is an automated update of the following tool: **tools/ncbi_datasets**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ncbi_datasets from version 12.27.1 to 12.30.0.
**Project home page:** https://www.ncbi.nlm.nih.gov/datasets
> Updating tools/ncbi_datasets from version 12.27.1 to 12.30.0

- tools/pangolin/pangolin.xml
I have updated tools/pangolin from version 3.1.17 to 3.1.19.
> Updating tools/pangolin from version 3.1.17 to 3.1.19

- tools/icescreen/icescreen.xml
Hello! This is an automated update of the following tool: **tools/icescreen**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/icescreen from version 1.0.1 to 1.0.3.
**Project home page:** https://icescreen.migale.inrae.fr
> Updating tools/icescreen from version 1.0.1 to 1.0.3

- data_managers/data_manager_interproscan/data_manager/interproscan.xml
Currently the interproscan data manager fails to index 2 member hmm databases: sfld and superfamily
This is due to a change in recent versions (>=3.2) of hmmer being less tolerant with duplicated ids in hmm files, there's [an issue upstream for that](https://github.com/ebi-pf-team/interproscan/issues/232).
This PR is a workaround for this problem: it forces the use of an older hmmer version for indexing only. It seems to work fine like this (no change in the index content between hmmer versions).
With this, we'll be able to get rid of an annoying thing in [the annotation tutorial](https://github.com/galaxyproject/training-material/blob/a072065d713efd9bbe370d7f606269fc97f5daac/topics/genome-annotation/tutorials/funannotate/tutorial.md?plain=1#L315).
> InterProScan DM: fix indexing of sfld and superfamily

- tools/pretext/pretext_map.xml
Hello! This is an automated update of the following tool: **tools/pretext**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/pretext from version 0.1.8 to 0.1.9.
**Project home page:** https://github.com/wtsi-hpag/PretextSnapshot/releases
> Updating tools/pretext from version 0.1.8 to 0.1.9

- tools/nextclade/macros.xml
- tools/nextclade/nextclade.xml
I have updated tools/nextclade from version 1.10.1 to 1.10.2.
> Updating tools/nextclade from version 1.10.1 to 1.10.2

- tools/pangolin/pangolin.xml
I have updated tools/pangolin from version 3.1.19 to 3.1.20.
> Updating tools/pangolin from version 3.1.19 to 3.1.20

- tools/freebayes/freebayes.xml
- tools/freebayes/leftalign.xml
- tools/freebayes/macros.xml
Hello! This is an automated update of the following tool: **tools/freebayes**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/freebayes from version 1.3.5 to 1.3.6.
**Project home page:** https://github.com/ekg/freebayes/releases
> Updating tools/freebayes from version 1.3.5 to 1.3.6

- tools/porechop/porechop.xml
Porechop was not finding files determined as formats of `fastq` or `fastq.gz` so just adding them to the formats allowed
> Allow porechop to detect fastq and fastq.gz files

- tools/nextclade/macros.xml
I have updated tools/nextclade from version 1.10.2 to 1.10.3.
> Updating tools/nextclade from version 1.10.2 to 1.10.3

- tools/limma_voom/limma_voom.xml
Hello! This is an automated update of the following tool: **tools/limma_voom**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/limma_voom from version 3.50.0 to 3.50.1.
**Project home page:** http://bioconductor.org/packages/release/bioc/html/limma.html
> Updating tools/limma_voom from version 3.50.0 to 3.50.1

- tools/cutadapt/cutadapt.xml
- tools/cutadapt/macros.xml
Hello! This is an automated update of the following tool: **tools/cutadapt**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/cutadapt from version 3.5 to 3.7.
**Project home page:** https://cutadapt.readthedocs.org/en/stable
> Updating tools/cutadapt from version 3.5 to 3.7

- tools/bcftools/bcftools_annotate.xml
Regex modified to allow backslash (`\_` between tags for command line) and underscores in tags (for `%FIRST_ALT`) for the `--set-id` option. The example given on the interface works (used in the test: `%CHROM\_%POS\_%REF\_%FIRST_ALT`)
I've modified the second test (add an assert_contents: `<has_text text="1_3062915_GTTT_G" />`
> Change the validator for set_id, add test, bump version

- tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml
> FASTQ-splitter: add output labels to identify forward and reverse

- tools/legsta/legsta.xml
As legsta preserves the file name in its output, the file name shown isn't very informative to the user:
```
FILE,SBT,flaA,pilE,asd,mip,mompS,proA,neuA
dataset_1.dat,1,1,4,3,1,1,1,1
```
I've used symbolic links to preserve file names:
```
#for $i in $contigs
ln -s '$i' '$i.name';
#end for
```
Which should now output:
```
FILE,SBT,flaA,pilE,asd,mip,mompS,proA,neuA
NC_006368.fna.bz2,1,1,4,3,1,1,1,1
```
Please let me know if there's another preferred way of doing this.
> Update legsta to preserve file name

- tools/ivar/ivar_trim.xml
Due to an option name mismatch auto-generation of the amplicon info file never happened in previous versions.
> Fix ivar trim's amplicon info on the fly generation

- tools/raven/macros.xml
Hello! This is an automated update of the following tool: **tools/raven**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/raven from version 1.7.0 to 1.8.0.
**Project home page:** https://github.com/lbcb-sci/raven/releases
> Updating tools/raven from version 1.7.0 to 1.8.0

- tools/nextclade/macros.xml
- tools/nextclade/nextclade.xml
I have updated tools/nextclade from version 1.10.3 to 1.11.0.
> Updating tools/nextclade from version 1.10.3 to 1.11.0

- tools/icescreen/icescreen.xml
Hello! This is an automated update of the following tool: **tools/icescreen**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/icescreen from version 1.0.3 to 1.0.4.
**Project home page:** https://icescreen.migale.inrae.fr
> Updating tools/icescreen from version 1.0.3 to 1.0.4

- tools/repeatmodeler/macros.xml
Hello! This is an automated update of the following tool: **tools/repeatmodeler**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/repeatmodeler from version 2.0.2a to 2.0.3.
**Project home page:** https://www.repeatmasker.org/RepeatModeler
> Updating tools/repeatmodeler from version 2.0.2a to 2.0.3

- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py
- data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
- Ignores github prereleases of pangolearn models
- Fixes --testmode
- Distinguishes between downloaded filename and release tag (though
currently they are always identical)
- Simplifies date parsing
> Fix pangolearn data manager

- tools/pathview/pathview.xml
Noticed accidentally that the weekly tests need forever for pathview, because the tests tried for a long time to build the container and failed with it.
> pathview: fix version token

- tools/busco/busco.xml
- tools/busco/macros.xml
Hello! This is an automated update of the following tool: **tools/busco**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/busco from version 5.3.1 to 5.3.2.
**Project home page:** http://busco.ezlab.org
> Updating tools/busco from version 5.3.1 to 5.3.2

- tools/biom_format/macros.xml
Hello! This is an automated update of the following tool: **tools/biom_format**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/biom_format from version 2.1.10 to 2.1.12.
**Project home page:** https://github.com/biocore/biom-format/releases
> Updating tools/biom_format from version 2.1.10 to 2.1.12

- tools/cutadapt/macros.xml
Hello! This is an automated update of the following tool: **tools/cutadapt**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/cutadapt from version 3.7 to 4.0.
**Project home page:** https://cutadapt.readthedocs.org/en/stable
> Updating tools/cutadapt from version 3.7 to 4.0

- tools/pangolin/pangolin.xml
I have updated tools/pangolin from version 3.1.20 to 4.0.4.
> Updating tools/pangolin from version 3.1.20 to 4.0.5

- tools/interproscan/interproscan.xml
- tools/interproscan/macros.xml
Forgot to add this new option in #4529, here it is.
I've tested this new version on galaxy.genouest.org, it seems to work (with this PR and https://github.com/bioconda/bioconda-recipes/pull/34597), @bgruening it'd be great if you could run the data manager on .eu + make the manual changes for restricted tools as for the previous version!
> InterProScan: add new subapp

- tools/freebayes/leftalign.xml
if ftype is not given comparison is made for binary files and not diff of sam files
not sure if this broke due to a change in Galaxy.. its kind of odd, isn't it?
> freebayes leftalign: fix failing weekly CI test

- tools/pangolin/pangolin.xml
This changeset
- fixes pangolin's pangoLEARN mode broken by the previous update by
taking into account that $engine.use_assignment_cache is only defined
in UShER mode
- ensures that recombinant-parents defined in constellations >= 0.1.7 do
not prevent lineage assignment by updating scorpio to a version that
knows how to handle them (see
https://github.com/cov-lineages/constellations/releases/tag/v0.1.7 and
https://github.com/cov-lineages/pangolin/issues/445)
- adds a test for failure with incompatible UShER mode settings
> Fix pangoLEARN mode, update scorpio

- tools/anndata/export.xml
- tools/anndata/import.xml
- tools/anndata/inspect.xml
- tools/anndata/macros.xml
- tools/anndata/manipulate.xml
- tools/anndata/modify_loom.xml
As it is currently, it modifies the input, then copies the input to the output. This just moves the copy up front: copy the input to the output, then modify the output.
I could update the galaxyN version, but that would affect all the tools in the suite, right?
> Modify anndata modify_loom so it doesn't write to the input

- tools/pathview/pathview.xml
Hello! This is an automated update of the following tool: **tools/pathview**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/pathview from version 1.24.0 to 1.34.0.
**Project home page:** https://bioconductor.org/packages/release/bioc/html/pathview.html
> Updating tools/pathview from version 1.24.0 to 1.34.0

- tools/stacks2/macros.xml
- tools/stacks2/stacks_cstacks.xml
- tools/stacks2/stacks_denovomap.xml
- tools/stacks2/stacks_sstacks.xml
- tools/stacks2/stacks_ustacks.xml
---
Hi,
Some Galaxy Australia users want to combine the output of multiple `ustacks` runs at the `cstacks` (catalog building) stage. The current wrapper sets the sample ID for the first sample to 1 and then increments by 1 for each sample. This means sample IDs collide across `ustacks` runs, which causes an error in `cstacks`.
I've added a new parameter (and a test) to `ustacks` to allow the user to set the ID for the first sample. I couldn't think of a lower-impact way of doing it.
Unrelated: one of the existing ustacks tests is failing. I think this might be because the locus ID in the ustacks output changes between runs. I had to modify the tests from diff to `assert_contents`.
Gruß!
Tom
> allow user to set sample ID in stacks2_ustacks

- .github/workflows/ci.yaml
The weekly tests are timing out on mothur, this should help
> Add test timeout for weekly / slash command tests

- tools/purge_dups/macros.xml
Hello! This is an automated update of the following tool: **tools/purge_dups**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/purge_dups from version 1.2.5 to 1.2.6.
**Project home page:** https://github.com/dfguan/purge_dups/releases
> Updating tools/purge_dups from version 1.2.5 to 1.2.6

- tools/pyega3/pyega3.xml
When providing the start position 0 to the pyega3 tool it will skip the argument, since the if will see a 0.
I think this change should fix it?
> Update pyega3.xml: missing --start

- tools/maxbin2/maxbin2.xml
**Issue**: when running with collections for `reads` or `abund` inputs, datasets in collection are took together (not in parallel). It makes then impossible to run it for individual assembly where contigs and reads are stored in collections.
Using the repeat may solve the issue and makes also closer to the tool design
After discussion with @bgruening, I will change the approach: ask the type of assembly from the beginning, and depending on that, use `multiple=true` or not
> MaxBin2: Modify reads/abunds to use repeat instead of multiple to support using collection

- tools/vg/deconstruct.xml
currently failing CI because if different line ordering
might be due to the use of two cores?
> vg deconstruct: sort test data

- tools/spyboat/spyboat.xml
which contains the number of used cores
> spyboat: allow 1 line difference in output

- tools/medaka/macros.xml
- tools/medaka/medaka_consensus.xml
linking is insufficient (fai file is still created next to the link target)
> medaka: copy fasta file

- tools/concoct/concoct.xml
- tools/concoct/macros.xml
- tools/concoct/test-data/process_log.txt
due to recent CI change the number of used CPUs changed
which is included in the log file.
test is fixed by using compare="re_match"
> concoct: fix test

- tools/datamash/datamash-ops.xml
- tools/datamash/macros.xml
- tools/datamash/test-data/na_values_input.tsv
Adds the `--narm` option in datamash, which can be set in order to ignore `NA` and `NaN` values when computing e.g. a mean over a column.
> Datamash: add --narm option to ignore NA or NaN values

- tool_collections/biotradis/bacteria_tradis.xml
From Matrix:
> hi, I'm using 'Transposon Insertion Sequencing'-'Bio-TraDis reads to counts'. And  I'm trying to set the parameter 2nb_mismatches in the 'search for a transposon tag' setting, but I cannot chose more than 1. How can I get this fixed?
> remove max value from nb_mismatches in tradis tool

- tools/hamronization/hamronize_summarize.xml
I had a student report not finding the summarize tool, hence this PR to prefix the name with "hamronize", like we do with other tool suites (seqtk, bedtools, circos.)
> Harmonize hAMRonize:summarize's name to convention of prefixing

- tools/lofreq/lofreq_alnqual.xml
- tools/lofreq/lofreq_call.xml
- tools/lofreq/lofreq_indelqual.xml
- set `ftype` .. otherwise bam are compared binary (@mvdbeek is this expected .. maybe its a Galaxy bug? But setting ftype also does not hurt here)
- increase lines_diff (xref https://github.com/CSB5/lofreq/issues/131)
> Lofreq fixes

- tools/bowtie2/bowtie2_wrapper.xml
- tools/hisat2/hisat2.xml
- tools/hisat2/hisat2_macros.xml
due to different number of used processors the order of the lines
in the (S)BAM may differ (not sure if due to hisat/samtools ..
but this does not matter I guess)
> hisat2, bowtie2: add sort attribute to bam test outputs

- tools/pangolin/pangolin.xml
This changeset represents a major rewiring (once more) of the wrapper's
logic:
- pin all core dependencies (defined by output of pangolin
--all-versions)
=> wrapper +galaxy version updates are supposed to keep core
dependencies up-to-date
- enable separate control over pangolin-data and constellations data
packages
- make use of conda env versions of data packages the default
- prepare wrapper for interoperability with future pangolin-data DM
> Update pangolin to v4.1

- tools/ivar/ivar_removereads.xml
- tools/ivar/ivar_trim.xml
- tools/ivar/prepare_amplicon_info.py
- tools/ivar/sanitize_bed.py
- tools/ivar/write_amplicon_info_file.py
This fixes a common stumbling block for users of the ivar trim and
removereads tools where even a single trailing extra line in the primer
bed or amplicon info file will cause the tools to fail witha hard to
understand traceback. With the changes here, empty (whitespace-only)
lines in either of the two files will simply be ignored by all relevant
Galaxy-specific helper scripts.
> Tolerate empty lines in ivar helper scripts inputs

- tools/instrain/instrain_profile.xml
- tools/instrain/macros.xml
tool currently fails CI
compare also calls unzip and should have the requirement
tool still fails, because Galaxy unzips the zip inputs: I see `ZIP file contained more than one file, only the first file was added to Galaxy.` in the Dataset Info of the input datasets (and the actual tool fails with `unzip: short read`).
> instrain: add zip requirement to all

- tools/fraggenescan/fraggenescan.xml
different numbers of used CPUs lead to different order of sequences
tool fails CI at the moment
> fraggenescan: compare sorted fasta

- .gitignore
- CODE_OF_CONDUCT.md
Also:
- Restore `.gitignore` file removed by mistake in commit 9968295 .
> Add Code of Conduct

- tools/ngmlr/ngmlr.xml
output order differs depending on the # of used cores
> ngmlr: fix test for multiprocessing

- tool_collections/snpeff/gbk2fa.py
- tool_collections/snpeff/snpEff_create_db.xml
- tool_collections/snpeff/snpEff_macros.xml
The current version of the tool is failing on up-to-date instances of Galaxy (usegalaxy.org and usegalaxy.eu) because the tool magically picks up incompatible magic data from the Galaxy venv:
- `magic.MagicException: b"File 5.32 supports only version 14 magic files. /cvmfs/[main.galaxyproject.org/venv/lib/python3.8/site-packages/pylibmagic/magic.mgc](http://main.galaxyproject.org/venv/lib/python3.8/site-packages/pylibmagic/magic.mgc)' is version 16"` on usegalaxy.org
- `magic.MagicException: b"File 5.32 supports only version 14 magic files. /opt/galaxy/venv/lib64/python3.8/site-packages/pylibmagic/magic.mgc' is version 16"` on usegalaxy.eu
It's not entirely clear to me how that happens and I find this a bit disturbing, but from the tool wrapper point of view the whole …
> Have Snpeff build detect genbank input file compression without any magic

- tools/maker/maker.xml
A Galaxy Australia user has reported a bug when they choose the advanced option "Consider single exon EST evidence when generating annotations"
> Fix maker error when single_length is specified

- tools/checkm/analyze.xml
- tools/checkm/lineage_wf.xml
- tools/checkm/macros.xml
- tools/checkm/taxonomy_wf.xml
- tools/checkm/tree.xml
---
All outputs are generated by defaults (and displayed in the workflow) if no options are selected for `extra_output` parameter (see [Galaxy issue](https://github.com/galaxyproject/galaxy/issues/7465#issuecomment-1207970222))
> CheckM: Add filter for empty extra output

- tools/chromeister/chromeister.xml
currently failing CI because stderr contains:
```
Fontconfig error: No writable cache directories
```
but exit_code is 0.
stderr is ignored if a up to date profile is used.
> chromeister: add profile

- tools/picard/picard_CollectSequencingArtifactsMetrics.xml
- tools/picard/picard_ValidateSamFile.xml
> picard: implement missing parameters

- tools/spades/macros.xml
- tools/spades/metaplasmidspades.xml
- tools/spades/metaspades.xml
- tools/spades/metaviralspades.xml
- tools/spades/plasmidspades.xml
- tools/spades/rnaviralspades.xml
- tools/spades/spades.xml
f37ce4136944e04dc14952bbfdca489ceda88d7d fixes current CI failure
Instead of 879ce2ee31c993faf0183f27d6d13bb1458c1e20 we could also define the `operation_mode` parameter in all tools?
> Spades fixes

- .github/workflows/pr.yaml
- fix function that emits a deprecation warning
- also output line (can't hurt)
> CI: lintr updates

- tools/odgi/build.xml
- tools/odgi/macros.xml
currently fails CI due to
```
|  odgi: /opt/conda/conda-bld/odgi_1616839257024/work/deps/gfakluge/src/gfakluge.hpp:569: size_t gfak::mmap_open(const string&, char*&, int&): Assertion `false' failed.
|  /tmp/tmpdi1icj3u/job_working_directory/000/2/tool_script.sh: line 22:     7 Aborted                 (core dumped) odgi build -g '/tmp/tmpdi1icj3u/files/b/0/4/dataset_b04a44e9-eafd-415b-a3a8-0e671b31ff1d.dat' -o '/tmp/tmpdi1icj3u/job_working_directory/000/2/outputs/galaxy_dataset_6817b8a3-8f3d-4f14-a7ad-d73d11568ad8.dat' --sort --to-gfa > '/tmp/tmpdi1icj3u/job_working_directory/000/2/outputs/galaxy_dataset_38a641a6-89d8-4d27-baf0-00a9e665dd58.dat'
```
which is because https://github.com/edawson/gfakluge/issues/65
> fix odgi build

- .github/workflows/pr.yaml
as in CI .. otherwise we will just have failing CI jobs for long running tools
> apply test timeout also to PRs

- tools/arriba/arriba.xml
- tools/arriba/macros.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/4799
problem was that the conditional and the contained parameter had the same name `wgs`.
also:
- wgs parameter should also (explicitly) accept vcf as documented
- do not check for gtf.gz datattype which does not exist in Galaxy and is also not allowed as input
- remove bash comment
TODO
> fix arriba

- tools/arriba/arriba.xml
- tools/arriba/macros.xml
`wgs_cond` was typed as `wg_cond` at line 76 causing an error when using SV data in Arriba. Part of fix #4801 
> Fix typo Arriba

- tools/spyboat/spyboat.xml
The `license` attribute refers to the wrapper's license, not the license of the underlying tool(s), see https://docs.galaxyproject.org/en/master/dev/schema.html#attributes
xref. https://github.com/galaxy-iuc/standards/issues/72
> Fix SpyBOAT wrapper license

- tools/vcf2maf/vcf2maf.xml
Previously, --ncbi_build was not set in the "no_vep"-case and therefore defaulted to "GRCh37". With this update, the parameter is set according to the dbkey of the input VCF file. Human and mouse are special cases as cBioPortal requires their assembly names in NCBI notation. Therefore, the dbkey of these is translated before.
> vcf2maf: Added partially missing ncbi_build parameter

- tools/map_param_value/.shed.yml
- tools/map_param_value/map_param_value.xml
This will be very helpful for the 5th bullet point in https://github.com/galaxyproject/iwc/pull/126:
> Also, if there is a way in galaxy to do a:
if $strandness is 'unstranded' then parameter value is blabla elif $strandess is 'forward' then parameter value is bliblibli else parameter value is blobloblo' This would be better than letting the user choose between 3 awk commands and this would help for the stranded coverage.
I think we will eventually want to allow attaching arbitrary expressions to steps, which have access to a particular steps' jobs object,  closer to what CWL allows, but in the meantime this can be used to have user-friendly text values as workflow inputs.
> Add map_param_value expression tool

- tools/pureclip/.shed.yml
This just adds the "CLIP-seq" toolshed category. There are a number of CLIP-seq related tools on Galaxy, so a CLIP-seq category will be useful to better categorize them.
> add CLIP-seq toolshed category

- tools/recentrifuge/macro.xml
Hello! This is an automated update of the following tool: **tools/recentrifuge**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/recentrifuge from version 1.9.1 to 1.10.0.
**Project home page:** https://github.com/khyox/recentrifuge/releases
> Updating tools/recentrifuge from version 1.9.1 to 1.10.0

- tools/seqkit/macros.xml
- tools/seqkit/test-data/stats_output1.tabular
- tools/seqkit/test-data/stats_output2.tabular
Hello! This is an automated update of the following tool: **tools/seqkit**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seqkit from version 2.2.0 to 2.3.1.
**Project home page:** https://bioinf.shenwei.me/seqkit
> Updating tools/seqkit from version 2.2.0 to 2.3.1

- tools/spades/macros.xml
- tools/spades/spades.xml
Hello! This is an automated update of the following tool: **tools/spades**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/spades from version 3.15.4 to 3.15.5.
**Project home page:** https://github.com/ablab/spades/releases
> Updating tools/spades from version 3.15.4 to 3.15.5

- tools/blast/macros.xml
- tools/blast/magicblast.xml
Hello! This is an automated update of the following tool: **tools/blast**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/blast from version 1.6.0 to 1.7.0.
**Project home page:** https://ncbi.github.io/magicblast
> Updating tools/blast from version 1.6.0 to 1.7.0

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/slash.yaml
This PR only change the github workflow yaml to avoid the deprecation warnings and use the new syntax: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> remove deprecated set-output syntax and update create-or-update-comment

- tools/table_compute/scripts/table_compute.py
- tools/table_compute/table_compute.xml
- tests 20 and 21 were suddenly failing in CI 
- failure is legit, but I don't know which galaxy change triggered it
- not sure what triggers the failing test 41 (it appears that the test is supposed to fail, but it is not recognized)
> Fix python linting errors for table_compute

- tools/ncbi_acc_download/macros.xml
- tools/ncbi_acc_download/ncbi_acc_download.xml
Hello! This is an automated update of the following tool: **tools/ncbi_acc_download**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ncbi_acc_download from version 0.2.7 to 0.2.8.
**Project home page:** https://github.com/kblin/ncbi-acc-download/releases
> Updating tools/ncbi_acc_download from version 0.2.7 to 0.2.8

- tools/proteinortho/proteinortho_grab_proteins.xml
- tools/proteinortho/proteinortho_macros.xml
- tools/proteinortho/proteinortho_summary.xml
the bioconda blat package seems outdated (last update ~ 4 years ago). seems now in ucsc-blat
might also be the reason for
https://github.com/BioContainers/multi-package-containers/pull/2378/checks failing
also CI is failing since the last update of proteinortho .. but it's a wild guess that this is related.
see also https://github.com/galaxyproject/tools-iuc/pull/4928
> proteinortho: use recent blat package

- data_managers/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py
- data_managers/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.xml
- data_managers/data_manager_gemini_database_downloader/test-data/gemini_versioned_databases.loc
- data_managers/data_manager_gemini_database_downloader/test-data/test.json
- data_managers/data_manager_gemini_database_downloader/tool_data_table_conf.xml.test
This specifies 18.09 as the profile of the wrapper to prevent Galaxy's Python from being used. It also changes the DM script to run the actual download last (so that script errors will surface immediately instead of after a download of several GBs), and adds tests and a test mode that does not actually download anything.
> Use gemini's python in its data manager

- tools/arriba/arriba.xml
- tools/arriba/macros.xml
the filter of output `aligned_bam` was broken (the used variables just do not exist). this led to an error because Galaxy tried to set metadata for and empty or non-existent file.
the output was removed because its not needed (its essentially the same as the input). it probably stems from an earlier version that included the alignment step.
also the alignment seems to be used if
- `$output_fusion_bams` and
- `str($visualization.do_viz)=="yes"`
so it needs to be generated in both
> fix arriba test

- data_managers/data_manager_interproscan/data_manager/interproscan.py
- data_managers/data_manager_interproscan/data_manager/interproscan.xml
- tools/interproscan/README.md
- tools/interproscan/interproscan.xml
- tools/interproscan/macros.xml
- tools/interproscan/test-data/interproscan.loc
Here's the interproscan update following https://github.com/bioconda/bioconda-recipes/pull/38043
I had to update the DM too as the data indexing script has a new name in this version, and is not indexing exactly the same way as in previous versions.
I hope we won't get too much surprises with this update :crossed_fingers: 
ping @pvanheus
> Update InterProScan to 5.59-91.0

- tools/proteinortho/proteinortho_macros.xml
Hello! This is an automated update of the following tool: **tools/proteinortho**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/proteinortho from version 6.1.2 to 6.1.5.
**Project home page:** https://gitlab.com/paulklemm_PHD/proteinortho
> Updating tools/proteinortho from version 6.1.2 to 6.1.5

- tools/annotatemyids/annotateMyIDs.xml
Hello! This is an automated update of the following tool: **tools/annotatemyids**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/annotatemyids from version 3.14.0 to 3.16.0.
> Updating tools/annotatemyids from version 3.14.0 to 3.16.0

- tools/ncbi_entrez_direct/macros.xml
Hello! This is an automated update of the following tool: **tools/ncbi_entrez_direct**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ncbi_entrez_direct from version 13.3 to 16.2.
**Project home page:** http://www.ncbi.nlm.nih.gov/books/NBK179288
> Updating tools/ncbi_entrez_direct from version 13.3 to 16.2

- tools/biom_format/macros.xml
Hello! This is an automated update of the following tool: **tools/biom_format**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/biom_format from version 2.1.12 to 2.1.13.
**Project home page:** https://github.com/biocore/biom-format/releases
> Updating tools/biom_format from version 2.1.12 to 2.1.13

- data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml
Update the GTDB data manager default URL to match the current version of the tool.
GTDB-Tk versions are tightly linked to the GTDB version. The default version offered by the data manager does not match the currently released GTDB-Tk tool version.
---
An additional comment - should the DB URL field be a `select` field, with hard-coded values? That way admins will easily be able to select the appropriate version to download, and we can hard-code the correct DB ID into the GTDB-Tk tool wrapper so that users don't need to figure out which DB is appropriate for the current tool version (I picture lots of failed jobs). Something like:
```yml
Select:
- R207_v2: matches GTDB-Tk v2.1.0+
- R207: matches GTDB-Tk v2.0.0
- R202: matches GTDB-Tk v1.5.0 - v1.7.0
```
I'll create a separate issue for …
> Fix GTDB default URL

- tools/pangolin/pangolin.xml
The freshly released pangolin 4.2 brings a change to the implementation (usher-sampled) of the tool's UShER mode.
This final wrapper 4.1 series update bumps all dependencies to the versions that will be used for 4.2 to enable direct comparison between the old usher and the new usher-sampled implementation.
> Update pangolin to 4.1.3 with latest dependencies

- .github/workflows/pr.yaml
I have tested this successfully  with 
- the standard merge and
- squash merge
Note, **rebase merge does not work** .. so we would need to disable this in the settings. This might be a limitation of the action used to get the PR number, but I guess its difficult / impossible because SHAs don't match to the SHAs of the commits in the PR. 
> PR workflow: report deployment failure

- .github/workflows/pr.yaml
If any of jobs needed for deployment fails, the deployment job is skipped and no message is triggered. 
Now a message should be triggered.
Just wondering if people subscribed to a PR still get the notification once the PR is closed .. guess so - but not sure.
> trigger deployment message on anything but success

- tools/biom_format/macros.xml
Hello! This is an automated update of the following tool: **tools/biom_format**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/biom_format from version 2.1.13 to 2.1.14.
**Project home page:** https://github.com/biocore/biom-format/releases
> Updating tools/biom_format from version 2.1.13 to 2.1.14

- tools/kleborate/kleborate.xml
Hello! This is an automated update of the following tool: **tools/kleborate**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/kleborate from version 2.2.0 to 2.3.0.
**Project home page:** https://github.com/katholt/Kleborate/wiki/releases
> Updating tools/kleborate from version 2.2.0 to 2.3.0

- tools/beagle/beagle.xml
- tools/beagle/macros.xml
and always set input extension for ext to avoid WARNING in log (which might be meaningful)
tool currently fails CI
> beagle: fix tests

- tools/mirnature/macros.xml
- tools/mirnature/mirnature.xml
stdout contains dataset IDs which are different in weekly CI tests
> fix mirnature tests

- tools/bioinformatics_cafe/.shed.yml
because TS does not allow dash
followup for https://github.com/galaxyproject/tools-iuc/pull/5094
> rename bioinf cafe suite

- tools/ivar/ivar_consensus.xml
> Force full-length ivar consensus builds

- tools/ivar/ivar_trim.xml
... for real this time after an insufficient previous attempt in [27f076c].
> Fix ivar trim use of autogenerated amplicon info

- tools/integron_finder/integron_finder.xml
- tools/integron_finder/macro.xml
This is needed because of https://github.com/gem-pasteur/Integron_Finder/issues/90 which results in a directory with multi-million of files.
> Add a safe guard to integron 

- tools/bedtools/coverageBed.xml
- tools/bedtools/test-data/mean_coverage.bed
Just add the `-mean options` which simplify the output to extract the mean depth of specific regions
> bedtool add mean option to calculate mean depth of specific bed regions

- tools/quast/macros.xml
- tools/quast/quast.xml
---
With the current implementation of QUAST, we do not support the mapping  (when reads are given) of raw data on contigs generated by assembly run on individual samples (because of the `multiple=True` and loops on inputs)
It should work like this: 
But in reality, currently, we have 2 use cases with individual assembly:
- With raw reads in paired collection:
This case was really computational expensive as raw reads were mapped on each contig files in the collection
- With reads in forward and reverse collections:
To solve this, I added a conditional for the assembly mode:
- If individual assembly, I removed all `multiple=True` and for loops on inputs, so QUAST runs several times in each element in collection
- If co-assembly, I kept the `multiple=True` and put loops on …
> Quast: support assemby (individual or co) modes

- tools/busco/busco.xml
- tools/busco/macros.xml
Hello! This is an automated update of the following tool: **tools/busco**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/busco from version 5.4.4 to 5.4.5.
**Project home page:** https://gitlab.com/ezlab/busco/-/releases
> Updating tools/busco from version 5.4.4 to 5.4.5

- tools/yahs/yahs.xml
hello! 👋🏼 
added an option to the yahs tools under the "preconfigured enzymes" to select Dovetail Omni-C, which is an enzyme-free prep, which means just running yahs without the restriction enzyme argument
> yahs: added option for Omni-C enzyme-free prep

- tools/kleborate/kleborate.xml
Hello! This is an automated update of the following tool: **tools/kleborate**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/kleborate from version 2.3.0 to 2.3.2.
**Project home page:** https://github.com/katholt/Kleborate/wiki/releases
> Updating tools/kleborate from version 2.3.0 to 2.3.2

- tools/ensembl_vep/ensembl_vep.xml
Hello! This is an automated update of the following tool: **tools/ensembl_vep**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ensembl_vep from version 108.0 to 109.3.
> Updating tools/ensembl_vep from version 108.0 to 109.3

- tools/arriba/macros.xml
Hello! This is an automated update of the following tool: **tools/arriba**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/arriba from version 2.3.0 to 2.4.0.
**Project home page:** https://github.com/suhrig/arriba/releases
> Updating tools/arriba from version 2.3.0 to 2.4.0

- tools/ivar/ivar_consensus.xml
- tools/ivar/ivar_trim.xml
- tools/ivar/macros.xml
- implements new -m default in ivar trim
- removes max value restriction on -m option in ivar consensus after upstream fix
- works around messed up ivar trim stdout/stderr in new version
> Update ivar suite of tools to v1.4

- tools/rgrnastar/macros.xml
Sorry, I found again an error into the wrapper of STAR. The label says the opposite of the value...
> Update STAR wrapper: fix outWigStrand

- tools/coverm/coverm_contig.xml
- tools/coverm/coverm_genome.xml
weekly CI failing with:
```
Output output1:  different than expected, difference (using diff):
( /tmp/tmpiesiezo1test3.tsv v. /tmp/tmpjejgm78btest3.tsv )
--- local_file
+++ history_data
@@ -1,4 +1,4 @@
Genome	fw0 Mean
+genome2	4.8142858
genome1	0
-genome2	4.8142858
genome3	0
```
just applied it to all tests
> Fix coverm test

- .github/workflows/pr.yaml
... but keep testing PR commits as before.
Includes only the uncontroversial part of #5199.
Regarding planemo-autoupdate, this will already cut the number of tests run down to half (since push tests are currently running on the autoupdate bots branches, while those same commits get tested also as part of the PRs).
> Test commits pushed to main, not other branches

- .tt_skip
- data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml
- tools/metaphlan/macros.xml
Updated metaphlan version, commented out DM test as the target file is too big to be used as a test.
> metaphlan  v4.0.5 -> v4.0.6

- data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml
Segata lab kindly re-organised their FTP server upon our request, so now we have a toy DB for tests.
> Update metaphlan: Toy db added

- tools/schicexplorer/macros.xml
- tools/schicexplorer/scHicAdjustMatrix.xml
- tools/schicexplorer/scHicCluster.xml
- tools/schicexplorer/scHicClusterCompartments.xml
- tools/schicexplorer/scHicClusterMinHash.xml
- tools/schicexplorer/scHicClusterSVL.xml
- tools/schicexplorer/scHicConsensusMatrices.xml
- tools/schicexplorer/scHicCorrectMatrices.xml
- tools/schicexplorer/scHicCreateBulkMatrix.xml
- tools/schicexplorer/scHicDemultiplex.xml
- tools/schicexplorer/scHicInfo.xml
- tools/schicexplorer/scHicMergeMatrixBins.xml
- tools/schicexplorer/scHicMergeToSCool.xml
- tools/schicexplorer/scHicNormalize.xml
- tools/schicexplorer/scHicPlotClusterProfiles.xml
- tools/schicexplorer/scHicPlotConsensusMatrices.xml
- tools/schicexplorer/scHicQualityControl.xml
there is no scool datatype in Galaxy. scool is currently sniffed as h5
which leads to an error with galaxyproject/galaxy#12073
possible solutions:
- replace scool by h5 and lower the profile
- add scool dataype to Galaxy and set the profile to the Galaxy version
where it was added
> schicexplorer misses scool datatype

- data_managers/data_manager_bowtie2_index_builder/data_manager_conf.xml
- data_managers/data_manager_bowtie_index_builder/data_manager_conf.xml
- data_managers/data_manager_build_amrfinderplus/data_manager/data_manager_build_amrfinderplus.xml
- data_managers/data_manager_build_amrfinderplus/data_manager_conf.xml
- data_managers/data_manager_build_amrfinderplus/test-data/amrfinderplus_test_data_manager_1.json
- data_managers/data_manager_build_bakta_database/data_manager_conf.xml
- data_managers/data_manager_build_bracken_database/data_manager_conf.xml
- data_managers/data_manager_build_kraken2_database/data_manager_conf.xml
- data_managers/data_manager_build_kraken_database/data_manager_conf.xml
- data_managers/data_manager_bwa_mem_index_builder/data_manager_conf.xml
- data_managers/data_manager_gatk_picard_index_builder/data_manager_conf.xml
- data_managers/data_manager_hisat2_index_builder/data_manager_conf.xml
- data_managers/data_manager_homer_preparsed/data_manager_conf.xml
- data_managers/data_manager_kallisto_index_builder/data_manager_conf.xml
- data_managers/data_manager_manual/data_manager_conf.xml
- data_managers/data_manager_mash_sketch_builder/data_manager_conf.xml
- data_managers/data_manager_mitos/data_manager_conf.xml
- data_managers/data_manager_ncbi_taxonomy_sqlite/data_manager_conf.xml
- data_managers/data_manager_picard_index_builder/data_manager_conf.xml
- data_managers/data_manager_salmon_index_builder/data_manager_conf.xml
- data_managers/data_manager_sam_fasta_index_builder/data_manager_conf.xml
- data_managers/data_manager_star_index_builder/data_manager_conf.xml
- data_managers/data_manager_twobit_builder/data_manager_conf.xml
xref https://github.com/galaxyproject/galaxy/pull/12255
I suggest to skip deployment, ie.. [skip-ci]
> remove deprecated `version` attribute from data_manager_conf.xml

- tools/sinto/sinto_fragments.xml
> Sinto fragment: correct the duplicated labels

- tools/ivar/ivar_trim.xml
- tools/ivar/macros.xml
This version fixes https://github.com/galaxyproject/tools-iuc/pull/5162#issuecomment-1482938130 and with that finally allows piping data between ivar trim and samtools sort.
> Update ivar to 1.4.2

- tools/metaphlan/macros.xml
- tools/metaphlan/metaphlan.xml
Addresses the Cheetah error encountered if a non-default analysis type is chosen:
...
File "/opt/galaxy/venv/lib64/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
return getattr(self, mainMethName)()
File "cheetah_DynamicallyCompiledCheetahTemplate_1681888750_8410845_53299.py", line 401, in respond
NameMapper.NotFound: cannot find 'tax_lev' while searching for 'analysis.analysis_type.tax_lev.tax_lev'
> Update metaphlan: error on alternative analysis types

- tools/ruvseq/ruvseq.R
- tools/ruvseq/ruvseq.xml
Changes in ruvseq wrapper and script to add Ruvseq Normalized counts output
Be aware that this normalized counts CANNOT be utilized for statistical purposes and further DESeq2, edgeR or limma analysis.
It can ONLY be used for vizualisation purposes
> Ruvseq add normcounts

- tools/drep/macros.xml
Hello! This is an automated update of the following tool: **tools/drep**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/drep from version 3.4.2 to 3.4.3.
**Project home page:** https://github.com/MrOlm/drep/releases
> Updating tools/drep from version 3.4.2 to 3.4.3

- tools/funannotate/funannotate_annotate.xml
- tools/funannotate/macros.xml
Fill an env var needed by some subprocess. Problem reported upstream in https://github.com/nextgenusfs/funannotate/issues/905
> Funannotate: fix for missing env var

- tools/repeatmodeler/macros.xml
- tools/repeatmodeler/repeatmodeler.xml
The thread count option has changed in 2.0.4, it's simpler now:
https://github.com/Dfam-consortium/RepeatModeler/blob/master/RELEASE-NOTES#LL7C39-L7C39
> RepeatModeler: adapt to new thread count option

- tools/minimap2/macros.xml
Hello! This is an automated update of the following tool: **tools/minimap2**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/minimap2 from version 2.24 to 2.26.
**Project home page:** https://github.com/lh3/minimap2/releases
> Updating tools/minimap2 from version 2.24 to 2.26

- tools/abyss/abyss-pe.xml
Hello! This is an automated update of the following tool: **tools/abyss**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/abyss from version 2.3.4 to 2.3.6.
**Project home page:** http://www.bcgsc.ca/platform/bioinfo/software/abyss
> Updating tools/abyss from version 2.3.4 to 2.3.6

- .github/workflows/pr.yaml
- .github/workflows/pr_without_tool_change.yaml
The intention here is to prevent the entire tool linting and tests workflow from running if the only files changed in a PR or a merge commit are in folders that do not contain tool-associated files.
This is kind of straightforward using paths-ignore, but needs a bit of extra work because of the repo's required status check (see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore and the note on status checks therein).
> Do not initiate tool tests if no tool was touched

- tools/getorganelle/get_organelle_from_reads.xml
- tools/getorganelle/macros.xml
Hello, 
Today I found that get_organelle_from_reads.xml was not able to work with "paired_collections" as input. 
I was able to find a couple of potential issues: 
- spelling of "in1_name1" 
- the paired_collection paramter name "fastq_input1" did not match the name used in the command block "paired_input".  
I thought this might fix my issue but I still get the error below: 
```
NameMapper.NotFound: cannot find 'paired_input' while searching for 'fastq_input.paired_input.forward.ext'
```
@bernt-matthias can you see where i might have gone wrong here? 
Fix errors with paired collection parameters
> Update get_organelle_from_reads.xml to handle paired collections correctly 

- tools/verkko/verkko.xml
Hello! This is an automated update of the following tool: **tools/verkko**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/verkko from version 1.2 to 1.3.1.
**Project home page:** https://github.com/marbl/verkko/releases
> Updating tools/verkko from version 1.2 to 1.3.1

- tools/deepmicro/deepmicro.xml
- tools/deepmicro/macros.xml
fix `cannot find 'dm' while searching for 'params.rl_type.dm'` bug for train on input option
> Bug fix for deepmicro

- tools/proteinortho/proteinortho.xml
- tools/proteinortho/proteinortho_macros.xml
- tools/proteinortho/proteinortho_summary.xml
> update proteinortho v6.2.3 and some changes to the xml

- data_managers/data_manager_dada2/data_manager/dada2_fetcher.xml
Just realized that I messed up the versioning of this datamanager in the past https://github.com/galaxyproject/tools-iuc/pull/3000
xref: https://github.com/galaxyproject/galaxy/issues/16276
> bump dada2 data manager

- tools/sra-tools/macros.xml
Hello! This is an automated update of the following tool: **tools/sra-tools**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/sra-tools from version 3.0.3 to 3.0.5.
**Project home page:** https://github.com/ncbi/sra-tools/releases
> Updating tools/sra-tools from version 3.0.3 to 3.0.5

- tool_collections/samtools/samtools_coverage/samtools_coverage.xml
- tool_collections/samtools/samtools_coverage/test-data/results_4.tabular
- tool_collections/samtools/samtools_coverage/test-data/results_5.tabular
In the samtools coverage tool, fixed 2 issues with the region parameter:
- region parameter is not specific to histogram output option so moved it out of that conditional and into the general additional options section
- region parameter was not working because the macros preparing the index do not work out of the box if the input files are inside a conditional
> Samtool coverage: fix region parameter

- tools/deseq2/deseq2.R
- tools/deseq2/deseq2.xml
- tools/deseq2/macros.xml
- tools/deseq2/test-data/size_factors_out.tsv
I  wish there would be a way to fix the displayed version numbers to something that follows the version of deseq2 itself. Displaying "2.11.40.8" is misleading.
> Update Deseq2 to v. 1.38

- tools/annotatemyids/.shed.yml
- tools/annotatemyids/annotateMyIDs.xml
Hello! This is an automated update of the following tool: **tools/annotatemyids**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/annotatemyids from version 3.16.0 to 3.17.0.
> Updating tools/annotatemyids from version 3.16.0 to 3.17.0

- tools/geneiobio/geneiobio-iframe.xml
Gene.iobio does not accept `vcf` as it has to find the `tbi` file which is only generated from the `vcf_bgzip` format.
> Remove VCF as viable format

- tools/bwa_mem2/bwa-mem2.xml
- tools/bwa_mem2/macros.xml
hello! 👋🏼 
this PR exposes the `-K` parameter in bwa-mem2, which is described in the help as: `-K INT        process INT input bases in each batch regardless of nThreads (for reproducibility) []`
normally, the program just sets this parameter scaled to the number of threads given, but we've been having some memory issues on our local infrastructure where we want to still give the program a good amount of cores but not have the memory necessarily scale up, too, so this lets us set it lower
> bwa-mem2: expose the `-K` parameter for batch size

- tools/mosdepth/mosdepth.xml
Hello! This is an automated update of the following tool: **tools/mosdepth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mosdepth from version 0.3.3 to 0.3.4.
**Project home page:** https://github.com/brentp/mosdepth/releases
> Updating tools/mosdepth from version 0.3.3 to 0.3.4

- tools/humann/macros.xml
Hello! This is an automated update of the following tool: **tools/humann**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/humann from version 3.7 to 3.8.
**Project home page:** http://huttenhower.sph.harvard.edu/humann
> Updating tools/humann from version 3.7 to 3.8

- tools/concoct/concoct.xml
- tools/concoct/macros.xml
Using the default value that is actually in the wrapper leads to error for many datasets. Looking at the tool code, I found out that the default value is different than the one defined in the wrapper. Using the new value fixes the error for the few datasets I tried
> [CONCOCT] Fix total_percentage_pca default value

- tools/bellerophon/bellerophon.xml
bellephoron  has a [--threads](https://github.com/davebx/bellerophon/blob/main/bellerophon/cli.py#L12) flag but it isn't used. The `GALAXY_SLOTS` variable is only used for the subsequent samtools command.
> Add --threads flag to bellerophon command

- tools/query_tabular/macros.xml
- tools/query_tabular/query_tabular.xml
See https://github.com/galaxyproject/galaxy/issues/16676 and https://github.com/python/cpython/issues/91222#issuecomment-1093946864 for more details.
In summary, from the Python issue description:
>This warning was introduced in 3.6. The reason is that in most other regular expression implementations global inline flags in the middle of the expression have different semantic: they affect only the part of the expression after the flag. But in Python they affect the whole expression. It caused confusion and was a source of bugs.
>
>After 5 releases it is a time to convert this warning into error. In future we can allow global inline flags in the middle of the expression with different semantic. It is safer if one or more intermediate versions will raise an error.
> query_tabular: Fix regex incompatibility error for Python3.11

- tools/sra-tools/fasterq_dump.xml
- tools/sra-tools/fastq_dump.xml
- tools/sra-tools/macros.xml
Hrm.. tests will only work with 23.1 (https://github.com/galaxyproject/galaxy/pull/15085)
> sra dump: allow spaces in defline

- tools/ncbi_datasets/datasets_gene.xml
- tools/ncbi_datasets/datasets_genome.xml
- tools/ncbi_datasets/macros.xml
The latest version of the installed tool errors out, which seems to be related to a change on the NCBI's end.
```
Warning: Current version of client does not support full genome reports! New version of client (15.19.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
Error:  unknown field "bioprojectAccession"
Usage
dataformat tsv genome [flags]
Examples
dataformat tsv genome --inputfile human/ncbi_dataset/data/assembly_data_report.jsonl
dataformat tsv genome --package human.zip
```
Updated the tool version to the latest available and corrected the tests accordingly, after which the tool started to work again.
> Fixed broken NCBI datasets download tool

- README.md
Previously the badges in the README just linked to the badge image, not the CI results.
> Fix CI badge URLs

- tools/medaka/macros.xml
- tools/medaka/snp.xml
Fixes https://github.com/galaxyproject/tools-iuc/issues/4119. The fasta input is many times smaller than the sequence data, so this is minimal overhead and we can move to singularity for this tool.
> Copy medaka fasta inputs

- tools/edger/edger.R
- tools/edger/edger.xml
When providing a single file to EdgeR for the factors, the levels of the different factors were not being passed through make.names to ensure their compliance with later R operations. As a result, you could get errors like:
```
Error in makeContrasts(contrasts = contrastData, levels = design) : 
The levels must by syntactically valid names in R, see help(make.names).  Non-valid names:
```
> Fix EdgeR: Deal with factor names on unified factor file

- tools/cojac/macros.xml
Hello! This is an automated update of the following tool: **tools/cojac**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/cojac from version 0.9 to 0.9.1.
**Project home page:** https://github.com/cbg-ethz/cojac/releases
> Updating tools/cojac from version 0.9 to 0.9.1

- tools/shovill/shovill.xml
Shovill seem to failed when input is indicated as fast or fastq.gz while it can work with this input.
I just add the fastq as input format
> Update shovill tool to accept fastq and fastq.gz

- tools/maf_stats/.shed.yml
- tools/maf_stats/maf_stats.xml
No idea what the tool does (the generated command line and the python script are super confusing) .. but species is not used.
> maf_stats: remove unused parameter

- .github/workflows/ci.yaml
note: tool_urls,shed_metadata effectively disable two tests that are by default enabled in the planemo-ci-action with `--ensure_metadata --urls` https://github.com/galaxyproject/planemo-ci-action/blob/fd4d12c417215f7cd9075227e784f4cd61c60044/planemo_ci_actions.sh#L115C7-L115C134
> add missing skip rules

- tools/drep/macros.xml
Hello! This is an automated update of the following tool: **tools/drep**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/drep from version 3.4.3 to 3.4.5.
**Project home page:** https://github.com/MrOlm/drep/releases
> Updating tools/drep from version 3.4.3 to 3.4.5

- tools/mosdepth/mosdepth.xml
Hello! This is an automated update of the following tool: **tools/mosdepth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mosdepth from version 0.3.4 to 0.3.5.
**Project home page:** https://github.com/brentp/mosdepth/releases
> Updating tools/mosdepth from version 0.3.4 to 0.3.5

- tools/repeatmodeler/macros.xml
Hello! This is an automated update of the following tool: **tools/repeatmodeler**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/repeatmodeler from version 2.0.4 to 2.0.5.
**Project home page:** https://www.repeatmasker.org/RepeatModeler
> Updating tools/repeatmodeler from version 2.0.4 to 2.0.5

- .github/workflows/pr_without_tool_change.yaml
Include workflow name in group. No need for workaround for runs on default branch.
> Fix fallback workflow concurrency

- tools/datamash/datamash-transpose.xml
Fixes https://github.com/galaxyproject/tools-iuc/issues/5621
You can never open files in cheetah templates, but this is impossible to check for systematically. Time to adopt cwl style command line bindings ?
> Fix datamash for pulsar, use file_size

- tools/abritamr/abritamr.xml
The identity argument should be unset.
If identity is not set, abritamr uses a curated threshold per gene. If a threshold is not present, it defaults to 0.9. The current default always uses a 0.9 threshold.
> Fix abritamr wrapper bug

- tools/coverm/coverm_genome.xml
- tools/coverm/macros.xml
- tools/coverm/test-data/all_fasta.loc
when iterating over dynamic selects one can not access
the fields property, but name and path column need to
be set manually for the select options, xref https://github.com/galaxyproject/galaxy/pull/16885
also adapts a test to check if code works
this never worked since there is obviously no element_identifier
attribute even if `.fields.path` would exist.
> coverm: fix usage of cached reference genomes

- tools/sra-tools/macros.xml
Avoids `2023-11-17T08:54:02 vdb-config.3.0.8 err: condition violated while updating node - Warning: normally this application should not be run as root/superuser`, which vdb-config emits for whatever reason. Unclear why this has passed on the CI in the past, but this makes the script simpler, saves some repeated calls to the binary and importantly fixes `--biocontainers` locally.
> Write sra-tools config settings to config file

- tool_collections/snpeff/snpEff_create_db.xml
Instead just copy out the actual .bin files.
We have no test coverage for snpeffdb files since those are composite files in disguise, I can test this manually.
Fixes #5647 
> Fix snpeffdb output to not contain broken symlinks

- tools/pretext/.shed.yml
- tools/pretext/pretext_map.xml
- tools/pretext/pretext_snapshot.xml
Current version of pretext map evaluates setting a minimum mapping quality as 0 to be false, and therefore sets it to the default of 10, despite 0 being a valid entry. This fixes that bug
> pretext map allow for map quality 0

- tools/orthofinder/macros.xml
- tools/orthofinder/orthofinder_only_groups.xml
Pick up new ["Hierarchical Orthogroups"](https://github.com/davidemms/OrthoFinder#phylogenetic-hierarchical-orthogroups-directory) output
Fixed  bioconda recipe (https://github.com/bioconda/bioconda-recipes/pull/45149) and update orthofinder to 2.5.5 (closes #5312)
---
> Update orthofinder and pick up new orthogroup output

- tools/pick_value/pick_value.xml
Gives the workflow editor the needed info for the output's data type. Otherwise connection to downstream tools (in particular if it accepts multiple datatypes, eg fasta,fasta.gz) were not possible.
I adapted and added tests to check for `ftypes`, to ensure that empty first repeat element does not create trouble.
The workflow functionality has been tested manually.
Should allow to run https://github.com/galaxyproject/iwc/pull/321.
We can independently check https://github.com/galaxyproject/tools-iuc/pull/5713 and simplify the IWC workflow a bit later. 
> `pick_value`: implement `format_souce`

- tools/mitos/mitos2.xml
`--noplots` also needs to be disabled for `ncRNA_structure_svg_plots`
> MITOS2: fix plotting of RNA structures only

- tools/funannotate/funannotate_annotate.xml
- tools/funannotate/funannotate_compare.xml
- tools/funannotate/macros.xml
I think I have made a mess of the `funannotate_annotate` wrapper :upside_down_face: 
We are still getting errors like this on Galaxy AU:
```
[Dec 22 04:43 AM]: Funannotate annotate has completed successfully!
... 
mv: cannot stat 'output/annotate_results/*.sqn': No such file or directory
```
It's hard to debug on Galaxy because it only happens with large inputs.  It has been reported upstream https://github.com/nextgenusfs/funannotate/issues/777#issuecomment-1771800833.
In this PR I've removed the `mv` commands by using a wildcard in `from_work_dir` instead for most outputs. The exception is the sqn files, which are picked up with `discover_datasets`.
@abretaud What do you think?
<details>
<summary>Edits</summary>
~~In this PR I've used discover_datasets to pick up files from the output …
> funannotate_annotate pick up sequin files with discover_datasets

- tools/ncbi_datasets/datasets_gene.xml
- tools/ncbi_datasets/datasets_genome.xml
- tools/ncbi_datasets/macros.xml
Suggest adding this text to the wrapper to clarify how to select a taxon. (If this is correct?)
* [- ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [- ] - This PR updates an existing tool or tool collection
> NCBI datasets: Update macros.xml regarding taxon selection

- data_managers/data_manager_build_bracken_database/data_manager/bracken_build_database.xml
This should clear up some confusion for the admins about this DM. See also https://github.com/galaxyproject/tools-iuc/issues/5745.
TODO:
Add Error message when the DM wants to point to a prebuilt DB that does not exist.
> Add help to bracken DM

- tools/tb-profiler/tb_profiler_profile.xml
This PR links tb-profiler to its bio.tools [entry](https://bio.tools/tb-profiler).
> Added bio.tools ref to tb-profiler

- tools/nextclade/macros.xml
- tools/nextclade/nextalign.xml
- tools/nextclade/nextclade.xml
This PR links nextclade to ist bio.tools [entry](https://bio.tools/nextclade).
> Add bio.tools ref to nextclade

- tools/sra-tools/fasterq_dump.xml
> Explicitly set tmp dir for fasterq-dump

- tools/ampvis2/boxplot.xml
- tools/ampvis2/core.xml
- tools/ampvis2/frequency.xml
- tools/ampvis2/heatmap.xml
- tools/ampvis2/macros.xml
- tools/ampvis2/octave.xml
- tools/ampvis2/ordinate.xml
- tools/ampvis2/rankabundance.xml
- tools/ampvis2/rarecurve.xml
- tools/ampvis2/timeseries.xml
- tools/ampvis2/venn.xml
hopefully `sim_size` is more stable.
Tests are currently failing in CI.
> Fix ampvis tests

- .github/CODEOWNERS
- tools/revoluzer/.shed.yml
- tools/revoluzer/crex.xml
- tools/revoluzer/distmat.xml
- tools/revoluzer/macros.xml
- tools/revoluzer/test-data/test.fas
The first two of some older tools which are apparently still used (revoluzer is more or less what I produced during my PhD a long time ago) :) Probably the first gene order analysis tools for Galaxy (with limited applicability .. probably only mitochondrial genomes).
University has shut down the old websites that provided these tools. So like for MITOS I would like to go Galaxy (unlike Galaxy revoluzer is C/C++, i.e. no other dependencies).
> Initial commit of revoluzer tools

- tools/pbtk/bam2fastx.xml
The outputs were never going to be produced. Together with https://github.com/galaxyproject/galaxy/issues/17829 we ended up with passing tests when they should have failed.
> Fix bam2fastx outputs

- tools/mirmachine/macros.xml
- tools/mirmachine/mirmachine.xml
* [ x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x] License permits unrestricted use (educational + commercial)
* [ x] This PR updates an existing tool or tool collection
> Added mirmachine optional arguments

- tools/ena_upload/ena_upload.xml
This issue for some reason was not picked up by our test build specifically to test the ISA json function
> ENA upload tool ISA - JSON support fix 

- tools/pretext/pretext_graph.xml
There appears to be an inconsistency in how the workflow editor reads input formats vs the tool form, where the accidental space left in the formats section of the inputs functioned ok on a tool form, but not in the workflow editor, which didn't recognize the bedgraph format as a valid connection. Fixing the space here and adding an issue on the galaxy repo for the inconsistency problem. Not bumping version because it's a minor bug fix of the wrapper, not the tool
> minor bug fix for pretext graph to function in workflows

- tools/dexseq/dexseq_count.xml
- tools/dexseq/macros.xml
I'm getting `[E::idx_find_and_load] Could not retrieve index file for '/mnt/user-data-volC/data13/c/e/b/dataset_cebddb26-4aa7-4051-9740-b79025ccddd4.dat'` running dexseq-count on Galaxy Australia.
I'm just pushing this as a quick fix for version 1.44 - the bioconductor package seems to be missing the htseq dependency for later versions (see https://github.com/galaxyproject/tools-iuc/pull/4295)
---
> Need bai for dexseq-count

- tools/bigscape/bigscape.xml
From a user error report:
**File: tool_stderr**
```
usage: BiG-SCAPE [-h] [-l LABEL] [-i INPUTDIR] -o OUTPUTDIR
[--pfam_dir PFAM_DIR] [-c CORES]
[--include_gbk_str INCLUDE_GBK_STR [INCLUDE_GBK_STR ...]]
[--exclude_gbk_str EXCLUDE_GBK_STR [EXCLUDE_GBK_STR ...]]
[-v] [--include_singletons] [-d DOMAIN_OVERLAP_CUTOFF]
[-m MIN_BGC_SIZE] [--mix] [--no_classify]
[--banned_classes {PKSI,PKSother,NRPS,RiPPs,Saccharides,Terpene,PKS-NRP_Hybrids,Others} [{PKSI,PKSother,NRPS,RiPPs,Saccharides,Terpene,PKS-NRP_Hybrids,Others} ...]]
[--cutoffs CUTOFFS [CUTOFFS ...]] [--clans-off]
[--clan_cutoff CLAN_CUTOFF CLAN_CUTOFF] [--hybrids-off]
[--mode {global,glocal,auto}] [--anchorfile ANCHORFILE]
[--force_hmmscan] [--skip_ma] [--mibig] [--mibig21]
[--mibig14] [--mibig13] [--query_bgc QUERY_BGC] …
```
> Fix typo in bigscape argument for excluded classes

- tools/iqtree/.shed.yml
- tools/iqtree/iqtree.xml
- tools/iqtree/iqtree_macros.xml
This PR links iqtree to its bio.tools [entry](https://bio.tools/iqtree).
> Add bio.tools ref to iqtree

- tools/rseqc/FPKM_count.xml
- tools/rseqc/RNA_fragment_size.xml
- tools/rseqc/RPKM_saturation.xml
- tools/rseqc/bam2wig.xml
- tools/rseqc/bam_stat.xml
- tools/rseqc/clipping_profile.xml
- tools/rseqc/deletion_profile.xml
- tools/rseqc/geneBody_coverage.xml
- tools/rseqc/infer_experiment.xml
- tools/rseqc/inner_distance.xml
- tools/rseqc/insertion_profile.xml
- tools/rseqc/junction_annotation.xml
- tools/rseqc/junction_saturation.xml
- tools/rseqc/mismatch_profile.xml
- tools/rseqc/read_GC.xml
- tools/rseqc/read_NVC.xml
- tools/rseqc/read_distribution.xml
- tools/rseqc/read_duplication.xml
- tools/rseqc/read_hexamer.xml
- tools/rseqc/read_quality.xml
- tools/rseqc/rseqc_macros.xml
- tools/rseqc/tin.xml
Based on last commit of @bgruening in #5618, fixed minor linting errors and updated `expected_num_outputs` parameters in some tools where it was incorrect.
> Tools/rseqc: Fixed linting error and updated test parameters in some tools

- tools/nanoplot/nanoplot.xml
The previous version has set `#set $f = $extension + ".gz"`, which then generates invalid symlinks.
By having fewer if statements here there are less things that can go wrong and we get test coverage with the existing tests.
> Fix and simplify nanoplot cheetah

- tools/bbtools/bbmerge.xml
- tools/bbtools/macros.xml
Worth noting that setting `-Xmx` via `$_JAVA_OPTIONS` in the job env as many admins do still overrides this. I pulled the clever bit of handling for that from bbnorm.
> Add `$GALAXY_SLOTS` and `$GALAXY_MEMORY_MB` to bbmerge

- tools/merqury/macros.xml
- tools/merqury/merqury.xml
- tools/merqury/merqury_plot_CN.xml
- tools/merqury/test-data/output_02_qv.tabular
- tools/merqury/test-data/output_03_qv.tabular
- tools/merqury/test-data/output_06_qv.tabular
Might be faster than https://github.com/bioconda/bioconda-recipes/pull/47201
> Fix containerized merqury

- tools/bbtools/bbduk.xml
- tools/bbtools/bbmap.xml
- tools/bbtools/bbmerge.xml
- tools/bbtools/macros.xml
The name attribute is not guaranteed to be unique, we can just use forward / reverse as symlink targets, which is also simpler.
> Fix bbduk, bbmerge bbmap for non-unique names

- tools/maaslin2/maaslin2.xml
- tools/maaslin2/macros.xml
[ *] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
[ *] This PR updates an existing tool or tool collection
> interaction:fixed effects and corrections modified

- tools/das_tool/das_tool.xml
- tools/das_tool/macros.xml
just use element identifiers if not given. Seems to be what the tool does by default: https://github.com/cmks/DAS_Tool/blob/bb0954f4f45a2340e9cb9b896d412e477c6c49fc/src/DAS_Tool.R#L398
No idea what the `--labels` argument is good for. But with `--labels ''` the program just fails. So this might be a solution.
> das tool: do not allow empty labels

- tools/hapcut2/hapcut2.xml
- tools/hapcut2/macros.xml
Hi,
This PR is based on https://github.com/galaxyproject/tools-iuc/pull/5971 for updating the HapCUT2. Tool XML was restructured and necessary minor changes were made as per the version update.
PS: @neoformit Would you like to have a look at the changes made by me, since you worked on wrapping this tool? 
Cheers,
Saim
> Version Update of HapCUT2 and Restructuring of XML file

- tools/metaphlan/macros.xml
- tools/metaphlan/metaphlan.xml
Hi, 
This PR fixes the #5958 reported at https://help.galaxyproject.org/t/metaphlan-issue-with-unknown-estimation-parameter/12157
The reported bug in the tool wrapper was due to an old parameter name `--unknown_estimation` that was renamed to `--unclassified_estimation` since **version 4.0.0**. 
**CHANGELOG Reference:** https://github.com/biobakery/MetaPhlAn/blob/3080d946db5bbe0dafaf05de91dbd38e4d0e6e22/CHANGELOG.md?plain=1#L125
Cheers,
Saim
> Bux Fix for Metaphlan3 : Renamed `--unknown-estimation` parameter to `--unclassified-estimation`

- tools/kofamscan/kofamscan.xml
and require options for the DB but allow to have no options for the subsets
> Add missing labels to the cached kofam DB parameters

- tools/bowtie2/bowtie2_macros.xml
- tools/bowtie2/bowtie2_wrapper.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/5983
by using a pipe bowtie2 and samtools run in parallel. since already bowtie2 alone uses more CPU than the assigned ones (less than 1 core) we should not do this, but run them serially.
background had a user running 2 fastq files (each 2.6GB) against a file containing 500k contigs. Running bowtie there was extremely efficient (tested up to 40 cores), i.e. for `GALAXY_SLOTS`=X the CPU usage (according to top) was `(X+1)*100%` .. probably because X alignment + 1 control thread are used.  
Alternatively we could do [this](https://github.com/galaxyproject/tools-iuc/blob/921fa90438b4ce2e9cf9c4129568f4036c318d82/tools/hisat2/hisat2.xml#L351), but I do not see a reason why we should.
also properly redirects `stderr`.
> bowtie2: do not overcommit

- tools/volcanoplot/.shed.yml
- tools/volcanoplot/volcanoplot.xml
Current version is not considering inputs in plot title and other options. Should fix #5976 
> Make title and others visible in volcanoplot

- tools/iqtree/iqtree_macros.xml
Hello! This is an automated update of the following tool: **tools/iqtree**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/iqtree from version 2.1.2 to 2.2.2.3.
**Project home page:** http://www.iqtree.org
> Updating tools/iqtree from version 2.1.2 to 2.3.3

- tools/scanpy/cluster_reduce_dimension.xml
- tools/scanpy/filter.xml
- tools/scanpy/inspect.xml
- tools/scanpy/macros.xml
- tools/scanpy/normalize.xml
- tools/scanpy/plot.xml
- tools/scanpy/remove_confounders.xml
The IUC Scanpy tools are using a profile version that doesn't allow us to install them alongside our tools on some private instances that we have. I noticed that the current profile had a value outside of the described ones on the [tools XML docs](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-profile), so I have nudged the value to the closest lower one.
This doesn't have any impact on tools really, mostly on where they can be installed, but let me know if this merits a `galaxy+<num>` version bump on tools. I hope that this change is acceptable.
> Reduce slightly scanpy tools profile for wider instance support

- tools/seqkit/macros.xml
- tools/seqkit/seqkit_fx2tab.xml
- tools/seqkit/seqkit_locate.xml
- tools/seqkit/seqkit_stats.xml
- tools/seqkit/test-data/stats_output1.tabular
- tools/seqkit/test-data/stats_output2.tabular
Hello! This is an automated update of the following tool: **tools/seqkit**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seqkit from version 2.3.1 to 2.4.0.
**Project home page:** https://bioinf.shenwei.me/seqkit
> Updating tools/seqkit from version 2.3.1 to 2.8.1

- tools/bedtools/bamToBed.xml
- tools/bedtools/bedToBam.xml
- tools/bedtools/bedpeToBam.xml
- tools/bedtools/complementBed.xml
- tools/bedtools/coverageBed.xml
- tools/bedtools/fisherBed.xml
- tools/bedtools/flankBed.xml
- tools/bedtools/getfastaBed.xml
- tools/bedtools/intersectBed.xml
- tools/bedtools/jaccardBed.xml
- tools/bedtools/macros.xml
- tools/bedtools/randomBed.xml
- tools/bedtools/shuffleBed.xml
- tools/bedtools/slopBed.xml
- tools/bedtools/sortBed.xml
- tools/bedtools/test-data/jaccardBed_strand_result2.bed
Hello! This is an automated update of the following tool: **tools/bedtools**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/bedtools from version 2.30.0 to 2.31.0.
**Project home page:** https://github.com/arq5x/bedtools2/releases
> Updating tools/bedtools from version 2.30.0 to 2.31.1

- tools/bwameth/bwameth.xml
Hello! This is an automated update of the following tool: **tools/bwameth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/bwameth from version 0.2.6 to 0.2.7.
**Project home page:** https://github.com/brentp/bwa-meth/releases
> Updating tools/bwameth from version 0.2.6 to 0.2.7

- .github/workflows/ci.yaml
- .github/workflows/slash.yaml
weekly tests currently show
```
Unexpected input(s) 'reaction-type', valid inputs are ['token', 'repository', 'issue-number', 'comment-id', 'body', 'body-path', 'body-file', 'edit-mode', 'append-separator', 'reactions', 'reactions-edit-mode']
```
also bump slash-command-dispactch (`Node.js 16 actions are deprecated`)
> CI: Fix reactions

- tools/bbgbigwig/bam_bed_gff_to_bigwig.xml
- tools/bbgbigwig/test-data/dbkeys.loc.sample
- tools/bbgbigwig/tool-data/dbkeys.loc.sample
- tools/bbgbigwig/tool_data_table_conf.xml.sample
@mvdbeek:
added a dbkey_loc.sample to test-data to try to fix that deployment problem?
tool-data seems to be MIA in the IUC repo.
Planemo does not like an empty tool_data_table_conf.xml.sample
update to closed PR #6088
> Fix bbgbigwig deployment lack of dbkey_loc.sample

- tools/khmer/extract-partitions.xml
- tools/mothur/chimera.check.xml
- tools/mothur/heatmap.bin.xml
- tools/mothur/heatmap.sim.xml
We can find them with
```
planemo lint -s command,tool_xsd,tests,general,help,inputs,citations,xml_order  --recursive
```
If we don't set an output format the hda extension becomes null in the database, and we fail at various places in the galaxy codebase. We can make Galaxy more resilient to it, but this is an easy fix here. Galaxy issue is here: https://github.com/galaxyproject/galaxy/issues/18383
> Add missing format attributes

- tools/funannotate/funannotate_annotate.xml
- tools/funannotate/funannotate_clean.xml
- tools/funannotate/funannotate_predict.xml
- tools/funannotate/macros.xml
Trying to fix the following kind of error found with predict tool:
```
[Jun 14 08:11 PM]: Mapping 557,291 proteins to genome using diamond and exonerate
File "/usr/local/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-p2g.py", line 252, in <module>
os.makedirs(tmpdir)
File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/tmp/p2g_927b8faa-730b-404d-a862-2631430ec16b'
File "/usr/local/bin/funannotate", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
mod.main(arguments)
File "/usr/local/lib/python3.8/site-packages/funannotate/predict.py", …
```
> Funannotate: use better tmpdir

- tools/unicycler/unicycler.xml
Fixes
https://sentry.galaxyproject.org/share/issue/f5ec29350256422da159e25b0875b7ee/ when users attempt to run jobs with unexpected fastq datatypes like fastqcssanger.gz, which is allowed because basic fastq/fastq.gz are allowd (this is a mistake IMO ...):
```
NotFound: cannot find 'lr'
File "galaxy/util/template.py", line 87, in fill_template
return unicodify(t, log_exception=False)
File "galaxy/util/__init__.py", line 1183, in unicodify
value = str(value)
File "Cheetah/Template.py", line 1053, in __unicode__
return getattr(self, mainMethName)()
File "cheetah_DynamicallyCompiledCheetahTemplate_1720043166_6268568_19017.py", line 172, in respond
NotFound: cannot find 'lr'
File "galaxy/util/template.py", line 87, in fill_template
return unicodify(t, log_exception=False)
File …
```
> Fix unicycler datatype comparisons

- tools/cutadapt/macros.xml
I had a user who used spaces in the adapter (for better visual orientation). these were silently replaced by X.
I think replacing the sanitizer by a validator is better, because more explicit behavior.
> cutadapt: replace adapter sanitizer by validator

- tools/snapatac2/macros.xml
- tools/snapatac2/peaks_and_motif_analysis.xml
Because of [this condition](https://github.com/galaxyproject/tools-iuc/blob/main/tools/snapatac2/peaks_and_motif_analysis.xml#L155) (which was accidentally added in the previous update) the updated anndata object is not written to the history. Fixed this bug and updated the test data. All the other tests that use the subsequent test data are also updated.
> fix pp.make_peak_matrix but  and it's test

- tools/dimet/dimet_differential_analysis.xml
- tools/dimet/dimet_metabologram.xml
- tools/dimet/macros.xml
- tools/dimet/test-data/AMINOACIDS-L-Cycloserine-T0-Control-T0--DEG_comparison1-abundances-cell.svg
- tools/dimet/test-data/CENTRAL_CARBON_METABOLISM-L-Cycloserine-T0-Control-T0--DEG_comparison1-abundances-cell.svg
> Metabologram fix

- tools/goenrichment/goenrichment.xml
- tools/goenrichment/goslimmer.xml
xref: https://github.com/galaxyproject/tools-iuc/issues/6135
@martindemko here you can try to add your Java stuff. I still think the `_JAVA_OPTIONS` is ok.
> add profiles to goenrichment

- data_managers/data_manager_omamer/data_manager/macros.xml
- data_managers/data_manager_omamer/data_manager/omamer.py
- data_managers/data_manager_omamer/data_manager/omamer.xml
Based on the LUCA database update request by @tbrown91 for OMArk, this PR concerns with updating the data manager to install the latest version of the OMark databases while retaining the older databases version.
> Updating LUCA database version in Omamer data manager

- tools/bcftools/bcftools_call.xml
- tools/bcftools/bcftools_cnv.xml
- tools/bcftools/bcftools_convert_from_vcf.xml
- tools/bcftools/bcftools_csq.xml
- tools/bcftools/bcftools_filter.xml
- tools/bcftools/bcftools_gtcheck.xml
- tools/bcftools/bcftools_isec.xml
- tools/bcftools/bcftools_mpileup.xml
- tools/bcftools/bcftools_norm.xml
- tools/bcftools/bcftools_plugin_color_chrs.xml
- tools/bcftools/bcftools_plugin_counts.xml
- tools/bcftools/bcftools_plugin_dosage.xml
- tools/bcftools/bcftools_plugin_fill_an_ac.xml
- tools/bcftools/bcftools_plugin_fill_tags.xml
- tools/bcftools/bcftools_plugin_fixploidy.xml
- tools/bcftools/bcftools_plugin_frameshifts.xml
- tools/bcftools/bcftools_plugin_impute_info.xml
- tools/bcftools/bcftools_plugin_mendelian.xml
- tools/bcftools/bcftools_plugin_missing2ref.xml
- tools/bcftools/bcftools_plugin_setgt.xml
- tools/bcftools/bcftools_plugin_split_vep.xml
- tools/bcftools/bcftools_plugin_tag2tag.xml
- tools/bcftools/bcftools_query.xml
- tools/bcftools/bcftools_roh.xml
- tools/bcftools/bcftools_stats.xml
- tools/bcftools/bcftools_view.xml
- tools/bcftools/macros.xml
There's no tgts_secion defined anywhere in the bcftools wrappers. This fixed https://github.com/galaxyproject/tools-iuc/issues/6177#issuecomment-2255836399
> Fix bcftools cheetah section variable name

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
Reverts galaxyproject/tools-iuc#6218
With planemo 0.75.25 we should be getting pillow and tifffile, making this unnecessary.
> Revert "ci.yaml and pr.yaml update"

- tools/cemitool/macros.xml
Hello! This is an automated update of the following tool: **tools/cemitool**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/cemitool from version 1.18.1 to 1.22.0.
**Project home page:** https://www.bioconductor.org/packages/release/bioc/html/CEMiTool.html
> Updating tools/cemitool from version 1.18.1 to 1.26.0

- tools/dram/dram_annotate.xml
- tools/dram/dram_distill.xml
- tools/dram/dram_merge_annotations.xml
- tools/dram/dram_neighborhoods.xml
- tools/dram/dram_strainer.xml
- tools/dram/macros.xml
Hello! This is an automated update of the following tool: **tools/dram**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/dram from version 1.3.5 to 1.4.1.
**Project home page:** https://github.com/WrightonLabCSU/DRAM/releases
> Updating tools/dram from version 1.3.5 to 1.5.0

- tools/gtdb_to_taxdump/ncbi-gtdb_map.xml
@mvdbeek This is not strictly needed but would be convenient and it was only deployed over the weekend. 
Feel free to close it if you think its too risky.
> change tool ID

- tools/pear/pear.xml
Changes use of --empirical-freqs so that flag (in full, for clarity and avoiding misusing scoring method) is only included in the command if user chooses 'disable empirical frequencies==YES', restoring [default behaviour](https://cme.h-its.org/exelixis/web/software/pear/doc.html). Bumped version suffix.
* [ x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x] This PR updates an existing tool or tool collection
> Correct PEAR --empirical-freqs param

- tools/checkm/macros.xml
- tools/checkm/plot.xml
- tools/checkm/taxonomy_wf.xml
Hello! This is an automated update of the following tool: **tools/checkm**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/checkm from version 1.2.0 to 1.2.1.
**Project home page:** https://github.com/Ecogenomics/CheckM/releases
> Updating tools/checkm from version 1.2.0 to 1.2.3

- tools/clair3/clair3.xml
- tools/clair3/test-data/all_fasta.loc
- tools/clair3/tool-data/all_fasta.loc.sample
- tools/clair3/tool_data_table_conf.xml.sample
- tools/clair3/tool_data_table_conf.xml.test
Update all_fasta files in clair3 repo to fix bug described in this issue: https://github.com/galaxyproject/tools-iuc/issues/6211
Should I bump the VERSION_SUFFIX for this change?
> Bug fix: update all_fasta columns in clair3 repo

- tools/ucsc_tools/fasplit/.lint_skip
- tools/ucsc_tools/fasplit/.shed.yml
- tools/ucsc_tools/fasplit/fasplit.xml
- tools/ucsc_tools/fatovcf/.shed.yml
- tools/ucsc_tools/fatovcf/fatovcf.xml
- tools/ucsc_tools/maftoaxt/.shed.yml
- tools/ucsc_tools/maftoaxt/maftoaxt.xml
- tools/ucsc_tools/twobittofa/.lint_skip
- tools/ucsc_tools/twobittofa/.shed.yml
- tools/ucsc_tools/twobittofa/twobittofa.xml
- tools/ucsc_tools/ucsc_axtchain/.shed.yml
- tools/ucsc_tools/ucsc_axtchain/axtchain.xml
- tools/ucsc_tools/ucsc_axttomaf/.shed.yml
- tools/ucsc_tools/ucsc_axttomaf/axttomaf.xml
- tools/ucsc_tools/ucsc_chainnet/.shed.yml
- tools/ucsc_tools/ucsc_chainprenet/.shed.yml
- tools/ucsc_tools/ucsc_chainprenet/chainprenet.xml
- tools/ucsc_tools/ucsc_chainsort/.shed.yml
- tools/ucsc_tools/ucsc_chainsort/chainsort.xml
- tools/ucsc_tools/ucsc_netfilter/netfilter.xml
- tools/ucsc_tools/ucsc_netsyntenic/netsyntenic.xml
- tools/ucsc_tools/wigtobigwig/wigtobigwig.xml
> UCSC tools version bump & polish

- tools/sniffles/sniffles.xml
- tools/sniffles/tool-data/all_fasta.loc.sample
- tools/sniffles/tool_data_table_conf.xml.sample
- tools/sniffles/tool_data_table_conf.xml.test
After #6328, there seem to be issue with this tool. It is invalid on the ToolShed: https://toolshed.g2.bx.psu.edu/repository?repository_id=fd2e07886563dc35&changeset_revision=3f6f028f418f
```
sniffles.xml - This file requires an entry in the tool_data_table_conf.xml file. Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error.
```
Hopefully, this PR will fix the issue
> Sniffles: Add tool_data_table_conf file and tool-data loc sample file

- tools/idr_download/idr_download_by_ids.py
- tools/idr_download/idr_download_by_ids.xml
* [X I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
I needed to add a new dependency as pylibtiff does not allow to write hyperstacks.
I used the asserts for images and the image_diff as much as I could.
> Improve idr_download to support download of the full hyperstack

- tool_collections/snpeff/.lint_skip
- tool_collections/snpeff/snpEff.xml
- tool_collections/snpeff/snpEff_create_db.xml
- tool_collections/snpeff/snpeff_get_chr_names.xml
- remove deprecated and redundant filter_options_attribute
- add expect_num_outputs (and improve tests)
> linter fixes for snpeff

- tools/gtdbtk/gtdbtk_classify_wf.xml
- tools/gtdbtk/macros.xml
Hello! This is an automated update of the following tool: **tools/gtdbtk**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/gtdbtk from version 1.7.0 to 2.1.1.
**Project home page:** https://github.com/Ecogenomics/GTDBTk/releases
> Updating tools/gtdbtk from version 1.7.0 to 2.4.0

- tools/ucsc_blat/blat.xml
Hello! This is an automated update of the following tool: **tools/ucsc_blat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ucsc_blat from version 377 to 445.
**Project home page:** http://genome.ucsc.edu/goldenPath/help/blatSpec.html
> Updating tools/ucsc_blat from version 377 to 469

- tools/tximport/tximport.xml
Hello! This is an automated update of the following tool: **tools/tximport**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/tximport from version 1.22.0 to 1.26.0.
**Project home page:** http://bioconductor.org/packages/tximport
> Updating tools/tximport from version 1.22.0 to 1.30.0

- tools/umi_tools/macros.xml
- tools/umi_tools/umi-tools_dedup.xml
- tools/umi_tools/umi-tools_group.xml
Hello! This is an automated update of the following tool: **tools/umi_tools**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/umi_tools from version 1.1.2 to 1.1.4.
**Project home page:** https://github.com/CGATOxford/UMI-tools/releases
> Updating tools/umi_tools from version 1.1.2 to 1.1.5

- tools/tn93/macros.xml
- tools/tn93/readreduce.xml
- tools/tn93/tn93.xml
- tools/tn93/tn93_cluster.xml
- tools/tn93/tn93_filter.xml
Hello! This is an automated update of the following tool: **tools/tn93**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/tn93 from version 1.0.6 to 1.0.9.
**Project home page:** https://github.com/veg/tn93/releases
> Updating tools/tn93 from version 1.0.6 to 1.0.14

- tools/bigwig_outlier_bed/bigwig_outlier_bed.py
- tools/bigwig_outlier_bed/bigwig_outlier_bed.xml
- tools/bigwig_outlier_bed/test-data/bedoutzero_sample
- tools/sniffles/sniffles.xml
Add option to create a bed track with a feature for each contiguous region with zeros for coverage. A low quantile setting will not work for this purpose - it needs to be zero for a stretch of sequence.
Trying to understand some large (200k+) regions in some VGP haplotype assemblies where one or both haplotypes have absolutely no coverage from Pacbio hifi reads. Possibly from bionano optical or other sources during curation, but it may not really exist? Seeing zero - absolutely no reads - mapping over substantial regions. 
Image below shows two haplotypes with coverage and windowmasker repeat bigwigs, from [bColStr4](https://usegalaxy.eu/datasets/4838ba20a6d867657c43f8441d416326/preview) SUPER_5:22,191,743..23,883,213 - the two haplotypes have slightly staggered regions …
> bigwig_outlier_bed: Option to find regions with zero coverage rather than rely on a low quantile

- tools/scanpy/cluster_reduce_dimension.xml
- tools/scanpy/macros.xml
- tools/scanpy/plot.xml
- If fa2 is missing, some functions fallback to 'fr' layout with a warning but the jobs were still passing. This PR adds fa2 and fix the test. 
- `pl.paga` adds `pos` under `adata.uns['paga']`. To subsequently run `tl.draw_graph` based on `paga`, the anndata object must be saved.
- Fixed a bug that failed check optional `fontsize` param in `pl.paga` function
- This update should not affect the upcoming GTA. 
@nomadscientist This should hopefully fix the trajectories tutorial.
> Scanpy add fa2 requirement and fix some bugs

- tools/fasttree/.lint_skip
- tools/fasttree/fasttree.xml
Leaving the `InputsBoolDistinctValues` skip: the boolean has no `truevalue` and `falsevalue`. It's used in a `filter` and an `if` statement of the command block .. and this works. 
> linter fixes for fasttree

- tools/moabs/.lint_skip
- tools/moabs/moabs.xml
> moabs: fix missing whens

- tools/meryl/arithmetic-kmers.xml
- tools/meryl/count-kmers.xml
- tools/meryl/filter-kmers.xml
- tools/meryl/groups-kmers.xml
- tools/meryl/histogram-kmers.xml
- tools/meryl/macros.xml
- tools/meryl/print.xml
- tools/meryl/trio-mode.xml
On very large meryldb archives, compressing the tar stream with a single-threaded zlib is the overwhelming amount of tool runtime. With 56 cores pigz decreased the compression runtime of a 24 GB meryldb from an estimated 30 hours to 9 minutes.
I also added `m` to the untar options so that mod times are not preserved. This can be useful when working with old datasets on HPC systems that have aggressive scratch cleanup.
Tested on the command line but not in the tools so I am relying on tool tests to catch my mistakes. =)
> Use multithreaded pigz for compression in meryl

- tools/tooldistillator/macro.xml
- tools/tooldistillator/tooldistillator.xml
Here are the changes:
- Correction of an error when giving staramr outputs: need to have specific dataset names
- Conditional parameter added for the tools version generating the outputs given to ToolDistillator: automatic recovery of the tool version or not
Thanks :smiley:
> Update ToolDistillator Galaxy Version 0.9.1+galaxy0 to 0.9.1+galaxy1

- data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.py
- data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml
Thanks to usegalaxy.eu and @bgruening we know that this DM exceeds 100 GB memory usage. Probably because the tar.gz of the full DB includes huge files: https://github.com/paulzierep/tools-iuc/blob/bc882c3b2f21b4d3bda7a6c584121c8e3f95eaf0/data_managers/data_manager_gtdbtk_database_installer/test-data/release220/readme.md
Hopefully by chunking the files it can be reduced. Cannot really test it locally, though.
> Update gtdb-tk DM - chunck extractall for memory efficiency

- tools/ampvis2/subset_taxa.xml
- tools/ampvis2/test-data/AalborgWWTPs-selected.taxonomy.list
We want to use ampvis2 subset in a workflow. The use case is, that we run differential abundance tools to select the taxa / OTU we are interested in and then plot them with ampvis2. Therefore, I modified the wrapper to allow the input of a file that contains the differential abundant taxa. 
@bernt-matthias what you think about it ?
> Ampvis subset allow file input for taxa selection

- tools/ucsc_tools/twobittofa/twobittofa.xml
Hello! This is an automated update of the following tool: **tools/ucsc_tools/twobittofa**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ucsc_tools/twobittofa from version 377 to 447.
**Project home page:** https://genome.ucsc.edu/goldenpath/help/twoBit.html
> Updating tools/ucsc_tools/twobittofa from version 377 to 472

- tools/srst2/macros.xml
- tools/srst2/srst2.xml
Fixes #6487 
Fixes #6459 
The collections are also separated because it made them very difficult to use in an automated way, especially with hamronize. 
Either they're a separate collection or you have to
- extract element identifiers (`txt,tabular` formatted output due to #6459 prevents this tool from selecting this collection weirdly)
- select matching element identifiers
- filter collection (because it won't let you just .. grep. you have to specify the precise list of identifiers. I get it, but the UX isn't great.)
> Fix 2 bugs in SRST2

- tools/hicexplorer/hicBuildMatrix.xml
- tools/hicexplorer/hicQuickQC.xml
- tools/hicexplorer/macros.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/6505
> hicexplorer: fix restriction/danglingSequence

- tools/freyja/macros.xml
This PR updates the freyja tool to 1.5.2 and adds new `--pathogen` option.
Fixes: #6513
---
> Update tools/freyja to 1.5.2

- tools/tb-profiler/tb_profiler_profile.xml
Related to https://github.com/galaxyproject/tools-iuc/pull/5139
> Updating tb-profiler to 6.4.0

- tools/bbtools/bbduk.xml
- tools/bbtools/bbmap.xml
- tools/bbtools/bbmerge.xml
- tools/bbtools/callvariants.xml
- tools/bbtools/macros.xml
- tools/bbtools/tadpole.xml
had a `Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space` in bbnorm. 
I could also implement a separate stdio rule foe this. 
> bbtools: use aggressive error detection

- tools/hicstuff/hicstuff_pipeline.xml
- tools/hicstuff/macros.xml
---
This PR introduces some minor changes in the hicstuff tool in addition to #6588  as enlisted below:
- Update profile version from 21.09 to 23.02
- Remove previous requirements (cooler,biopython) that are now redundant.
> Minor tool updates to tools/hicstuff

- tools/dada2/dada2_assignTaxonomyAddspecies.xml
- tools/dada2/dada2_primercheck.xml
- tools/dada2/dada2_removeBimeraDenovo.xml
Just had a user with ridiculous amounts of chimeric reads. This seems to be often caused by primers that have not been removed. But the user told me that primers should have been removed... So I needed to check. Luckily the dada2 tutorial contained some simple R code for checking.
> dada2: add tool to check for primers

- tools/augustus/augustus.xml
- tools/augustus/macros.xml
> Augustus: text is txt

- tools/fasttree/.lint_skip
- tools/fasttree/fasttree.xml
Fixes https://github.com/galaxyproject/tools-iuc/pull/6389#issuecomment-2545001051, broken by the addition of a newer profile version in that PR. We should probably not make it possible to skip error-level linting.
> Fix fasttree tool

- .github/workflows/ci.yaml
I guess writing it to `GITHUB_STEP_SUMMARY` will still not work (because it's to large). But there is only one way to find out.
> Create combined markdown report in weekly CI

- data_managers/data_manager_checkm2/data_manager/checkm2_datamanager.xml
- data_managers/data_manager_checkm2/data_manager_conf.xml
- data_managers/data_manager_checkm2/test-data/checkm2.loc
- data_managers/data_manager_checkm2/tool-data/checkm2.loc.sample
- data_managers/data_manager_checkm2/tool_data_table_conf.xml.sample
- data_managers/data_manager_checkm2/tool_data_table_conf.xml.test
- tools/checkm2/test-data/checkm2.loc
- tools/checkm2/tool-data/checkm2.loc.sample
- tools/checkm2/tool_data_table_conf.xml.sample
- tools/checkm2/tool_data_table_conf.xml.test
Data manager passses all tests, but fails when merged. This should hopefully fix that
> Try adding dbkey to fix checkm2 data manager issue

- tools/irma/createMissingFiles.py
- tools/irma/irma.xml
Adds IRMAs output: amended consensus fasta as optional output & logs/run_info.txt, which includes meta data for the IRMA run (optional aswell).
Added a new test, that covers these 2 new outputs.
> IRMA update: Add amended consensus output and run info

- tools/irma/irma.xml
Due to excessive I/O usage of SSW, the assembler used in IRMA is changed to minimap2.
The used modified version of SSW opens the reference for every read. This leads to excessive I/O workload in the assembling process (opening the ref files more than 10.000 times). To avoid this, the assembler is now set to minimap2 (fixed). It has a constant number of reference file accesses (32 per assembled segment). 
> Changed assembler from SSW to minimap2

- tools/multiqc/bamtools_plugin.xml
- tools/multiqc/bcftools_plugin.xml
- tools/multiqc/cutadapt_plugin.xml
- tools/multiqc/fastp_plugin.xml
- tools/multiqc/fastqc_plugin.xml
- tools/multiqc/featurecounts_plugin.xml
- tools/multiqc/flexbar_plugin.xml
- tools/multiqc/macros.xml
- tools/multiqc/picard_plugin.xml
- tools/multiqc/pycoqc_plugin.xml
- tools/multiqc/qualimap_plugin.xml
- tools/multiqc/samtools_plugin.xml
- tools/multiqc/star_plugin.xml
- tools/multiqc/trimmomatic_plugin.xml
Bump MultiQC to version 1.27, because the current version 1.24.1 had a [bug](https://github.com/MultiQC/MultiQC/issues/2810) in calculating the average read length.
> Update MultiQC to version 1.27

- tools/volcanoplot/volcanoplot.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/6620
> volcanoplot bump

- tools/fairy/.shed.yml
- tools/fairy/fairy_cov.xml
- tools/fairy/fairy_sketch.xml
- tools/fairy/macros.xml
> Add bio.tools to fairy

- tools/muon/macros.xml
Failed on toolshed because non-optional params have no value set. It was not caught in linting.
> fix muon params

- tools/table_compute/table_compute.xml
Fix the following error:
```
cp: can't stat '/jetstream2/scratch/main/jobs/65014985/tool_files/scripts/safety.py': No such file or directory
```
> Add missing required_files to run remotely

- tools/fastk/fastk.xml
---
Based on https://github.com/galaxyproject/galaxy/pull/19615 this PR replaces the tar dataype with fastk_ktab_tar for fastk_fastk tool
> Changing datatype of FASTK tool from tar to fastk_ktab_tar

- tools/freyja/freyja_boot.xml
- tools/freyja/freyja_demix.xml
- tools/freyja/macros.xml
---
This PR resolves the issue reported in https://github.com/galaxyproject/tools-iuc/issues/6681 by @dadrasarmin regarding unexpected behavior in the Freyja Demix tool when a custom Usher barcode file is provided for analysis. The underlying issue has been fixed by modifying the code to ensure proper handling of custom barcode files. Additionally, relevant tests have been added to verify expected behavior
> Fix unexpected behavior in Freyja Demix with custom Usher barcode files

- data_managers/data_manager_build_staramr/data_manager/data_manager_build_staramr_download.xml
Updated the DM to the latest version of starAMR + minor modifications into label and help
> Update starAMR DM version

- tools/spades/macros.xml
Since `false && ... && false || true` is `true` the spades tools using these macros never fail
> Fix spades CLI

- tools/funannotate/funannotate_annotate.xml
- tools/funannotate/funannotate_clean.xml
- tools/funannotate/funannotate_predict.xml
- tools/funannotate/funannotate_sort.xml
We can skip deployment (just want to have this in the next release), but I also do not mind bumping versions.
> Funannotate: more consistent tool names

- tools/recentrifuge/macro.xml
- tools/recentrifuge/recentrifuge.xml
> Remove conflicting URL from tools/recentrifuge causing linting failure

- tools/quicktree/quicktree.xml
The output of Quicktree was labelled as "Stockholm Format", but this isn't true and rather confusing, so updated the label of the output dataset
> [Quicktree] fix output label

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
Planemo [now](https://github.com/galaxyproject/planemo/pull/1502) has a linter checking if the version was bumped. This makes sense for PR, but not in weely CI.
> skip linter version bumped check in weekly CI and deploy also if lint fails 

- tools/bwa_mem2/bwa-mem2.xml
- tools/bwa_mem2/macros.xml
Should reduce the number of files being created.
Saw
```
[bam_sort_core] merging from 28200 files and 120 in-memory blocks
```
... for a 2+ TB file which is a challenge for any filesystem
> bwa-mem2: Sort with max-memory per thread

- tools/bwa_mem2/bwa-mem2.xml
- tools/bwa_mem2/macros.xml
Causes more problems than it solves. Fixes https://github.com/galaxyproject/tools-iuc/issues/6898
This reverts commit c5a57522f74771171525db6902c055393014f1cc.
> Revert "Sort with max-memory per thread"

- tools/arriba/arriba.xml
- tools/arriba/arriba_draw_fusions.xml
- tools/arriba/arriba_get_filters.xml
- tools/arriba/macros.xml
---
This PR updates outdated documentation links, replacing them with the new GitHub Wiki links as per the latest update.
Fixes: https://github.com/galaxyproject/tools-iuc/pull/6892
> Updating and fixing outdated links in tools/arriba

- tools/bakta/bakta.xml
- tools/bakta/macro.xml
the tool currently requires the value. otherwise the symlinks created in the beginning will not work
not sure if the DB is really needed.
> bakta: make amrfinder db mandatory

- .github/workflows/pr.yaml
make use of `planemo lint` again when merging to main but skip version check.
> Hardening linter skipping

- data_managers/data_manager_fetch_busco/data_manager/busco_fetcher.xml
- data_managers/data_manager_fetch_busco_options/.shed.yml
- data_managers/data_manager_fetch_busco_options/data_manager/busco_options.xml
and update profile for both DMs to trigger re-deployment
> fix shed.yaml for data_manager_fetch_busco_options

- tool_collections/fastx_toolkit/fasta_clipping_histogram/fasta_clipping_histogram.xml
- tool_collections/fastx_toolkit/fasta_formatter/fasta_formatter.xml
- tool_collections/fastx_toolkit/fasta_nucleotide_changer/fasta_nucleotide_changer.xml
- tool_collections/fastx_toolkit/fastq_quality_boxplot/fastq_quality_boxplot.xml
- tool_collections/fastx_toolkit/fastq_quality_converter/fastq_quality_converter.xml
- tool_collections/fastx_toolkit/fastq_quality_filter/fastq_quality_filter.xml
- tool_collections/fastx_toolkit/fastq_to_fasta/fastq_to_fasta.xml
- tool_collections/fastx_toolkit/fastx_artifacts_filter/fastx_artifacts_filter.xml
- tool_collections/fastx_toolkit/fastx_barcode_splitter/fastx_barcode_splitter.xml
- tool_collections/fastx_toolkit/fastx_clipper/fastx_clipper.xml
- tool_collections/fastx_toolkit/fastx_collapser/fastx_collapser.xml
- tool_collections/fastx_toolkit/fastx_nucleotides_distribution/fastx_nucleotides_distribution.xml
- tool_collections/fastx_toolkit/fastx_quality_statistics/fastx_quality_statistics.xml
- tool_collections/fastx_toolkit/fastx_renamer/fastx_renamer.xml
- tool_collections/fastx_toolkit/fastx_reverse_complement/fastx_reverse_complement.xml
- tool_collections/fastx_toolkit/fastx_trimmer/fastx_trimmer.xml
I intentionally do not bump :)
> fastx toolkit: remove URL that is long gone

- tools/miniprot/miniprot_index.xml
Unlike most indexing steps, multi-threading is supported ([and recommended](https://github.com/lh3/miniprot/blob/4aaf71d03a229ec62fcfef379328103843da9511/README.md#L18)).
> Add threads option to miniprot_index

- tools/bellavista/bellavista_prepare.xml
- tools/bellavista/macros.xml
This update adds the input images (and other inputs like cell boundaries if specified) in the output tarball.
This tarball is much more easier to use for bellavista interactive tool.
> update bellavista - include inputs to tar file

- tools/gtdbtk/gtdbtk_classify_wf.xml
The help text for gtdbtk is out of sync with database version filter: update this from “This version of GTDB-Tk requires GTDB version 207 or 214” to “This version of GTDB-Tk requires GTDB version 220”.
> Update gtdbtk_classify_wf.xml help text

- tools/fastk/logex.xml
---
As per the VGP requirement, FastK Logex tool was updated to accommodate collection inputs.
> Update FastK Logex: Supporting collections as input

- tools/fastk/logex.xml
---
This PR is a small patch that add missing collection type to Logex tool.
> Logex tool Patch : Add missing collection type

- tools/table_compute/table_compute.xml
If `<required_files/>` is used it must include all tool files to be transferred. Fixes part of https://github.com/galaxyproject/pulsar/issues/392
> Fix  ``required_files`` in Table Compute

- tools/squirrel/macros.xml
- tools/squirrel/squirrel-phylo.xml
outputs `aa_recon` and `branch_snps` are `csv` not `png` files. I think a transposition error results in the outputs of these two files being tagged as `png`.
> Fix bug in output formats of Squirrel-Phylo

- data_managers/data_manager_deeparg/tool_data_table_conf.xml.sample
Had to fix the .loc files manually on .eu to make this DM work and chances are this is the root of the problem.
> deeparg DM: fix .loc file name in sample file

- tools/kma/.lint_skip
We can skip the version bump here (which is the reason of the failing lint)
> kma: remove .lint-skip file

- tools/velvet/.lint_skip
- tools/velvet/macros.xml
- tools/velvet/velvetg.xml
- tools/velvet/velveth.xml
tool tests fail for a long time because CI now uses 2 cores and test-data has been generated with 1 core. this is because velvet is not deterministic for multiple cores
https://www.biostars.org/p/86907/
https://github.com/dzerbino/velvet/issues/56
> velvet: linter and test fixes

- tools/lexicmap/tool-data/lexicmap_index.loc.sample
- tools/lexicmap/tool-data/lexicmap_index.loc.xml
@bgruening @bernt-matthias The deploy step failed for lexicmap. I looked at how bwa and blast had their tool-data configured and tried to mimic it. The question if I should have named the sample file like this instead `tool-data/lexicmap_index.loc` instead of `tool-data/lexicmap_index.loc.sample`
> update samples file for lexicmap indexes

- data_managers/data_manager_gtdbtk_database_installer/.lint_skip
- data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.py
- data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml
- tools/gtdbtk/gtdbtk_classify_wf.xml
- tools/gtdbtk/macros.xml
- tools/gtdbtk/test-data/gtdbtk_database_versioned.loc.test
> Gtdb-TK: add version 226
