galaxyproject/tools-iuc

data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
=> Update pangolearn data manager: Bump pangolearn DM version number

tools/edger/edger.R, tools/edger/edger.xml
=> edgeR: update to 3.34.0

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml
=> limma: update to 3.48.0

tools/nextclade/nextclade.xml
=> Update nextclade to version 0.14.4

tools/bracken/macros.xml
Hello! This is an automated update of the following tool: **tools/bracken**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/bracken tool version(s)

tools/meryl/macros.xml, tools/meryl/meryl.xml
This PR modifies the input mode in the *group_kmers* option.
=> Update meryl union inputs

tools/hyphy/hyphy_annotate.xml, tools/hyphy/test-data/annotate-out1.json
=> Add JSON output dataset to HyPhy-Annotate.

tools/ivar/ivar_variants.xml, tools/ivar/test-data/zika/Z52_a_pass.vcf
=> Allow ivar_variants to make multiple outputs

tools/hyphy/hyphy_summary.xml, tools/hyphy/scripts/hyphy_summary.py
HyPhy-Summary would fail to output the annotation summary due to incorrect error checking.
=> Fix bug in HyPhy-Summary

tools/salsa2/salsa2.xml
=> bump tool version to 2.3

tools/pangolin/pangolin.xml
=> Update pangolin to version 3.1.4

tools/edger/edger.R, tools/edger/edger.xml, tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml
A fix for a couple of the plots
=> edgeR limma: fix plots

tools/egsea/egsea.R, tools/egsea/egsea.xml
=> EGSEA: update to v1.20.0

tools/rgrnastar/rg_rnaStar.xml
=> RNA STAR: add --winAnchorMultimapNmax option

tools/intervene/macros.xml
Hello! This is an automated update of the following tool: **tools/intervene**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/intervene tool version(s)

tools/fastqe/fastqe.xml
=> FASTQE: small fixes

tools/fasta_stats/fasta-stats.pl, tools/fasta_stats/fasta-stats.xml, tools/fasta_stats/test-data/ng50_out.txt, tools/fasta_stats/test-data/test_out.txt
=> fixed min/max bug and added N90 and L90

tools/prinseq/prinseq.xml, tools/tbvcfreport/tbvcfreport.xml, tools/tbvcfreport/test-data/rif_resistant_drug_resistance_report.html, tools/tbvcfreport/test-data/rif_resistant_drug_resistance_report.txt, tools/tbvcfreport/test-data/rif_resistant_variants_report.html, tools/tbvcfreport/test-data/rif_resistant_variants_report.txt, tools/tbvcfreport/test-data/rif_resistant_variants_report_with_lineage.html, tools/tbvcfreport/test-data/rif_resistant_variants_report_with_lineage.txt
=> Update tbvcfreport to 0.1.8

tools/pangolin/fetch_latest_pangolearn.py, tools/pangolin/pangolin.xml
=> Update pangolin: add better support for noting network problems

tools/emboss_5/emboss_fuzznuc.xml, tools/emboss_5/test-data/emboss_fuzznuc_out2.tabular
=> Add missing fuzznuc parameters

tools/lumpy_sv/lumpy_preprocessing.xml, tools/lumpy_sv/macros.xml
=> lumpy: fix bam tests

tools/bwameth/bwameth.xml
xref https://github.com/galaxyproject/tools-iuc/issues/3699
=> bwameth: fix bam diff

tools/slamdunk/alleyoop.xml, tools/slamdunk/macros.xml, tools/slamdunk/slamdunk.xml
xref https://github.com/galaxyproject/tools-iuc/issues/3699
=> slamdunk: fix bam diff

tools/metaeuk/metaeuk_easy_predict.xml
Hello! This is an automated update of the following tool: **tools/metaeuk**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/metaeuk tool version(s)

tools/ncbi_acc_download/macros.xml
Hello! This is an automated update of the following tool: **tools/ncbi_acc_download**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/ncbi_acc_download tool version(s)

tools/pangolin/pangolin.xml
=> Updating tools/pangolin tool version(s)

tools/miniasm/miniasm.xml
Hello! This is an automated update of the following tool: **tools/miniasm**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/miniasm tool version(s)

.github/CODEOWNERS
corrects username to ping in the codeowners file due to my renaming.
=> Fix my username in the codeowners file

tools/seqwish/seqwish.xml
Hello! This is an automated update of the following tool: **tools/seqwish**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/seqwish tool version(s)

tools/ruvseq/ruvseq.xml
Hello! This is an automated update of the following tool: **tools/ruvseq**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/ruvseq tool version(s)

tools/vsnp/vsnp_determine_ref_from_data.xml
=> Bump vsnp_determine_ref_from_data requirements

tools/collection_column_join/collection_column_join.xml
Update to help section to provide more comprehensive overview of capabilities of this fantastic tool. Related to #11068
=> Edits for column join help section

tools/tb-profiler/tb_profiler_profile.xml
Hello! This is an automated update of the following tool: **tools/tb-profiler**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/tb-profiler tool version(s)

tools/vardict/macros.xml, tools/vardict/test-data/all_variants_paired.vcf, tools/vardict/test-data/all_variants_single.vcf, tools/vardict/test-data/passed_variants_paired.vcf, tools/vardict/test-data/passed_variants_single.vcf, tools/vardict/vardict.xml
Hello! This is an automated update of the following tool: **tools/vardict**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/vardict tool version(s)

tool_collections/samtools/cram_to_bam/samtools_cram_to_bam.xml
=> Fix cram to bam writing crai file to Galaxy database directory.

data_managers/data_manager_dada2/data_manager/dada2_fetcher.xml
=> Add silva 138 dataset to dada2 data manager

tools/ivar/ivar_removereads.xml, tools/ivar/ivar_trim.xml, tools/ivar/write_amplicon_info_file.py
=> Update: Add option to ivar_trim and ivar_removereads to compute amplicon info file

tools/iqtree/iqtree.xml, tools/iqtree/iqtree_macros.xml
Many parameter names were changed, and a few new options were added.
=> Update iqtree wrapper to 2.1.2

tools/iqtree/iqtree.xml
Correct the --rand parameter and add help for the -m parameter, as suggested when #3871 was reviewed
=> Update iqtree wrapper

tools/meryl/macros.xml, tools/meryl/meryl.xml
=> add potential meryl-fix

tools/pangolin/pangolin.xml
=> Update pangolin to version 3.1.11

tools/pretext/pretext_map.xml
Hello! This is an automated update of the following tool: **tools/pretext**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/pretext tool version(s)

tools/iqtree/iqtree.xml
Add datatypes for input, quote date dataset path
=> Fix iqtree inputs

tools/iqtree/iqtree.xml
The lab that requested this update also asked me to include the least square dating report in the outputs when performing time tree reconstruction.
=> Update iq-tree: Add output and test for LSD report.

data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.py, data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.xml, data_managers/data_manager_selection_background/data_manager_conf.xml, data_managers/data_manager_selection_background/test-data/selection-out1.json, data_managers/data_manager_selection_background/tool_data_table_conf.xml.sample
Use consistent data table naming, add sample .loc
=> Update selection data manager

tools/pangolin/pangolin.xml
output seems to have changed
not sure if the new assertions will be useful in the future. opinions?
=> fix pangolin tests

tools/tb_variant_filter/tb_variant_filter.xml
=> Update tb_variant_filter: Switch profile to 20.09

tools/weather_app/simple_weather.xml
-  keep stderr and add pipefail (this way we may be able to debug this more easily)
- add retry (maybe this helps)
was failing weekly CI once: https://github.com/galaxyproject/tools-iuc/issues/3666#issuecomment-847671000
=> simple weather pipefail and retry

data_managers/data_manager_star_index_builder/tool-data/rnastar_index2x_versioned.loc.sample, tools/rgrnastar/tool-data/rnastar_index2x_versioned.loc.sample
=> Fix typo breaking loading of STAR data table

.github/workflows/pr.yaml
=> Cancel in-progress GitHub workflows when a PR is updated

tools/medaka/medaka_consensus.xml
=> Avoid medaka to write to inputdir

tools/bowtie2/bowtie2_macros.xml, tools/bowtie2/bowtie2_wrapper.xml
Hello! This is an automated update of the following tool: **tools/bowtie2**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/bowtie2 tool version(s)

tools/metaphlan/macros.xml
Hello! This is an automated update of the following tool: **tools/metaphlan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/metaphlan tool version(s)

tools/abyss/abyss-pe.xml
Hello! This is an automated update of the following tool: **tools/abyss**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/abyss tool version(s)

tools/slamdunk/alleyoop.xml, tools/slamdunk/macros.xml, tools/slamdunk/slamdunk.xml, tools/slamdunk/test-data/reads_slamdunk_mapped_filtered_tcount.tsv
Hello! This is an automated update of the following tool: **tools/slamdunk**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/slamdunk tool version(s)

tools/proteinortho/proteinortho.xml, tools/proteinortho/proteinortho_grab_proteins.xml, tools/proteinortho/proteinortho_macros.xml, tools/proteinortho/proteinortho_summary.xml
Hello! This is an automated update of the following tool: **tools/proteinortho**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/proteinortho tool version(s)

tools/metaspades/metaspades.xml, tools/rnaspades/rnaspades.xml, tools/spades/spades.xml
=> Quote strings in bash tests

tools/proteinortho/proteinortho_grab_proteins.xml
=> Fix breaking typo in proteinortho wrapper

tools/spades/spades.xml
=> Spades: add tmp-dir option

.github/workflows/pr.yaml
=> Prevent cancelling of in-progress toolshed uploads

tools/usher/usher.xml
=> usher: fix typo

tools/scanpy/normalize.xml
=> fix typo in scanpy test

tools/tximport/tximport.R, tools/tximport/tximport.xml
=> Use camel-case args for countsFromAbundance option

tools/anndata/import.xml
=> Avoid anndata_import writing to input directory

tools/feelnc/feelnc_wrapper.xml
=> Avoid feelnc writing to input directory

tools/salsa2/salsa2.xml
This PR closes https://github.com/galaxyproject/tools-iuc/issues/3530
=> Salsa2: modify sequence input options

tools/chira/chira_extract.xml
=> chira_extract: avoid writing FASTA index to inputdir

tools/slamdunk/alleyoop.xml, tools/slamdunk/macros.xml, tools/slamdunk/slamdunk.xml, tools/slamdunk/test-data/reads_slamdunk_mapped_filtered_snp.vcf
follow up to https://github.com/galaxyproject/tools-iuc/pull/3835
- add new cvf parameter
- add argument attributes
TODO:
=> slamdunk update continued

tools/minia/minia.xml
Hello! This is an automated update of the following tool: **tools/minia**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/minia tool version(s)

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Test against release 21.09

tools/berokka/berokka.xml
Update berokka to version 0.2.3 which is the latest version in bioconda.
=> upgrade berokka to 0.2.3

tools/deepvariant/deepvariant.xml, tools/deepvariant/macros.xml
This PR disables the use_openvino option since it restricts the use of Deepvariant to Intel cpus.
Test history: https://usegalaxy.eu/u/gallardoalba/h/deepvariant-real-data
=> Fix Deepvariant bug

tools/nextclade/macros.xml, tools/nextclade/nextclade.xml, tools/nextclade/test-data/strict_qc.json
=> Update nextclade to version 1.4.0

tools/amplican/amplican.xml
This PR removes some empty help sections.
=> Amplican: remove help sections

tools/trycycler/macros.xml
Hello! This is an automated update of the following tool: **tools/trycycler**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/trycycler tool version(s)

tools/meryl/meryl.xml
currently failing weekly CI
just increased the allowed diff ..
=> Fix meryl test assertion

data_managers/data_manager_bowtie2_index_builder/data_manager/bowtie2_index_builder.xml
=> upgrade bowtie2 dependency

data_managers/data_manager_sam_fasta_index_builder/data_manager/data_manager_sam_fasta_index_builder.xml
=> upgrade samtools dependency

tools/quast/quast.xml
=> Quast: fix label

data_managers/data_manager_build_bracken_database/data_manager/bracken_build_database.py, data_managers/data_manager_build_bracken_database/data_manager/bracken_build_database.xml, data_managers/data_manager_build_bracken_database/data_manager_conf.xml
=> Bracken Data Manager: Add support for pre-built DBs

tools/salsa2/salsa2.xml
This PR improves the documentation.
=> SALSA2: Update parameters documentation

tools/pretext/.shed.yml, tools/pretext/pretext_map.xml, tools/pretext/pretext_snapshot.xml
This PR improves the parameter documentation and some additional modifications.
=> PretextMap: improve parameters documentation

tools/circos/alignments-to-links.xml, tools/circos/bundlelinks.xml, tools/circos/circos.xml, tools/circos/gc_skew.xml, tools/circos/macros.xml, tools/circos/resample.xml, tools/circos/scatter-from-wiggle.xml, tools/circos/stack-histogram.xml, tools/circos/text-from-interval.xml, tools/circos/tiles-from-interval.xml
This PR fixes a path composition in the Circos preset option.
=> fix Circos preset option

tools/crossmap/crossmap_vcf.xml
=> Symlink crossmap_vcf fasta input to prevent writing to the input directory to generate fasta index

tools/tetyper/tetyper.xml
=> tetyper: avoid writing indices to inputdir

tool_collections/biotradis/bacteria_tradis.xml
=> Bio-TraDis: avoid writing to input directory

tools/orthofinder/macros.xml, tools/orthofinder/orthofinder_only_groups.xml
Hello! This is an automated update of the following tool: **tools/orthofinder**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/orthofinder tool version(s)

data_managers/data_manager_funannotate/data_manager/funannotate.py, data_managers/data_manager_funannotate/data_manager/funannotate.xml
Getting certificate errors for a strange reason with the default download mode, so adding this wget option which should fix the problem
=> Funannotate data manager: add the wget option to 

tools/interproscan/interproscan.xml
A tiny bugfix for interproscan (I hope it's the last :crossed_fingers:)
=> Interproscan: fix path to data

tools/minimap2/macros.xml, tools/minimap2/minimap2.xml
=> minimap upgrade

tools/pangolin/pangolin.xml
tool is failing weekly CI at the moment
=> pangolin: make tests pass again

tools/deseq2/deseq2.xml, tools/deseq2/deseq2_macros.xml
This PR can close https://github.com/galaxyproject/tools-iuc/pull/2883 I think.
=> DESeq2: update dependencies

tools/pretext/pretext_map.xml
fixes: https://github.com/galaxyproject/tools-iuc/issues/4171
=> fixes https://github.com/galaxyproject/tools-iuc/issues/4171

tools/ggplot2/ggplot2_pca.xml, tools/ggplot2/macros.xml
This PR fixes a test, which fails due to lint tool-list.
=> Fix ggplot2 tests: modify validators

tools/interproscan/interproscan.xml, tools/interproscan/macros.xml
A tiny bugfix for interproscan
=> Interproscan: fix output collection

.gitignore, tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml
This PR:
- change omero-py version from 5.7.1 to 5.10.1.
- add `.vscode` to gitignore (I hope you don't mind)
- add an option which will download all images of a dataset
=> Idr update modify

tools/crossmap/crossmap_bam.xml
=> crossmap: remove unused test param

tools/genebed_maf_to_fasta/genebed_maf_to_fasta.xml
=> genebed_maf_to_fasta: remove unused test param

tools/berokka/berokka.xml
=> berokka: remove unused test param

tools/funannotate/funannotate_annotate.xml, tools/funannotate/funannotate_compare.xml, tools/funannotate/macros.xml
Yet another funannotate PR! I've just realised there was a missing dep for the compare tool... Adding it + corresponding tests
=> Funannotate compare: add missing dep

tools/flair/flair_collapse.xml
=> flair collapse: add missing mapq parameter to command

tools/kma/kma_map.xml
=> kma: add missing parameters to command

tools/quast/macros.xml, tools/quast/quast.xml
=> quast: add unused param to command

tools/orthofinder/macros.xml, tools/orthofinder/orthofinder_only_groups.xml
=> orthofinder: use inflation test parameter

tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/analyze_diff_expr.xml, tools/trinity/contig_exn50_statistic.xml, tools/trinity/define_clusters_by_cutting_tree.xml, tools/trinity/describe_samples.xml, tools/trinity/filter_low_expr_transcripts.xml, tools/trinity/gene_to_trans_map.xml, tools/trinity/run_de_analysis.xml, tools/trinity/samples_qccheck.xml, tools/trinity/super_transcripts.xml, tools/trinity/trinity.xml
=> trinity: fix test param name

tools/ncbi_entrez_eutils/egquery.xml, tools/ncbi_entrez_eutils/macros.xml
=> ncbi-eutils: remove unused parameter

tools/codeml/codeml.xml
and make all outputs valid cheetah placeholders
=> codeml: fix test parameters

tools/mummer4/delta-filter.xml, tools/mummer4/dnadiff.xml, tools/mummer4/mummer.xml, tools/mummer4/mummerplot.xml, tools/mummer4/nucmer.xml, tools/mummer4/show-coords.xml
=> mummer: remove unused test param

tools/masigpro/masigpro.R, tools/masigpro/masigpro.xml
=> masigpro: remove unused test param

tools/repeatmodeler/repeatmodeler.xml
=> repeatmodeler: remove unused test params

tool_collections/bamtools/bamtools/bamtools.xml, tool_collections/bamtools/bamtools_filter/bamtools-filter.xml, tool_collections/bamtools/bamtools_split/bamtools_split.xml, tool_collections/bamtools/bamtools_split/bamtools_split_mapped.xml, tool_collections/bamtools/bamtools_split/bamtools_split_paired.xml, tool_collections/bamtools/bamtools_split/bamtools_split_ref.xml, tool_collections/bamtools/bamtools_split/bamtools_split_tag.xml, tool_collections/bamtools/macros.xml
=> bamtools: bump and remove unused test parameter

tools/bwameth/bwameth.xml
=> bwameth: fix test parameter

tools/bioext/bealign.xml
=> bealign: fix test parameter name

tools/bandage/bandage_image.xml, tools/bandage/bandage_info.xml
=> bandage: remove unused test param

tools/last/lastal.xml, tools/last/lastdb.xml, tools/last/lastsplit.xml, tools/last/lasttrain.xml, tools/last/macros_last.xml, tools/last/maf-convert.xml
=> lastal: add missing parameter to command

tools/velvet_optimiser/velvetoptimiser.xml
also 
- add argument to all inputs
- validator, min, max for kmer parameters
=> velvet_optimizer: add missing kmer_step to command

tools/meme/macros.xml, tools/meme_chip/macros.xml
Thanks @nsoranzo 
https://github.com/galaxyproject/tools-iuc/pull/4241#discussion_r757765655
Maybe this is OK wo bump, since https://github.com/galaxyproject/tools-iuc/pull/4241 was just merged hours ago
=> meme* add missing semicolon

tools/edger/edger.xml, tools/limma_voom/limma_voom.xml
=> limma: remove redundant (and unused) parameter

tools/raceid/macros.xml, tools/raceid/raceid_clustering.xml, tools/raceid/raceid_filtnormconf.xml, tools/raceid/raceid_inspectclusters.xml, tools/raceid/raceid_inspecttrajectories.xml, tools/raceid/raceid_trajectory.xml
- clustering: rfseed is commented in the command file
also rename version tokens
=> raceid: parameter fix

tools/freebayes/freebayes.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/4270
=> fix standard-filters argument in cheetah

tools/vsnp/vsnp_build_tables.py, tools/vsnp/vsnp_get_snps.py
=> Change vSNP processors

tools/megan/blast2rma.xml, tools/megan/daa2rma.xml, tools/megan/macros.xml
=> Add the MEGAN daa2rma tool

data_managers/data_manager_diamond_database_builder/data_manager/data_manager_diamond_database_builder.xml, data_managers/data_manager_diamond_database_builder/data_manager_conf.xml, data_managers/data_manager_diamond_database_builder/tool-data/ncbi_accession2taxid.loc.sample
=> Add ncbi_accession2taxid data table sample

data_managers/data_manager_diamond_database_builder/data_manager/data_manager_diamond_database_builder.xml
=> Revert diamond_database_builder profile version to the one that worked

tools/megan/blast2lca.xml, tools/megan/blast2rma.xml, tools/megan/daa2rma.xml, tools/megan/daa_meganizer.xml, tools/megan/macros.xml, tools/megan/sam2rma.xml, tools/megan/test-data/input1.sam, tools/megan/test-data/input2.sam
=> Add the MEGAN sam2rma tool

tools/seqwish/seqwish.xml
Hello! This is an automated update of the following tool: **tools/seqwish**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seqwish from version 0.7.2 to 0.7.3.
**Project home page:** https://github.com/ekg/seqwish/releases
=> Updating tools/seqwish from version 0.7.2 to 0.7.3

tools/pangolin/pangolin.xml
=> Update pangolin to use the latest scorpio (necessary for BA.3 lineage)

tools/picrust/compare_biom.xml
=> picrust compare biom: add missing param to command

tools/trycycler/trycycler_consensus.xml
not used on the CLI, and apparently really not needed: doc also list
only 3 necessary inputs: https://github.com/rrwick/Trycycler/wiki/Generating-a-consensus
=> trycycler: remove unused param reads

tool_collections/samtools/samtools_markdup/samtools_markdup.xml, tool_collections/samtools/samtools_merge/samtools_merge.xml, tool_collections/samtools/samtools_mpileup/samtools_mpileup.xml, tool_collections/samtools/samtools_view/samtools_view.xml
=> samtools: fix unused parameters

tools/seurat/seurat.xml
Hello! This is an automated update of the following tool: **tools/seurat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seurat from version 4.0.5 to 4.0.6.
**Project home page:** https://github.com/satijalab/seurat/releases
=> Updating tools/seurat from version 4.0.5 to 4.0.6

tools/rnaquast/rna_quast.xml
This PR fixes the` --busco` option and includes some information in the help sections.
=> rnaQUAST: fix --busco option

tools/seurat/seurat.xml
Hello! This is an automated update of the following tool: **tools/seurat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seurat from version 4.0.6 to 4.1.0.
**Project home page:** https://github.com/satijalab/seurat/releases
=> Updating tools/seurat from version 4.0.6 to 4.1.0

.github/workflows/pr.yaml
To be in line with the IUC Standards recommendation:
https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/integration_checklist.html#testing-your-tool
=> Increase `MAX_FILE_SIZE` to 1Mb

tools/spades/macros.xml
=> SPAdes - Add quotes missed for symlinks

tools/bowtie2/bowtie2_macros.xml, tools/bowtie2/bowtie2_wrapper.xml
Hello! This is an automated update of the following tool: **tools/bowtie2**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/bowtie2 from version 2.4.4 to 2.4.5.
**Project home page:** http://bowtie-bio.sourceforge.net/bowtie2
=> Updating tools/bowtie2 from version 2.4.4 to 2.4.5

tools/rpfba/rpfba.xml
Update **rpfba** tool to **5.12.1**
=> Update rpfba v5.12.1

tools/bbtools/bbduk.xml, tools/bbtools/bbmap.xml, tools/bbtools/macros.xml
=> bbtools, ensure read pair identifiers differ

tools/ucsc_tools/fasplit/fasplit.xml, tools/ucsc_tools/twobittofa/twobittofa.xml
and use TOOL_VERSION in all ucsc tools
=> bump fasplit

tools/metaphlan/macros.xml, tools/metaphlan/test-data/SRS014464-Anterior_nares-abundances.tabular
Hello! This is an automated update of the following tool: **tools/metaphlan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/metaphlan from version 3.0.13 to 3.0.14.
**Project home page:** https://github.com/biobakery/MetaPhlAn/releases
=> Updating tools/metaphlan from version 3.0.13 to 3.0.14

tools/fastp/macros.xml
=> Update fastp to version 0.23.2

tools/shovill/shovill.xml
=> shovill: Fix handling of compressed fastq

tools/ncbi_datasets/macros.xml
Hello! This is an automated update of the following tool: **tools/ncbi_datasets**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ncbi_datasets from version 12.30.0 to 12.32.0.
**Project home page:** https://www.ncbi.nlm.nih.gov/datasets
=> Updating tools/ncbi_datasets from version 12.30.0 to 12.32.0

.github/workflows/ci.yaml, .github/workflows/pr.yaml
https://github.com/galaxyproject/tools-iuc/issues/4367 looks pretty good now.
=> Test against 22.01

tools/artic/artic_minion.xml
=> Fix quoting issue introduced in previous artic_minion change

tools/maker/macros.xml, tools/maker/maker.xml
As asked by author in https://github.com/galaxyproject/iwc/pull/47#issuecomment-962260646
=> Maker: add an option to warn users about license

tools/interproscan/README.md, tools/interproscan/interproscan.xml, tools/interproscan/macros.xml
Just adding some doc on how to install signalp etc for interproscan
ping @bgruening if you want to test this on .eu
=> InterProScan: add doc for licensed components

tools/pygenometracks/macros.xml, tools/pygenometracks/pyGenomeTracks.xml
This is a super small update which is useful when using collections.
I am not sure I can make a test as it will only affect some text in an image...
=> Minor update of pyGenomeTracks

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Sync CI workflows with tools-devteam

tools/ncbi_datasets/macros.xml
Hello! This is an automated update of the following tool: **tools/ncbi_datasets**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/ncbi_datasets from version 13.3.0 to 13.4.0.
**Project home page:** https://www.ncbi.nlm.nih.gov/datasets
=> Updating tools/ncbi_datasets from version 13.3.0 to 13.4.0

tools/tb-profiler/.shed.yml, tools/tb-profiler/tb_profiler_profile.xml
=> Update TB-Profiler to version 4.1.1

tools/bbtools/bbmap.xml
=> Fix bbmap paired read identifiers

tools/pathview/pathview.r, tools/pathview/pathview.xml
since it is sniffed as txt
xref https://github.com/galaxyproject/galaxy/pull/12073
=> pathwiew: 1 column tabular input should also accept txt

tools/structure/structure.xml
so allow txt
xref: https://github.com/galaxyproject/galaxy/pull/12073
=> structure: infile is not necessarily tab separated

tools/stacks/stacks_populations.xml, tools/stacks/stacks_stats.xml
=> --window_size does not exists in stacks_population

tools/seqwish/seqwish.xml
Hello! This is an automated update of the following tool: **tools/seqwish**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seqwish from version 0.7.3 to 0.7.4.
**Project home page:** https://github.com/ekg/seqwish/releases
=> Updating tools/seqwish from version 0.7.3 to 0.7.4

tools/vsnp/vsnp_get_snps.xml
=> Eliminate auto selection of Excel filter so tool will work with Pulsar

data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py, data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
Yet another fix for the pangolearn data manager.
=> Create pangolearn data that pangolin cannot ignore

tools/seqwish/seqwish.xml
Hello! This is an automated update of the following tool: **tools/seqwish**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seqwish from version 0.7.4 to 0.7.5.
**Project home page:** https://github.com/ekg/seqwish/releases
=> Updating tools/seqwish from version 0.7.4 to 0.7.5

.github/workflows/ci.yaml, .github/workflows/pr.yaml
relies on https://github.com/galaxyproject/planemo-ci-action/pull/25
=> use the available cores for Galaxy jobs

tools/interproscan/README.md, tools/interproscan/macros.xml, tools/interproscan/test-data/interproscan.loc
=> Update InterProScan to 5.55-88.0

tools/pangolin/pangolin.xml
=> Pangolin assignment cache fix

tools/dexseq/plotdexseq.xml
The latest plotDexseq has version @VERSION@.1.
=> change @VERSION@ to @TOOL_VERSION@ in plotDexseq.xml

tools/malt/macros.xml, tools/malt/malt_run.xml
=> Fix malt_run code for pulsar

tools/seurat/seurat.xml
Hello! This is an automated update of the following tool: **tools/seurat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seurat from version 4.1.0 to 4.1.1.
**Project home page:** https://github.com/satijalab/seurat/releases
=> Updating tools/seurat from version 4.1.0 to 4.1.1

tools/spades/coronaspades.xml, tools/spades/spades.xml
=> fix https://github.com/galaxyproject/tools-iuc/issues/4555

tools/salsa2/salsa2.xml
Addition of options -m to clean assembly and -s to provide estimated genome size
=> Salsa2 : Addition of options -m and -s

tools/goseq/goseq.xml
Should hopefully fix https://github.com/galaxyproject/tools-iuc/pull/4571#issuecomment-1149736727
=> Bump up all goseq peer dependencies

tools/prot-scriber/prot-scriber.xml, tools/prot-scriber/test-data/8_Proteins_prot-scriber.out, tools/prot-scriber/test-data/8_Proteins_vs_Trembl_blastp.txt
bump to v.0.1.3
Wait for https://github.com/bioconda/bioconda-recipes/pull/35364 to be merged to get v0.1.3 from bioconda
=> Update prot-scriber to v.0.1.3

tool_collections/samtools/samtools_markdup/samtools_markdup.xml, tool_collections/samtools/samtools_stats/samtools_stats.xml
=> samtools fixes

tools/cutadapt/cutadapt.xml
failing due to https://github.com/galaxyproject/tools-iuc/pull/4490
=> cutadapt: fix test

tools/anndata/export.xml, tools/anndata/import.xml, tools/anndata/inspect.xml, tools/anndata/loompy_to_tsv.py, tools/anndata/macros.xml, tools/anndata/manipulate.xml, tools/anndata/modify_loom.xml
and standardize version tokens
=> anndata export: open loompy file read only

tools/barrnap/barrnap.xml
=> barrnap: symlink fasta file

tools/nanocompore/sampcomp.xml
=> nanocompore: symlink reference

tools/ragtag/macros.xml, tools/ragtag/ragtag.xml
=> ragtag: symlink input fasta files

tools/kc-align/kc-align.xml
tool only accepts 1 thread or a number of threads that can be divided by 3
=> kc-align fix number of threads

tools/fermikit/fermi2.xml, tools/fermikit/fermikit_run_calling.xml
because fai file is created
also add tool verison tokens
=> fermikit: link fasta

tools/delly/call.xml, tools/delly/cnv.xml, tools/delly/lr.xml, tools/delly/macros.xml
since fai files are created
test data gets slighly smaller (due to shorter path)
=> delly: link fasta files

tools/ensembl_vep/ensembl_vep.xml
tool creates additional files next to the fasta
=> ensembl_vep: link input fasta

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Target release_22.05

tools/irissv/irissv.xml
=> Irissv: fix errors related to bai file creation

tools/flash/flash.xml
=> Flash test fix

tools/yahs/yahs.xml
=> bump yahs version

tools/pangolin/pangolin.xml
Also adds direct support of fasta.gz input to the tool.
=> Update pangolin to v4.1.2, pangolin-data to 1.12

tools/yahs/yahs.xml
=> yahs: add logfile

tools/nonpareil/nonpareil.xml
since the tool tries to write files like `....dat.enve-seq.7` next
to the input
also update profile and rename version token
=> nonpareil: link input

.gitignore
=> Ignore ``.idea`` directory

tools/metabat2/jgi_summarize_bam_contig_depths.xml, tools/metabat2/macros.xml
=> MetaBAT2: Enable individual mode for multiple inputs in the coverage tool

data_managers/data_manager_nextclade/.shed.yml, data_managers/data_manager_nextclade/data_manager/nextclade_dm.py, data_managers/data_manager_nextclade/data_manager/nextclade_dm.xml, data_managers/data_manager_nextclade/data_manager_conf.xml, data_managers/data_manager_nextclade/test-data/nextclade.loc, data_managers/data_manager_nextclade/tool-data/nextclade.loc, data_managers/data_manager_nextclade/tool_data_table_conf.xml.sample, data_managers/data_manager_nextclade/tool_data_table_conf.xml.test
=> Add nextclade data manager

tools/metabat2/jgi_summarize_bam_contig_depths.xml, tools/metabat2/macros.xml, tools/metabat2/metabat2.xml, tools/metabat2/test-data/process_log.txt
=> MetaBAT2: split outputs in differents output collections and files

tools/pangolin/tool_data_table_conf.xml.sample, tools/pangolin/tool_data_table_conf.xml.test
=> Update tool_data_table_conf to match current tool data tables

data_managers/data_manager_nextclade/test-data/nextclade.loc, data_managers/data_manager_nextclade/tool-data/nextclade.loc
=> remove references to pangolin in nextclade data manager files

tools/humann/humann_barplot.xml
=> humann: remove unused test parameters

tools/delly/lr.xml
=> delly fix test attribute

tools/bwa/bwa.xml
=> bwa: add missing parameter to CLI

tools/bcftools/bcftools_isec.xml, tools/bcftools/bcftools_mpileup.xml, tools/bcftools/bcftools_view.xml
isec: remove unused parameters (no idea how they are used)
mpileup: add unused param to CLI
view: fix regions test parameter spec
=> bcftools: misc parameter fixes

tools/biom_format/biom_from_uc.xml, tools/biom_format/macros.xml
=> biom-format: implement missing parameter

tool_collections/biotradis/bacteria_tradis.xml, tool_collections/biotradis/macros.xml
and make conditional parameters select
=> bacteria tradis: implement missing param tagdir

tools/ncbi_datasets/datasets_genome.xml, tools/ncbi_datasets/macros.xml
=> ncbi datasets: bump

tools/rpbasicdesign/rpbasicdesign.xml
fixes CI failure
```
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.9/site-packages/rpbasicdesign/cli.py", line 14, in <module>
from rpbasicdesign.Designer import Designer
File "/usr/local/lib/python3.9/site-packages/rpbasicdesign/Designer.py", line 23, in <module>
from rptools.rplibs import rpSBML, rpPathway
File "/usr/local/lib/python3.9/site-packages/rptools/rplibs/__init__.py", line 7, in <module>
from rptools.rplibs.rpPathway import rpPathway
File "/usr/local/lib/python3.9/site-packages/rptools/rplibs/rpPathway.py", line 46, in <module>
from .rpSBML import rpSBML …
```
=> rpbasicdesign: bump

tools/gatk4/gatk4_Mutect2.xml
The removed parameters are absent from the CLI help.
=> gatk4: add missing and remove nonexistent parameters

tools/raceid/macros.xml, tools/raceid/macros_cheetah.xml, tools/raceid/raceid_clustering.xml, tools/raceid/scripts/cluster.R, tools/raceid/scripts/clusterinspect.R, tools/raceid/scripts/trajectoryinspect.R
=> raceid clustering: remove unused parameter

tools/telescope/telescope_assign.xml
fails in weely CI and is also documented as not working:
https://github.com/mlbendall/telescope/blob/6cd55256c6016feffdbfe10346bfecfcb1e30965/README.md?plain=1#L129
=> telescope: disable parallel processing

tools/salsa2/salsa2.xml
=> Change salsa output format from tabular to agp

tools/megan/blast2rma.xml, tools/megan/daa2rma.xml, tools/megan/daa_meganizer.xml, tools/megan/sam2rma.xml
for some reason (?) output sizes changed .. currently fails CI
=> fix megan tests

tools/ncbi_datasets/macros.xml
Failing CI. Lets see if this helps
=> bump ncbi datasets

tools/nextclade/nextclade.xml
=> nextclade: fix test

data_managers/data_manager_dram_database_downloader/.shed.yml, data_managers/data_manager_dram_database_downloader/data_manager/data_manager_dram_download.py, data_managers/data_manager_dram_database_downloader/data_manager/data_manager_dram_download.xml, data_managers/data_manager_dram_database_downloader/data_manager_conf.xml, data_managers/data_manager_dram_database_downloader/test-data/dram_databases.loc, data_managers/data_manager_dram_database_downloader/tool-data/dram_databases.loc.sample, data_managers/data_manager_dram_database_downloader/tool_data_table_conf.xml.sample, data_managers/data_manager_dram_database_downloader/tool_data_table_conf.xml.test, tools/dram/.shed.yml, tools/dram/dram_set_database_locations.py, tools/dram/dram_set_database_locations.xml, tools/dram/macros.xml
=> Add DRAM data manager and set db locations tools

tools/red/red.xml, tools/red/test-data/small.bed
Adding bed output for Red tool (repeat masking)
=> Red: add bed output

tools/miniprot/macros.xml, tools/miniprot/miniprot.xml
=> Update miniprot to version 0.3

tools/sbml2sbol/.shed.yml, tools/sbml2sbol/sbml2sbol.xml, tools/sbml2sbol/test-data/lycopene.xml, tools/sbml2sbol/test-data/sbol_lycopene_output.xml, tools/sbml2sbol/test-data/sbol_lycopene_output2.xml, tools/sbml2sbol/wrap.xml
Add new tool **sbml2sbol** : https://github.com/neilswainston/SbmlToSbol
Thank you.
=> add new tool sbml2sbol

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Fix:
```
Error: Unable to resolve action `r-lib/actions@master`, unable to find version `master`
```
Also update R version to 'release'.
=> Update version of GitHub actions used

tools/das_tool/macros.xml
Hello! This is an automated update of the following tool: **tools/das_tool**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/das_tool from version 1.1.4 to 1.1.5.
**Project home page:** https://github.com/cmks/DAS_Tool/releases
=> Updating tools/das_tool from version 1.1.4 to 1.1.5

tools/seurat/seurat.xml
Hello! This is an automated update of the following tool: **tools/seurat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/seurat from version 4.1.1 to 4.2.0.
**Project home page:** https://github.com/satijalab/seurat/releases
=> Updating tools/seurat from version 4.1.1 to 4.2.0

tools/tetoolkit/tetranscript.xml
Hello! This is an automated update of the following tool: **tools/tetoolkit**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/tetoolkit from version 2.2.1 to 2.2.3.
**Project home page:** http://hammelllab.labsites.cshl.edu/software
=> Updating tools/tetoolkit from version 2.2.1 to 2.2.3

tools/raxml/raxml.xml
Hello! This is an automated update of the following tool: **tools/raxml**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/raxml from version 8.2.4 to 8.2.12.
**Project home page:** http://www.exelixis-lab.org/web/software/raxml
=> Updating tools/raxml from version 8.2.4 to 8.2.12

tools/ena_upload/ena_upload.xml, tools/ena_upload/extract_tables.py
Upgrade version. 
Improve interactive submission: submission of metadata using the tool input fields (not through input files).
=> Upgrade to 0.6.1  and improve individual submissions

tools/ucsc_blat/blat.xml
- use correct text datatype and remove `psl` datatype which does not exist  (xref https://github.com/galaxyproject/tools-iuc/issues/4009)
- and some  cosmetic improvements
=> Make `blat` use an up to date bioconda package + fixes

tools/ncbi_datasets/.shed.yml, tools/ncbi_datasets/datasets_genome.xml, tools/ncbi_datasets/macros.xml
Recover https://github.com/galaxyproject/tools-iuc/pull/4886 (which was deleted for some reason .. I only marked it as draft while working on it).
=> Update ncbi datasets

.github/workflows/ci.yaml
I hope that helps with
```
 --
No space left on device : '/home/runner/runners/2.299.1/_diag/pages/7fa8a17c-a556-4235-9dfe-8e504f8053e6_fa5bf8d6-a3cd-598b-c37e-7051536e76dc_1.log'
```
in https://github.com/galaxyproject/tools-iuc/actions/runs/3510417129
=> Clean up dotnet folder for space

tools/ncbi_datasets/datasets_gene.xml, tools/ncbi_datasets/datasets_genome.xml, tools/ncbi_datasets/macros.xml
non fasta files were not decompressed
as a bonus (or to say sorry for introducing the bug and opening PRs at fast pace) I added bio.tools xref and version command.
=> ncbi datasets: bugfix

tools/ucsc_blat/blat.xml
=> Add pslx to BLAT outputs

data_managers/data_manager_gtdbtk_database_installer/.shed.yml, data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.py, data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml, data_managers/data_manager_gtdbtk_database_installer/data_manager_conf.xml, data_managers/data_manager_gtdbtk_database_installer/test-data/gtdbtk_database.loc, data_managers/data_manager_gtdbtk_database_installer/tool-data/gtdbtk_database.loc.sample, data_managers/data_manager_gtdbtk_database_installer/tool_data_table_conf.xml.sample, data_managers/data_manager_gtdbtk_database_installer/tool_data_table_conf.xml.test
=> Add the data_manager_gtdbtk_database_installer tool

data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.py, data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml, data_managers/data_manager_metaphlan_database_downloader/data_manager_conf.xml, data_managers/data_manager_metaphlan_database_downloader/test-data/metaphlan_database_versioned.loc, data_managers/data_manager_metaphlan_database_downloader/tool-data/metaphlan_database_versioned.loc.sample, data_managers/data_manager_metaphlan_database_downloader/tool_data_table_conf.xml.sample, data_managers/data_manager_metaphlan_database_downloader/tool_data_table_conf.xml.test, tools/metaphlan/extract_metaphlan_database.xml, tools/metaphlan/macros.xml, tools/metaphlan/merge_metaphlan_tables.xml, tools/metaphlan/metaphlan.xml, tools/metaphlan/test-data/test_database.loc, tools/metaphlan/test-data/test_database_versioned.loc, tools/metaphlan/tool-data/metaphlan_database_versioned.loc.sample, tools/metaphlan/tool_data_table_conf.xml.sample, tools/metaphlan/tool_data_table_conf.xml.test
=> Data manager update for metaphlan

tools/tb_variant_filter/tb_variant_filter.xml
=> Update to version 0.3.6, change default region filter to farhat_rlc

tools/das_tool/macros.xml
Hello! This is an automated update of the following tool: **tools/das_tool**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/das_tool from version 1.1.5 to 1.1.6.
**Project home page:** https://github.com/cmks/DAS_Tool/releases
=> Updating tools/das_tool from version 1.1.5 to 1.1.6

tools/tb-profiler/tb_profiler_profile.xml
=> Update tb-profiler to version 4.4.0

tools/cherri/cherri_train.xml
=> cherri choose the correct output file in case single input

tools/hicexplorer/hicAggregateContacts.xml, tools/hicexplorer/hicConvertFormat.xml, tools/hicexplorer/hicCorrectMatrix.xml, tools/hicexplorer/hicCorrelate.xml, tools/hicexplorer/hicDetectLoops.xml, tools/hicexplorer/hicDifferentialTAD.xml, tools/hicexplorer/hicNormalize.xml, tools/hicexplorer/hicPCA.xml, tools/hicexplorer/hicPlotMatrix.xml, tools/hicexplorer/hicPlotSVL.xml, tools/hicexplorer/hicTransform.xml, tools/hicexplorer/macros.xml
=> hiccorrectmatrix: is writing to input file

tools/pangolin/pangolin.xml
=> Update pangolin to version 4.2

.tt_skip
Probably causes weekly test failures #5061 
=> Exclude metaphlan datamanager from tests

.github/workflows/pr.yaml, tools/aldex2/aldex2.xml
This reverts commit 356f921c6fb6b9c68f5df46510b23038fe1058fa.
merged on accident
=> Revert "Topic/bump test (#5068)"

tools/funannotate/.shed.yml, tools/funannotate/funannotate_compare.xml, tools/funannotate/funannotate_predict.xml, tools/funannotate/macros.xml
currently failing CI. tool tries to write other files next to the input.
=> fix funannotate predict

tools/ncbi_entrez_eutils/efetch.py, tools/ncbi_entrez_eutils/einfo.xml, tools/ncbi_entrez_eutils/eutils.py, tools/ncbi_entrez_eutils/macros.xml, tools/ncbi_entrez_eutils/test-data/pubmed.metadata.xml
use re_contains (indentation) of the xml changed
=> fix einfo test

tools/ggplot2/ggplot_point.xml
=> Add missing parentheses to ggplot2_point

tools/cherri/cherri_train.xml, tools/cherri/macros.xml
=> cherri update: add a separate temp directory for each train command

tools/sra-tools/macros.xml
Hello! This is an automated update of the following tool: **tools/sra-tools**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/sra-tools from version 3.0.0 to 3.0.3.
**Project home page:** https://github.com/ncbi/sra-tools/releases
=> Updating tools/sra-tools from version 3.0.0 to 3.0.3

data_managers/data_manager_gatk_picard_index_builder/tool_dependencies.xml, data_managers/data_manager_snpsift_dbnsfp/tool_dependencies.xml, tools/data_source_iris_tcga/tool_dependencies.xml
=> remove leftover tool_dependencies.xml

tools/krakentools/combine_kreports.xml, tools/krakentools/test-data/combined_kreport.tabular, tools/krakentools/test-data/only_combined_count.tabular
Add a wrapper for combine_kreports.py in [krakentools](https://github.com/jenniferlu717/KrakenTools) 
---
=> Add a wrapper for combine kreports tool

tools/picard/picard_CollectAlignmentSummaryMetrics.xml, tools/picard/picard_CollectBaseDistributionByCycle.xml, tools/picard/picard_CollectInsertSizeMetrics.xml, tools/picard/picard_MarkDuplicates.xml, tools/picard/picard_MarkDuplicatesWithMateCigar.xml, tools/picard/picard_MergeBamAlignment.xml, tools/picard/picard_SamToFastq.xml
=> increases max optical dup distance to  2x recommended for novaseq

data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.py, data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml, tools/metaphlan/macros.xml
a) Update metaphlan 4.0.3 -> 4.0.5
b) Update the data manager for the new metaphlan DB
c) Fix a bug in the current data manager: downloaded data is stored in a wrong data table.
=> metaphlan 4.0.5 + bug fix

tools/metaphlan/macros.xml
Hello! This is an automated update of the following tool: **tools/metaphlan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/metaphlan from version 4.0.3 to 4.0.5.
**Project home page:** https://github.com/biobakery/MetaPhlAn/releases
=> Updating tools/metaphlan from version 4.0.3 to 4.0.5

tools/hyphy/hyphy_slac.xml
=> Fix hyphy slac tolerances to prevent future issues on testing

tools/pbgcpp/tool-data/all_fasta.loc.sample, tools/pbgcpp/tool_data_table_conf.xml.sample
---
Trying to fix the deploy error from https://github.com/galaxyproject/tools-iuc/pull/5125#issuecomment-1451528450
=> add tool data table conf file

tools/pbgcpp/.shed.yml, tools/pbmm2/.shed.yml
=> Fix .shed.yml for pbgcpp

tools/cat/cat_add_names.xml, tools/cat/cat_bins.xml, tools/cat/cat_contigs.xml, tools/cat/cat_prepare.xml, tools/cat/cat_summarise.xml, tools/cat/macros.xml
Also this PR fixes a bug in cat bin.
=> Update CAT tools v5.0.3 -> 5.2.3

tools/rgrnastar/macros.xml, tools/rgrnastar/rg_rnaStarSolo.xml
This PR includes the changes requested by an user in https://help.galaxyproject.org/t/starsolo-spliced-and-unspliced-matrices/9514
=> Update STARSOLO: add Velocyto option

tools/ensembl_vep/ensembl_vep.xml
could not be resolved (some incompatibilities: 3.4 comes from bioconda 3.10 from conda-forge)
xref https://github.com/BioContainers/multi-package-containers/pull/2562
=> ensembl vep: fix requirements

.github/workflows/pr.yaml, tools/sansa/annotate.xml
size of bcf output changed when the container was updated to
quay.io/biocontainers/sansa:0.0.8--h4a2b439_2
so I added delta
=> sansa: fix tests

tools/metaphlan/macros.xml
Hello! This is an automated update of the following tool: **tools/metaphlan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/metaphlan from version 4.0.5 to 4.0.6.
**Project home page:** https://github.com/biobakery/MetaPhlAn/releases
=> Updating tools/metaphlan from version 4.0.5 to 4.0.6

data_managers/data_manager_humann_database_downloader/data_manager/data_manager_humann_download.xml, tools/humann/humann.xml, tools/humann/humann_barplot.xml, tools/humann/macros.xml
I revisited humann and it looks like it still works after the new DB release.
=> humann v 3.6.1

README.md
Added documentation and links to other Galaxy tool repositories
=> Added additional tool repositories

tools/dexseq/dexseq.R, tools/dexseq/dexseq.xml, tools/dexseq/dexseq_count.xml, tools/dexseq/macros.xml, tools/dexseq/plotdexseq.R, tools/dexseq/plotdexseq.xml
=> Dexseq update 1.28->1.44

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Target release_23.0

tools/pyega3/pyega3.xml
=> Update pyega version from 4.0.5 to 5.0.2

tool_collections/samtools/samtools_markdup/samtools_markdup.xml
=> samtools markdup: fix output action setting format

data_managers/data_manager_twobit_builder/data_manager/twobit_builder.py, data_managers/data_manager_twobit_builder/data_manager/twobit_builder.xml
=> add -long option to fa2twobit

tools/repeatmodeler/macros.xml, tools/repeatmodeler/repeatmodeler.xml
=> Update RepeatModeler v2.0.3 to v2.0.4

tools/repeatmasker/macros.xml, tools/repeatmasker/repeatmasker.xml, tools/repeatmasker/test-data/README.md, tools/repeatmasker/test-data/small.fasta.cat, tools/repeatmasker/test-data/small.fasta.gff, tools/repeatmasker/test-data/small.fasta.log, tools/repeatmasker/test-data/small.fasta.stats, tools/repeatmasker/test-data/small_dfam.fasta.cat, tools/repeatmasker/test-data/small_dfam.fasta.log, tools/repeatmasker/test-data/small_dfam.fasta.stats, tools/repeatmasker/test-data/small_dfam_rattus.fasta.cat, tools/repeatmasker/test-data/small_dfam_rattus.fasta.log, tools/repeatmasker/test-data/small_dfam_rattus.fasta.stats, tools/repeatmasker/test-data/small_dfam_up.fasta.cat, tools/repeatmasker/test-data/small_dfam_up.fasta.log, tools/repeatmasker/test-data/small_dfam_up.fasta.stats
First commit to check if non standard tool version is linted, xref https://github.com/galaxyproject/galaxy/issues/15945
=> RepeatMasker: update to 4.1.5

tools/humann/humann.xml, tools/humann/macros.xml, tools/humann/tool-data/metaphlan_database.loc.sample
https://github.com/biobakery/humann/commit/b2faa610982ca96b9bf49a661102c835df64585c suggests that at least some functionalities are hard coded to work with the new metaphlan DB.
(Instead of https://github.com/galaxyproject/tools-iuc/pull/5265#issuecomment-1518679480 ) 
=> Update humann 3.6.1 -> 3.7

tools/icescreen/icescreen.xml, tools/icescreen/test-data/NC_004668_137848_164286_detected_ME.summary, tools/icescreen/test-data/NC_013798_298468_322494_NC_020450_643089_661957_detected_ME.summary
=> update icescreen v1.2.0

.github/workflows/pr.yaml, tools/repeatmasker/macros.xml
xref https://github.com/galaxyproject/galaxy/pull/15962#issuecomment-1515169606
=> PR workflow: fail on warning

tools/cnvkit/call.xml, tools/cnvkit/reference.xml
=> last corrections to the CNVkit tool

tools/velocyto/velocyto_cli.xml
I just realized that with the initial wrapper it was not convenient to work with collections.
=> Update wrapper of velocyto to more easily work with collections

tools/isoformswitchanalyzer/IsoformSwitchAnalyzeR.R, tools/isoformswitchanalyzer/isoformswitchanalyzer.xml, tools/isoformswitchanalyzer/macros.xml
This PR fixes the following bugs:
- Salmon inputs: reference in FASTA format didn't work previously
- Volcano plot and MA-like plot fixes (previously not generated)
- Increased size of summary plots
- Figure Genome wide improved: include all splicing types
=> IsoformSwitchAnalyzeR: Fix bugs

tools/kallisto/kallisto_quant.xml, tools/kallisto/macros.xml
=> Update Kallisto: include missing datatypes and remove unnecesary conditional

tools/sleuth/sleuth.R
=> Sleuth fix linting

tools/gtdbtk/gtdbtk_classify_wf.xml, tools/gtdbtk/macros.xml
=> Fix gtdbtk outputs

tools/freyja/freyja_aggregate_plot.xml, tools/freyja/freyja_boot.xml, tools/freyja/freyja_demix.xml, tools/freyja/macros.xml
=> Freyja update to 1.4.4

tools/pangolin/pangolin.xml
=> Update pangolin to version 4.3

tools/pangolin/pangolin.xml
=> Fix typo disrupting pangoLEARN mode of pangolin

tools/bakta/bakta.xml
New bakta branch from the last main version
=> bakta 1.8.1 to pass github CI/CD

tools/coverm/coverm_contig.xml, tools/coverm/coverm_genome.xml, tools/coverm/macros.xml
=> CoverM: support for individual and co-assembly & wrapper restructuration

tools/amrfinderplus/macro.xml
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/amrfinderplus from version 3.11.14 to 3.11.17.
**Project home page:** https://github.com/ncbi/amr/releases
=> Updating tools/amrfinderplus from version 3.11.14 to 3.11.17

tools/pharokka/macros.xml, tools/pharokka/test-data/pharokka_db.loc, tools/pharokka/tool-data/pharokka_db.loc.sample, tools/pharokka/tool_data_table_conf.xml.sample, tools/pharokka/tool_data_table_conf.xml.test
Update tool to use data table with version column
=> Pharokka update

tools/dada2/dada2_removeBimeraDenovo.xml, tools/dada2/macros.xml, tools/dada2/test-data/gentest.R
supersedes https://github.com/galaxyproject/tools-iuc/pull/3370
=> Bump dada2 + some fixes

.github/workflows/ci.yaml, .github/workflows/pr.yaml
and clean dornet folder for consistency with weekly CI
=> bump CI workflows to 23.1

.github/workflows/pr.yaml, tools/ucsc_blat/blat.xml
=> Skip lint on merge

tool_collections/fastx_toolkit/fasta_clipping_histogram/fasta_clipping_histogram.xml, tool_collections/fastx_toolkit/fasta_formatter/fasta_formatter.xml, tool_collections/fastx_toolkit/fasta_nucleotide_changer/fasta_nucleotide_changer.xml, tool_collections/fastx_toolkit/fastq_quality_boxplot/fastq_quality_boxplot.xml, tool_collections/fastx_toolkit/fastq_quality_converter/fastq_quality_converter.xml, tool_collections/fastx_toolkit/fastq_quality_filter/fastq_quality_filter.xml, tool_collections/fastx_toolkit/fastq_to_fasta/fastq_to_fasta.xml, tool_collections/fastx_toolkit/fastx_artifacts_filter/fastx_artifacts_filter.xml, tool_collections/fastx_toolkit/fastx_barcode_splitter/fastx_barcode_splitter.xml, tool_collections/fastx_toolkit/fastx_clipper/fastx_clipper.xml, tool_collections/fastx_toolkit/fastx_collapser/fastx_collapser.xml, tool_collections/fastx_toolkit/fastx_nucleotides_distribution/fastx_nucleotides_distribution.xml, tool_collections/fastx_toolkit/fastx_quality_statistics/fastx_quality_statistics.xml, tool_collections/fastx_toolkit/fastx_renamer/fastx_renamer.xml, tool_collections/fastx_toolkit/fastx_reverse_complement/fastx_reverse_complement.xml, tool_collections/fastx_toolkit/fastx_trimmer/fastx_trimmer.xml, tool_collections/fastx_toolkit/macros.xml
Fixes https://github.com/galaxyproject/tools-iuc/issues/5412 by reverting to old macros.xml
=> Revert macros.xml

tools/tb_variant_filter/tb_variant_filter.xml
=> Update tb_variant_filter to version 0.4.0

tools/amrfinderplus/macro.xml
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/amrfinderplus from version 3.11.17 to 3.11.18.
**Project home page:** https://github.com/ncbi/amr/releases
=> Updating tools/amrfinderplus from version 3.11.17 to 3.11.18

tools/ensembl_vep/.shed.yml, tools/ensembl_vep/ensembl_vep.xml
=> Fix autoupdate Ensembl_vep 

tools/cojac/cooc_mutbamscan.xml, tools/cojac/cooc_tabmut.xml
=> cosmetic changes

tools/annotatemyids/annotateMyIDs.xml
=> Annotatemyids bt

tools/recentrifuge/macro.xml, tools/recentrifuge/recentrifuge.xml
update recentrifuge from 1.10.0 to 1.12.1
=> update recentrifuge to 1.12.1

tools/sra-tools/fasterq_dump.xml, tools/sra-tools/fastq_dump.xml, tools/sra-tools/macros.xml
=> sratools: make defline user configurable

tools/biom_format/biom_add_metadata.xml, tools/biom_format/biom_convert.xml, tools/biom_format/biom_from_uc.xml, tools/biom_format/biom_normalize_table.xml, tools/biom_format/biom_subset_table.xml, tools/biom_format/biom_summarize_table.xml, tools/biom_format/macros.xml
The `--collapsed-observations` and `--collapsed-samples` arguments were mixed up.
=> fixed some arguments(biom-convert)

tools/edger/edger.R, tools/edger/edger.xml
Makes the use of the tool compatible with newer r-base versions.
=> Update EdgeR to use non breaking way of passing contrasts with newer r-base versions

tools/ucsc_tools/fatovcf/.shed.yml, tools/ucsc_tools/fatovcf/fatovcf.xml
=> Add long_description #5388

tools/pycoqc/macros.xml, tools/pycoqc/pycoqc.xml
=> Add description for pycoqc

tools/amrfinderplus/macro.xml
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/amrfinderplus from version 3.11.18 to 3.11.20.
**Project home page:** https://github.com/ncbi/amr/releases
=> Updating tools/amrfinderplus from version 3.11.18 to 3.11.20

tools/pyega3/pyega3.xml
=> Fix urls in help

tools/hapog/hapog.xml
=> Hapo-G - Tool : Add different label to outputs

tools/edger/edger.R, tools/edger/edger.xml, tools/edger/test-data/contrasts_file.txt
This PR makes EdgeR fully workflow compatible by adding a contrasts file option. It also adds an optional formula field for more complex modelling.
=> Update EdgeR: Provide optional formula and contrasts file for multiple contrasts

tools/funannotate/funannotate_annotate.xml, tools/funannotate/funannotate_predict.xml, tools/funannotate/macros.xml
Potential workaround for #5527 
---
=> funannotate_annotate mv: target 'out.tbl' is not a directory - delete part files in large output datasets

tools/mzmine/.shed.yml, tools/mzmine/mzmine_batch.xml, tools/mzmine/test-data/test_small.xml
The MS community (or better the W4M repo) was unable to process this quite trivial tool: https://github.com/workflow4metabolomics/tools-metabolomics/pull/241. 
Guess we can just continue to add metabolomics tools over here. 
=> Add mzmine

tools/ribowaltz/macros.xml, tools/ribowaltz/ribowaltz.R, tools/ribowaltz/ribowaltz.xml, tools/ribowaltz/ribowaltz_plot.R, tools/ribowaltz/ribowaltz_plot.xml
=> update ribowaltz with an extra option

tools/phyml/phyml.xml, tools/phyml/test-data/phylip_phyml_stats.txt
=> Bump and improve phyml

tools/sra-tools/fastq_dump.xml, tools/sra-tools/macros.xml
https://github.com/galaxyproject/tools-iuc/issues/5540
=> Fix fastq-dump and sratools version update

tools/amrfinderplus/macro.xml
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/amrfinderplus from version 3.11.20 to 3.11.26.
**Project home page:** https://github.com/ncbi/amr/releases
=> Updating tools/amrfinderplus from version 3.11.20 to 3.11.26

tools/sra-tools/macros.xml
would suggest to skip ci (deployment) here.
=> sra-tools: remove unused attribute

tools/amrfinderplus/amrfinderplus.xml, tools/amrfinderplus/macro.xml
=> Add bio.tools for amrfinderplus

tools/icescreen/icescreen.xml, tools/kleborate/kleborate.xml, tools/proteinortho/proteinortho.xml, tools/proteinortho/proteinortho_grab_proteins.xml, tools/proteinortho/proteinortho_macros.xml, tools/proteinortho/proteinortho_summary.xml
=> Add biotools xref to icescreen, kleborate, proteinortho

tools/filtlong/filtlong.xml, tools/filtlong/macros.xml
=> add bio.tools entry

tools/ancombc/ancombc.xml, tools/ancombc/macros.xml
=> Add biotools for ancombc

tools/binning_refiner/binning_refiner.xml, tools/binning_refiner/macros.xml
=> Add biotools for binning_refiner

tools/clustalw/macros.xml, tools/clustalw/rgClustalw.xml
=> Add bio.tools 

tools/jellyfish/jellyfish.xml
=> Add bio.tools id for Jellyfish by editing xml 

tools/funannotate/funannotate_annotate.xml, tools/funannotate/funannotate_predict.xml, tools/funannotate/macros.xml
=> Add max_header_length to funannotate

tools/clustalw/macros.xml
=> fix bio.tools

tools/diamond/diamond.xml
=> Add bio.tool ID to diamond.xml

tools/fastp/fastp.xml, tools/fastp/macros.xml
=> Fastp: add bio.tools entry

tools/instrain/.shed.yml, tools/instrain/instrain_compare.xml, tools/instrain/instrain_profile.xml, tools/instrain/macros.xml
=> Replace EDAM by biotools for instrain

tools/pick_value/.shed.yml, tools/pick_value/pick_value.xml, tools/pick_value/test-data/simple_line.txt, tools/pick_value/test-data/simple_line_alternative.txt
I think this will see a good deal of use in combination with conditional workflow steps, and this will allow us to make changes more easily and in a versioned way.
=> Export pick_value expression tool from Galaxy codebase

tools/metabat2/macros.xml, tools/metabat2/metabat2.xml
=> Add biotools for MetaBAT2

tools/semibin/bin.xml, tools/semibin/concatenate_fasta.xml, tools/semibin/generate_cannot_links.xml, tools/semibin/generate_sequence_features.xml, tools/semibin/macros.xml, tools/semibin/semibin.xml, tools/semibin/train.xml
=> upgrade from SemiBin to SemiBin2

tools/concoct/concoct.xml, tools/concoct/concoct_coverage_table.xml, tools/concoct/cut_up_fasta.xml, tools/concoct/extract_fasta_bins.xml, tools/concoct/macros.xml, tools/concoct/merge_cut_up_clustering.xml
=> Add biotools for CONCOCT

tools/edger/edger.R, tools/edger/edger.xml, tools/edger/test-data/contrasts_file.txt
Improves some case handling when using complex contrasts.
Deals with #5548
=> Fix EdgeR: Sanitise base name for files when coming from contrasts or factors

tools/megahit/megahit_wrapper.xml
otherwise, it will use 90% of the available memory which does not work in HPC
=> Give megahit info on available memory 

tools/baredsc/baredsc_combine_2d.xml, tools/baredsc/macros.xml
=> Update baredSC: implement new parameter for combined_2d: getPVal

tools/blast/macros.xml, tools/blast/magicblast.xml
=> Fix magicblast when output format is tabular

tools/funannotate/funannotate_annotate.xml, tools/funannotate/macros.xml
=> multiple output from funannotate_annotate

tools/sceasy/sceasy.xml
Fix to SCEasy tool where dataset inputs weren't being detected properly within a <when> clause. Bug report here: https://github.com/galaxyproject/galaxy/issues/17160
Thanks to @wee-snufkin for spotting and testing.
Related: https://github.com/galaxyproject/training-material/issues/4566
=> Fix to SCEasy tool

tools/diffbind/diffbind.R, tools/diffbind/diffbind.xml
of https://github.com/galaxyproject/tools-iuc/issues/5632
we could also be more strict and check equality of the names, i.e. the names of the i-th element of the peaks data and  the i-th element of the bam data need to be equal. But this requires changes to the tests: file names need to become equal in the test data .. or we restrict/switch to collection inputs  (maybe its sufficient to use collections)
=> diffbind: first idea for a fix

tools/jellyfish/jellyfish.xml
=> jellyfish size parameter needs a unit

.github/workflows/pr.yaml
Got tired of downloading artifacts. So I copy pasted from IWC :) 
Example here: https://github.com/bernt-matthias/tools-iuc/pull/105#issuecomment-1885822466
=> Post test resuts markdown to PR

tools/polypolish/macro.xml, tools/polypolish/polypolish.xml
I updated the samtools tools from 1.13 to 1.19 and add the multi threading option to increase efficacity
=> Polypolish update dependencies

.github/workflows/pr.yaml
Just learned that comments to PR are not working for PR opened from branches. IWC just discusses/explores possibilities. So maybe just leave the code for now....
=> Print summary below the artifacts

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Update python version to 3.11 and galaxy branch to 23.2

.github/workflows/pr.yaml
=> Remove comment stuff, fix posting test reports when test(s) actually failed

tools/bwa/bwa-mem.xml
=> add collection test to bwa-mem

tools/proteinortho/proteinortho.xml, tools/proteinortho/proteinortho_macros.xml
=> proteinortho: update version

tools/trimmomatic/trimmomatic.xml, tools/trimmomatic/trimmomatic_macros.xml
* [x ] - This PR updates an existing tool or tool collection
Fixes https://github.com/galaxyproject/tools-iuc/issues/5703 by adding `default_identifier_source` to outputs.
=> Fix trimmomatic outputs

tools/isescan/isescan.xml, tools/isescan/macro.xml
I forgot in the first wrapper to add the label information to each outputs...
=> isescan: add the label information for file outputs

tools/hapog/hapog.xml
=> Update Hapo-G from 1.3.6 to 1.3.7

tools/hamronization/hamronize_summarize.xml, tools/hamronization/hamronize_tool.xml, tools/hamronization/macros.xml
=> Add biotools for hamronization

tools/icescreen/icescreen.xml
=> Add biotools for icescreen

tools/hifiasm_meta/hifiasm_meta.xml
=> Add biotools for hifiasm-meta

tools/graphlan/.shed.yml, tools/graphlan/graphlan.xml, tools/graphlan/graphlan_annotate.xml, tools/graphlan/graphlan_macros.xml
=> Add biotools for graphlan

tools/export2graphlan/.shed.yml, tools/export2graphlan/export2graphlan.xml
=> Add biotools for export2graphlan

tools/fargene/fargene.xml
=> Add biotools for fargene

tools/fastqe/.shed.yml, tools/fastqe/fastqe.xml
=> Add biotools for fastqe

tools/dram/dram_annotate.xml, tools/dram/dram_distill.xml, tools/dram/dram_merge_annotations.xml, tools/dram/dram_neighborhoods.xml, tools/dram/dram_strainer.xml, tools/dram/macros.xml
=> Add biotools for DRAM

tools/biom_format/biom_add_metadata.xml, tools/biom_format/biom_convert.xml, tools/biom_format/biom_from_uc.xml, tools/biom_format/biom_normalize_table.xml, tools/biom_format/biom_subset_table.xml, tools/biom_format/biom_summarize_table.xml, tools/biom_format/macros.xml
=> Add biotools for biomformat

tools/picrust/categorize_by_function.xml, tools/picrust/compare_biom.xml, tools/picrust/format_tree_and_trait_table.xml, tools/picrust/macros.xml, tools/picrust/metagenome_contributions.xml, tools/picrust/normalize_by_copy_number.xml, tools/picrust/predict_metagenomes.xml
=> Add biotools to picrust

tools/gtdbtk/gtdbtk_classify_wf.xml
=> Add biotools to GTDB-Tk

tools/phyloseq/macros.xml, tools/phyloseq/phyloseq_from_dada2.xml, tools/phyloseq/phyloseq_plot_ordination.xml, tools/phyloseq/phyloseq_plot_richness.xml
=> Add biotools to phyloseq

tool_collections/kraken2/kraken2/kraken2.xml
=> Add biotools to kraken2

tools/metaphlan/macros.xml, tools/metaphlan/merge_metaphlan_tables.xml, tools/metaphlan/test-data/SRS014464-Anterior_nares-abundances-samefiledifferentname.tabular
Requested by @mthang for column header issue #5224
=> metaphlan column header issue

.github/workflows/ci.yaml, .github/workflows/pr.yaml, tools/aegean/canongff3.xml, tools/aegean/gaeval.xml, tools/aegean/locuspocus.xml, tools/aegean/macros.xml, tools/aegean/parseval.xml
=> Bump github actions

tools/spades/biosyntheticspades.xml, tools/spades/coronaspades.xml, tools/spades/macros.xml, tools/spades/metaplasmidspades.xml, tools/spades/metaspades.xml, tools/spades/metaviralspades.xml, tools/spades/plasmidspades.xml, tools/spades/rnaspades.xml, tools/spades/rnaviralspades.xml, tools/spades/spades.xml
=> Add biotools for spades tools

tools/rgrnastar/macros.xml
Sorry @lldelisle @bgruening I didn't mean to change this.
=> rgrnastar restore IDX_VERSION_SUFFIX

tools/cat/cat_add_names.xml, tools/cat/cat_bins.xml, tools/cat/cat_contigs.xml, tools/cat/cat_prepare.xml, tools/cat/cat_summarise.xml, tools/cat/macros.xml
=> Add biotools to CAT

tools/multigsea/macros.xml, tools/multigsea/multiGSEA.R, tools/multigsea/multigsea.xml
=> Bump multigsea

tools/rasusa/rasusa.xml
=> update rasusa with default values to subsmaple

tools/rasusa/rasusa.xml
=> add values for all non-optional params

tools/gtdbtk/gtdbtk_classify_wf.xml, tools/gtdbtk/macros.xml, tools/gtdbtk/test-data/gtdbtk_database.loc
Tested this locally on our cluster.
=> bump gtdbtk

tools/cnv-phenopacket/.shed.yml, tools/cnv-phenopacket/cnv-phenopacket.xml, tools/cnv-phenopacket/csv2xlsx.xml, tools/cnv-phenopacket/macros.xml, tools/cnv-phenopacket/test-data/igsr-1000-genomes-30x-on-grch38.tsv, tools/cnv-phenopacket/test-data/phenopacket.json
=> Add cnv phenopacket tool

tools/deepvariant/deepvariant.xml, tools/deepvariant/macros.xml
=> case-sensitive datatypes

tools/hamronization/hamronize_summarize.xml, tools/hamronization/hamronize_tool.xml, tools/hamronization/macros.xml, tools/hamronization/test-data/mykrobe/mykrobe.json
- Update to the new version
- Add missing supported tools
- Use tool-based conditions in inputs
- Use input metadata for tools available in Galaxy
- Use `change_format` for output instead of filter and tests
- Update tests
=> Update hAMRonization wrapper

tools/abritamr/abritamr.xml
=> Add bio.tools for abriTAMR

tools/nanoplot/nanoplot.xml, tools/nanoplot/test-data/NanoStats.txt, tools/nanoplot/test-data/NanoStats_post_filtering.txt
Hello! This is an automated update of the following tool: **tools/nanoplot**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/nanoplot from version 1.41.0 to 1.41.3.
**Project home page:** https://github.com/wdecoster/NanoPlot/releases
=> Updating tools/nanoplot from version 1.41.0 to 1.42.0

tools/omark/macros.xml, tools/omark/omark.xml, tools/omark/test-data/omamer.loc, tools/omark/tool-data/omamer.loc.sample
Fixing problems identified while testing on real data
=> Omark fixes

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> bump workflows to 24.0

tools/valet/valet.xml
=> Update bio.tools xref for valet.xml

tools/miniasm/miniasm.xml
This PR links miniasm to its  bio.tools [entry](https://bio.tools/miniasm).
=> Added bio.tools ref to miniasm

tools/plasflow/plasflow.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/plasflow
=> Add bio.tools for PlasFlow

tools/miniprot/macros.xml, tools/miniprot/miniprot.xml, tools/miniprot/miniprot_index.xml
This PR links miniprot to its bio.tools [entry](https://bio.tools/miniprot).
=> Added bio.tools ref to miniprot

tools/pycoqc/macros.xml, tools/pycoqc/pycoqc.xml
This PR links pycoqc to its bio.tools [entry](https://bio.tools/pycoqc).
=> Added bio.tools ref to pycoqc

tools/seqsero2/macros.xml, tools/seqsero2/seqsero2.xml
This PR links seqsero2 to its bio.tools [entry](https://bio.tools/SeqSero2).
=> Added bio.tools ref to seqsero2

tools/ivar/macros.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/ivar
=> Add bio.tools for ivar

tools/kraken_biom/.shed.yml, tools/kraken_biom/macros.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/kraken-biom
=> Add bio.tools for kraken-biom

tools/scoary/.shed.yml, tools/scoary/scoary.xml
This PR links scoary to its bio.tools [entry](https://bio.tools/scoary).
=> Added bio.tools ref to scoary

tools/kraken_taxonomy_report/kraken_taxonomy_report.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/kraken-taxonomy-report
=> Add bio.tools for kraken taxonomy report

tools/pygenometracks/macros.xml, tools/pygenometracks/pyGenomeTracks.xml
This PR links pygenometracks to its bio.tools [entry](https://bio.tools/pygenometracks).
=> Added bio.tools ref to pygenometracks

tools/krocus/krocus.xml, tools/krocus/macros.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/krocus
=> Add bio.tool for krocus

tools/lorikeet/lorikeet.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/lorikeet
=> add bio.tools for lorikeet

tools/sonneityping/parse_mykrobe_predict.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/sonneityping
=> add bio.tools

tool_collections/kraken/kraken-filter.xml, tool_collections/kraken/kraken-mpa-report.xml, tool_collections/kraken/kraken-report.xml, tool_collections/kraken/kraken-translate.xml, tool_collections/kraken/kraken.xml, tool_collections/kraken/macros.xml
This PR links kraken to its bio.tools [entry](https://bio.tools/kraken).
=> Add bio.tools ref to kraken

tools/qiime/qiime_add_on/collapse_samples.xml, tools/qiime/qiime_add_on/make_otu_table.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/qiime_add_on
=> add bio.tools for qiime_add_on

tools/maaslin2/maaslin2.xml, tools/maaslin2/macros.xml
This PR links maaslin2 to its bio.tools [entry](https://bio.tools/maaslin2).
=> Add bio.tools ref to maaslin2

tools/meningotype/meningotype.xml
This PR links meningotype to its bio.tools [entry](https://bio.tools/meningotype).
=> Add bio.tools ref to meningotype

tools/nanopolishcomp/eventaligncollapse.xml, tools/nanopolishcomp/freqmethcalculate.xml, tools/nanopolishcomp/macros.xml
This PR links nanopolishcomp to its bio.tools [entry](https://bio.tools/nanopolishcomp).
=> Add bio.tools ref to nanopolishcomp

tools/crispr_studio/crispr_studio.xml
This PR links crisprstudio to its bio.tools [entry](https://bio.tools/crisprstudio).
=> Add bio.tools ref to crisprstudio

tool_collections/biotradis/bacteria_tradis.xml, tool_collections/biotradis/macros.xml, tool_collections/biotradis/tradis_essentiality.xml, tool_collections/biotradis/tradis_gene_insert_sites.xml
This PR links biotradiis to its bio.tools [entry](https://bio.tools/biotradis).
=> Add bio.tools ref to biotradis

tool_collections/bamtools/bamtools/bamtools.xml, tool_collections/bamtools/bamtools_filter/bamtools-filter.xml, tool_collections/bamtools/bamtools_split/.shed.yml, tool_collections/bamtools/bamtools_split/bamtools_split_mapped.xml, tool_collections/bamtools/bamtools_split/bamtools_split_paired.xml, tool_collections/bamtools/bamtools_split/bamtools_split_ref.xml, tool_collections/bamtools/bamtools_split/bamtools_split_tag.xml, tool_collections/bamtools/macros.xml
This PR links bamtools to its bio.tools [entry](https://bio.tools/bamtools).
=> Add bio.tools to bamtools

.github/PULL_REQUEST_TEMPLATE.md
=> Remove the extra list in the PR template

tools/usher/macros.xml, tools/usher/matutils.xml, tools/usher/usher.xml
This PR links usher to its bio.tools [entry](https://bio.tools/usher).
=> Replace EDAM by bio.tools in usher

tools/omark/omark.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/omark
=> Add bio.tools for OMArk

tools/red/red.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/red
=> add bio.tools for Red

tools/compleasm/compleasm.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/compleasm
=> Add bio.tools for compleasm

tools/repeatmodeler/repeatmodeler.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/repeatmodeler
=> add bio.tools for repeatmodeler

tools/tsebra/tsebra.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/tsebra
=> add bio.tools for tsebra

tools/cutadapt/cutadapt.xml, tools/cutadapt/macros.xml
replace [planemo-autoupdate/tools/cutadapt](https://github.com/galaxyproject/tools-iuc/pull/5880)
wondering if we can allow IUC members to push to the  planemo-autoupdate repo?
=> Updating tools/cutadapt to 4.7

.github/workflows/ci.yaml
and skip more linters (we only want the biocontainers check here)
=> weekly CI: show summary

tools/mitos/mitos.xml, tools/mitos/mitos2.xml, tools/mitos/test-data/NC_012920.seq, tools/mitos/test-data/mitos2_NC_012920.seq
=> bump mitos

tools/colabfold/colabfold_alphafold.xml
Adds optional=true" for num models, which was causing deployment issues
=> fix deployment issue with colabfold

tools/pangolin/pangolin.xml
=> Update pangolin dependencies and add bio.tools xref

tools/varvamp/macros.xml, tools/varvamp/varvamp.xml
=> Update varVAMP to version 1.1.2

tools/seqsero2/macros.xml, tools/seqsero2/seqsero2.xml
=> update Seqsero2 test

tools/chopin2/chopin2.xml, tools/chopin2/macros.xml, tools/chopin2/test-data/selection.txt, tools/chopin2/test-data/summary.txt, tools/chopin2/test-data/summary_1.txt, tools/chopin2/test-data/summary_2.txt, tools/chopin2/test-data/summary_3.txt
BUMP the version, fixed linting error and updated test data 
https://github.com/cumbof/chopin2/releases/tag/1.0.8
> This releases fixes a major bug in the generation of random level vectors.
Using previous versions of chopin2 is highly discouraged!
=> Chopin 1.0.8 - Fixed linting error and updated test data 

tools/spades/macros.xml, tools/spades/spades.xml
=> spades: set tmp dir

tools/varvamp/macros.xml
=> Update varVAMP to latest release

tools/mitos/mitos.xml, tools/mitos/mitos2.xml, tools/mitos/test-data/mitos2_NC_012920.gff
https://help.galaxyproject.org/t/mitos-2-yeast-genetic-code/12281/2
=> mitos2: add missing genetic codes

tools/mosdepth/mosdepth.xml, tools/mosdepth/test-data/output_region_distribution.tabular, tools/mosdepth/test-data/output_region_distribution_median.tabular
Hi,
This PR is linked with https://github.com/galaxyproject/tools-iuc/pull/5991 for updating the mosdepth tool. In the current PR, the test dataset was updated as per the newer tool version.
Cheers,
Saim
=> Version update of mosdepth tool along with updated test datasets

tools/varvamp/macros.xml, tools/varvamp/varvamp.xml
=> Update varVAMP to v1.2.0

tools/stringtie/macros.xml, tools/stringtie/stringtie.xml, tools/stringtie/stringtie_merge.xml, tools/stringtie/test-data/stringtie_merge_out1.gtf, tools/stringtie/test-data/stringtie_merge_out2.gtf, tools/stringtie/test-data/stringtie_out10.gtf, tools/stringtie/test-data/stringtie_out11.gtf, tools/stringtie/test-data/stringtie_out1_re.gtf, tools/stringtie/test-data/stringtie_out2_re.gtf, tools/stringtie/test-data/stringtie_out3_re.gtf, tools/stringtie/test-data/stringtie_out4_re.gtf, tools/stringtie/test-data/stringtie_out5.gtf, tools/stringtie/test-data/stringtie_out6.gtf, tools/stringtie/test-data/stringtie_out8.gtf, tools/stringtie/test-data/stringtie_out9.gtf
=> Updated stringtie version and test data

tools/fastk/fastk.xml, tools/fastk/macros.xml
=> FastK: Added ktab files to output and minor changes

tools/fastk/fastk.xml, tools/fastk/macros.xml
=> FASTK: MInor changes to tool

tools/bigscape/bigscape.xml
=> Add bio.tools to big-scape

tools/fastani/.shed.yml, tools/fastani/fastani.xml, tools/fastani/macros.xml
=> Add bio.tools for FastANI

tools/bbtools/bbduk.xml, tools/bbtools/bbmap.xml, tools/bbtools/bbmerge.xml, tools/bbtools/bbnorm.xml, tools/bbtools/callvariants.xml, tools/bbtools/macros.xml, tools/bbtools/tadpole.xml
=> Add bio.tools xref

tools/dimet/dimet_abundance_plot.xml, tools/dimet/dimet_differential_analysis.xml, tools/dimet/dimet_isotopologues_plot.xml, tools/dimet/dimet_metabologram.xml, tools/dimet/macros.xml
=> Update dimet description

tools/snapatac2/dimension_reduction_clustering.xml, tools/snapatac2/macros.xml, tools/snapatac2/peaks_and_motif_analysis.xml, tools/snapatac2/plotting.xml, tools/snapatac2/preprocessing.xml
=> Update SanpATAC2 tools, add peak analysis functions

tools/dada2/dada2_dada.xml, tools/dada2/dada2_mergePairs.xml, tools/dada2/macros.xml
as discussed with @bebatut 
also bumps
=> Dada2 add output

tools/ncbi_fcs_gx/macros.xml, tools/ncbi_fcs_gx/ncbi_fcs_gx.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/ncbi_fcs
Thanks!
=> Add bio.tools for ncbi_fcs_gx

tools/tbvcfreport/tbvcfreport.xml, tools/tbvcfreport/test-data/rif_resistant.vcf, tools/tbvcfreport/test-data/rif_resistant_drug_resistance_report.html, tools/tbvcfreport/test-data/rif_resistant_drug_resistance_report.txt, tools/tbvcfreport/test-data/rif_resistant_variants_report.html, tools/tbvcfreport/test-data/rif_resistant_variants_report.txt, tools/tbvcfreport/test-data/rif_resistant_variants_report_with_lineage.html, tools/tbvcfreport/test-data/rif_resistant_variants_report_with_lineage.txt, tools/tbvcfreport/test-data/vcf_with_no_protein_report.html, tools/tbvcfreport/test-data/vcf_with_no_protein_report.txt
=> Update tbvcfreport to version 1.0.0

tools/orfipy/macros.xml, tools/orfipy/orfipy.xml
=> Orfipy: add --longest pram as requested by a user

tools/cami_amber/.shed.yml
=> Update .shed.yml for cami-amber tools

tools/metabuli/metabuli.xml
=> Add bio.tools to metabuli

tools/volcanoplot/volcanoplot.xml
=> Fix doi for volcanoplot tool

data_managers/data_manager_fetch_plasmidfinder/data_manager/macro.xml, data_managers/data_manager_fetch_plasmidfinder/tool_data_table_conf.xml.sample
discovered by @natefoo ... is that the proper fix? Probably needs a bump.
=> fix DM of plasmidfiner?

tools/ncbi_datasets/datasets_gene.xml, tools/ncbi_datasets/datasets_genome.xml, tools/ncbi_datasets/macros.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/6056
=> ncbi datasets: update

tools/tbvcfreport/tbvcfreport.xml
=> Update tbvcfreport to 1.0.1

tools/hgvsparser/.shed.yml, tools/hgvsparser/buildHGVS.R, tools/hgvsparser/hgvsparser.xml, tools/hgvsparser/parseHGVS.R, tools/hgvsparser/test-data/inputBuilder.csv, tools/hgvsparser/test-data/inputParser.csv
=> add hgvsparser

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
=> kraken2 data manager: fix date

data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml
Just copy pasted the names from http://cmprod1.cibio.unitn.it/biobakery4/metaphlan_databases/
fixes https://github.com/galaxyproject/tools-iuc/issues/4997 https://github.com/galaxyproject/tools-iuc/issues/5002 ?
=> add new reference data to metaphlan DM

tools/integron_finder/macro.xml, tools/integron_finder/test-data/integron_log, tools/integron_finder/test-data/summary.tsv, tools/integron_finder/test-data/test10_integrons_table.tsv, tools/integron_finder/test-data/test1_integrons_table.tsv, tools/integron_finder/test-data/test2_integrons_table.tsv, tools/integron_finder/test-data/test3_integrons_table.tsv, tools/integron_finder/test-data/test4_integrons_table.tsv, tools/integron_finder/test-data/test5_integrons_table.tsv, tools/integron_finder/test-data/test6_integrons_table.tsv, tools/integron_finder/test-data/test7_integrons_table.tsv, tools/integron_finder/test-data/test8_integrons_table.tsv, tools/integron_finder/test-data/test9_integrons_table.tsv, tools/integron_finder/test-data/test9_summary.tsv
This PR is concerned with https://github.com/galaxyproject/tools-iuc/pull/6070. Only test dataset was updated.
=> Updated the test data tools/integron finder

tools/aldex2/aldex2.xml
=> Aldex2: Allow larger diff

tools/varvamp/macros.xml, tools/varvamp/varvamp.xml
=> Remove arbitrary upper limits on some qPCR parameters

tools/falco/falco.xml
Falco was not working with compressed FASTQ (fastq.gz), so I updated a bit of code, Should work fine now.
=> accept fastq.gz

tools/chopin2/macros.xml, tools/chopin2/test-data/selection.txt, tools/chopin2/test-data/summary.txt, tools/chopin2/test-data/summary_3.txt
This PR fix the issue in [@cumbof/chopin2/issues/1](https://github.com/cumbof/chopin2/issues/1)
=> Update chopin2 tool and fix test-data

tools/tb-profiler/tb_profiler_profile.xml
=> Relax profile requirements for `tb_profiler_profile` tool

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Bump workflows to 24.1

tools/ivar/macros.xml
=> Update ivar to version 1.4.3, fix bio.tools link

tools/query_tabular/.shed.yml, tools/query_tabular/filter_tabular.xml, tools/query_tabular/filters.py, tools/query_tabular/load_db.py, tools/query_tabular/macros.xml, tools/query_tabular/query_tabular.xml, tools/query_tabular/sqlite_to_tabular.xml
Fixes
https://sentry.galaxyproject.org/share/issue/2fdb36e276fd4e21889ced01da9683da/:
```
NotFound: cannot find 'tbl'
File "galaxy/jobs/runners/__init__.py", line 297, in prepare_job
job_wrapper.prepare()
File "galaxy/jobs/__init__.py", line 1260, in prepare
) = tool_evaluator.build()
File "galaxy/tools/evaluation.py", line 586, in build
global_tool_logs(self._build_config_files, config_file, "Building Config Files")
File "galaxy/tools/evaluation.py", line 98, in global_tool_logs
raise e
File "galaxy/tools/evaluation.py", line 94, in global_tool_logs
return func()
File "galaxy/tools/evaluation.py", line 658, in _build_config_files
self.__write_workdir_file(config_filename, config_text, param_dict, is_template=is_template)
File "galaxy/tools/evaluation.py", line 791, in …
```
=> Fix filter_tabular tool if ``skip_lines`` is left unset

tools/falco/falco.xml
- Mention FastQC in the description to make the tool findable when searching for the original
- Add information about advantages and current limitations compared to FastQC to help section
- Do not produce the results summary file by default, but only on demand
- Simplify symlinking
=> Improve the Falco wrapper

tools/snapatac2/macros.xml, tools/snapatac2/preprocessing.xml
=> Fix SnapATAC2 gene activity matrix bug

tools/qualimap/.shed.yml, tools/qualimap/qualimap_bamqc.xml, tools/qualimap/qualimap_counts.xml, tools/qualimap/qualimap_macros.xml, tools/qualimap/qualimap_multi_bamqc.xml, tools/qualimap/qualimap_rnaseq.xml
For @wm75 to fix the versions mess.
=> udpate qualimap

tools/mg_toolkit/.shed.yml
=> Update mg_toolkit .shed.yml

tools/bcftools/bcftools_call.xml, tools/bcftools/bcftools_cnv.xml, tools/bcftools/bcftools_consensus.xml, tools/bcftools/bcftools_convert_from_vcf.xml, tools/bcftools/bcftools_gtcheck.xml, tools/bcftools/bcftools_plugin_color_chrs.xml, tools/bcftools/bcftools_stats.xml, tools/bcftools/macros.xml
=> Fix ection typo in bcftools_gtcheck

tools/snapatac2/macros.xml, tools/snapatac2/peaks_and_motif_analysis.xml, tools/snapatac2/preprocessing.xml
=> Update snapatac2 to 2.6.4

tools/cnv-vcf2json/cnv-vcf2json.xml, tools/cnv-vcf2json/macros.xml, tools/cnv-vcf2json/test-data/output.json
=> update cnv-vcf2json tool version

tools/compleasm/compleasm.xml
Based on tool update request by @Delphine-L, this PR concerns with addition of the `threads` parameter to the compleasm tool wrapper.
=> Added threads parameter to compleasm tool

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> ci.yaml and pr.yaml update

tools/roary/roary.xml
xref: https://github.com/galaxyproject/tools-iuc/issues/5751
=> add -z option to roary

tools/bcftools/bcftools_mpileup.xml
=> fix for 6204

tools/basil/all_fasta.loc.sample, tools/basil/basil.xml, tools/basil/test-data/all_fasta.loc.test, tools/basil/tool_data_table_conf.xml.sample, tools/basil/tool_data_table_conf.xml.test
=> add new reference genomes

tools/bigscape/bigscape.xml, tools/bigscape/test-data/NC_012963.1.region001.no-genbank-suffix
fixes: https://github.com/galaxyproject/tools-iuc/issues/6015
=> add explicit gbk suffix

tools/pear/.shed.yml, tools/pear/pear.xml
maybe related to https://github.com/galaxyproject/tools-iuc/issues/6176
=> udpate, fix pear

tools/picrust2/macros.xml, tools/picrust2/place_seqs.xml
=> Fixed minor linting issue in picrust2

tools/fastp/fastp.xml, tools/fastp/macros.xml
--detect_adapter_for_pe option does not have to be the default if nothing else is used.
=> Update fastp wrapper

data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.py
=> Change the url to the right files in gtdbtk DM

data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.py, data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml
This PR adds:
* a test case that checks all URLs used if they exist
* more explicit distinction between metadata and main DB
* Test case for both metadata types as spotted here: https://github.com/galaxyproject/tools-iuc/pull/6242
=> Update GTDB-tk DM

tools/nanoplot/nanoplot.xml, tools/nanoplot/test-data/NanoStats.txt, tools/nanoplot/test-data/NanoStats_post_filtering.txt
Fixes: https://github.com/galaxyproject/tools-iuc/pull/6224
=> Updated test data for nanoplot

tools/cemitool/CEMiTool.R, tools/cemitool/cemitool.xml, tools/cemitool/macros.xml
=> added beta parameter to cemitool

tools/beacon2-import/analyses.xml, tools/beacon2-import/biosamples.xml, tools/beacon2-import/bracket.xml, tools/beacon2-import/cnv.xml, tools/beacon2-import/cohorts.xml, tools/beacon2-import/datasets.xml, tools/beacon2-import/gene.xml, tools/beacon2-import/import.xml, tools/beacon2-import/individuals.xml, tools/beacon2-import/macros.xml, tools/beacon2-import/range.xml, tools/beacon2-import/runs.xml, tools/beacon2-import/sequence.xml
=> update cnv tool and forward the test to test collection

tools/iqtree/iqtree.xml, tools/iqtree/iqtree_macros.xml
=> Update iqtree and fix some options

tools/colabfold/colabfold_alphafold.xml, tools/colabfold/colabfold_msa.xml, tools/colabfold/macros.xml
* Make the a3m output of `colabfold_alphafold` a collection (from @astrovsky01)
* Allow for admins to add arbitrary params (e.g. `--host-url http://msa.example.org`) to `colabfold_msa` with the `$COLABFOLD_EXTRA_OPTIONS` env var
=> Small ColabFold updates

tools/add_input_name_as_column/add_input_name_as_column.py, tools/column_order_header_sort/column_order_header_sort.py, tools/cwpair2/cwpair2.py, tools/cwpair2/cwpair2_util.py, tools/ebi_tools/ebeye_urllib.py, tools/extract_genomic_dna/extract_genomic_dna.py, tools/repmatch_gff3/repmatch_gff3_util.py, tools/tn93/tn93_cluster.py, tools/vsnp/vsnp_determine_ref_from_data.py
=> Fix all flake8 linter problems

tools/virheat/macros.xml, tools/virheat/virheat.xml
=> VirHEAT: fix error when no .vcf in samplename

tools/rnaquast/macros.xml, tools/rnaquast/rna_quast.xml
=> Fix _ Upgrade rna quast

tools/crossmap/crossmap_bam.xml, tools/crossmap/crossmap_bed.xml, tools/crossmap/crossmap_bigwig.xml, tools/crossmap/crossmap_gff.xml, tools/crossmap/crossmap_region.xml, tools/crossmap/crossmap_vcf.xml, tools/crossmap/crossmap_wig.xml, tools/crossmap/macros.xml
Hello! This is an automated update of the following tool: **tools/crossmap**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/crossmap from version 0.6.1 to 0.6.3.
**Project home page:** http://crossmap.sourceforge.net
=> Updating tools/crossmap from version 0.6.1 to 0.7.0

tools/edger/edger.xml
analogous to what we do in the matrix case of the conditional. using a validator seems also favourable compared to silently changing factor names
fixes https://github.com/galaxyproject/tools-iuc/issues/6297
=> edger: use validators for factor name

data_managers/data_manager_gtdbtk_database_installer/data_manager/gtdbtk_database_installer.xml
=> Bump gtdbtk DM version

tools/anndata/.shed.yml, tools/baredsc/.shed.yml, tools/cite_seq_count/.shed.yml, tools/cosg/.shed.yml, tools/dropletutils/.shed.yml, tools/episcanpy/.shed.yml, tools/raceid/.shed.yml, tools/scanpy/.shed.yml, tools/scater/.shed.yml, tools/sceasy/.shed.yml, tools/schicexplorer/.shed.yml, tools/scpipe/.shed.yml, tools/seurat/.shed.yml, tools/sinto/.shed.yml, tools/snapatac2/.shed.yml, tools/umi_tools/.shed.yml, tools/velocyto/.shed.yml
Adding the "Single Cell" shed category to all the single-cell tools. The tests will fail because there is no shed category in Planemo yet. Waiting for the planemo update.
=> Add Single Cell category to all single-cell tools

tools/microsatbed/microsatbed.xml
=> bump pytrf version in microsatbed

tools/spapros/.shed.yml, tools/spapros/evaluation.xml, tools/spapros/selection.xml
=> Fixing spapros wrapper

tools/gtdbtk/gtdbtk_classify_wf.xml, tools/gtdbtk/macros.xml
=> Fix the filter for the GTDB-Tk version

tools/scanpy/inspect.xml, tools/scanpy/macros.xml
=> Scanpy fix a bug with tl.rank_genes_groups method

tools/metaphlan/metaphlan.xml
I suppose that's what you were going for in 08789338233fab7f29d24c16f910fb3e7c8692d0 @bernt-matthias ?
=> Fix paired non-collection input symlink in metaphlan

tools/arriba/.lint_skip, tools/arriba/arriba.xml, tools/arriba/macros.xml
- the stars seemed to make no sense
- add $ to check whole text
=> arriba fix validator

tools/structureharvester/.lint_skip, tools/structureharvester/structureharvester.xml
=> fix linter errors for structure harvester

tools/checkm/.lint_skip
=> checkm: remove unneeded lint skip

tools/ggplot2/.lint_skip, tools/ggplot2/ggplot2_heatmap.xml, tools/ggplot2/ggplot2_pca.xml, tools/ggplot2/ggplot_histogram.xml, tools/ggplot2/ggplot_point.xml, tools/ggplot2/ggplot_violin.xml, tools/ggplot2/macros.xml
=> Linter fixes for ggplot

tool_collections/vcflib/vcffilter/.lint_skip, tool_collections/vcflib/vcffilter/vcffilter.xml, tool_collections/vcflib/vcfsort/.lint_skip, tool_collections/vcflib/vcfsort/vcfsort.xml
=> Linter fixes for vcflib

tools/khmer/.lint_skip, tools/khmer/abundance-dist-single.xml, tools/khmer/abundance-dist.xml, tools/khmer/count-median.xml, tools/khmer/do-partition.xml, tools/khmer/extract-partitions.xml, tools/khmer/filter-abund.xml, tools/khmer/filter-below-abund.xml, tools/khmer/macros.xml, tools/khmer/normalize-by-median.xml
=> Linter and other fixes: khmer

tools/quickmerge/.lint_skip, tools/quickmerge/quickmerge.xml
=> linting: fix quickmerge test

tools/quickmerge/.shed.yml
=> quickmerge fix owner

tools/merlin/.lint_skip, tools/merlin/merlin.xml
=> linter fixes merlin

tools/hicstuff/.lint_skip, tools/hicstuff/hicstuff_pipeline.xml, tools/hicstuff/macros.xml
=> hicstuff: linter fixes (and improvements)

tools/gffcompare/.lint_skip, tools/gffcompare/gffcompare.xml
=> linter fixes for gffcompare

tools/bctools/.lint_skip, tools/bctools/convert_bc_to_binary_RY.xml, tools/bctools/coords2clnt.xml, tools/bctools/extract_aln_ends.xml, tools/bctools/extract_bcs.xml, tools/bctools/macros.xml, tools/bctools/merge_pcr_duplicates.xml, tools/bctools/remove_tail.xml, tools/bctools/rm_spurious_events.xml
=> linter fixes for bctools

tools/presto/.lint_skip, tools/presto/presto_alignsets.xml, tools/presto/presto_assemblepairs.xml, tools/presto/presto_buildconsensus.xml, tools/presto/presto_collapseseq.xml, tools/presto/presto_filterseq.xml, tools/presto/presto_maskprimers.xml, tools/presto/presto_pairseq.xml, tools/presto/presto_parseheaders.xml, tools/presto/presto_parselog.xml, tools/presto/presto_partition.xml, tools/presto/prestor_abseq3.xml
=> Linter fixes presto

tools/pe_histogram/.lint_skip, tools/pe_histogram/pe_histogram.xml
=> linter fixes for pe_histogram

tool_collections/galaxy_sequence_utils/fastq_combiner/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_combiner/fastq_combiner.xml, tool_collections/galaxy_sequence_utils/fastq_filter/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_filter/fastq_filter.xml, tool_collections/galaxy_sequence_utils/fastq_groomer/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_groomer/fastq_groomer.xml, tool_collections/galaxy_sequence_utils/fastq_manipulation/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_manipulation/fastq_manipulation.xml, tool_collections/galaxy_sequence_utils/fastq_masker_by_quality/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_masker_by_quality/fastq_masker_by_quality.xml, tool_collections/galaxy_sequence_utils/fastq_paired_end_deinterlacer/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_paired_end_deinterlacer/fastq_paired_end_deinterlacer.xml, tool_collections/galaxy_sequence_utils/fastq_paired_end_interlacer/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_paired_end_interlacer/fastq_paired_end_interlacer.xml, tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_paired_end_joiner/fastq_paired_end_joiner.xml, tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_paired_end_splitter/fastq_paired_end_splitter.xml, tool_collections/galaxy_sequence_utils/fastq_stats/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_stats/fastq_stats.xml, tool_collections/galaxy_sequence_utils/fastq_to_tabular/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_to_tabular/fastq_to_tabular.xml, tool_collections/galaxy_sequence_utils/fastq_trimmer/.lint_skip, tool_collections/galaxy_sequence_utils/fastq_trimmer/fastq_trimmer.xml, tool_collections/galaxy_sequence_utils/fastqtofasta/.lint_skip, tool_collections/galaxy_sequence_utils/fastqtofasta/fastq_to_fasta.xml, tool_collections/galaxy_sequence_utils/macros.xml, tool_collections/galaxy_sequence_utils/tabular_to_fastq/.lint_skip, tool_collections/galaxy_sequence_utils/tabular_to_fastq/tabular_to_fastq.xml
=> linter fixes for galaxy_sequence_utils

tools/augustus/macros.xml
@bernt-matthias not sure why the test pass but this is needed to fix https://github.com/galaxyproject/tools-iuc/pull/6402/files
also see https://github.com/BioContainers/multi-package-containers/pull/3315
=> Use tool_version for augustus

tools/hansel/.lint_skip, tools/hansel/bio_hansel.xml
=> linter fixes for hansel

tool_collections/cufflinks/cuff_macros.xml, tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.xml, tool_collections/cufflinks/cuffdiff/.lint_skip, tool_collections/cufflinks/cuffdiff/cuffdiff_wrapper.xml, tool_collections/cufflinks/cufflinks/cufflinks_wrapper.xml, tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.xml, tool_collections/cufflinks/cuffnorm/.lint_skip, tool_collections/cufflinks/cuffnorm/cuffnorm_wrapper.xml, tool_collections/cufflinks/cuffquant/cuffquant_wrapper.xml
Only bumping `cuffnorm` (changed output names).
=> linter fixes for cufflinks

tools/intermine_galaxy_exchange/.lint_skip, tools/intermine_galaxy_exchange/intermine_galaxy_exchange.xml
=> Fix galaxy_intermine_exchange test

data_managers/data_manager_star_index_builder/.lint_skip, data_managers/data_manager_star_index_builder/data_manager/rna_star_index_builder.xml
Some test parameters were not existing in the inputs. 
=> fix star DM test

tools/salsa2/.lint_skip
=> Remove unused linter skip

tools/umi_tools/.lint_skip, tools/umi_tools/macros.xml, tools/umi_tools/umi-tools_counts.xml, tools/umi_tools/umi-tools_dedup.xml, tools/umi_tools/umi-tools_extract.xml, tools/umi_tools/umi-tools_group.xml, tools/umi_tools/umi-tools_whitelist.xml
=> Linter fixes for umitools

tools/samblaster/.lint_skip, tools/samblaster/samblaster.xml
=> linter fixes for samblaster

tools/rrparser/.lint_skip, tools/rrparser/rrparser.xml
=> rrparser: fix missing when

tools/porechop/.lint_skip, tools/porechop/porechop.xml
=> porechop: fix frong test parameter

tools/vsnp/.lint_skip, tools/vsnp/vsnp_statistics.xml
=> vsnp: fix test parameters

tools/hivclustering/.lint_skip, tools/hivclustering/hivclustering.xml, tools/hivclustering/macros.xml
=> linter fixes for hivclustering

tools/lofreq/.lint_skip, tools/lofreq/lofreq_alnqual.xml, tools/lofreq/lofreq_call.xml, tools/lofreq/lofreq_viterbi.xml
=> Linter fixes  lofreq

tools/sniffles/.lint_skip
=> Remove unneeded lint skip: sniffles

tools/cutesv/.lint_skip, tools/cutesv/cutesv.xml, tools/cutesv/macros.xml
=> cutesv: fix wrong test parameter

tools/barcode_splitter/.lint_skip, tools/barcode_splitter/barcode_splitter.xml
=> barcodeplitter fix missing when

tools/vcf2maf/.lint_skip, tools/vcf2maf/vcf2maf.xml
=> vcf2maf: fix wrong test parameter

tools/colibread/.lint_skip, tools/colibread/commet.xml, tools/colibread/discosnp_RAD.xml, tools/colibread/discosnp_pp.xml, tools/colibread/kissplice.xml, tools/colibread/lordec.xml, tools/colibread/macros.xml, tools/colibread/mapsembler2.xml, tools/colibread/takeabreak.xml
=> Linter fixes colibread

tools/freyja/macros.xml
Hello! This is an automated update of the following tool: **tools/freyja**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/freyja from version 1.3.8 to 1.3.11.
**Project home page:** https://github.com/andersen-lab/Freyja/releases
=> Updating tools/freyja from version 1.3.8 to 1.5.1

tools/cutesv/cutesv.xml, tools/cutesv/macros.xml
This PR fixes the https://github.com/galaxyproject/tools-iuc/pull/6435
--
=> Updating tools/cutesv

tools/mapseq/mapseq.xml, tools/mapseq/test-data/sequences.mapseq
MAPseq 2.1.1b includes a `-seed` flag to ensure reproducibility.
=> Update MAPseq and add seed option

data_managers/data_manager_groot_database_downloader/.shed.yml
=> Update .shed.yml : miss owner

tools/mummer4/.lint_skip
not needed anymore https://github.com/galaxyproject/tools-iuc/pull/6439
=> mummer4: remove lint skip

tools/abritamr/abritamr.xml
=> Make abritamr outputs tabular

tool_collections/cufflinks/cuff_macros.xml, tool_collections/cufflinks/cuffmerge/cuffmerge_wrapper.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/6480
=> fix cuffmerge for more than 2 inputs

tools/featurecounts/.shed.yml, tools/featurecounts/featurecounts.xml
=> Updates .shed.yml file for tools/featurecounts

tools/fastk/macros.xml
Hi,
This PR links the tools to its bio.tools entry: https://bio.tools/FASTK
=> Add bio.tools for fastk

tools/seurat/create_seurat.xml, tools/seurat/inspect_and_manipulate.xml, tools/seurat/integrate.xml, tools/seurat/macros.xml, tools/seurat/neighbors_clusters_markers.xml, tools/seurat/normalize_select_features_scale.xml, tools/seurat/plot.xml, tools/seurat/reduce_dimensions.xml
=> Seurat add bio.tools

tools/sinto/macros.xml, tools/sinto/sinto_barcode.xml, tools/sinto/sinto_fragments.xml
* [] This PR adds a new tool or tool collection
Add newly created bio.tools entry
=> [ci skip] Sinto add bio.tools

tools/raceid/macros.xml, tools/raceid/raceid_clustering.xml, tools/raceid/raceid_filtnormconf.xml, tools/raceid/raceid_inspectclusters.xml, tools/raceid/raceid_inspecttrajectories.xml, tools/raceid/raceid_trajectory.xml
=> RaceID link newly created bio.tools entry

tools/trycycler/macros.xml
Added trycycler bio.tools id
Added bio.tools id annotation as part of the 2024 ELIXIR BioHackathon
=>  add bio.tools id to xml

tools/snapatac2/dimension_reduction_clustering.xml, tools/snapatac2/macros.xml, tools/snapatac2/peaks_and_motif_analysis.xml, tools/snapatac2/plotting.xml, tools/snapatac2/preprocessing.xml
=> Add bio.tools id to snapatac2

tools/seurat/create_seurat.xml, tools/seurat/macros.xml
=> Seurat allow create_seurat to use txt barcodes file

tools/anndata/export.xml, tools/anndata/import.xml, tools/anndata/inspect.xml, tools/anndata/macros.xml, tools/anndata/manipulate.xml, tools/anndata/modify_loom.xml
Add bio.tools and edam ontology
=> Add bio.tools and edam ontologies for anndata

tools/sniffles/sniffles.xml, tools/sniffles/test-data/expected_outcome3.vcf, tools/sniffles/test-data/expected_outcome4.vcf, tools/sniffles/test-data/expected_outcome5.vcf, tools/sniffles/test-data/expected_outcome6.vcf, tools/sniffles/test-data/expected_output.vcf, tools/sniffles/test-data/expected_output2.vcf
Update sniffles to 2.5.2 release and update test outputs.
=> update sniffles to new 2.5.2 release

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py, data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
=> Kraken2 DM: Add support for installing pre-built EuPathDB databases

tools/snipit/snipit.xml
faster than the bot for once :-)
=> Update snipit to v1.6

tools/abyss/abyss-pe.xml
This PR updates the abyss tool to 2.3.10 and fixes issue reported in https://github.com/galaxyproject/tools-iuc/pull/6490#issuecomment-2479003830
Fixes: #6490
---
=> Fixing linting issues and updating tools/abyss

tools/ncbi_fcs_gx/macros.xml, tools/ncbi_fcs_gx/ncbi_fcs_gx.xml
=> Fix quoting of `$TMPDIR` in NCBI FCS-GX

data_managers/data_manager_mapseq/data_manager/macros.xml, data_managers/data_manager_mapseq/data_manager/mapseq_db_fetcher.xml
=> Update MAPseq DM

tools/halfdeep/halfdeep.xml, tools/halfdeep/macros.xml
=> fixing mapped-reads symlinks

tools/raceid/.shed.yml
Fix `remote_repository_url` in shed.yml
=> raceid tool fix repo url

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py, data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
=> Kraken2 DM: Add 2024-09-04 prebuilt databases + core_nt and gtdb_genome_reps

tools/cnvkit/autobin.xml, tools/cnvkit/batch.xml, tools/cnvkit/breaks.xml, tools/cnvkit/call.xml, tools/cnvkit/diagram.xml, tools/cnvkit/genemetrics.xml, tools/cnvkit/heatmap.xml, tools/cnvkit/macros.xml, tools/cnvkit/reference.xml, tools/cnvkit/scatter.xml, tools/cnvkit/segment.xml, tools/cnvkit/segmetrics.xml
And fix the `TestsCaseValidation` errors which will keep us busy for the next years :( .. @jmchilton could you imagine an automatization for fixing these errors? I just can not imagine that these linter errors will ever be fixed...
=> cnvkit: text is txt

tools/tetyper/.lint_skip, tools/tetyper/tetyper.xml
=> tetyper: profile, text is txt and better testing

.github/workflows/ci.yaml, .github/workflows/pr.yaml
https://github.com/galaxyproject/tools-iuc/issues/6617 looks good
=> Test against release branch 24.2

tools/scanpy/filter.xml
Related to this PR: https://github.com/galaxyproject/tools-iuc/pull/6644
=> Move filtering functions from Anndata to Scanpy tool

data_managers/data_manager_checkm2/tool_data_table_conf.xml.sample, data_managers/data_manager_checkm2/tool_data_table_conf.xml.test
Fixes merge issue from https://github.com/galaxyproject/tools-iuc/pull/6542
=> Fix checkm2 data manager issue

tools/phyloseq/macros.xml, tools/phyloseq/phyloseq_plot_bar.R
=> remove OTU separation lines in phyloseq bar chart tool

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
=> Kraken2 DM: update to newest DBs

tools/ena_upload/ena_upload.xml
=> Start updating ENA upload to ena-upload-cli 0.7.5

tools/spacexr/.shed.yml, tools/spacexr/macros.xml
PR to resolve: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/820
* [ x I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x License permits unrestricted use (educational + commercial)
=> spacexr: update shed.yml

tools/fairy/fairy_cov.xml, tools/fairy/macros.xml
=> Update fairy_cov 

data_managers/data_manager_deeparg/.shed.yml
having suite in DM overwritten the tool shed.yml: https://github.com/galaxyproject/tools-iuc/blob/main/tools/deeparg/.shed.yml
=> Fix deeparg DM shed.yml

tools/nanoplot/nanoplot.xml, tools/nanoplot/test-data/NanoStats.txt, tools/nanoplot/test-data/NanoStats_post_filtering.txt
---
This PR updates the test data of nanoplot and fixes #6711
=> Updating tools/nanoplot

tools/porechop/porechop.xml
Will be needed as MultiQC input.
=> Add log file output to Porechop

tools/binette/.shed.yml
=> Fix Binette .shed typo (icu -> iuc)

tools/cami_amber/cami_amber.xml, tools/cami_amber/cami_amber_add_length.xml, tools/cami_amber/cami_amber_convert_to_biobox.xml, tools/cami_amber/macros.xml
=> Add bio.tools to CAMI AMBER

tools/ivar/ivar_consensus.xml, tools/ivar/ivar_filtervariants.xml, tools/ivar/ivar_removereads.xml, tools/ivar/ivar_trim.xml, tools/ivar/ivar_variants.xml, tools/ivar/macros.xml
=> Fix ivar biotools in macros

tools/raven/macros.xml, tools/raven/raven.xml
=> Add Raven bio.tools

tools/srst2/.shed.yml
=> Fix SRST2 remote_repository_url

tools/staramr/staramr_search.xml
=> Add StarAMR biotools

tools/fastk/fastk.xml, tools/fastk/histex.xml, tools/fastk/logex.xml, tools/fastk/macros.xml
=> Add bio.tools to fastk

tools/kraken_biom/.shed.yml, tools/kraken_biom/kraken_biom.xml, tools/kraken_biom/macros.xml
=> Add kraken-biom biotools

tools/sickle/sickle.xml, tools/sickle/test-data/sickle.log
---
This PR adds log option to Sickle tool along with additional test, and introduces some minor structural changes to the tool.
=> Add log option to Sickle tool for MultiQC plugin

tools/quicktree/quicktree.xml
=> Replace EDAM terms by bio.tools in quicktree

.github/workflows/pr.yaml, tools/phyloseq/phyloseq_plot_bar.R
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
=> Replace ubuntu-20.04 runner

tools/bbtools/bbduk.xml, tools/bbtools/macros.xml
Needed as an input for MultiQC.
=> Add log file param to BBDuk (BBTools)

tools/ppanggolin/macros.xml
=> PPanGGOLiN: Add panRGP citation

tools/megahit/megahit_wrapper.xml
=> Add log file param to MEGAHIT

tools/deeparg/deeparg_predict.xml, tools/deeparg/deeparg_short_reads.xml, tools/deeparg/macros.xml
Update deepARG with minor changes for tools deployement because deploy failed in this PR (https://github.com/galaxyproject/tools-iuc/pull/6646) due to issues into DM part. Issues are now solved but tools are still not deployed.
=> Update deepARG with minor changes for tools deployement

tools/binette/binette.xml
=> Add biotools ref to binette

tools/fastk/logex.xml, tools/fastk/macros.xml
---
This PR fixes a minor issue in the input format of the Logex tool of FastK toolsuite.
=> Fix input format for Logex tool

tools/iqtree/iqtree.xml, tools/iqtree/iqtree_macros.xml
---
This PR fixes the linting error issue in https://github.com/galaxyproject/tools-iuc/pull/6768
=> Update and fixing linting errors in tools/iqtree

tools/ncbi_datasets/datasets_gene.xml, tools/ncbi_datasets/datasets_genome.xml, tools/ncbi_datasets/macros.xml
=> Update and fix ncbi datasets

tools/metaphlan/metaphlan.xml
I think we should pay more attention to: https://github.com/galaxyproject/tools-iuc/issues/4085
This one is really bad in my opinion. 
=> Metaphlan fixes

tools/ncbi_datasets/macros.xml
---
This PR updates the tool and removes a minor hyphen from an option as mentioned by @bernt-matthias in https://github.com/galaxyproject/tools-iuc/pull/6794
=> Minor update to tools/ncbi datasets

tools/revoluzer/distmat.xml, tools/revoluzer/macros.xml
depends on https://github.com/bioconda/bioconda-recipes/pull/54322
=> bump revoluzer to 0.1.7

data_managers/data_manager_funannotate_options/.shed.yml, tools/funannotate/tool-data/funannotate_options.loc.sample
=> funannotate add missing loc.sample file

tools/decontam/decontam.xml
=> Add description to decontam

tools/revoluzer/macros.xml
requires https://github.com/bioconda/bioconda-recipes/pull/54427
=> bump revoluzer

tools/gtdbtk/gtdbtk_classify_wf.xml, tools/gtdbtk/macros.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/6773
=> gtdbtk: do not allow spaces in link names

tools/bracken/.shed.yml, tools/bracken/macros.xml
Fixes: https://github.com/galaxyproject/tools-iuc/pull/6824
=> Update homepage url in .shed for tools/bracken

tools/checkm2/checkm2.xml
=> Add a DB filter to prevent using the newest DB from CheckM2

tools/rrparser/rrparser.xml
This PR removes conflicting URL for planemo linting test. 
Fixes: https://github.com/galaxyproject/tools-iuc/pull/6850
=> Linter fixes to tools/rrparser

tools/ampvis2/venn.xml
=> Fix typo in venn.xml

tools/drep/drep_compare.xml, tools/drep/drep_dereplicate.xml, tools/drep/macros.xml
=> dRep: Add thread number and remove debug mode

tools/bwa_mem2/.lint_skip, tools/bwa_mem2/bwa-mem2.xml, tools/bwa_mem2/macros.xml
=> Ad missing samtools yield in bwa-mem2

tools/merquryfk/merquryfk.xml
---
This PR adds a new tool MerquryFK, to the existing MerquryFK toolsuite.
=> New tool addition: Add MerquryFK tool

tools/kmer2stats/kmer2stats.xml
The output is with tabs so tabular is the better format here
=> Update kmer2stats tool

data_managers/data_manager_kaiju/data_manager/kaiju_data_manager.xml, tools/kaiju/kaiju-addTaxonNames.xml
Minor fix for https://github.com/galaxyproject/tools-iuc/pull/6908
=> Fix kaiju capitalization

tools/drep/macros.xml
=> drep: add outputs

tool_collections/snpsift/snpsift/snpSift_extractFields.xml, tool_collections/snpsift/snpsift/snpSift_rmInfo.xml, tools/arriba/arriba.xml, tools/circos/macros_conffiles.xml, tools/column_maker/column_maker.xml, tools/gemini/gemini_burden.xml, tools/gemini/gemini_inheritance.xml, tools/gemini/gemini_roh.xml, tools/hicexplorer/hicCompartmentalization.xml, tools/ncbi_datasets/datasets_gene.xml, tools/packaged_annotation_loader/load_annotations.xml, tools/quast/quast.xml, tools/scanpy/filter.xml
Hoping to get away with not bumping versions ...
=> Ensure text parameter sanitizers aren't bypassed

tools/gffcompare/gffcompare.xml, tools/gffcompare/macros.xml
=> Updating gffCompare to 0.12.9 and sanitizing planemo tests

tools/volcanoplot/macros.xml, tools/volcanoplot/volcanoplot.xml
=> updated volcanoplot to use column names

tool_collections/samtools/samtools_coverage/samtools_coverage.xml
---
This PR fixes the tool description for samtools coverage as per issue reported in https://github.com/galaxyproject/tools-iuc/issues/6981
Fixes: https://github.com/galaxyproject/tools-iuc/issues/6981
=> Fix samtools coverage tool description

tools/fastk/logex.xml
---
This PR is a patch for mishandling of hidden files required for Logex to run.
=> Fix mishandling of hidden files in Logex

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Release testing looks good: https://github.com/galaxyproject/tools-iuc/actions/runs/15109633166
=> Run tests against release_25.0

tools/sequali/sequali.xml
=> Update sequali to 1.0.1

tools/tooldistillator/macro.xml, tools/tooldistillator/test-data/coreprofiler/results.tsv, tools/tooldistillator/tooldistillator.xml
This update now allows ToolDistillator to parse and obtain a JSON format with their content and/or metadata from the tool outputs of **CoreProfiler**
Thanks 😃
=> Update ToolDistillator Galaxy Version 0.9.2+galaxy1 to 0.9.3+galaxy0

tools/omark/macros.xml
Hello, I am opening this PR to modify the OMark dependencies in order to correct the error I had in this other PR (https://github.com/galaxyproject/iwc/pull/767).
Thank you ! Have a nice day!
Romane
=> Change dependencies OMark

tools/ncbi_fcs_gx/macros.xml, tools/ncbi_fcs_gx/ncbi_fcs_gx.xml
Otherwise, it silently fails, making debugging somewhat difficult.
=> NCBI FCS-GX: do not suppress sync_files.py output if it fails

data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml
=> Update metaphlan DM

tools/proteinortho/proteinortho_clustering.xml, tools/proteinortho/proteinortho_grab_proteins.xml, tools/proteinortho/proteinortho_macros.xml
Update proteinortho to 6.3.6 and added a new sub-tool (proteinortho clustering) to the tool suit
=> update proteinortho 6.3.6

tools/checkm/macros.xml, tools/checkm/plot.xml
---
This PR updates CheckM to 1.2.4 and incorporates changes in some test.
Fixes: https://github.com/galaxyproject/tools-iuc/pull/7053
=> Update tools/checkm to 1.2.4

tools/mirmachine/macros.xml, tools/mirmachine/mirmachine.xml
---
This PR updates MirMachine to 0.3.0.1 with adapted test-data.
Fixes: https://github.com/galaxyproject/tools-iuc/pull/7055
=> Update tools/mirmachine to 0.3.0.1

tools/checkm/.lint_skip, tools/checkm/analyze.xml, tools/checkm/lineage_wf.xml, tools/checkm/macros.xml, tools/checkm/plot.xml, tools/checkm/qa.xml, tools/checkm/taxonomy_wf.xml, tools/checkm/tree.xml
=> checkm lint fixes

tools/deg_annotate/deg_annotate.xml
=> Use profile version for DEG annotate

tools/deeparg/deeparg_short_reads.xml, tools/deeparg/macros.xml
=> Update : deeparg adaptation for paired collection

tools/graphlan/.shed.yml
=> fix remote_repository_url Graphlan

tools/datamash/datamash-transpose.xml, tools/datamash/macros.xml
---
This PR fixes some linting errors and updates the tool datamash.
Closes: https://github.com/galaxyproject/tools-iuc/pull/6912
=> Fixing linting errors for tools/datamash

tools/rnaquast/.lint_skip, tools/rnaquast/macros.xml, tools/rnaquast/rna_quast.xml
=> Linter fixes rnaquast

tools/amplican/.lint_skip, tools/amplican/amplican.xml, tools/amplican/macros.xml
=> Linter fixes amplican

tools/velocyto/.lint_skip, tools/velocyto/velocyto_cli.xml
=> fix linter issue in velocyto

tools/gffcompare/.lint_skip, tools/gffcompare/gffcompare.xml, tools/gffcompare/macros.xml
---
Fixes: https://github.com/galaxyproject/tools-iuc/pull/7157
=> Update tools/gffcompare to 0.12.10

tools/mosdepth/mosdepth.xml
---
Fixes: https://github.com/galaxyproject/tools-iuc/pull/7135
=> Update tools/mosdepth to 0.3.11

tools/evidencemodeler/.lint_skip, tools/evidencemodeler/.shed.yml, tools/evidencemodeler/evidencemodeler.xml
=> fix linter issue of evidence modeler

tools/last/.lint_skip, tools/last/lastal.xml, tools/last/lastdb.xml, tools/last/lastsplit.xml, tools/last/lasttrain.xml, tools/last/macros_last.xml, tools/last/maf-convert.xml
=> last: fix lint and remove unneeded conditional

tools/eukrep/.shed.yml, tools/eukrep/eukrep.xml
=> initial commit of eukrep

tools/micro_decon/.shed.yml, tools/micro_decon/decon.R, tools/micro_decon/macros.xml, tools/micro_decon/micro_decon.xml, tools/micro_decon/test-data/decon_table.csv, tools/micro_decon/test-data/difference_mean.csv, tools/micro_decon/test-data/difference_sum.csv, tools/micro_decon/test-data/input.csv, tools/micro_decon/test-data/otus_removed.csv, tools/micro_decon/test-data/reads_removed.csv, tools/micro_decon/test-data/remove_cont_decon_table.csv, tools/micro_decon/test-data/remove_thresh_decon_table.csv
=> Add a new tool: microDecon

tools/minimap2/.lint_skip, tools/minimap2/macros.xml, tools/minimap2/minimap2.xml
=> Minimap linter fixes and remove input of paired data in separate/interleaved datasets 

tools/orthofinder/.lint_skip, tools/orthofinder/macros.xml, tools/orthofinder/orthofinder_only_groups.xml
https://help.galaxyproject.org/t/difficulty-in-using-orthofinder/14300/26
=> Orthofinder improvements

tools/gamma/gamma-s.xml, tools/gamma/test-data/gamma-s_amr.gamma, tools/gamma/test-data/gamma-s_out.gamma
GAMMA-S is the other tool from the GAMMA package.
=> New tool: GAMMA-S , part of the GAMMA package

tools/comebin/comebin.xml, tools/comebin/macros.xml
=> Fix COMEBin

tools/seqkit/macros.xml, tools/seqkit/test-data/stats_output1.tabular, tools/seqkit/test-data/stats_output2.tabular
---
Fixes: https://github.com/galaxyproject/tools-iuc/pull/7239
=> Update tools/seqkit to 2.10.1

data_managers/data_manager_build_coreprofiler/data_manager/data_manager_build_coreprofiler_download.xml
=> Update coreprofiler and replace schemas

tools/panta/panta.xml
=> Fix Panta deployment error

.github/dependabot.yml
=> Enable dependabot version updates for GitHub actions

data_managers/data_manager_checkm2/data_manager/checkm2_datamanager.xml
=> Update CheckM2 DM from 1.0.2 to 1.1.0 and revert DM workaround
