packages/package_onto_perl_1_41/tool_dependencies.xml
=> Fix broken package in ONTO-PERL

CONTRIBUTING.md
See #35, there were some TODOs that needed to be addressed. I just made some fairly generic changes, IUC members please comment on this and we can get them all patched in!
=> Fix some of TODOs on the contribution doc

packages/package_mummer_3_23/.shed.yml, packages/package_mummer_3_23/tool_dependencies.xml
Fix for: https://github.com/galaxyproject/tools-iuc/issues/9#issuecomment-75721174
=> Add mummer package created by James Johnson.

packages/package_vcflib_8a5602bf07/tool_dependencies.xml
Originally owned by @nekrut but hopefully will be adopted by the IUC.
=> introduce vcflib package

packages/package_samtools_1_2/.shed.yml, packages/package_samtools_1_2/tool_dependencies.xml
I copied the 1.1, took @davebx binary and added action to remove the /usr/local prefix to the recipe (also by Dave) :)
=> introduce package samtools v 1.2

packages/package_samtools_0_1_16/.shed.yml, packages/package_samtools_0_1_16/tool_dependencies.xml, packages/package_samtools_0_1_18/.shed.yml, packages/package_samtools_0_1_18/tool_dependencies.xml
so we have all samtools under one roof
=> adopt the rest of devteam's samtools

packages/package_samtools_1_0/tool_dependencies.xml, packages/package_samtools_1_1/tool_dependencies.xml, packages/package_samtools_1_2/tool_dependencies.xml
so they will resolve on install time.
=> Update samtools dependencies

packages/package_bedtools_2_18/.shed.yml, packages/package_bedtools_2_19/.shed.yml, packages/package_bedtools_2_20/.shed.yml, packages/package_bedtools_2_22/.shed.yml, packages/package_biopython_1_61/.shed.yml, packages/package_ccat_3_0/.shed.yml, packages/package_cummerbund_2_8_2/.shed.yml, packages/package_deseq2_1_0_17/.shed.yml, packages/package_deseq2_1_2_10/.shed.yml, packages/package_dill_0.2/.shed.yml, packages/package_eigen_2_0/.shed.yml, packages/package_eigen_3_1/.shed.yml, packages/package_gemini_0_10_0/.shed.yml, packages/package_gnu_grep_2_14/.shed.yml, packages/package_graphicsmagick_1_3/.shed.yml, packages/package_macs2_2_1_0/.shed.yml, packages/package_matplotlib_1_2/.shed.yml, packages/package_matplotlib_1_4/.shed.yml, packages/package_mummer_3_23/.shed.yml, packages/package_numpy_1_9/.shed.yml, packages/package_perl_5_18/.shed.yml, packages/package_prodigal_2_60/.shed.yml, packages/package_python_2_7/.shed.yml, packages/package_python_3_4/.shed.yml, packages/package_rpy2_2_3_6/.shed.yml, packages/package_sailfish_0_6/.shed.yml, packages/package_segemehl_0_1_6/.shed.yml, packages/package_seqtk_1_0_r75/.shed.yml, packages/package_stringtie_0_97/.shed.yml, packages/package_stringtie_1_0_1/.shed.yml
@erasche here are my last changes! Thanks for pushing me :)
=> `shed.yml` cleanups

packages/package_graphicsmagick_1_3/.shed.yml, packages/package_graphicsmagick_1_3_20/.shed.yml, packages/package_graphicsmagick_1_3_20/tool_dependencies.xml
Makes me wonder if I should check the TS for other things not mirrored in this repository...
=> Graphicsmagick 1.3.20 was missing despite being in TS

packages/package_ballgown_1_0_3/.shed.yml, packages/package_biopython_1_61/readme.rst, packages/package_dill_0.2/.shed.yml, packages/package_samtools_0_1_16/.shed.yml, packages/package_samtools_0_1_18/.shed.yml, packages/package_samtools_1_0/.shed.yml, packages/package_samtools_1_2/.shed.yml, packages/package_ucsc_tools_0_1/.shed.yml, tool_collections/snpeff/.shed.yml, tools/bedtools/.shed.yml, tools/gemini/.shed.yml, tools/macs2/.shed.yml, tools/seqtk/.shed.yml
=> Shed fixes

data_managers/data_manager_snpeff/repository_dependencies.xml, tool_collections/snpeff/repository_dependencies.xml, tool_collections/snpsift/snpsift_dbnsfp/repository_dependencies.xml, tool_collections/snpsift/snpsift_dbnsfp_generic/repository_dependencies.xml
... these data types are now part of main Galaxy.
Should fix https://github.com/galaxyproject/tools-iuc/issues/88
=> Remove repository datatype dependencies

tools/gemini/gemini_load.xml
This should fix https://github.com/galaxyproject/tools-iuc/issues/62
=> Don't write into the databse directory during gemini build.

packages/package_openms_2_0/.shed.yml, packages/package_openms_2_0/tool_dependencies.xml, packages/package_tpp_4_8_0/.shed.yml, packages/package_tpp_4_8_0/tool_dependencies.xml
Both are for the GalaxyP project.
=> This will add openms and TPP packages

README.md
Some extra motivation for IUC members to fix bugs :)
=> Fancy new badges

packages/package_cd_hit_auxtools_0.5_2012_03_07_fix_dan/.shed.yml, packages/package_cd_hit_auxtools_0.5_2012_03_07_fix_dan/tool_dependencies.xml
see also https://github.com/galaxyproject/tools-devteam/pull/124
=> Add package_cd_hit_auxtools_0.5_2012_03_07_fix_dan

tools/gatk2/readme.rst
=> include note about GATK2 warning in the log

tools/stringtie/stringtie.xml, tools/stringtie/test-data/stringtie_out1.gtf, tools/stringtie/test-data/stringtie_out2.gtf, tools/stringtie/test-data/stringtie_out3.gtf, tools/stringtie/test-data/stringtie_out4.gtf, tools/stringtie/test-data/stringtie_out5.gtf
This will support latest 1.0.3 version of stringtie
=> Polish to stringtie interface and test update

tools/bedtools/macros.xml, tools/bedtools/mapBed.xml
=> Bedtools bugfix

packages/package_cummerbund_2_8_2/tool_dependencies.xml
And also update the setup_r_environment to download mirrored tarballs.
=> Fix dependency for RCurl.

packages/package_ruby_2_0/tool_dependencies.xml, packages/package_ruby_2_1/.shed.yml, packages/package_ruby_2_1/tool_dependencies.xml, packages/package_ruby_2_2/.shed.yml, packages/package_ruby_2_2/tool_dependencies.xml
This PR updates our ruby packages and will add the new ruby 2.2 version.
=> Update ruby package

packages/package_r_limma_3_25_3/.shed.yml, packages/package_r_limma_3_25_3/tool_dependencies.xml
- Follow up to #147 in which I switched package version and forgot to rename the folder/change versions elsewhere.
- CC @bgruening @peterjc 
- Thanks to @yhoogstrate for reporting.
=> Renamed package to correct name for version

tools/progressivemauve/progressivemauve.xml
Should've been caught earlier...but I'm not even sure what's wrong with the [planemo tests](http://gx.hx42.org/job/IUC-Github/274/Planemo_HTML_Reports/progressivemauve.html)
=> Non-optional file needs to be corrected

packages/package_libgd_2_1/tool_dependencies.xml
Mirrors https://github.com/galaxyproject/tools-devteam/pull/143
=> Package fixes

packages/package_python_2_7/tool_dependencies.xml
This fixes my problems with the new scientific python stack, in particular bx-python.
xref: https://github.com/galaxyproject/tools-iuc/issues/168
=> don't depend on TS openssl library

packages/package_cummerbund_2_8_2/tool_dependencies.xml, packages/package_r_limma_3_25_3/tool_dependencies.xml
Host is not live yet, please do not merge.
=> Update URL with soon-to-be-live bioaRchive host

packages/package_ucsc_tools_0_1/tool_dependencies.xml, packages/package_ucsc_tools_312/.shed.yml, packages/package_ucsc_tools_312/tool_dependencies.xml
This will add a new package for all freely available UCSC tools for academic and commercial use. No OS-X support for now.
=> UCSC tools from the galaxy depot

packages/package_rnacode_0_3/.shed.yml, packages/package_rnacode_0_3/tool_dependencies.xml
Needed for https://github.com/bgruening/galaxytools/issues/137
=> Adding package for RNAcode

packages/package_python_2_7_bcbiogff_0_6_2/tool_dependencies.xml, packages/package_python_2_7_pyyaml_3_11/.shed.yml, packages/package_python_2_7_pyyaml_3_11/tool_dependencies.xml, tools/jbrowse/macros.xml, tools/jbrowse/tool_dependencies.xml
=> JBrowse missing pyyaml

packages/package_libcurl_7_35/tool_dependencies.xml, packages/package_python_2_7/tool_dependencies.xml, packages/package_python_3_4/tool_dependencies.xml, packages/package_ruby_2_0/tool_dependencies.xml, packages/package_ruby_2_1/tool_dependencies.xml, packages/package_ruby_2_2/tool_dependencies.xml
openssl should be installed by the system package manager.
=> Remove dependencies on openssl.

packages/package_krona_2_5/tool_dependencies.xml
Explicit dependency on perl 5.18.1, move some ancillary files into $INSTALL_DIR.
=> Updates to KronaTools

packages/package_krona_2_5/tool_dependencies.xml
See https://github.com/galaxyproject/tools-iuc/pull/233#issuecomment-126790827 .
=> Fix and simplify install recipe.

packages/package_monocle_1_0_0/tool_dependencies.xml
#212 fix dependencies for monocle using the download_store.
=> Add persistent links to monocle

packages/package_libpng_1_2/.shed.yml, packages/package_libpng_1_2/tool_dependencies.xml, packages/package_pear_0_9_6/.shed.yml, packages/package_protk_1_2_4/tool_dependencies.xml, packages/package_ruby2_bioruby_1_4/tool_dependencies.xml, tools/bedtools/tool_dependencies.xml, tools/pear/.shed.yml
Hi there,
these are various fixes I came across while preparing to do automated shed_test installations
using jenkins.
=> Minor fixes encountered during automated tool testing

packages/package_r_3_1_2/.shed.yml
=> Typo in package R 3.1.2 .shed.yml

data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.xml, tool_collections/snpeff/snpEff.xml, tool_collections/snpeff/snpEff_download.xml, tool_collections/snpsift/snpsift/snpSift_annotate.xml, tool_collections/snpsift/snpsift/snpSift_caseControl.xml, tool_collections/snpsift/snpsift/snpSift_filter.xml, tools/differential_count_models/rgedgeRpaired_nocamera.xml, tools/gemini/gemini_annotate.xml, tools/gemini/gemini_autosomal_recessive.xml, tools/gemini/gemini_burden.xml, tools/gemini/gemini_macros.xml, tools/gemini/gemini_pathways.xml, tools/gemini/gemini_query.xml, tools/gemini/gemini_roh.xml, tools/gemini/gemini_windower.xml, tools/htseq/htseqsams2mx.xml, tools/macs2/macs2_macros.xml, tools/rglasso/rg_nri.xml, tools/rglasso/rglasso_cox.xml, tools/rgrnastar/rg_rnaStar.xml, tools/taxonomy_krona_chart/taxonomy_krona_chart.xml, tools/tool_factory_2/rgToolFactory2.xml
This is attribute is not used in the new tool form.
If this gets accepted I will also remove the entry from the wiki.
=> remove the size attribute

packages/package_freetype_2_5_2/tool_dependencies.xml, packages/package_python_2_7_deeptools_1_5_11/.shed.yml, packages/package_python_2_7_deeptools_1_5_11/tool_dependencies.xml, packages/package_python_2_7_matplotlib_1_4/tool_dependencies.xml, packages/package_ucsc_tools_312/tool_dependencies.xml
=> Add new deeptools package

tools/bedtools/annotateBed.xml, tools/bedtools/test-data/annotateBed_result.bed
This makes data-collections more useful for the BEDtool annotate.
=> Use labels from display_name

tools/gatk2/depth_of_coverage.xml, tools/gatk2/gatk2_macros.xml, tools/gatk2/haplotype_caller.xml, tools/gatk2/unified_genotyper.xml, tools/gatk2/variant_apply_recalibration.xml, tools/gatk2/variant_eval.xml, tools/gatk2/variant_recalibrator.xml, tools/gatk2/variant_select.xml
In support of https://github.com/galaxyproject/tools-iuc/issues/239
=> Swap all repeats to multiple='True' where appropriate

tools/bedtools/bamToBed.xml, tools/bedtools/tool_dependencies.xml
=> sort BAM file by name as default to improve usability

tools/dexseq/dexseq.xml
Should say:
```R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut", DEXSeq version 1.14.2 (depends on DESeq2 1.8.1)```
=> Added a version command to DEXSeq wrapper

tools/rgrnastar/rg_rnaStar.xml
Fix https://github.com/galaxyproject/tools-iuc/commit/5fdc662cc9eaf5c96bcd3579341dc5ae867dc16e#commitcomment-13623293 .
Ping @yhoogstrate.
=> Use GALAXY_SLOTS in RNA STAR.

packages/package_deseq2_1_8_2/.shed.yml, packages/package_deseq2_1_8_2/tool_dependencies.xml, tools/deseq2/.shed.yml, tools/deseq2/deseq2.xml, tools/deseq2/tool_dependencies.xml
New release of DESeq2 requested by @mikelove in https://github.com/galaxyproject/tools-iuc/pull/20
=> Deseq2 update

packages/package_freetype_2_5_2/tool_dependencies.xml
And I was wondering what package iuc could be ;)
=> Fix name for package libpng.

tools/bioperl/bp_genbank2gff3.xml, tools/bioperl/macros.xml, tools/bioperl/test-data/seq.gb, tools/bioperl/test-data/seq.gb.0.gff, tools/bioperl/test-data/seq.gb.1.gff, tools/bioperl/tool_dependencies.xml
Not all of the bioperl tools will be worth wrapping, especially when covered by other suites (e.g. seqtk), but some are definitely of interest. 
Done:
- genbank2gff3
Maybe todo? (Feel free to edit this list)
- bp_mutate
- bp_flanks
- ?
=> Bioperl genbank2gff3

packages/package_r2_limma_3_25_3/.shed.yml, packages/package_r2_limma_3_25_3/tool_dependencies.xml
Add an limma package for R2 and rpy. So that we have a solid dependency for @peterjc  venn_list tool.
=> add limma package for R2

packages/package_sailfish_0_7_6/.shed.yml, packages/package_sailfish_0_7_6/tool_dependencies.xml
Needed for https://github.com/bgruening/galaxytools/pull/254
=> add new sailfish package

tools/hisat2/hisat2.xml, tools/hisat2/hisat2_macros.xml
=> Fix misnamed parameter. Remove multiple.

packages/package_pixman_0_32_6/tool_dependencies.xml
=> Fix pixman compilation on OS X.

packages/package_khmer_2_0/tool_dependencies.xml, tools/khmer/abundance-dist-single.xml, tools/khmer/abundance-dist.xml, tools/khmer/count-median.xml, tools/khmer/do-partition.xml, tools/khmer/extract-partitions.xml, tools/khmer/filter-abund.xml, tools/khmer/filter-below-abund.xml, tools/khmer/macros.xml, tools/khmer/normalize-by-median.xml, tools/khmer/repository_dependencies.xml
@mr-c mostly style fixes.
I have two questions inline for you.
xref: https://github.com/galaxyproject/tools-iuc/pull/80
@jmchilton @erasche before we upload it, we have the opportunity to fix the tool ids and use this repos as demultiplexing example.
=> khmer style fixes

packages/package_augustus_3_1/tool_dependencies.xml
Fixes: https://github.com/galaxyproject/tools-iuc/issues/343
=> change download location for augustus

packages/package_r_crisprseek_1_10_0/.shed.yml, packages/package_r_crisprseek_1_10_0/tool_dependencies.xml, packages/package_r_crisprseek_1_11_0/.shed.yml, packages/package_r_crisprseek_1_11_0/tool_dependencies.xml
I am going to port CRISPRseek to galaxy. Could you please check and merge my CRISPRseek dependancy.
=> package_r_crisprseek biocundoctor dependancy definitions added

packages/package_r_crisprseek_1_11_0/.shed.yml
The version in .shed.yml was 1.10.0. I changed to 1.11.0.
=> Version fixed

tools/datamash/.shed.yml, tools/datamash/datamash-ops.xml, tools/datamash/datamash-reverse.xml, tools/datamash/datamash-transpose.xml
These tools are not yet on the MTS and we should change the ID's now to make it pretty.
ping @davebx @erasche
=> demultiplex datamash tools 

packages/package_qorts_0_3_18/.shed.yml, packages/package_qorts_0_3_18/tool_dependencies.xml
This tool is a recommended prior step for running JunctionSeq.
=> Add package definition for QoRTs 0.3.18

tools/hmmer3/.shed.yml
Depends on 
In support of (todo: find issue where we were all talking about demultiplexing and I volunteered to do it on my repository.)
=> Demultiplex the hmmer tools

packages/package_python_2_7_qiime_1_9_1/.shed.yml, packages/package_python_2_7_qiime_1_9_1/tool_dependencies.xml
This add the Qiime package to get a new community effort from @lparsons rolling!
For more information see here: http://dev.list.galaxyproject.org/QIIME-tools-for-Galaxy-WIP-call-for-collaborators-td4668035.html
=> add Qiime package

packages/package_homer_4_2/tool_dependencies.xml
xref: https://github.com/galaxyproject/tools-iuc/issues/363
=> Adding new download link to the homer package

packages/package_samtools_1_2/tool_dependencies.xml
@nsoranzo you mind testing? I don't have anything that isn't linux x86_64 so can't trigger that part of the installation recipe.
=> Add bgzip/tabix

packages/package_xz_5_0_5/tool_dependencies.xml
fixes: https://github.com/galaxyproject/tools-iuc/issues/363
=> xz dependencies update

packages/package_khmer_2_0/tool_dependencies.xml, packages/package_screed_0_9/tool_dependencies.xml
... else install will fail. Hopefully this will be the last fix to get khmer properly installed.
=> Pre-create lib dir

packages/package_raxml_8_2_4/tool_dependencies.xml, tools/raxml/.shed.yml, tools/raxml/raxml.xml, tools/raxml/test-data/RAxML_parsimonyTree.galaxy.multi, tools/raxml/tool_dependencies.xml
Followup to https://github.com/galaxyproject/tools-iuc/pull/372.
* address @nsoranzo and Bjoern's reviews
* style fixes
* move seed into advanced config
ping @tiagoantao @nsoranzo
=> post-merge RAxML updates

packages/package_gnu_awk_4_1_0/tool_dependencies.xml
Should fix https://github.com/galaxyproject/tools-iuc/issues/418
=> Integrate an "Extrawurst" for OS-X

packages/package_r_3_2_0/tool_dependencies.xml
Fixed the wrong download link for R 3.2.0
=> Fixed a URL for R 3.2.0

tools/datamash/datamash-reverse.xml, tools/datamash/datamash-transpose.xml
Should fix https://github.com/galaxyproject/tools-iuc/issues/291
=> remove -W parameter from the datamash tools

packages/package_diamond_0_7_9/.shed.yml, packages/package_diamond_0_7_9/tool_dependencies.xml
This PR adds the mash package as part of the [2nd IUC hackathon](
https://github.com/galaxyproject/tools-iuc/issues/299).
Diamond: https://github.com/marbl/Mash
ping @bebatut
=> add package diamond

packages/package_flash_1_2_11/.shed.yml, packages/package_flash_1_2_11/tool_dependencies.xml
Adding the flash (Fast Length Adjustment of SHort reads) tool which is
part of the FROGS workflow. This is my first contribution so there might be a lot of basic stuff missing.
=> Adding new tool package: FLASH v1.2.11

packages/package_swarm_2_1_5/.shed.yml, packages/package_swarm_2_1_5/tool_dependencies.xml
Here is the package for Swarm (issues #433 and #299 )
Anthony
=> Package for Swarm

tools/seqtk/seqtk_sample.xml
To allow decimal value input for seqtk_sample, I changed the variable to a float. That's pretty much it.
Thanks!
=> Changed seqtk_sample's subsample fraction/number variable to float to allow decimals

packages/package_freetype_2_5_2_matplotlib_fix/.shed.yml, packages/package_freetype_2_5_2_matplotlib_fix/tool_dependencies.xml, packages/package_python_2_7_matplotlib_1_4/tool_dependencies.xml
Hopefully this fixes @dpryan79 issue in #417.
=> Fix for #417

packages/package_krona_2_6/.shed.yml, packages/package_krona_2_6/tool_dependencies.xml, tools/taxonomy_krona_chart/taxonomy_krona_chart.xml, tools/taxonomy_krona_chart/test-data/krona_test1.html
Removed now defunct `-a` option
=> Update to krona. Now uses krona 2.6 from github

packages/package_diamond_0_7_10/.shed.yml, packages/package_diamond_0_7_10/tool_dependencies.xml
Diamond 0.7.9 was not uploaded to the MTS so I replaced this version with a new one.
Ping @nekrut
=> update diamond package

tools/trinity/tool_dependencies.xml, tools/trinity/trinity.xml
=> Trinity fixes.

packages/package_galaxy_sequence_utils_1_0_1/.shed.yml, packages/package_galaxy_sequence_utils_1_0_1/tool_dependencies.xml
xref https://github.com/galaxyproject/tools-devteam/pull/309
xref https://github.com/galaxyproject/sequence_utils/pull/2
=> Add package_galaxy_sequence_utils_1_0_1.

packages/package_r_3_2_1/tool_dependencies.xml
@mvdbeek does this seems right to you?
=> Add LD_LIBRARY_PATH which seems to be needed.

packages/package_genometools_1_5_7/.shed.yml, packages/package_genometools_1_5_7/tool_dependencies.xml
Hi,
I would need genometools for reago. Bjorn suggests to integrate the package as an iuc package.
Bérénice
=> Genometools package

packages/package_sailfish_0_6/tool_dependencies.xml
Fix: https://github.com/galaxyproject/tools-iuc/issues/515
=> Include cmake as build dependency

packages/package_r_3_0_3/tool_dependencies.xml, packages/package_r_3_1_0/tool_dependencies.xml, packages/package_r_3_1_1/tool_dependencies.xml, packages/package_r_3_1_2/tool_dependencies.xml, packages/package_r_3_2_0/tool_dependencies.xml
We already got this in package_r_3_2_1.
=> Follow up to PR #510, R needs fontconfig.

packages/package_circos_0_67_5/tool_dependencies.xml
Now links to a tar.gz on the depot server
=> dead link to SVG-perl package

packages/package_libpng_1_6_7/tool_dependencies.xml
Hi,
It's seem that libpng need zlib so I just add a dependency.
Cheers
Gildas
=> libpng need zlib

packages/package_freetype_2_5_2/tool_dependencies.xml
Hi,
The same history.
Freetype seems to need zlib
Cheers
=> freetype need the zlib dependency

packages/package_tophat_2_1_0/.shed.yml, packages/package_tophat_2_1_0/tool_dependencies.xml
In preparation for https://github.com/galaxyproject/tools-devteam/issues/324
=> Add new tophat recipe

packages/package_picard_2_0_1/.shed.yml, packages/package_picard_2_0_1/tool_dependencies.xml
For https://github.com/galaxyproject/tools-iuc/issues/559
=> add new picard package

.tt_blacklist, tools/stringtie/stringtie.xml
Remove stringtie from the blacklist, since we already have a conda dependency for all vesions.
=> enable stringtie testing

packages/package_hmmer_3_1b1/.shed.yml, packages/package_hmmer_3_1b1/tool_dependencies.xml, packages/package_hmmer_3_1b2/.shed.yml, packages/package_hmmer_3_1b2/tool_dependencies.xml
Fixes #563
*coughs*. We really need to make a decision on https://github.com/galaxyproject/tools-iuc/pull/213
=> Cherrypick changes from (still unmerged sha256sum branch)

packages/package_hmmer_3_1b1/.shed.yml, packages/package_hmmer_3_1b2/.shed.yml
=> set hmmer homepage_url

tools/hisat2/hisat2.xml
Solves https://github.com/galaxyproject/tools-iuc/issues/512 (ping @davebx )
=> HISAT2: dbkey being passed through to alignment

packages/package_libpng_1_6_7/tool_dependencies.xml
My apologies
libpng need CPPFLAGS and LDFLAGS from zlib during the compilation.
You may use a sexier method like autoconf to do that but I didn't manage to do without using shell_command.
=> Zlib4libpng

data_managers/data_manager_mothur_toolsuite/README, data_managers/data_manager_mothur_toolsuite/data_manager/data_manager_fetch_mothur_reference_data.xml, data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py, data_managers/data_manager_mothur_toolsuite/data_manager_conf.xml, data_managers/data_manager_mothur_toolsuite/tool-data/mothur_aligndb.loc.sample, data_managers/data_manager_mothur_toolsuite/tool-data/mothur_lookup.loc.sample, data_managers/data_manager_mothur_toolsuite/tool-data/mothur_map.loc.sample, data_managers/data_manager_mothur_toolsuite/tool-data/mothur_taxonomy.loc.sample, data_managers/data_manager_mothur_toolsuite/tool_data_table_conf.xml.sample
PR to add the data manager from https://github.com/fls-bioinformatics-core/galaxy-tools/tree/master/data_manager_mothur_toolsuite to the `mothur` branch as part of PR #429 ("WIP: Add mothur wrappers").
=> Add a data manager for Mothur toolsuite

packages/package_python_2_7_10_pybigwig_0_2_5/.shed.yml, packages/package_python_2_7_10_pybigwig_0_2_5/tool_dependencies.xml, packages/package_python_2_7_deeptools_2_1_0/.shed.yml, packages/package_python_2_7_deeptools_2_1_0/tool_dependencies.xml
@bgruening: Can you update the wrappers in your repository as well?
=> Bump pybigwig deeptools

packages/package_perl_xml_simple_2_22/.shed.yml, packages/package_perl_xml_simple_2_22/tool_dependencies.xml
@nsoranzo can you please add this one and bioperl to the prokka tool and change the readme file?
Thanks!
=> add the Perl library XML::Simple

packages/package_meme_4_11_0/tool_dependencies.xml
@gregvonkuster this is needed + you need to add this into th requirement tag of the meme-meme tools. But I guess you can do this with your next update.
=> Add perl deps to meme.

packages/package_libmagic_5_25/.shed.yml, packages/package_libmagic_5_25/tool_dependencies.xml
Is required for complete functionality of sra-toolkit [building of ncbi-copycat] (PR #598).
=> add libmagic

tools/datamash/datamash-ops.xml, tools/datamash/test-data/group_compute_input.txt, tools/datamash/test-data/group_compute_output.txt
Thanks @nsoranzo! This explains a lot :)
=> fix typo spotted by Nicola and revert the test data

data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.py, data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py, data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.py, data_managers/data_manager_star_index_builder/data_manager/rnastar_index_builder.py
=> Do not import from galaxy.util.json . Fix flake8 errors.

tools/data_source_iris_tcga/.shed.yml, tools/data_source_iris_tcga/iris_tcga.xml, tools/data_source_iris_tcga/tool_dependencies.xml
WIP, due to https://github.com/galaxyproject/tools-iuc/pull/605.
=> Add IRIS-TCGA data source tool.

packages/package_kraken_0_10_6_eaf8fb68/.shed.yml, packages/package_kraken_0_10_6_eaf8fb68/tool_dependencies.xml
=> Add package definition for kraken 0.10.6.

tools/fasta_nucleotide_color_plot/fasta_nucleotide_color_plot.xml
=> Fix tool id for fasta_nucleotide_color_plot

tools/stacks/stacks_procrad.xml
Still some work to be done tomorrow. The python wrapper will no longer be needed
=> Begin changes to process radtags (wip)

tools/hisat2/hisat2.xml
=> Use threads in the samtools view step.

tools/meme/meme.xml
We can use clusters, who cares about this restriction ;)
ping @gregvonkuster do you mind do merge this PR as your first one here.
=> Increase the maxsize by default.

packages/package_python_2_7_10_pybigwig_0_2_7/.shed.yml, packages/package_python_2_7_10_pybigwig_0_2_7/tool_dependencies.xml, packages/package_python_2_7_deeptools_2_2_2/tool_dependencies.xml
@bgruening Can you double check this?
=> Add pyBigWig-0.2.7 and update deepTools-2.2.2 to use it

tools/taxonomy/lca_wrapper/lca.py, tools/taxonomy/ncbi2tax/tool-data/ncbi_taxonomy.loc.sample, tools/taxonomy/poisson2test/poisson2test.py, tools/taxonomy/poisson2test/poisson2test.xml, tools/taxonomy/poisson2test/tool_dependencies.xml, tools/taxonomy/tax2tree/tax2tree.xml
=> fix some comments from myself

tools/taxonomy_krona_chart/tool_dependencies.xml
Hello,
I changed package version in `tool_dependencies.xml` to get the expected package in `taxonomy_krona_chart.xml`
Bérénice
=> Krona: Correct package version

tools/gatk2/gatk2_macros.xml
=> Add multiple="True" to input_variants param for GATK2

.travis.yml
Only if a tool was tested with planemo-test and only to TTS
=> Add automatic TTS push after

tools/vsearch/alignment.xml
Address comment from @jmchilton in https://github.com/galaxyproject/tools-iuc/commit/a4f87c1d61e50f7d799c4dde8c70c6fc789cc06f#commitcomment-16748640
=> Add optional output

packages/package_deseq2_1_10_0/tool_dependencies.xml, packages/package_trinity_2_1_1/tool_dependencies.xml
Reverts galaxyproject/tools-iuc#740
=> Revert "Trinity: fix wrong sha256sum"

tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/trinity.xml
Hi,
Here are some small changes to trinity: now it can have multiple input fastqs, and I fixed some option names too
=> Trinity: multiple input and small cosmetic changes

tools/stacks/stacks_procrad.xml
Just a PR to allow fasta input to process_radtags.
=> Stacks: allow fasta format for process_radtags

tools/trinity/run_DE_analysis.xml
This should fix: https://github.com/galaxyproject/tools-iuc/issues/746
ping @abretaud
=> Fix limma dependency

tools/bam_to_scidx/.shed.yml, tools/fasta_nucleotide_color_plot/.shed.yml
connecting to the tool's Java source code
=> Add homepage urls for 2 ChIP-exo tools

.travis.yml, data_managers/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py, data_managers/data_manager_hisat2_index_builder/data_manager/hisat2_index_builder.py, data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py, data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_download.py, data_managers/data_manager_snpsift_dbnsfp/data_manager/data_manager_snpsift_dbnsfp.py, datatypes/msa/stockholm_1_0/stockholm_1_0.py, datatypes/snpeff_datatypes/snpeff.py, datatypes/snpsift_dbnsfp_datatypes/snpsift_dbnsfp.py, datatypes/snpsift_dbnsfp_datatypes/tabular_to_dbnsfp.py, setup.cfg
First step for #467.
1439 errors/warnings remaining in `tools/`.
=> flake8 Python files in datatypes/ and data_managers/

packages/package_ncbi_vdb_2_6_2/.shed.yml, packages/package_ncbi_vdb_2_6_2/tool_dependencies.xml, packages/package_ngs_sdk_1_2_3/.shed.yml, packages/package_ngs_sdk_1_2_3/tool_dependencies.xml, packages/package_sra_toolkit_2_6_2/.shed.yml, packages/package_sra_toolkit_2_6_2/tool_dependencies.xml
This is the current version in bioconda. The update includes the dependent
packages in the same version used by the conda package.
Ping @bgruening @Takadonet
=> Update to version 2.6.2 of package_sra_toolkit

tools/bedtools/closestBed.xml, tools/bedtools/coverageBed.xml
Also quote datasets in closestBed command
=> Update coverageBed tool for changes in 2.24

tools/differential_count_models/rgedgeRpaired_nocamera.xml, tools/rglasso/rg_nri.xml, tools/stringtie/stringtie.xml, tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/run_DE_analysis.xml, tools/trinity/samples_qccheck.xml, tools/trinity/trinity.xml
Found with `planemo lint --doi` and https://github.com/galaxyproject/planemo/pull/484
=> Fix doi style citations.

.travis.yml
xref: https://github.com/galaxyproject/tools-iuc/issues/765
=> Travis MTS push

README.md
sould fix: https://github.com/galaxyproject/tools-iuc/issues/765
Nicola feel free to modify and merge.
=> Automatic push of tools

tools/hisat2/hisat2.xml
Should fix: https://github.com/galaxyproject/tools-iuc/issues/777
=> Fix hisat dependency

data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py
fixes the PEP8 warnings for the mothur data manager
=> fix PEP8 warnings mothur data manager

packages/package_lapack_3_4/tool_dependencies.xml
=> Lapack package: add lib path to LIBRARY_PATH too

packages/package_stacks_1_40/tool_dependencies.xml, tools/stacks/macros.xml, tools/stacks/stacks_assembleperead.xml, tools/stacks/stacks_cstacks.xml, tools/stacks/stacks_denovomap.xml, tools/stacks/stacks_genotypes.xml, tools/stacks/stacks_populations.xml, tools/stacks/stacks_procrad.xml, tools/stacks/stacks_pstacks.xml, tools/stacks/stacks_refmap.xml, tools/stacks/stacks_rxstacks.xml, tools/stacks/stacks_sstacks.xml, tools/stacks/stacks_ustacks.xml
=> Small fixes for stacks

packages/package_stacks_1_40/tool_dependencies.xml
=> stacks: fix wrong depot url

tools/stacks/tool_dependencies.xml
=> Stacks: fix indentation and package version

tools/stacks/stacks_refmap.xml
=> Stacks: remove a mysterious option that should not be there + add a missing one

packages/package_stacks_1_40/tool_dependencies.xml
Oops, a small typo in the depot url...
=> Fix stacks package path

packages/package_stacks_1_40/tool_dependencies.xml
Another install problem with stacks package
=> Fix bam.h not found during stacks compilation

packages/package_atlas_3_10/tool_dependencies.xml, packages/package_lapack_3_4/tool_dependencies.xml
=> Load cmake env before compiling lapack

packages/package_atlas_3_10/tool_dependencies.xml
This shold fix part of #815 issue
=> Fix for atlas compilation

.travis.yml, packages/package_r_edger_3_12_0/tool_dependencies.xml, tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/run_DE_analysis.xml, tools/trinity/tool_dependencies.xml
=> Fix Trinity dependencies

packages/package_atlas_3_10/tool_dependencies.xml
=> Fix package_atlas_3_10 installation issues

.tt_blacklist, tools/xpath/macros.xml, tools/xpath/xpath, tools/xpath/xpath.xml
For bxlab/galaxy_hackathon/issues/23
=> Xpath: conda testing

packages/package_samtools_0_1_19/tool_dependencies.xml, packages/package_stacks_1_40/tool_dependencies.xml, tools/stacks/macros.xml, tools/stacks/stacks_assembleperead.xml, tools/stacks/stacks_cstacks.xml, tools/stacks/stacks_denovomap.xml, tools/stacks/stacks_genotypes.xml, tools/stacks/stacks_populations.xml, tools/stacks/stacks_procrad.xml, tools/stacks/stacks_pstacks.xml, tools/stacks/stacks_refmap.xml, tools/stacks/stacks_rxstacks.xml, tools/stacks/stacks_sstacks.xml, tools/stacks/stacks_ustacks.xml
Several Stacks tools can print important things to the log, so we want to keep it too
=> Stacks: various fixes

.tt_blacklist, tools/raxml/test-data/RAxML_parsimonyTree.galaxy.multi
Enable automatic conda testing for raxml
=> Raxml: conda testing

.tt_blacklist, tools/art/art_454.xml, tools/art/art_illumina.xml, tools/art/art_solid.xml, tools/art/macros.xml
See https://github.com/bxlab/galaxy_hackathon/issues/23
I didn't update the galaxy package to match the newer bioconda version, so I guess we should wait tonight meeting before merging
=> Art: conda testing

tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/run_DE_analysis.xml, tools/trinity/samples_qccheck.xml
A small PR:
-better regex to avoid mixing datasets in data collections
-make datasets non visible outside data collections
=> Trinity: better output for run_DE_analysis

tools/meme/fimo.xml, tools/meme/fimo_wrapper.py
1. Change remove_duplicate_coords param from a boolean to a select list - works better in workflows
2. Add dest attribute to argparse arguments
=> Minor fixes for fimo version 4.11.0.3

README.md
=> Add gitter channel

tools/stacks/stacks_denovomap.xml, tools/stacks/stacks_ustacks.xml
Just a fix for a bug we found during the training
=> Small stacks bug

tools/meme/fimo.xml
This does not seem to affect the tool's behavior, but its a more ideal filter.
=> Clarify filtering methods for fimo options

tools/transdecoder/transdecoder.xml
=> Add --cpu option to TransDecoder

.tt_blacklist, packages/package_meme_4_11_1/tool_dependencies.xml, tools/meme/fimo.xml, tools/meme/meme.xml, tools/meme/test-data/fimo_output_html_1.html, tools/meme/test-data/fimo_output_html_2.html, tools/meme/test-data/fimo_output_xml_1.xml, tools/meme/test-data/fimo_output_xml_2.xml, tools/meme/test-data/meme_output_html_1.html, tools/meme/test-data/meme_output_html_2.html, tools/meme/test-data/meme_output_txt_1.txt, tools/meme/test-data/meme_output_txt_2.txt, tools/meme/test-data/meme_output_xml_1.xml, tools/meme/test-data/meme_output_xml_2.xml, tools/meme/tool_dependencies.xml
This now includes commits from #868.
Tests for meme will not pass until https://github.com/bioconda/bioconda-recipes/pull/1938 is merged.
=> Small meme cleanup + Update meme tools to version 4.11.1

packages/package_bwa_0_7_12/tool_dependencies.xml, packages/package_chemfp_1_1/tool_dependencies.xml, packages/package_flash_1_2_11/tool_dependencies.xml, packages/package_freetype_2_5_2_matplotlib_fix/tool_dependencies.xml, packages/package_galaxy_sequence_utils_1_0_1/tool_dependencies.xml, packages/package_gnu_coreutils_8_25/tool_dependencies.xml, packages/package_jbrowse_1_12_0/tool_dependencies.xml, packages/package_kraken_0_10_6_eaf8fb68/tool_dependencies.xml, packages/package_legacy_blast_2_2_22/tool_dependencies.xml, packages/package_libxslt_1_1_28/tool_dependencies.xml, packages/package_macs2_2_1_0_20151222/tool_dependencies.xml, packages/package_mothur_1_36_1/tool_dependencies.xml, packages/package_ncbi_vdb_2_5_2/tool_dependencies.xml, packages/package_ngs_sdk_1_1_3/tool_dependencies.xml, packages/package_python_2_7/tool_dependencies.xml, packages/package_r_2_11_0/tool_dependencies.xml, packages/package_r_2_15_0/tool_dependencies.xml, packages/package_r_3_0_3/tool_dependencies.xml, packages/package_r_3_1_0/tool_dependencies.xml, packages/package_r_3_1_1/tool_dependencies.xml, packages/package_r_3_1_2/tool_dependencies.xml, packages/package_r_3_2_1/tool_dependencies.xml, packages/package_rsem_1_2_28/tool_dependencies.xml, packages/package_sra_toolkit_2_5_2/tool_dependencies.xml, packages/package_stringtie_1_2_3/tool_dependencies.xml, packages/package_subread_1_4_6_p5/tool_dependencies.xml, packages/package_tophat_2_0_14/tool_dependencies.xml, packages/package_tpp_4_6_3/tool_dependencies.xml, packages/package_trinity_2_1_1/tool_dependencies.xml, packages/package_vsearch_1_9_7/tool_dependencies.xml
=> Add sha256sum and use https on download_by_url and download_file actions

packages/package_python_2_7_10_pybigwig_0_2_8/.shed.yml, packages/package_python_2_7_10_pybigwig_0_2_8/tool_dependencies.xml, packages/package_python_2_7_deeptools_2_3_0/.shed.yml, packages/package_python_2_7_deeptools_2_3_0/tool_dependencies.xml
This bumps the available packages for pyBigWig and deepTools to the most recent versions.
=> Update pyBigWig and deepTools to the latest versions

packages/package_gfclient_35x1/tool_dependencies.xml, packages/package_gfserver_35x1/tool_dependencies.xml, packages/package_tbl2asn_22_4/tool_dependencies.xml
Ping @erasche and @remimarenco.
=> Remove spaces in <url_template> as they are not supported in Galaxy

packages/package_deseq2_1_2_10/tool_dependencies.xml
=> Add XVector R dependency to package_deseq2_1_2_10

packages/package_deseq2_1_2_10/tool_dependencies.xml
Reported by @diehlsa  on https://github.com/galaxyproject/tools-iuc/issues/890#issuecomment-234230946 .
=> Add dependency on libxml2 for R XML package

tools/trinity/.shed.yml, tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/filter_low_expr_transcripts.xml, tools/trinity/gene_to_trans_map.xml, tools/trinity/run_de_analysis.xml, tools/trinity/samples_qccheck.xml
Just corrections for tool names from #894
=> Proper names for trinity tools

packages/package_numpy_1_9/tool_dependencies.xml, packages/package_python_2_7_numpy_1_9/tool_dependencies.xml
Depends on https://github.com/galaxyproject/cargo-port/pull/83
=> Upgrade numpy tarball for OS X compatibility.

packages/package_python_2_7_deeptools_2_3_3/.shed.yml, packages/package_python_2_7_deeptools_2_3_3/tool_dependencies.xml
=> add new deeptools version 2.3.3

packages/package_perl_xml_parser_expat_2_41/tool_dependencies.xml
Attempt to correct this issue: https://github.com/galaxyproject/galaxy/issues/1913#issuecomment-242829812 - ping @natefoo
=> Add dependency on expat version 2.1.0

tools/trinity/filter_low_expr_transcripts.xml
Just a little bugfix for the trinity filter script
=> Fix wrong option for trinity filter script

packages/package_stacks_1_40/tool_dependencies.xml
A little fix for #916 thanks to @yhoogstrate 
At some point we should update to 1.42 too, but I don't have the time right now
=> Fix for stacks compilation

.travis.yml, tools/bedtools/coverageBed.xml
Worked for a devteam PR at https://github.com/galaxyproject/tools-devteam/pull/386 thanks to @mvdbeek.
=> Update .travis.yml for latest Galaxy and Planemo enhancements.

packages/package_rpy2_2_7_8/.shed.yml, packages/package_rpy2_2_7_8/tool_dependencies.xml
This matches what is available in conda.
=> rpy2 2.2.7.8 package

tool_collections/snpeff/snpEff.xml, tool_collections/snpeff/snpEff_databases.xml, tool_collections/snpeff/snpEff_download.xml, tool_collections/snpeff/snpEff_macros.xml
Finish work started by @yhoogstrate in #928. I need this for #912.
=> Test snpEff in Conda

data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_color_space_index_builder.xml, data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.py, data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.xml, data_managers/data_manager_bowtie_index_builder/tool_dependencies.xml
This uses bowtie 1.1.2, which is also available in conda.
=> Datamanager bowtie update

packages/package_python_2_7_deeptools_2_3_5/.shed.yml, packages/package_python_2_7_deeptools_2_3_5/tool_dependencies.xml
=> Add deepTools 2.3.5

tools/bcftools/.shed.yml, tools/bcftools/bcftools_plugin_color_chrs.xml, tools/biom_format/.shed.yml, tools/datamash/.shed.yml, tools/deseq2/.shed.yml
Plus fix a bug in unreleased `bcftools_plugin_color_chrs` tool.
=> Fix more .shed.yml and URLS

tools/stacks/macros.xml, tools/stacks/stacks_assembleperead.xml, tools/stacks/stacks_cstacks.xml, tools/stacks/stacks_denovomap.xml, tools/stacks/stacks_genotypes.xml, tools/stacks/stacks_populations.xml, tools/stacks/stacks_procrad.xml, tools/stacks/stacks_pstacks.xml, tools/stacks/stacks_refmap.xml, tools/stacks/stacks_rxstacks.xml, tools/stacks/stacks_sstacks.xml, tools/stacks/stacks_ustacks.xml, tools/stacks/test-data/populations/batch_1.vcf, tools/stacks/tool_dependencies.xml
A PR to update stacks from 1.40 to 1.42.
Not ready to merge yet as there is a mysterious segfault for the populations command. I'll contact Stacks developer.
Also, I took the liberty to remove the tool_dependencies.xml file as I didn't have the courage to create a stacks_1_42 package (the compilation procedure changed a little). I can write it if some of you wish though. (But I hope you won't :smile: )
=> Stacks 1.42 update

.travis.yml
xref https://github.com/galaxyproject/tools-iuc/issues/961#issuecomment-249241697
=> Fail build if shed_lint fails

tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_macros.xml, tools/sra-tools/sra_pileup.xml
Default was 20G apparently ... .
May solve https://github.com/galaxyproject/galaxy/issues/2533#issuecomment-250280494 ?
ping @natefoo
=> Increase maximum download filesize to 200G and use new sra-tools version

tools/abyss/.shed.yml, tools/abyss/abyss-pe.xml
=> Fix scaffolding with long sequences

tools/pilon/pilon.xml
* Cosmetic fix to label of reference genome
* Note new 'circles' fix, not implemented yet
=> Update pilon requirement to v 1.20

.travis.yml
Workaround for https://github.com/galaxyproject/planemo/issues/588.
Ping @peterjc.
=> Add master branch to git repository when fixing TRAVIS_COMMIT_RANGE

tools/bedtools/annotateBed.xml, tools/bedtools/clusterBed.xml, tools/bedtools/coverageBed.xml, tools/bedtools/genomeCoverageBed.xml, tools/bedtools/jaccardBed.xml, tools/bedtools/macros.xml, tools/bedtools/mapBed.xml, tools/bedtools/mergeBed.xml, tools/bedtools/multiCov.xml, tools/bedtools/multiIntersectBed.xml, tools/bedtools/sortBed.xml, tools/bedtools/unionBedGraphs.xml
-- to check if the new travis-ci procedure works.
=> Remove trailing whitespaces in bedtools

.travis.yml
Tweak for #998 from @nsoranzo to resolve https://github.com/galaxyproject/planemo/issues/588
Fix needs to use ``origin/master`` as per Nicola's comment https://github.com/galaxyproject/planemo/issues/588#issuecomment-252275927
=> TravisCI: Workaround for force updated branches

tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_macros.xml, tools/sra-tools/sra_pileup.xml
One more fix for https://github.com/galaxyproject/galaxy/issues/2533#issuecomment-255220589
=> Use exit code for determining sratools failure

tools/bedtools/bedToIgv.xml, tools/bedtools/test-data/igv_bed_script.txt
Handy if you need to take a lot screenshots.
=> Add bedToIgv tool

tools/prokka/readme.rst
=> Update Prokka readme

tools/featurecounts/featurecounts.xml, tools/featurecounts/tool-data/gene_sets.loc.sample, tools/featurecounts/tool_data_table_conf.xml.sample
This implements my request in #1016, namely that featureCounts support datatables, so people needn't keep uploading the same GTF file.
=> datatable support in featureCounts

packages/package_bioconductor_edger_3_14_0/tool_dependencies.xml
https://github.com/galaxyproject/cargo-port/pull/106
=> edgeR : Update limma sha256sum

packages/package_bioconductor_limma_3_28_10/tool_dependencies.xml
https://github.com/galaxyproject/cargo-port/pull/107
💤
=> Limma update shasum

tools/trinotate/.shed.yml
https://github.com/galaxyproject/tools-iuc/pull/1030
One more commit 👍
=> trinotate add a .shed.yml

packages/package_python_2_7_deeptools_2_4_0/.shed.yml, packages/package_python_2_7_deeptools_2_4_0/tool_dependencies.xml
=> Add deepTools-2.4.0

packages/package_stringtie_1_2_3/tool_dependencies.xml
=> Add zlib set_environment_for_install to package_stringtie_1_2_3

tools/jbrowse/jbrowse.py, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml, tools/jbrowse/readme.rst, tools/jbrowse/test-data/track_config/test.xml
A tiny fix for a problem with the jbrowse script and python3...
=> Jbrowse: python3 + new options

tools/cwpair2/cwpair2.xml, tools/cwpair2/cwpair2_macros.xml, tools/cwpair2/tool_dependencies.xml
This should not depend on anaconda, which is one GB in size.
=> Cwpair2 conda

tools/trinity/filter_low_expr_transcripts.xml
We are just finishing one week of training around many subjects.
And for sure, we will propose some minor PR around Trinity wrappers.
=> filter_low_expr_transcripts change output format

data_managers/data_manager_bwameth_index_builder/tool_data_table_conf.xml.sample, tools/bwameth/tool_data_table_conf.xml.sample
Followup to #893 
Before uploading the data managers by hand we better also update the bwameth data manager.
=> No duplicate entries for bwameth data table

tools/blastxml_to_gapped_gff3/.shed.yml, tools/blastxml_to_gapped_gff3/blastxml_to_gapped_gff3.py, tools/blastxml_to_gapped_gff3/blastxml_to_gapped_gff3.xml
The tool was actually never tested in #1068 due to the problem introduced in #1067 and fixed in #1079.
=> Fix blastxml_to_gapped_gff3

CONTRIBUTING.md
Updated to point to new Galaxy docs
=> Update link for Best Practices page

tools/qiime/align_seqs.xml, tools/qiime/alpha_diversity.xml, tools/qiime/alpha_rarefaction.xml, tools/qiime/assign_taxonomy.xml, tools/qiime/beta_diversity.xml, tools/qiime/beta_diversity_through_plots.xml, tools/qiime/count_seqs.xml, tools/qiime/macros.xml, tools/qiime/tool_dependencies.xml
Hi,
I started to rework and clean the QIIME wrapper few month ago. This work can be useful for the next week contribution fest #1078 
Bérénice
=> Work on Qiime

tools/qiime/generate_test_data.sh, tools/qiime/test-data/map.tsv.html, tools/qiime/validate_mapping_file.xml
Hi,
I clean the wrapper for `validate_mapping_file.xml` and I add a `bash` script to keep track on how the test data are generated. 
Bérénice
=> QIIME: validate_mapping_file wrapper

packages/package_python_2_7_deeptools_2_4_2/.shed.yml, packages/package_python_2_7_deeptools_2_4_2/tool_dependencies.xml
This adds deepTools-2.4.2, which contains a few bug fixes.
This should already be available in bioconda.
=> Add deepTools-2.4.2

tools/sickle/sickle.xml
Followup to https://github.com/galaxyproject/tools-iuc/pull/1139
ping @nsoranzo
=> Use sanger option if not solexa or illumina datatype

tools/qiime/qiime_core/beta_diversity_through_plots_html_generation.py, tools/qiime/qiime_core/jackknifed_beta_diversity_output_management.py
Hi,
I fixed flake8 linting for 2 python scripts.
Bérénice
=> QIIME: fix flake8

tools/ebi_tools/ebeye_urllib.py, tools/ebi_tools/ebi_search_rest_results.xml, tools/ebi_tools/generate_macros.py, tools/ebi_tools/macros.xml
Hi,
I updated the options in macros file and I fixes some Python stuff.
Bérénice
=> Fixes in EBI Search tool

data_managers/data_manager_plant_tribes_scaffolds_downloader/.shed.yml
Somehow I missed this file - sorry!
=> Add .shed.yml for data_manager_plant_tribes_scaffolds_downloader

tools/blastxml_to_gapped_gff3/blastxml_to_gapped_gff3.py
Just fixing the shebang until perl is compatible with python code :)
=> Blastxml_to_gapped_gff3: fix wrong shebang

data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.py, data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.xml
to install default configuration files along with the scaffolds data.
=> Enhance the data_manager_plant_tribes_scaffolds_download tool

tools/bwameth/bwameth.xml
without these options it gets into legacy mode and the tool break
see: https://github.com/samtools/samtools/issues/349
=> samtools 1.2 needs more params to reliably sort

packages/package_python_2_7_deeptools_2_5_0/.shed.yml, packages/package_python_2_7_deeptools_2_5_0/tool_dependencies.xml
This adds deepTools-2.5.0, which should be available in bioconda shortly.
=> Add deepTools-2.5.0

data_managers/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.xml
=> quotes are already returned as part of the string

tools/stacks/macros.xml
Without this I'm getting an unauthorized request error when trying to run the tool.
=> Fix stacks container requirement.

data_managers/data_manager_bwameth_index_builder/data_manager/bwameth_index_builder.py
before this patch the data manager fails with a key not found dict error
=> fixes for broken bwameth datamager 

data_managers/data_manager_picard_index_builder/data_manager/picard_index_builder.py
The wrapper was still adjusted to the tool shed package.
Fixes https://github.com/galaxyproject/galaxy/issues/3907
=> Fix picard index builder

tools/hisat2/hisat2.xml, tools/hisat2/hisat2_macros.xml
This is a follow up to #1245 that includes fixes that were mentioned by @nsoranzo.
=> Fixes, courtesy of @nsoranzo

tools/picard/picard_CollectRnaSeqMetrics.xml, tools/picard/picard_MarkDuplicates.xml
Included help section description and optional BARCODE_TAG option available in 2.7.1.
=> Added BARCODE_TAG option.

data_managers/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py
Introduced in https://github.com/galaxyproject/tools-iuc/pull/26 .
=> Fix data table name in data_manager_snpEff_databases.py

tools/trinity/analyze_diff_expr.xml
fix issue https://github.com/galaxyproject/tools-iuc/issues/1275
=> Trinity / analyze_diff_expr: fix issue

tools/freebayes/freebayes.xml
old method always examined all entries in bam file, 
this method respect the user's entry to target or region fields
=> Freebayes regionfix

tool_collections/samtools/bam_to_cram/.shed.yml, tool_collections/samtools/cram_to_bam/.shed.yml
these were never uploaded to TTS or MTS so we can change safely
=> change owner of bam_to_cram and cram_to_cam

tools/spades/spades.xml
Added the tabular stats outputs that are mentioned in the help section
and were in the original tool wrapper.
=> SPAdes - Add tabular stats outputs

.travis.yml, tools/bedtools/macros.xml
track new Galaxy version in our testing setup.
=> track release_17.05

.travis.yml
Qiime and mothur are merged. Now we can cleanup python files if needed.
=> activate pep8 testing again

tools/stacks/stacks_clonefilter.xml
There was a serious typo on my submission:
fastqsangergz -> fastqsanger.gz
This PR corrects it.
Thanks
=> Correcting a bug on the fastqsanger.gz output datatype

tools/stacks/stacks_clonefilter.xml
This corrects a bug with barcoding
=> corrects a bug with barcoding

tools/fastqc/rgFastQC.xml
That should help building a multiqc report.
Ping @nekrut
=> Use element identifier when building report

tools/mothur/make.shared.xml, tools/mothur/summary.single.xml, tools/mothur/unifrac.weighted.xml
fixes for 3 small bugs reported by @arbernard (thanks!)
=> Mothur: small bugfixes

data_managers/data_manager_bowtie_index_builder/tool_dependencies.xml
bowtie 1.1.2 is available in bioconda. I tested this manually, all is working well.
=> Condafy bowtie datamanager

tools/goseq/goseq.xml
and remove mention of getgo tool that never materialized.
=> Fix nobias variable in goseq tool

tools/fasta_nucleotide_color_plot/fasta_nucleotide_color_plot.xml
Also apply standard discussed here https://github.com/galaxy-iuc/standards/issues/43
=> Add detect_errors command attribute to fasta_nucleotide_color_plot

tools/tag_pileup_frequency/tag_pileup_frequency.xml
Also apply standard discussed here https://github.com/galaxy-iuc/standards/issues/43
=> Add detect_errors command attribute to tag_pileup_frequency

tools/meme/fimo.xml, tools/meme/macros.xml, tools/meme/meme.xml, tools/meme/test-data/fimo_output_html_1.html, tools/meme/test-data/fimo_output_html_2.html, tools/meme/test-data/fimo_output_xml_1.xml, tools/meme/test-data/fimo_output_xml_2.xml, tools/meme/test-data/meme_output_html_1.html, tools/meme/test-data/meme_output_html_2.html, tools/meme/test-data/meme_output_txt_1.txt, tools/meme/test-data/meme_output_txt_2.txt, tools/meme/test-data/meme_output_xml_1.xml, tools/meme/test-data/meme_output_xml_2.xml, tools/meme/tool_dependencies.xml
and update requirements to meme 4.11.2 and graphicsmagick to 1.3.23
=> Condafy meme and fimo

tools/snp-sites/.shed.yml, tools/snp-sites/snp-sites.xml, tools/snp-sites/test-data/input.fasta, tools/snp-sites/test-data/output.fasta, tools/snp-sites/test-data/output.phylip, tools/snp-sites/test-data/output.vcf, tools/spades/spades.xml
Source: https://github.com/sanger-pathogens/snp-sites
Conda recipe provided by authors
=> SNP-sites tool

tools/metaphlan2/metaphlan2.xml
format should be `biom1` not `biom`
also some small [stylefixes](https://github.com/galaxy-iuc/standards/issues/43)
ping @bebatut
=> MetaPhlAn2: fix biom output format

tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_pileup.xml
I initially expected the tools to take a .sra file as input
=> adds "download" to tool names

tools/hisat2/hisat2.xml, tools/hisat2/hisat2_macros.xml
Also add some `argument` attributes.
Fix https://github.com/galaxyproject/tools-iuc/issues/1406 .
Ping @chambm.
=> Fix default values for some hisat2 options

tools/deseq2/deseq2.xml
=> Add missing r-getopt requirement for deseq2

tool_collections/kraken/kraken/kraken.xml, tool_collections/kraken/kraken_filter/kraken-filter.xml, tool_collections/kraken/kraken_report/kraken-mpa-report.xml, tool_collections/kraken/kraken_report/kraken-report.xml, tool_collections/kraken/kraken_translate/kraken-translate.xml, tool_collections/kraken/macros.xml
I updated the version to 1.2.3 so that all of the kraken wrappers will get an update, since one of them was previously already 1.2.2 and the others were 1.2.1
I also granted iuc write access to the four repositories, so that will actually work. 
This will enable toolshed installation of the condafied krakens.
=> Bump kraken versions to create new installable revisions in toolshed.

tool_collections/bamtools/bamtools_filter/bamtools-filter.xml
Fix https://github.com/galaxyproject/tools-devteam/issues/484.
=> Add + and - as allowed filtering tag.

tools/mothur/classify.seqs.xml
also the mothur documentation refers to wang (https://mothur.org/wiki/Classify.seqs)
=> version 1.28.0 changed name of bayesian method to wang

tools/iwtomics/loadandplot.xml
Fixed a bug about optional input fields.
If a value has not been selected in an optional input field, do not send it as parameter to the tool executable.
=> IWTomics bug fix

.travis.yml, data_managers/data_manager_qiime_database_downloader/data_manager/data_manager_qiime_download.py, datatypes/msa/stockholm_1_0/stockholm_1_0.py, datatypes/snpeff_datatypes/snpeff.py, tools/extract_genomic_dna/extract_genomic_dna.py, tools/fastqc/rgFastQC.py, tools/gff3_rebase/gff3_rebase.py, tools/ngsutils/filter.py, tools/query_tabular/load_db.py
Stop checking `deprecated/` directory.
Fix https://github.com/galaxyproject/tools-iuc/issues/1530
=> Fix new linting errors for flake8 3.5.0

tools/multiqc/multiqc.xml
Fixes #1540 by adding brackets to designate the variable name.
=> Fixes #1540 - MultiQC featureCounts module

data_managers/data_manager_mothur_toolsuite/.shed.yml, data_managers/data_manager_mothur_toolsuite/data_manager/data_manager_fetch_mothur_reference_data.xml, data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py
A few changes to the mothur data manager as I needed it on our instance. I'm not sure of the status of this data manager currently, here's the PR anyway.
As there was no .shed.yml it was not available in toolshed, so I added the file.
I also added newer data to the option + various small fixes
=> Mothur data manager fixes

data_managers/data_manager_rsync_g2/data_manager/data_manager_rsync.py, data_managers/data_manager_rsync_g2/data_manager/data_manager_rsync.xml
There are existing newerish Galaxy framework bugs preventing this data manager from working:
- https://github.com/galaxyproject/galaxy/issues/4810
- https://github.com/galaxyproject/galaxy/issues/4809
=> Fix g2 rsync data manager.

tools/flash/flash.xml
Reason is that parse out "Read combination statistics" in downstream analyses.
=> save stdout to separate dataset

tools/stringtie/macros.xml, tools/stringtie/stringtie.xml, tools/stringtie/test-data/cached_locally/gene_sets.loc, tools/stringtie/test-data/cached_locally/ref.gtf, tools/stringtie/test-data/deseq2/gene_counts.tsv, tools/stringtie/test-data/deseq2/transcript_counts.tsv, tools/stringtie/test-data/stringtie_out6.gtf, tools/stringtie/tool_data_table_conf.xml.sample, tools/stringtie/tool_data_table_conf.xml.test
This PR has the changes from this fix https://github.com/galaxyproject/tools-iuc/pull/1517 plus some more suggested modifications for StringTie.
=> StringTie modifications

tool_collections/snpeff/snpEff.xml, tool_collections/snpeff/snpEff_databases.xml, tool_collections/snpeff/snpEff_download.xml, tool_collections/snpeff/snpEff_macros.xml
Introduced in commit 4777de05ef35a3b4603a20b31acb28f3d032b54b .
=> Fix non-existing Conda version

tools/hisat2/hisat2.xml
Is this ok?
It was pretty confusing for a few of our users to have spliced alignments deactivated by default.
=> change defaults for spliced alignments

tools/mothur/pcr.seqs.xml
=> mothur pcr.seqs: also allow unaligned fasta input

tools/featurecounts/featurecounts.xml
Added a few missing options, `--fracOverlap`, `--fracOverlapFeature`,
and `--byReadGroup`.
=> Upgrade featurecounts to 1.6.0

tools/multiqc/multiqc.xml
The EnginesOn start-up project is now the Enancio start-up
=> Update original affiliation

tools/jbrowse/jbrowse.xml, tools/jbrowse/readme.rst, tools/jbrowse/test-data/all_fasta.loc, tools/jbrowse/test-data/gencode/test-data_table.xml, tools/jbrowse/tool_data_table_conf.xml.test
A quick fix for the bug reported in https://github.com/galaxyproject/tools-iuc/issues/1559#issuecomment-344786612
Added a test case too
=> JBrowse: fix error with built-in genome

tools/sra-tools/sam_dump.xml
fixes: https://github.com/galaxyproject/tools-iuc/issues/1445
=> remove header option from SRA

tools/rseqc/geneBody_coverage.xml, tools/rseqc/junction_annotation.xml, tools/rseqc/read_quality.xml, tools/rseqc/rseqc_macros.xml
Now that MultiQC is available, it's much more efficient to run Gene Body Coverage in batch mode and use MultiQC to combine the plots.
=> Allow both batch and merged mode for RSeQC Gene Body Coverage

tools/annotatemyids/.shed.yml
Change categories to have new official category "Genome annotation"
=> fix category in annotatemyids .shed.yml

tools/iqtree/iqtree.xml
Fixes related to conflicting bootstrap and modelling parameters, as well as flags for supplementary trees.
=> Fix IQTree - conflicting params

tools/unicycler/unicycler.xml
Hi,
I worked a bit on the wrapper of Unicycler
- Fix some options that were not correctly taken into account in the command
- Format a bit (mostly the indentation in the command section)
- Add default values to some params and remove their "optionality"
- Fix paired collection
- Move some params to sections
Berenice
=> Unicycler fixes

tools/bcftools/macros.xml
Forgot two lines where  '&&' were missing.
=> Fix macros.xml when input was *_bgzip files

tools/bedtools/coverageBed.xml, tools/bedtools/intersectBed.xml
This is intended to allow bedtools to create multiple output files (one for each input B)
=> add reduce/iterate conditional to bedtools

tools/bedtools/nucBed.xml
=> Update nucBed.xml typo fix

data_managers/data_manager_manual/.shed.yml, data_managers/data_manager_manual/README, data_managers/data_manager_manual/data_manager/data_manager_manual.py, data_managers/data_manager_manual/data_manager/data_manager_manual.xml, data_managers/data_manager_manual/data_manager_conf.xml, data_managers/data_manager_manual/tool_data_table_conf.xml.sample
Allows manually building data table entries and optionally providing filesystem content.
=> Add a Manual Data Manager.

tools/ucsc_tools/fasplit/fasplit.xml, tools/ucsc_tools/twobittofa/twobittofa.xml
Fix https://github.com/galaxyproject/tools-iuc/issues/1689
=> UCSC tools: update package version

tools/macs2/macs2_callpeak.xml
fixes: https://github.com/galaxyproject/tools-iuc/pull/1698
=> Clarify for MACS2 that no pdf is produced if no model or BAMPE is selected

.travis.yml
=> update conda version

tools/onto_toolkit/get_ancestor_terms.xml
was text -> now obo (was probably forgotten)
=> fix get_ancestor_terms input type

tools/mageck/mageck_count.xml, tools/mageck/mageck_mle.xml, tools/mageck/mageck_pathway.xml, tools/mageck/mageck_test.xml, tools/mageck/test-data/out.count.bam.txt, tools/mageck/test-data/out.count.fastq.txt
Found some things that needed fixing and made some small improvements.
I assume I need to update the wrapper version for this but do I update it in all the .xmls or just somewhere in the macros.xml? (I only modified some xmls and to varying degrees, ranging from cosmetic changes to changing defaults, so am not sure what version changes to make here.)
=> Fixes for MAGeCK

tools/bedtools/coverageBed.xml, tools/bedtools/macros.xml
also fixes gff and gff3 output sorting
=> adds -sorted support for bedtool coverage when using bams

tools/msaboot/msaboot.xml
Incremented version number for msaboot wrapper due to small bug fix in the source code.
=> msaboot - increment version (bug fix)

tools/hicexplorer/macros.xml
=> Update to version 2.1

packages/package_python_2_7/tool_dependencies.xml
=> Setuptools url fix

tools/featurecounts/featurecounts.xml, tools/featurecounts/gene_sets.loc, tools/featurecounts/gene_sets.loc.sample, tools/featurecounts/test-data/featurecounts_anno.loc, tools/featurecounts/test-data/gene_sets.loc, tools/featurecounts/tool-data/featurecounts_anno.loc.sample, tools/featurecounts/tool_data_table_conf.xml.sample, tools/featurecounts/tool_data_table_conf.xml.test
This PR is a start towards a fix for https://github.com/galaxyproject/tools-iuc/issues/1754 as reported by @jennaj
=> featureCounts fix - require active selection of built-in annotation

tools/trinotate/trinotate.xml
The quick fix for https://github.com/galaxyproject/tools-iuc/issues/1770
=> Trinotate: fix sqlite database url

tools/mothur/chimera.uchime.xml
@nsoranzo this should fix the failing test you mentioned on gitter
=> mothur: fix filter

tools/hisat2/hisat2.xml
=> Fix advanced scoring options in Hisat2

tools/umi_tools/umi-tools_whitelist.xml
Linking for non-gz files fixed
=> Fix to umi_tools whitelist

tools/hmmer3/alimask.xml, tools/hmmer3/hmmalign.xml, tools/hmmer3/hmmbuild.xml, tools/hmmer3/hmmconvert.xml, tools/hmmer3/hmmemit.xml, tools/hmmer3/hmmfetch.xml, tools/hmmer3/hmmscan.xml, tools/hmmer3/hmmsearch.xml, tools/hmmer3/jackhmmer.xml, tools/hmmer3/macros.xml, tools/hmmer3/nhmmer.xml, tools/hmmer3/nhmmscan.xml, tools/hmmer3/phmmer.xml, tools/hmmer3/test-data/MADE1.nhmmscan_out, tools/hmmer3/test-data/MADE1.nhmmscan_out.aliscoresout, tools/hmmer3/test-data/MADE1.nhmmscan_out.dfamtblout, tools/hmmer3/test-data/MADE1.nhmmscan_out.tblout, tools/hmmer3/test-data/nhmmer.out.dfamtblout, tools/hmmer3/test-data/nhmmer.out.tblout
=> Multiple HMMER3 fixes

tools/umi_tools/macros.xml, tools/umi_tools/umi-tools_extract.xml, tools/umi_tools/umi-tools_whitelist.xml
* Added paired inputs for `extract`
* Macrofied common options for `extract` and `whitelist`
* Only `extract` wrapper version has been bumped due to added functionality.
=> Fix to umi_tools

tools/meme/meme.xml
Fix https://github.com/galaxyproject/galaxy/issues/5966 .
=> Fix meme BibTeX citation

tools/codeml/codeml.xml, tools/codeml/test-data/1_codeml.ctl, tools/codeml/test-data/2_codeml.ctl, tools/codeml/test-data/3_codeml.ctl, tools/colibread/takeabreak.xml, tools/dexseq/.shed.yml, tools/disco/README.rst
discovered by planemo shed_lint.
=> Fix linting issues

tools/repeatmasker/repeatmasker.xml, tools/repeatmasker/test-data/fake_repbase.embl, tools/repeatmasker/test-data/small.fasta.stats, tools/repeatmasker/test-data/small_repbase.fasta.log, tools/repeatmasker/test-data/small_repbase.fasta.stats
Hey,
I found some issues with the new RepeatMasker (thanks for updating it @pvanheus!), so here's PR to fix them.
I also added a (hacky) test case for the RepBase, with a fake embl file (just a tiny extract from the dfam embl file bundled with repeatmasker).
=> RepeatMasker: small bug fixes

tools/featurecounts/featurecounts.xml
To fix https://github.com/galaxyproject/tools-iuc/issues/1859 reported by @lparsons and @nsoranzo
=> FeatureCounts: remove dbkey requirement for bam files and history GTF

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml, tools/limma_voom/test-data/out_rscript.txt
=> Limma-voom: Output heatmap for top genes

tools/cutadapt/cutadapt.xml, tools/cutadapt/macros.xml
- use element_identifer in input filename (@lparsons suggestion here: https://github.com/galaxyproject/tools-iuc/pull/1821#issuecomment-381175523)
- add mention of MultiQC to report output help
=> Cutadapt: Add element_identifier for MultiQC

tools/fastqc/rgFastQC.xml
FastQC release 0.11.7 fixes a bug dealing with short sequences. No changes to the interface.
=> Update FastQC to 0.11.7 bugfix release

tools/bowtie2/bowtie2_macros.xml, tools/bowtie2/bowtie2_wrapper.xml
=> Bowtie2 properly set dbkey on outputs

tools/rgrnastar/macros.xml, tools/rgrnastar/rg_rnaStar.xml
Like #1902 and #1927 but for STAR.
=> STAR properly set dbkey on outputs

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml
- Make file input more robust eg to quotes in gene descriptions (otherwise can get issues with NAs etc)
- Add option to output file with library size information
- Also output before norm.factors for individual sample MD plots
=> Limma-voom: small improvements

tools/cutadapt/cutadapt.xml
We can't really test this since the testing framework sets GALAXY_SLOTS to 1, but I've tested this locally and all tests pass.
Fixes #1934.
=> Fix cutadapt in multicore mode

tool_collections/snpeff/snpEff.xml
Useful for downstream analysis with multiqc
=> Adds csvStats option to snpEff

tools/hivclustering/.shed.yml
=> Fix hivclustering .shed.yml URLs.

tools/pygenometracks/pyGenomeTracks.xml
Adding a hot fix to display the labels for x-axis on top or bottom.
=> [pyGenomeTracks] Adding top/bottom hotfix

data_managers/data_manager_build_kraken_database/data_manager/kraken_database_builder.xml, data_managers/data_manager_build_kraken_database/data_manager_conf.xml
Hi I got some error when running the kraken database builder, so I figured the best way forward was to update to the next stable release of kraken. Currently it depends on some weird in between versions version.
=> update kraken version

data_managers/data_manager_build_kraken_database/data_manager/kraken_database_builder.xml
Whoops did not properly do my research.
Rest of the interface has not changed so this should fix any issues.
=> fix options to match options in kraken >1.0

data_managers/data_manager_star_index_builder/data_manager/rna_star_index_builder.xml
This is required if building large or complex genomes.
=> Provide parameter for rnastar index builder to increase available RAM

tools/bedtools/flankBed.xml
It was a bit tricky figure out what "Genome file" means in this case. So I clarified with "bedTool genome file" and also a description by Jennifer Hillman Jackson on how to get it (which is how I got mine to run the tool).
* [X ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
A very minor alteration of the help text to help researchers using the tool for the first time.
FOR REVIEWER:
=> Describe Genome files

data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.py, data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.xml
for data_manager_plant_tribes_scaffolds_download
FOR REVIEWER:
=> Update scaffold download source

tools/velvet_optimiser/velvetoptimiser.xml
=> fixing old velveth optimiser

tools/trinity/abundance_estimates_to_matrix.xml, tools/trinity/align_and_estimate_abundance.xml, tools/trinity/macros.xml
=> trinity 2.8.2 is available

tools/structure/structure.xml
Fix https://github.com/galaxyproject/tools-iuc/issues/2004
=> Fix tool Structure output file names for tool structureHarvester

tool_collections/snpeff/snpeff_get_chr_names.xml
they are case sensitive I think
=> snpeff - fix macro token names

tools/sra-tools/sra_macros.xml
=> bump SRA tools

tools/plasflow/.shed.yml, tools/plasflow/plasflow.xml
Toolshed upload failed on original merge of tool because of lack of output during the conda creation step ([travis build log](https://travis-ci.org/galaxyproject/tools-iuc/jobs/425191861)), this PR is mainly to test if it succeeds against latest master with the new channel order 
ping @bgruening @willemdek11
=> Plasflow: test the travis test

CONTRIBUTING.md
FOR REVIEWER:
I think tools-iuc have this policy already, this just makes it more explicit than just the PR checklist.
=> adds license guidelines, fixes #2054

tools/gemini/gemini_macros.xml, tools/gemini/gemini_query.xml, tools/gemini/gemini_stats.xml, tools/iqtree/iqtree.xml, tools/iqtree/iqtree_macros.xml, tools/shovill/shovill.xml, tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_macros.xml, tools/sra-tools/sra_pileup.xml
=> Make certain tools conform to IUC best practices

tools/gemini/gemini_gene_wise.xml
should have been part of #2133
=> IUC best practices for gemini_gene_wise wrapper

tools/nanoplot/nanoplot.xml
=> Nanoplot: add threads parameter

tools/metaspades/metaspades.xml
* [ x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x] - License permits unrestricted use (educational + commercial)
* [x ] - This PR updates an existing tool or tool collection
FOR REVIEWER:
=> Update metaSpades to show fastg file

tools/meme_chip/meme_chip.xml
This closes #1891 
FOR REVIEWER:
=> Fix meme_chip

tools/bedtools/mapBed.xml
=> Samtools view bed fix

tools/kallisto/kallisto_quant.xml
this is an important missing parameter
=> kallisto quant: add strand specificity options and test

macros/read_group_macros.xml
Fixes https://github.com/galaxyproject/tools-iuc/issues/1736
=> added prefilled text

tools/volcanoplot/volcanoplot.R
=> Volcano plot: Fix for labelling significant

tools/limma_voom/limma_voom.xml
=> Limma: update to v3.36.5 and update dependencies

tools/mageck/mageck_macros.xml
=> Mageck: update to v0.5.8

tools/goenrichment/goenrichment.xml
* [ x ] - This PR updates an existing tool or tool collection
Just added a name to the output label to make it more distinguishable.
=> Goenrichment

tools/slamdunk/slamdunk.xml
=> Slamdunk: Add GALAXY_SLOTS

tools/snippy/snippy.xml, tools/snippy/test-data/fna_ref/snps.gff, tools/snippy/test-data/fna_ref/snps.txt, tools/snippy/test-data/gbk_ref/snps.gff, tools/snippy/test-data/gbk_ref/snps.txt, tools/snippy/test-data/map_qual/snps.gff, tools/snippy/test-data/map_qual/snps.txt, tools/snippy/test-data/min_cov/snps.gff, tools/snippy/test-data/min_cov/snps.txt, tools/snippy/test-data/min_frac/snps.gff, tools/snippy/test-data/min_frac/snps.txt
=> Fix Snippy Paired Collection Handling

tools/gemini/gemini_load.xml
=> Point out CADD scores licensing issue

tools/progressivemauve/progressivemauve.xml
=> Fix output_backbone copypasta

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml
- Update to v3.38.3 and update dependencies
- Add similar changes as for edgeR here: https://github.com/galaxyproject/tools-iuc/pull/2284#partial-pull-merging
- Bug fix if using other FDR methods
- Clarify naming of groups etc
=> limma-voom: update to v3.38.3

tools/goseq/goseq.xml
=> goseq: update to v1.34.0

tools/egsea/egsea.xml
=> EGSEA: update to v1.10.0

tools/unicycler/unicycler.xml
=> udpate unicycler to latest version

tools/volcanoplot/volcanoplot.R, tools/volcanoplot/volcanoplot.xml
=> Volcanoplot: add options for no label boxes and custom axis limits

tools/megahit/.shed.yml
Forgot to update the .yaml description. 
=> updated MEGAHIT description to say version 1.1.3

tools/jbrowse/jbrowse.py, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml
Just some small changes to add needed options for the new track types.
=> Jbrowse: small fixes

.travis.yml, tools/busco/busco.xml
=> r-ggplot2 is part of the conda package

tools/dexseq/macros.xml
=> dexseq  1.28.1

tools/collection_column_join/collection_column_join.xml
I've had a few users a little confused by this tool so have made some small edits to try to clarify
Is this ok with you @abretaud?
=> Collection column join: small changes to parameter text

.travis.yml, tools/annotatemyids/annotateMyIDs.xml
Fix for https://github.com/galaxyproject/tools-iuc/issues/2319
=> Annotatemyids: fix for header

tool_collections/vcflib/vcffilter/vcffilter.xml
=> Update VCFFilter documentation on logical negation

tools/goseq/goseq.r, tools/goseq/goseq.xml
=> goseq: small modifications to top 10 plot

tools/megahit_contig2fastg/megahit_contig2fastg.xml
=> add fastg datatype specification to MEGAHIT_contig2fastg

tools/ggplot2/ggplot_point.xml, tools/ggplot2/macros.xml
- fix variable names for colors when plotting factors 
- allow the use of float for xy_scaling 
- add an option to plot points and/or lines 
=> Update the gg_point tool

tools/berokka/berokka.xml
Changes:
- Remove version field from "perl-bioperl" requirement. For some
reason it caused the environment to become unsolvable.
- Add requirement for blast
=> Requirements Fix

tools/ggplot2/ggplot_point.xml
=> correct typo in a condition to plot factors on  multiple plots

tools/ggplot2/ggplot_histogram.xml
=> ggplot_histogram.xml minor typo in help

tools/snippy/snippy.xml, tools/snippy/test-data/b_2_fna_ref_mincov_2_minqual_60.snps.gff
=> Fix handling of single/paired_interleaved inputs

tools/bowtie2/bowtie2_wrapper.xml
=> Bump up bowtie2 version and fix sam filter in advanced mode

tools/multiqc/readme.rst
'fixes' https://github.com/galaxyproject/tools-iuc/issues/2362
=> Describe fix for multiqc encoding problem

tool_collections/vcflib/vcffilter/vcffilter.xml
Fixing indentations causing rendering issues.
=> Update VCFFilter wrapper.

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml
- Plot -log10(Pvalue) instead of lods as no lods after treat
- Change Glimma plots to use logCPM for counts instead of raw counts
=> Limma: small change to glimma plots

tool_collections/kraken2/kraken2/kraken2.xml, tool_collections/kraken2/macros.xml
=> update kraken2 to version 2.0.8_beta

tools/fgsea/fgsea.R, tools/fgsea/fgsea.xml
Need to set seed for reproducibility https://github.com/ctlab/fgsea/issues/1
=> Fgsea:set seed

tool_collections/vcflib/vcffilter/test-data/vcffilter-test2.vcf, tool_collections/vcflib/vcffilter/vcffilter.xml
Extend #2385 to add test case for vcffilter for invert tool parameter.
=> vcffilter touch up

tools/bandage/bandage_image.xml, tools/bandage/bandage_info.xml, tools/bandage/macros.xml
Updated the bandage tool to document all of the formats that are supported
=> Document filetype support

tools/slamdunk/macros.xml
* [ x ]  - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x ] - License permits unrestricted use (educational + commercial)
* [ x ] - This PR updates an existing tool or tool collection
@bgruening Will now write the long-promised blog entry
=> Slamdunk citation added.

tools/limma_voom/limma_voom.R, tools/limma_voom/limma_voom.xml, tools/limma_voom/test-data/contrasts.txt
=> Limma: add option to input table of contrasts

.travis.yml, tools/compose_text_param/.shed.yml, tools/compose_text_param/compose_text_param.xml
=> Add compose param expression tool

tools/picard/picard_MarkDuplicates.xml
=> Markdup umi fix

tools/annotatemyids/annotateMyIDs.xml
For https://help.galaxyproject.org/t/annotating-gene-ids-local-deseq2-rats-annotatemyids/1327
=> Annotatemyids: add rat

tools/transit/macros.xml
Tested locally, tests pass on all three wrappers.
=> Update transit to use tool version 2.5.2

tools/exonerate/exonerate.xml
Apparently there's a a --cores option for exonerate, let's use it!
=> Exonerate: add --cores option

tools/bandage/bandage_image.xml, tools/bandage/macros.xml
=> Bandage: add parameters to add name and length labels to nodes

tools/diffbind/diffbind.R, tools/diffbind/diffbind.xml
This should fix https://github.com/galaxyproject/tools-iuc/issues/2480
=> Diffbind: update to v2.10.0 and fix some warnings

tools/jbrowse/macros.xml, tools/jbrowse/readme.rst
=> update jbrowse to 1.16.5

tools/goenrichment/goenrichment.xml, tools/goenrichment/goslimmer.xml, tools/goenrichment/macros.xml
=> Fix goenrichment URLs

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py, data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml, data_managers/data_manager_build_kraken2_database/data_manager_conf.xml
=> kraken2 data manager: Allow cleanup to be optional

tools/volcanoplot/volcanoplot.xml
=> trigger a test - is that failing?

tools/export2graphlan/export2graphlan.xml
---
With this PR, I:
- Make almost all parameters optional
I did that to make sure to use always the default values of the tool, but also to fix some execution issues
- Remove quotes around number values 
- Add a proper version command
- Add detect_error in command
- Update the test
- Update to the latest version
=> export2graphlan: Update to make most of parameters optional

tools/varscan/macros.xml, tools/varscan/varscan.py, tools/varscan/varscan_somatic.xml
Introduces false-positive filtering for indels, makes results of false-positive filtering comparable to the original varscan/bam-readcount pipeline, and exposes new parameters for controlling pileup generation.
=> Enhance varscan somatic tool

tools/rgrnastar/macros.xml, tools/rgrnastar/rg_rnaStar.xml, tools/rgrnastar/test-data/rnastar_index2_versioned.loc
=> swap with/wo gene model in STAR

tools/genrich/genrich.xml
=> Changes to Genrich xml

tools/roary/roary.xml
update roary to latest version in conda. 
Allow for collection identifier or filename to be used instead of everything tempDIGITAL
=> update roary to latest version in conda. 

tools/dropletutils/dropletutils.xml, tools/dropletutils/scripts/dropletutils.Rscript
This fixes the exploding memory problem caused by converting data from sparse to raw
=> Fix to DropletUtils

tools/jbrowse/jbrowse.py, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml
Hey @abretaud, looks like we broke support of bed/gbk in https://github.com/galaxyproject/tools-iuc/pull/1683 with the indexing because it's all gff specific.
- I've separated out a BED version since I need that.
- I've resurrected the genbank from a previous commit of the generic 'features' method.
- I've included the MAF code from #2551 in case we ever solve the issues there.
=> Fix JBrowse for BED

tools/rgrnastar/macros.xml, tools/rgrnastar/rg_rnaStarSolo.xml
=> Bump STAR to 2.7.2b

.travis.yml, tools/abyss/abyss-pe.xml, tools/abyss/test-data/abyss-stats1.tab, tools/abyss/test-data/abyss-stats2.tab, tools/abyss/test-data/abyss-stats3.tab
Also speed-up Travis builds that don't really run test.
=> Update ABySS to v. 2.2.1

tools/rgrnastar/rg_rnaStarSolo.xml
=> Minor Fix to STARSolo (training fixes)

tools/umi_tools/macros.xml, tools/umi_tools/umi-tools_counts.xml, tools/umi_tools/umi-tools_extract.xml
Update to the UMI tools wrapper to fix a parsing error on a comma
=> Updated barcode sanitizer and bumped updated tools

tools/table_compute/scripts/safety.py, tools/table_compute/scripts/table_compute.py, tools/table_compute/table_compute.xml
=> Table compute fixes

tools/kallisto/kallisto_pseudo.xml, tools/kallisto/macros.xml, tools/kallisto/test-data/kallisto_pseudo_out1.tab, tools/kallisto/test-data/kallisto_pseudo_out6.tab
- Remove option that no longer exists
- Update output filenames
- Update test data
- Update kallisto dependency to 0.46.0
- Update samtools dependency to 1.9
=> Fix kallisto_pseudo

tools/unicycler/.shed.yml, tools/unicycler/unicycler.xml
=> Update unicycler to v0.4.8

tools/maker/maker.xml
We got the following error:
`NotFound: cannot find 'repeatmasker' while searching for 'repeat_masking.repeat_source.repeatmasker.rmlib'`
xref: https://help.galaxyproject.org/t/maker-failed-to-communicate-with-remote-job-server/2064/2
ping @abretaud; does that look good for you?
fyi @gmauro
=> Repeatmasker in maker: rmlib does not exists

tools/tb-profiler/macros.xml, tools/tb-profiler/tb_profiler_profile.xml
=> Update to tb-profiler 2.6.1

tools/rgrnastar/rg_rnaStarSolo.xml
Added ability to consume collection pairs
Removed strict barcode size restriction
Added collection test
Added test if R1 and R2 are same type for all pairs
=> STARsolo fix to consume paired list

data_managers/data_manager_manual/data_manager/data_manager_manual.py, data_managers/data_manager_manual/data_manager/data_manager_manual.xml, data_managers/data_manager_manual/test-data/dbkeys.loc, data_managers/data_manager_manual/test-data/dm6.data_manager_json, data_managers/data_manager_manual/tool_data_table_conf.xml.test
=> Fix data manager manual on python3

data_managers/data_manager_star_index_builder/data_manager/rna_star_index_builder.py, data_managers/data_manager_star_index_builder/data_manager/rna_star_index_builder.xml, data_managers/data_manager_star_index_builder/data_manager_conf.xml, tools/rgrnastar/macros.xml, tools/rgrnastar/tool_data_table_conf.xml.sample, tools/rgrnastar/tool_data_table_conf.xml.test
=> Fix issues with STAR data manager index path and versioning

tool_collections/snpeff/snpEff_databases.xml
=> Guarantee header line in snpeff databases output

tools/table_compute/table_compute.xml
=> Table compute Help text fix

data_managers/data_manager_manual/data_manager/data_manager_manual.py
One more fix I missed in https://github.com/galaxyproject/tools-iuc/pull/2644
=> Fix creating new data table on python 3

tools/bcftools/bcftools_consensus.xml
=> bcftools_consensus: add 'rename' parameter

docs/guide_for_reviewers.md
and what to do to keep tool lineage when migrating tools to tools-iuc.
=> Clarify TS owner check

tools/qualimap/qualimap_bamqc.xml, tools/qualimap/qualimap_rnaseq.xml, tools/qualimap/test-data/features.gtf
=> Prevent qualimap from trying to autodetect of regions files formats

tools/snippy/macros.xml, tools/snippy/test-data/a_fna_ref_mincov_2_minqual_60.snps.txt, tools/snippy/test-data/b_2_fna_ref_mincov_2_minqual_60.snps.gff, tools/snippy/test-data/b_fna_ref_mincov_2_minqual_60.snps.gff, tools/snippy/test-data/b_fna_ref_mincov_2_minqual_60.snps.txt
=> snippy: Update to v4.4.5

tools/gffread/gffread.xml, tools/gffread/test-data/Homo_sapiens.GRCh37_19.71.gff3, tools/gffread/test-data/ecoli-k12.processed.gff3
=> Update gffread to version 0.11.6

tools/gprofiler/README, tools/gprofiler/gprofiler_random.xml, tools/gprofiler/macros.xml
=> Fix formatting for gProfiler

tool_collections/kraken2/macros.xml, tools/spades/macros.xml
=> Fix data params format options

tools/dada2/README.md
I have completed the list of tools and added the conda prerequisite. 
=> Update dada2 readme.

tools/repeatmasker/repeatmasker.xml
and fix bool cheetah evaluation
=> repeatmasker: sed use -E instead of -r

tools/prokka/prokka.xml, tools/snippy/macros.xml, tools/snippy/snippy-core.xml, tools/snippy/snippy.xml
=> snippy: add tar requirement and use -x

tools/fargene/fargene.xml, tools/fargene/macros.xml
=> fargene: add tar requirement

tools/breseq/breseq.xml, tools/breseq/macros.xml
=> breseq: add tar requirement

tools/masigpro/masigpro.xml
=> masigpro: add coreutils requirement (for paste)

tools/art/macros.xml
=> Update art version

tools/abyss/abyss-pe.xml
No new command line options upstream
=> Abyss update

tools/extract_genomic_dna/extract_genomic_dna.xml, tools/ucsc_tools/twobittofa/twobittofa.xml
=> Extract_genomic_dna: use newer ucsc-fatotwobit version

data_managers/data_manager_bowtie2_index_builder/data_manager/bowtie2_index_builder.xml, data_managers/data_manager_bowtie2_index_builder/test-data/bowtie2_data_manager.json
=> Add python 3.7 to bowtie2, fix test data order

tools/variant_analyzer/mut2read.py, tools/variant_analyzer/mut2read.xml, tools/variant_analyzer/mut2sscs.py, tools/variant_analyzer/mut2sscs.xml, tools/variant_analyzer/read2mut.py, tools/variant_analyzer/read2mut.xml, tools/variant_analyzer/va_macros.xml
=> variant_analyzer: use up to date matplotlib

tools/umi_tools/umi-tools_counts.xml, tools/umi_tools/umi-tools_dedup.xml, tools/umi_tools/umi-tools_group.xml, tools/umi_tools/umi-tools_whitelist.xml
=> Add sed requirement, bump samtools requirement for umi_tools

tools/dropletutils/dropletutils.xml
Add fonts and increase image delta to 400.
Fonts should ultimately probably be included with the r package
upstream.
=> Fix dropletutils test

tools/migmap/migmap.xml
=> Use migmap 1.0.3, fixes missing bzip2.so

tools/bandage/bandage_image.xml, tools/bandage/bandage_info.xml, tools/bandage/macros.xml
goes together with https://github.com/bioconda/bioconda-recipes/pull/19070
=> Fix containerized Bandage

tools/extract_genomic_dna/extract_genomic_dna.xml
=> Fix dynamic filter in extract_genomic_dna

tools/tag_pileup_frequency/tag_pileup_frequency.xml
I hit the merge button a little too early.
Cancelled the upload though.
=> Bump tag_pileup_frequency

tools/fasttree/fasttree.xml
=> Fix fasttree

tools/repmatch_gff3/repmatch_gff3.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/586
I guess we don't need to bump
=> repmatch: Adding input format specs to help

tools/jbrowse/jbrowse-fromdir.xml, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml
=> Jbrowse: fix errors in singularity

tools/scanpy/cluster_reduce_dimension.xml, tools/scanpy/macros.xml
=> Scanpy: Fix some parameter description and an extra comma

tools/augustus/augustus.xml, tools/augustus/augustus_training.xml, tools/augustus/macros.xml, tools/augustus/test-data/augustus.hints.output.gtf, tools/augustus/test-data/augustus.hints_and_range.output.gtf, tools/augustus/test-data/human_augustus_protein_codingseq_introns_cds_main.gtf, tools/augustus/test-data/human_augustus_utr-on.gff, tools/augustus/test-data/human_augustus_utr-on.gtf
An update for augustus, that should hopefully fix the container test too (#2701 )
I also fix the code that was trying to copy `/` when AUGUSTUS_CONFIG_PATH env var was not set (like in singularity container).
=> Augustus 3.3.3

data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py, data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml, data_managers/data_manager_build_kraken2_database/test-data/kraken2_custom_data_manager.json
=> Fix kraken2 data manager

tools/bctools/macros.xml, tools/bctools/merge_pcr_duplicates.xml, tools/bctools/rm_spurious_events.xml
=> Add missing coreutils to bctools

tools/sina/macros.xml, tools/sina/sina.xml
=> Fix containerized sina execution

tools/rcorrector/FilterUncorrectabledPEfastq.py, tools/rcorrector/rcorrector.xml
=> Fix containerized rcorrector

tools/mykrobe/.shed.yml, tools/mykrobe/macro.xml, tools/mykrobe/mykrobe_genotype.xml, tools/mykrobe/mykrobe_predict.xml
Updating Mykrobe from Conda version 0.6.1 to 0.7.0.
=> Update Mykrobe version from 0.6.1 to 0.7.0

tools/star_fusion/star_fusion.xml
=> Fix containerized star-fusion

tools/cat/cat_bins.xml, tools/cat/cat_contigs.xml, tools/cat/macros.xml
=> CAT/BAT change range fraction defaults for cat_bins

tools/circos/circos.xml, tools/circos/macros.xml, tools/circos/macros_conffiles.xml
Should fix a handful of bugs required for https://github.com/galaxyproject/training-material/pull/1548
=> Maybe final Circos update

tools/qualimap/qualimap_macros.xml, tools/qualimap/test-data/rnaseq_qc_results_custom.txt, tools/qualimap/test-data/rnaseq_qc_results_default.txt
=> Bump qualimap, fixes containerized execution

tools/bcftools/bcftools_plugin_counts.xml
=> Fix bcftools typo

tools/varscan/varscan_somatic.xml
=> Fix varscan_somatic test

tools/anndata/inspect.xml, tools/anndata/macros.xml
=> Fix containerized anndata inspect

tools/slamdunk/macros.xml, tools/slamdunk/slamdunk.xml, tools/slamdunk/test-data/reads1_overallrates.csv, tools/slamdunk/test-data/reads_slamdunk_mapped_filtered_tcount.tsv, tools/slamdunk/test-data/summary.txt
=> Update slamdunk, fix tests

tools/seurat/seurat.xml
=> Update test delta for seurat

tools/tb-profiler/macros.xml, tools/tb-profiler/tb_profiler_profile.xml
=> Update and fix tb_profiler tests

tools/prokka/prokka.xml, tools/prokka/test-data/out.err, tools/prokka/test-data/out.gff, tools/prokka/test-data/out.tbl, tools/roary/roary.xml, tools/roary/test-data/out/summary_statistics.txt, tools/roary/test-data/test2/summary_statistics.txt
=> a few updates to prokka and roary

tool_collections/snpeff/snpEff_macros.xml, tool_collections/snpeff/snpeff_get_chr_names.xml
=> Fix snpEff_get_chr_names tests

tools/weather_app/simple_weather.xml
=> Fix weather tool test

tools/miniasm/miniasm.xml
=> Bump miniasm to 0.3

tools/gfa_to_fa/gfa_to_fa.xml
=> Fix gfa_to_fa

tools/tb-profiler/macros.xml
=> tb-profiler: Bump version to 2.8.4

tools/onto_toolkit/get_relationship_id_vs_relationship_def.xml, tools/onto_toolkit/get_relationship_id_vs_relationship_name.xml, tools/onto_toolkit/get_relationship_types.xml, tools/onto_toolkit/get_terms_by_relationship_type.xml
=> Fix onto_tk tests

tools/colibread/discosnp_RAD.xml, tools/colibread/test-data/discosnpRAD/vcf_file.vcf
=> Fix discosnp_RAD_test

tools/repeatmasker/repeatmasker.xml
=> Fix repeatmasker tests

tools/circos/macros.xml, tools/circos/macros_conffiles.xml
Thanks for the logs @gmauro, it was super helpful.
=> Fix broken macro usage in circos

tools/pathview/pathview.xml
=> Fix pathview tests

tools/heinz/visualization.xml
Add fonts-conda-ecosystem while we wait for https://github.com/conda-forge/graphviz-feedstock/pull/42
=> Fix heinz visualization

tools/graphlan/graphlan.xml, tools/graphlan/graphlan_annotate.xml, tools/graphlan/graphlan_macros.xml, tools/graphlan/test-data/intermediary_tree
=> Bump graphlan, fix tests

tools/humann2/humann2.xml
=> Fix humann2 test

tools/htseq_count/htseq-count.xml
=> Fix htseq-count samout option

tools/snippy/snippy-core.xml, tools/snippy/snippy.xml
=> Change how snippy passes zipped output dirs to snippy-core

data_managers/data_manager_manual/data_manager/data_manager_manual.xml
=> Fix profile for data_manager_manual

data_managers/data_manager_bwameth_index_builder/data_manager/bwameth_index_builder.py, data_managers/data_manager_bwameth_index_builder/data_manager/bwameth_index_builder.xml, data_managers/data_manager_bwameth_index_builder/test-data/all_fasta.loc, data_managers/data_manager_bwameth_index_builder/test-data/bwameth_data_manager.json, data_managers/data_manager_bwameth_index_builder/test-data/phiX174.fasta, data_managers/data_manager_bwameth_index_builder/tool_data_table_conf.xml.test
=> Add bwameth_data_manager test

data_managers/data_manager_picard_index_builder/data_manager/picard_index_builder.py, data_managers/data_manager_picard_index_builder/data_manager/picard_index_builder.xml, data_managers/data_manager_picard_index_builder/test-data/all_fasta.loc, data_managers/data_manager_picard_index_builder/test-data/phiX174.fasta, data_managers/data_manager_picard_index_builder/test-data/picard_index_builder_data_manager.json, data_managers/data_manager_picard_index_builder/tool_data_table_conf.xml.test
=> Add test for data_manager_picard_index_builder

tools/quast/quast.xml
=> Fix quast tests, needs isolated home dir

tools/idr_download/.shed.yml, tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml
=> add missing IDR shed.yml file

tools/anndata/manipulate.xml, tools/scanpy/cluster_reduce_dimension.xml, tools/scanpy/filter.xml, tools/scanpy/inspect.xml, tools/scanpy/normalize.xml, tools/scanpy/plot.xml, tools/scanpy/remove_confounders.xml
Mirrors fixes to the PBMC 3K tutorial here: https://github.com/galaxyproject/training-material/pull/1751
=> Scanpy and Anndata minor fixes to labels

tools/pygenometracks/pyGenomeTracks.xml
Without this, you can't set a min value of `0.0` for example -- the argument simply gets ignored.
=> Pygenometracks fix minmax

tools/jbrowse/macros.xml, tools/jbrowse/readme.rst
=> JBrowse: update to 1.16.8

tools/stacks2/stacks_populations.xml
might fix https://github.com/galaxyproject/tools-iuc/issues/2863
I opened a now PR since I don't know how fast we are with https://github.com/galaxyproject/tools-iuc/pull/2859
=> stacks2: fix stacks2 populations batch-size

tools/hyphy/hyphy_absrel.xml, tools/hyphy/hyphy_bgm.xml, tools/hyphy/hyphy_busted.xml, tools/hyphy/hyphy_fade.xml, tools/hyphy/hyphy_fel.xml, tools/hyphy/hyphy_fubar.xml, tools/hyphy/hyphy_gard.xml, tools/hyphy/hyphy_meme.xml, tools/hyphy/hyphy_relax.xml, tools/hyphy/hyphy_slac.xml, tools/hyphy/macros.xml
=> Update HyPhy tools to correctly use MPI.

tools/hyphy/hyphy_absrel.xml, tools/hyphy/hyphy_bgm.xml, tools/hyphy/hyphy_busted.xml, tools/hyphy/hyphy_fade.xml, tools/hyphy/hyphy_fel.xml, tools/hyphy/hyphy_fubar.xml, tools/hyphy/hyphy_gard.xml, tools/hyphy/hyphy_meme.xml, tools/hyphy/hyphy_relax.xml, tools/hyphy/hyphy_slac.xml, tools/hyphy/macros.xml
=> Update HyPhy tools to 2.5.3

tools/hyphy/macros.xml
=> hyphy version 2.5.5

tools/chira/chira_extract.xml, tools/chira/chira_merge.xml, tools/chira/chira_quantify.xml
=> chira: remove quotes for boolean params in command

tools/chira/chira_extract.xml
=> chira: remove unnecessary quotes and add labels for some params

tools/chira/macros.xml
=> chira: update version

tools/deseq2/deseq2.R, tools/deseq2/deseq2.xml, tools/snippy/macros.xml, tools/snippy/snippy-core.xml, tools/snippy/snippy.xml, tools/snippy/snippy_clean_full_aln.xml
No user-facing parameters were changed
=> Update to snippy 4.5.0

tools/ncbi_entrez_eutils/ecitmatch.xml, tools/ncbi_entrez_eutils/efetch.xml, tools/ncbi_entrez_eutils/egquery.xml, tools/ncbi_entrez_eutils/einfo.xml, tools/ncbi_entrez_eutils/elink.xml, tools/ncbi_entrez_eutils/epost.xml, tools/ncbi_entrez_eutils/esearch.xml, tools/ncbi_entrez_eutils/esummary.xml, tools/ncbi_entrez_eutils/eutils.py, tools/ncbi_entrez_eutils/macros.xml, tools/ncbi_entrez_eutils/test-data/pubmed.metadata.xml
=> Fix ncbi_eutils tests

tools/hicexplorer/hicDetectLoops.xml, tools/hicexplorer/hicValidateLocations.xml
Fixing two typos and copy&paste errors.
ping @bgruening
=> HiCExplorer version 3.4.2.1

tools/chira/macros.xml
=> update chira version

tools/hyphy/macros.xml
=> HyPhy version 2.5.7

tools/hyphy/hyphy_meme.xml
=> Make the MEME test a little more lenient

tools/kc-align/kc-align.xml
=> Kc-Align Update

tools/mageck/mageck_gsea.xml, tools/mageck/mageck_macros.xml, tools/mageck/mageck_test.xml
=> Mageck: update to v0.5.9

tools/minimap2/minimap2.xml
=> add c option

data_managers/data_manager_build_kma_index/data_manager/kma_build_index.py, data_managers/data_manager_mash_sketch_builder/data_manager/mash_sketch_builder.py, setup.cfg, tools/iedb_api/iedb_api.py
since flake8 wasn't used before it should not have any side effects
plus some flake improvements that accumulated on my repo for testing
=> be more strict with flake8

tools/gatk4/gatk4_Mutect2.xml, tools/gatk4/macros.xml
=> Fix java options and sample name for Mutect2

tools/kc-align/kc-align.xml
=> Bump kcalign version

tools/chira/macros.xml
=> update chira to 1.1.5

tools/raxml/raxml.xml
=> RAxML UX improvements from Michael Buhl

tools/kc-align/kc-align.xml
=> Update Kc-Align Version

tools/hyphy/hyphy_busted.xml, tools/hyphy/hyphy_prime.xml, tools/hyphy/hyphy_sm19.xml, tools/hyphy/macros.xml
=> Update HyPhy to 2.5.9

tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml, tools/idr_download/test-data/test_output.log
Some errors fixed by @bgruening
=> IDR download - Add error handling

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.11

data_managers/data_manager_fetch_ncbi_taxonomy/data_manager/ncbi_taxonomy_fetcher.xml
=> data_manager_fetch_ncbi_taxonomy: Provide default value for NCBI taxonomy URL

.github/workflows/ci.yaml
=> Skip cron tests on forks

tools/ggplot2/ggplot_point.xml
Should fix https://github.com/galaxyproject/tools-iuc/issues/2874
=> Dont' quote numeric value in ggplot_point

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.12

tools/sarscov2formatter/sarscov2formatter.xml, tools/sarscov2summary/sarscov2summary.xml
=> Fix quotes and minor formatting for sarscov2formatter

.github/workflows/pr.yaml
@bgruening : lets see if this fixes it.
=> PR workflow fix to early checkout

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.14

tools/presto/prestor_abseq3.xml
=> Fix prestor_abseq tests

tools/gatk4/gatk4_Mutect2.xml, tools/gatk4/macros.xml, tools/gatk4/test-data/all_fasta.loc, tools/gatk4/test-data/cached_locally/all_fasta.loc, tools/gatk4/test-data/cached_locally/cached_reference.fa, tools/gatk4/tool_data_table_conf.xml.test
=> Correct 'cached' option for selecting ref. gen. in Mutect2

tools/kc-align/kc-align.xml
=> Update Kc Version

tools/tasmanian_mismatch/.shed.yml, tools/tasmanian_mismatch/README.rst
I'm hoping that these tweaks will cause this tool to appear in the toolshed
=> Tasmanian toolshed tweaks

tools/scanpy/cluster_reduce_dimension.xml, tools/scanpy/filter.xml, tools/scanpy/inspect.xml, tools/scanpy/macros.xml, tools/scanpy/normalize.xml, tools/scanpy/plot.xml, tools/scanpy/remove_confounders.xml
This is a small patch to https://github.com/galaxyproject/tools-iuc/pull/3039
=> Plot with Scanpy: Changes way in which coloring defaults are set (smallfix)

.github/workflows/ci.yaml, .github/workflows/pr.yaml
And switch PR testing to Galaxy 20.05 too.
=> CI: Install `wheel` package to cache more packages

tools/prokka/prokka.xml
=> Fix prokka output format of genbank dataset 

tools/chira/chira_extract.xml, tools/chira/chira_map.xml, tools/chira/chira_merge.xml, tools/chira/macros.xml
=> update chira to 1.3.3

tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml
=> added timestamp when streaming image fileobject into tar

tools/seurat/seurat.xml
=> Update rmarkdown requirement of Seurat to v2.2

tools/circos/karyotype-from-fasta.py, tools/circos/karyotype-from-lengths.py, tools/circos/macros.xml
=> Add DOI to Circos now that it is published

tools/chira/chira_extract.xml, tools/chira/macros.xml
=> update chira version and fix a parameter

tools/velvet/.shed.yml
=> velvet: change URL to IUC

tools/last/tool-data/lastdb.loc.sample
A follow-up to #3084 and #2749 to fix the error in https://github.com/galaxyproject/tools-iuc/runs/780547232
=> Last: fix TS upload error, second edition

tools/hyphy/macros.xml
=> Update hyphy to 2.5.15

tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml
=> simplifying with libtiff, removing dependencies on PIL

tools/ont_fast5_api/compress_fast5.xml, tools/ont_fast5_api/fast5_subset.xml, tools/ont_fast5_api/multi_to_single_fast5.xml, tools/ont_fast5_api/single_to_multi_fast5.xml
=> ont-api: recursive search fast5 files

tools/roary/roary.xml
Per a user request, this output is desirable to them.
apologies, pushed to wrong origin.
=> Expose pan_genome_ref.fa for roary

tools/shovill/shovill.xml
=> update to shovill 1.1.0 and change test

tools/sra-tools/fasterq_dump.xml, tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_macros.xml
=> Fix sra-tools file_list mode

tools/chira/macros.xml
=> update chira to 1.3.7

tool_collections/samtools/samtools_reheader/samtools_reheader.xml
=> Expose the --no-PG option of samtools reheader

tool_collections/cufflinks/cuff_macros.xml, tool_collections/cufflinks/cuffdiff/cuffdiff_wrapper.xml, tool_collections/cufflinks/cuffnorm/cuffnorm_wrapper.xml
Porting https://github.com/galaxyproject/tools-devteam/pull/231 over.
- Prevent commas in condition names
- Fix typos
- Fix indentation
=> Fixes for cuffdiff and cuffnorm

tools/cutadapt/cutadapt.xml, tools/cutadapt/macros.xml
in addition it should fix https://github.com/galaxyproject/tools-iuc/issues/2986 
=> cutadapt: do not ignore maxn for 0 and adapter sanitizer

tools/fasttree/fasttree.xml
=> fix fasttree version command

tools/tetoolkit/tetranscript.xml
See: https://github.com/mhammell-laboratory/TEtranscripts/releases/tag/2.2.0
=> [TEToolkit] update to 2.2.0

data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.py, data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager/data_manager_plant_tribes_scaffolds_download.xml, data_managers/data_manager_plant_tribes_scaffolds_downloader/data_manager_conf.xml, data_managers/data_manager_plant_tribes_scaffolds_downloader/test-data/plant_tribes_scaffolds.json, data_managers/data_manager_plant_tribes_scaffolds_downloader/tool_data_table_conf.xml.test
=> Add data_manager_plant_tribes_scaffolds_downloader functional test

tools/interval2maf/.shed.yml, tools/interval2maf/interval2maf.py
=> Add .shed.yml to interval2maf

data_managers/data_manager_ncbi_taxonomy_sqlite/data_manager/data_manager_ncbi_taxonomy_sqlite.py, data_managers/data_manager_ncbi_taxonomy_sqlite/data_manager/data_manager_ncbi_taxonomy_sqlite.xml
=> Update: Use correct output_directory for data_manager_ncbi_taxonomy_sqlite

tools/seurat/Seurat.R, tools/seurat/seurat.xml
Related: https://github.com/galaxyproject/tools-iuc/issues/3115
=> Expose perplexity parameter in Seurat

tools/ont_fast5_api/.shed.yml
=> ont_fast5_api: Update remote url and homepage

tools/fastqe/fastqe.xml
=> Fastqe: escape element identifier

.github/workflows/pr.yaml
Suggested (kind-of) by @pvanheus
=> Deploy on TS even if it failed on TTS

tools/chira/chira_quantify.xml, tools/chira/macros.xml
=> update chira to 1.4.0

tools/gatk4/gatk4_Mutect2.xml
=> Update to Mutec4

README.md
Fixes #3160
Thanks @peterjc :)
=> Update badge: travis -> GA

tools/sra-tools/fasterq_dump.xml, tools/sra-tools/fastq_dump.xml, tools/sra-tools/sam_dump.xml, tools/sra-tools/sra_macros.xml
and use tee to keep stdout+stderr
=> Update sra toolkit to 2.10.8

tools/jbrowse/jbrowse.py, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml
These are a bit easier for embedding e.g. in the GTN like in https://github.com/galaxyproject/training-material/pull/1547. I wish it was fewer images since there are still ~100 of those, but, it's an improvement until JBrowse2 is ready.
=> Allow producing more minimal jbrowses

tools/miniasm/miniasm.xml
=> Add note to miniasm: NOTE:  This tool may take a long time depending on the size and characteristics of your dataset.

tools/query_tabular/filter_tabular.xml, tools/query_tabular/filters.py, tools/query_tabular/load_db.py, tools/query_tabular/macros.xml, tools/query_tabular/query_db.py, tools/query_tabular/query_tabular.xml, tools/query_tabular/test-data/filtered_customers_results.tsv
=> Query tabular

data_managers/data_manager_mothur_toolsuite/data_manager/data_manager_fetch_mothur_reference_data.xml, data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py
and add a test for each of them
=> fix links in mothur data manager

tools/hyphy/hyphy_absrel.xml, tools/hyphy/test-data/absrel-out1.json
=> Add support for multiple nucleotide substitions to HyPhy-aBSREL.

.github/workflows/ci.yaml, .github/workflows/pr.yaml, .github/workflows/slash.yaml
=> Run weekly tests against 20.09 and add slash commands

tools/plink/plink.xml
Changes datatypes for ease of workflow dev
=> Plink1.9 workflow fix

.github/workflows/slash.yaml
=> Run slash commands only on galaxyproject side

data_managers/data_manager_salmon_index_builder/data_manager/salmon_index_builder.py, data_managers/data_manager_salmon_index_builder/data_manager/salmon_index_builder.xml
=> updates data manager to q7 version of index used in latest salmon tool

tools/plink/plink.xml
=> Plink accept vcf.gz as input without uncompressing

tools/plink/plink.xml
=> increase speed by not converting as a separate command

tools/artic/artic_minion.xml
=> Fix and enhance the artic minion all-in-one tool

tools/vsnp/vsnp_add_zero_coverage.py, tools/vsnp/vsnp_build_tables.py
This caused the merge build to fail ( https://github.com/galaxyproject/tools-iuc/actions/runs/275006830 ), so the tool was never uploaded to the TSs.
=> Fix flake8 issues for vsnp

tools/seurat/seurat.xml
=> Update Seurat to 3.2.2

tools/sina/sina.xml
Applied changes in parameters that are relevant for CSV output files ->https://github.com/epruesse/SINA/releases/tag/v1.7.0
=> Update: SINA to 1.7.1

.github/workflows/pr.yaml
=> Don't try to deploy on forks

tools/tetoolkit/tetranscript.xml
Only few changes, details: https://github.com/mhammell-laboratory/TEtranscripts/releases/tag/2.2.1
=> Update Tetoolkit to 2.2.1

tools/plink/plink.xml
=> Plink: better phenotype file modularity and quantitative phenotype file outputs

tools/proteinortho/proteinortho.xml, tools/proteinortho/proteinortho_grab_proteins.xml, tools/proteinortho/proteinortho_macros.xml
- Some  sanitizer in proteinortho_grab_proteins.xml (missing some special characters)
- updated proteinortho to 6.0.23 (from 6.0.14)
=> update proteinortho 6.0.23

tools/lofreq/lofreq_alnqual.xml, tools/lofreq/lofreq_call.xml, tools/lofreq/lofreq_filter.xml, tools/lofreq/lofreq_indelqual.xml, tools/lofreq/lofreq_viterbi.xml
and drop workaround for https://github.com/CSB5/lofreq/issues/85.
=> Add profile to lofreq tools, drop tmpdir workaround

tools/artic/artic_minion.xml
This is a follow-up on #3214 where I wrongly assumed that the artic pipeline would emit its final variant list in compressed *and* uncompressed form.
=> Fix artic minion again

tools/novoplasty/novoplasty.xml
Minor bug fixes. Wrapper not changed. https://github.com/ndierckx/NOVOPlasty/releases/tag/NOVOPlasty4.2
=> Update NOVOplasty to 4.2

tools/colibread/lordec.xml, tools/mummer4/macros.xml, tools/mummer4/mummer.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/3246
in case CI does not complain opening a PR seems less effort than creating issue comments (https://github.com/galaxyproject/tools-iuc/pull/3245#issuecomment-707252304) or issues (https://github.com/galaxyproject/tools-iuc/issues/3246) 
lets see :)
=> use GALAXY_SLOTS

tools/scpipe/scpipe.xml
=> Various scpipe fixes

tools/medaka/annotateVCF.py, tools/medaka/variant.xml
Had an issue with annotateVCF.py not handling insertions when quantifying SNPs correctly.
=> fixing bug with annotateVCF.py

.github/workflows/pr.yaml
=> Fix typo in ``pr.yaml``

tools/vsearch/search.xml, tools/vsearch/test-data/search_dbmatched_uc.tsv
fixes https://github.com/galaxyproject/tools-iuc/issues/3275
=> vsearch: make uc output tabular

tool_collections/biotradis/bacteria_tradis.xml, tool_collections/biotradis/tradis_essentiality.xml, tool_collections/biotradis/tradis_gene_insert_sites.xml
added `echo $?` .. so the tool should not fail anymore .. but it is .. don't get it
Isn't failing for non-containerized tests ... even without the `echo $?`. Maybe just a faulty container?
=> tradis essentiality fix?

tools/raven/macros.xml
=> Raven update

tools/last/lasttrain.xml, tools/last/test-data/last_train.txt, tools/last/test-data/last_train_E.txt
=> Make last train -E optional

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Pass the calculated number of chunks to planemo

tools/ggplot2/macros.xml
=> Issue 3297

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.23

tools/emboss_5/emboss_dreg.xml, tools/emboss_5/emboss_format_corrector.py, tools/emboss_5/emboss_preg.xml, tools/emboss_5/macros.xml, tools/emboss_5/test-data/dreg.seqtable, tools/emboss_5/test-data/preg.seqtable
fixes: https://github.com/galaxyproject/tools-iuc/issues/3060
also add tests
=> emboss: properly sanitize regex

tools/multiqc/multiqc.xml
=> Multiqc: update to v1.9

tools/idr_download/idr_download_by_ids.py, tools/idr_download/idr_download_by_ids.xml
=> fixing bugs and adding test to IDR download tool

.github/workflows/pr.yaml
=> fix typo in PR workflow

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Also:
- Fix regression in check for tool that can't be tested in biocontainers (my fault, sorry!)
- Small refactor, add comments
=> Don't skip tools in `.tt_biocontainer_skip` during weekly CI testing

.github/workflows/pr.yaml, tools/deseq2/deseq2.R, tools/deseq2/deseq2.xml, tools/deseq2/get_deseq_dataset.R, tools/exomedepth/exomedepth.R, tools/exomedepth/exomedepth.xml
Replace some errant ligature characters with their ASCII equivalents
=> Replace ligature characters with ASCII equivalents

tools/flair/flair_collapse.xml, tools/flair/flair_correct.xml, tools/flair/flair_macros.xml
=> flair: add profile, replace tabs

tools/spyboat/output_report.py, tools/spyboat/spyboat.xml, tools/spyboat/spyboat_cli.py, tools/spyboat/test-data/output1.html
=> fixed output filters and html tweaks

tools/feelnc/feelnc_wrapper.xml
=> Update feelnc to 0.2

tools/rgrnastar/macros.xml, tools/rgrnastar/rg_rnaStar.xml, tools/rgrnastar/rg_rnaStarSolo.xml
This should hopefully fix this issue from the tutorial https://github.com/galaxyproject/training-material/issues/2103
=> update star to version 2.7.6a

tools/hicexplorer/macros.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/2952
=> hiccorrelate: fix access to range

tools/snpfreqplot/heatmap_for_variants.R, tools/snpfreqplot/helperFunctions.R, tools/snpfreqplot/snpEffExtract.R, tools/snpfreqplot/snpfreqplot.xml, tools/snpfreqplot/test-data/no_variants.vcf, tools/snpfreqplot/test-data/single_variant.vcf
=> Enable snpfreqplot to recycle colors and handle small inputs

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.24

tools/dada2/.shed.yml
=> fix duplicate category in dada2 shed.yml

.github/workflows/pr.yaml, .tt_skip, tools/jbrowse/jbrowse.xml, tools/jbrowse/macros.xml
Seems like #3401 didn't get uploaded to TS as jbrowse was put to the skip list...
=> Remove jbrowse from skip list

tools/sina/sina.xml
Just a bug fix. See https://github.com/epruesse/SINA/releases/tag/v1.7.2
=> Update SINA to 1.7.2

tools/mitobim/mitobim.xml
finishing https://github.com/galaxyproject/tools-iuc/pull/3400
=> mitobim: add validators

tools/gecko/README.md, tools/gecko/gecko.xml
=> update to 1.2 to match latest version because of bad versioning

tools/snpfreqplot/heatmap_for_variants.R, tools/snpfreqplot/snpfreqplot.xml
=> Yet another snpfreqplot fix

tools/tb-profiler/macros.xml
=> Update tb-profiler to version 2.8.14

tools/rnaspades/rnaspades.xml
Taken from the regular SPAdes wrapper.
=> Add memory option to rnaSPAdes

tools/hyphy/macros.xml
=> Update HyPhy wrappers to 2.5.25

.github/workflows/ci.yaml, .github/workflows/pr.yaml, tools/bowtie2/bowtie2_macros.xml, tools/bowtie2/bowtie2_wrapper.xml
=> Sync ci and pr GitHub workflows

tools/vsnp/vsnp_add_zero_coverage.xml, tools/vsnp/vsnp_build_tables.xml, tools/vsnp/vsnp_determine_ref_from_data.py
=> Fix data_meta tags and slight cleanup for args

tools/metaspades/metaspades.xml
=> Add memory option to metaSPAdes

tools/hyphy/macros.xml
This _should_ address the issue in veg/hyphy#1265
=> Update to HyPhy 2.5.26

tools/ruvseq/ruvseq.R, tools/ruvseq/ruvseq.xml
CI failure was because the parameter name `designFormula` was changed to
`design_formula` in the function `get_deseq_dataset` which is imported
from `get_deseq_dataset.R` (which is a symlink into `../deseq2`).
don't think that we need to bump the version here. question is if the symlink is a good idea?
=> fix ruvseq

tools/gatk4/.shed.yml, tools/gatk4/gatk4_Mutect2.xml
=> Fix remote repository URL in .shed.yml

tools/humann2/humann2.xml
same as in the diamond tools
https://github.com/bgruening/galaxytools/blob/15c382f71f1984aecff67ef9d268b992528996b2/tools/diamond/macros.xml#L14
=> humann2: add oom for diamond

.github/workflows/pr.yaml
=> add repository list to deploy

tools/bcftools/bcftools_consensus.xml, tools/bcftools/macros.xml
=> Add --include filter to bcftools consensus

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> Fix quotes in GH workflows

tools/spyboat/spyboat.xml
=> Increase spyboat test output delta

.github/workflows/ci.yaml, .github/workflows/pr.yaml
=> switch workflows to Galaxy release 21.01

tools/medaka/convert_VCF_info_fields.py, tools/medaka/variant.xml
=> Medaka update

tools/minimap2/minimap2.xml
=> Fix minimap2 min_occ_floor option

tools/jvarkit/jvarkit_wgscoverageplotter.xml
=> Switch to new wrapper for jvarkit-wgscoverageplotter

tools/query_tabular/filter_tabular.xml, tools/query_tabular/filters.py, tools/query_tabular/query_tabular.xml, tools/query_tabular/test-data/filtered_customers_results.tsv
Fix error for placing replacement  value.
=> Query_tabular fix column replace error

tools/prokka/prokka.xml, tools/roary/roary.xml
@Slugger70 can you look at this one, please. The only big change that I wanted to do is adding `min="2"` to roary's gff inputs. We got a few error reports from users that only supply one GFF file.
=> update prokka ad roary

tool_collections/kraken2/kraken2/kraken2.xml, tool_collections/kraken2/kraken2/test-data/kraken_test2_report.tab
=> Fix kraken2 report-minimizer-data option

tools/rnaquast/rna_quast.xml
=> rnaquast update to 2.2.0

tools/medaka/convert_VCF_info_fields.py, tools/medaka/variant.xml
Fixing errors I ran into with medaka variant... Last update before bumping to more recent medaka version I promise.
=> Fixing small errors in medaka variant and convert_VCF_info_fields.xml

tools/hyphy/macros.xml
=> Update to HyPhy 2.5.29

tools/vsnp/vsnp_build_tables.xml
test for collection was ignored until 21.01 (galaxyproject/galaxy#11313)
=> fix vsnp_build_tables test

tools/strelka/strelka_germline.xml
xref galaxyproject/galaxy#11313
=> fix test of strelka germline

tools/column_maker/column_maker.py, tools/column_maker/column_maker.xml
xref. https://github.com/galaxyproject/tools-devteam/pull/585#issuecomment-783774704 and https://github.com/galaxyproject/tools-devteam/pull/586
@martenson Can you please check if IUC has the necessary permissions on https://toolshed.g2.bx.psu.edu/view/devteam/column_maker/ ?
=> Merge `column_maker` changes from tools-devteam

tools/pycoqc/pycoqc.xml
output containes a date so we need to allow for a lines diff of 2
=> pycoqc: fix test

tools/jbrowse/macros.xml, tools/jbrowse/readme.rst
Just a small update https://github.com/GMOD/jbrowse/releases/tag/1.16.11-release
=> Update jbrowse to 1.16.11

tools/metaphlan2/metaphlan2.xml
=> metaphlan fix --input_type parameter

.github/workflows/ci.yaml, .github/workflows/pr.yaml, tools/dexseq/dexseq.R, tools/dexseq/dexseq_helper.py, tools/dexseq/plotdexseq.R
GitHub workflows is being migrated to Ubuntu 20.04, which is breaking the R linting CI job with:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
unable to load shared object '/home/runner/work/_temp/Library/stringi/libs/stringi.so':
libicui18n.so.60: cannot open shared object file: No such file or directory
Calls: lint_dir ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```
This is due to R package cache, its key should depend also on the Ubuntu version.
Fix https://github.com/galaxyproject/tools-iuc/issues/3539
=> Fix R linting + lint dexseq

tools/minimap2/minimap2.xml
=> Minimap2 update

tools/abricate/test-data/output_list.txt
seems that test data got an update. date column in the output changed
and made the test fail in weekly CI.
=> abricate_list fix test

tools/meryl/macros.xml, tools/meryl/meryl.xml
This PR fixes the calculate kmer size option, some labels and includes the memory and threads parameters.
=> Fix calculate kmers and labels

tools/hyphy/macros.xml
=> Update HyPhy wrappers to 2.5.30

tools/bcftools/bcftools_view.xml
=> implement --genotype option, add test

tools/meryl/macros.xml, tools/meryl/meryl.xml
=> Update meryl v1.3 and tests

tools/abricate/abricate.xml, tools/abricate/abricate_list.xml, tools/abricate/abricate_summary.xml, tools/abricate/macros.xml, tools/abricate/test-data/output_summary.txt
Add abricate tool for the [command to summarize results across samples](https://github.com/tseemann/abricate#combining-reports-across-samples)
=> Abricate summary tool

tools/fasta_stats/fasta-stats.pl, tools/fasta_stats/fasta-stats.xml, tools/fasta_stats/test-data/ng50_out.txt
=> Added NG50 to fasta_stats

data_managers/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.xml, data_managers/data_manager_metaphlan_database_downloader/test-data/metaphlan_database.loc, data_managers/data_manager_metaphlan_database_downloader/tool_data_table_conf.xml.test
=> Add test to metaphlan data manager

tools/mash/mash_sketch.xml
This PR fixes the genome_size parameter max value.
=> Fix mash sketch genome size parameter max value

tools/nextclade/nextclade.xml
=> Update nextclade: Fix handling of tabular output in nextclade

tools/orthofinder/macros.xml, tools/orthofinder/orthofinder_only_groups.xml
- fix filter
- fix 1 test
- and add expect_num_outputs to all tests
=> fix orthofinder

tools/bedtools/bamToBed.xml
=> allow BAM to BED to consume more diverse BAM datatypes

tools/trinity/trinity.xml
xref. https://github.com/galaxyproject/tools-iuc/pull/3543/files#r630401871
=> Fix fastq.gz support in Trinity

.github/workflows/ci.yaml, .github/workflows/pr.yaml
see also here https://github.com/galaxyproject/tools-iuc/issues/3666
=> update CI/PR workflow to 21.05

tools/metaphlan/formatoutput.py, tools/metaphlan/macros.xml, tools/metaphlan/metaphlan.xml
=> MetaPhlAn: update version and add new outputs and formatting

tools/hyphy/hyphy_bgm.xml
=> Correct output handling for HyPhy-BGM.

.github/workflows/pr.yaml
that indicates success if no tools were changed
@mvdbeek maybe something like this helps?
=> add a job to PR workflow

data_managers/data_manager_humann_database_downloader/data_manager/data_manager_humann_download.py, data_managers/data_manager_humann_database_downloader/data_manager/data_manager_humann_download.xml, tools/humann/humann.xml, tools/humann/macros.xml
---
HUMAnN tools using the files downloaded with DM in `utility_mapping` need the file extension to work
=> HUMAnN: fix some parameters, move tmp files to collection and add extension for some files in DM

tools/ivar/ivar_removereads.xml, tools/ivar/ivar_trim.xml, tools/ivar/macros.xml, tools/ivar/prepare_amplicon_info.py
Exposes new -f and -x options of ivar trim.
=> Upgrade ivar to v1.3.1

tools/nextclade/nextclade.xml
=> Update nextclade, add "keep header" selector

tools/tb_variant_filter/tb_variant_filter.xml
=> Update tb_variant_filter to 0.3.0, add support for farhat_rlc

README.md
=> show badges for master branch

tools/tb-profiler/macros.xml, tools/tb-profiler/tb_profiler_profile.xml
=> Update tb-profiler to 3.0.4

.github/workflows/ci.yaml, .github/workflows/pr.yaml
from master to main.
xref. https://github.com/galaxyproject/tools-iuc/issues/3691
=> Prepare CI for default branch rename

.github/workflows/pr.yaml
followup to https://github.com/galaxyproject/tools-iuc/pull/3669
=> lint only if tools or repos

.github/workflows/pr.yaml
=> fix typo in PR

tools/tb_variant_filter/tb_variant_filter.xml
=> Update tb_variant_filter to 0.3.5

data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py, data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml, data_managers/data_manager_pangolearn/test-data/pangolearn.loc
=> Update pangoLEARN DM to accomodate new DB version

tools/umi_tools/umi-tools_extract.xml
fixes https://github.com/galaxyproject/tools-iuc/issues/2271
=> remove --supress-stats for unitools extract

tools/mitos/macros.xml, tools/mitos/mitos.xml, tools/mitos/mitos2.xml
Per request of the MITOS maintainers (including myself) 
=> add mitos support mail
